### ISSUE TITLE
brunch cannot be installed because ansi-color is gone from npm

### ISSUE THREAD

**Issue by josevalim** [brunch/brunch#1004]
Folks, this is just a heads up. Currently it is impossible to install brunch because the ansi-color package just vanished from npm: https://www.npmjs.com/package/ansi-color

Since loggy depends on it and brunch depends on loggy, we get an error. I am not sure what is the best way to proceed here, I don't know if ansi-color is just temporarily done or forever.

**Comment by josevalim** [comment]
It seems to be a npm issue: https://github.com/npm/npm/issues/9168

**Comment by bagbee** [comment]
try to add to packege.json dependencies:
"ansi-color": "http://registry.npmjs.org/ansi-color/-/ansi-color-0.2.1.tgz"

it helped me.

**Comment by vdesdoigts** [comment]
Thanks @bagbee

**Comment by paulmillr** [comment]
WTF is this shit

**Comment by paulmillr** [comment]
Just pushed new laggy version. Should fix this.
