### ISSUE TITLE
How possible seo and hashbang?

### ISSUE THREAD

**Issue by erayarslan** [brunch/brunch#1006]
Like ost.io
I cant see any PhantomJS code in source.

**Comment by es128** [comment]
This is not really a question for brunch, but [googlebot executes javascript to render pages](http://googlewebmastercentral.blogspot.com/2014/05/understanding-web-pages-better.html). There is not necessarily a need at this point to serve static html for seo. If you find that you do need to do it anyway, it's up to the structure of your app and server, not anything to do with Brunch's role as a build tool.

**Comment by paulmillr** [comment]
SEO actually uses pushState. Try enabling pushState for your web server (nginx or apache) — pointing to `index.html`, it should work

**Comment by erayarslan** [comment]
@paulmillr i know that trick.
i just asked a "brunch has any seo feature?"
so thank u for responses guys!
