### ISSUE TITLE
Provide plugin API for compiling to arbitrary, non-concatenated output

### ISSUE THREAD

**Issue by lalomartins** [brunch/brunch#1007]
Use case: I'm working on some very simple landing pages, and I don't want to use client-side templates because it's overkill (and makes the load time slower for no reason). But I don't want to write HTML either :smile_cat: not when I have jade.

Plugins such as jaded-brunch, jade-static-brunch, and siml-static-brunch hack his by writing the files themselves inside the `compile` method. However, this bypasses the brunch pipeline and can have unexpected side-effects (e.g. see #916). Providing an API for this use case would make things neater.

Not sure what this API should look like, though. Off the top of my head, maybe instead of passing a string to the callback, an object with options, which may include a `path` property?

Example of why bypassing the pipeline is bad, if anyone needs convincing:

```coffee
  onCompile: (generatedFiles) ->
    if generatedFiles.length
      console.log generatedFiles.map (f) -> f.path.replace(/^.*\//, '')
```

output:
```log
11 Aug 12:49:38 - info: compiled 4 files into 2 files, copied 22 in 2697ms
[ 'index.js', 'index.css' ]
```

**Comment by paulmillr** [comment]
Agree.

**Comment by lalomartins** [comment]
Poking at the source, it's already possible to return an object — `{compiled, sourceMap, compilerDeps}`. So the API that comes to mind is adding an optional `path` property there.

**Comment by paulmillr** [comment]
@lalomartins how would it work?

**Comment by lydell** [comment]
Possibly related: #749.

**Comment by bmatcuk** [comment]
I'd like to see this feature implemented in brunch, too, but, for the time being, I've implemented it myself in a plugin: [brunch-static](https://github.com/bmatcuk/brunch-static).

I subscribe to the *NIX ideology of "small programs that do one thing well", so brunch-static is a plugin whose sole purpose is to write out static files while overcoming some of the pitfalls of this sort of "hack". For example, it returns null to brunch to avoid writing anything in the template javascript file, and then does its own dependency tracking to get around the fact that brunch will not track dependencies if you return null (see #916 and [this comment on #557](https://github.com/brunch/brunch/issues/557#issuecomment-17785676)).

The actual work is done by "processors": the only processor available currently is [html-brunch-static](https://github.com/bmatcuk/html-brunch-static) which is responsible for building static html files with full support for layouts and partials via yaml front matter and handlebars (ala jekyll, if you've ever used it). Again, html-brunch-static relegates processing to processors of its own. There are currently three available: handlebars (built-in to html-brunch-static), markdown ([marked-brunch-static](https://github.com/bmatcuk/marked-brunch-static)), and jade ([jade-brunch-static](https://github.com/bmatcuk/jade-brunch-static)).

It's still a hack, but by consolidating the hack into a single place (ie, brunch-static), it can be standardized and improvements can benefit everyone while removing the burden from plugin developers. As the functionality is moved into brunch, brunch-static can eventually go away.

These four plugins have just been published to npm. I've tested them locally, but you may still run into some bugs. Please file github issues for any bugs you find!

**Comment by es128** [comment]
@bmatcuk :+1: very cool

I still think if a future rewrite of brunch ever happens this concept should get full support core, but for now with what we have today that seems like a great approach.

**Comment by bmatcuk** [comment]
Agreed! Thank you =)

**Comment by goshakkk** [comment]
I have submitted a PR that would provide a first-class support for this type of plugins — see https://github.com/brunch/brunch/pull/1356

The dependencies, if a plugin declares any, should also work properly, though I haven't tested extensively. I did test by rewriting static-jade-brunch's current functionality to take advantage of this kind of API (without implementing the deps function, though it probably can be just borrowed from jade-brunch) https://github.com/brunch/static-jade-brunch/blob/new-api/lib/index.js
