### ISSUE TITLE
Better config validation

### ISSUE THREAD

**Issue by Flaise** [brunch/brunch#1011]
When I execute `brunch build` with a configuration file that looks like this:

    exports.config = {
        paths: {
            watched: 'src'
        },
        files: {}
    }

the output is a stack trace. It appears that I'm not supposed to write my `watched` configuration like that but since the module that reads the configuration file doesn't give a descriptive error message, I had to do lots of trial-and-error to figure out what the problem was.

The output is:

    .../node_modules/brunch/node_modules/async-each/index.js:5
        if (!Array.isArray(items)) throw new TypeError('each() expects array as fi
                                     ^
    TypeError: each() expects array as first argument
      at each (.../node_modules/brunch/node_modules/async-each/index.js:5:38)
      at initWatcher (.../node_modules/brunch/lib/watch.js:179:10)
      at launchWatcher (.../node_modules/brunch/lib/watch.js:550:14)
      at .../node_modules/brunch/lib/watch.js:574:14
      at .../node_modules/brunch/lib/helpers.js:604:12
      at .../node_modules/brunch/lib/helpers.js:565:16
      at .../node_modules/brunch/lib/helpers.js:511:12
      at .../node_modules/brunch/node_modules/read-components/index.js:263:16
      at .../node_modules/brunch/node_modules/read-components/index.js:72:14
      at FSReqWrap.cb [as oncomplete] (fs.js:226:19)

In contrast, when I comment out the `watched` attribute and then execute `brunch build`, the tool appears to do nothing, successfully, as we might expect.

Brunch 1.8.5
Node 0.12.7
Ubuntu 14.04

**Comment by es128** [comment]
`watched` expects an array `['src']`, which is documented, but your point is valid.

Yes, this could be improved, but there isn't really a catchall solution to this. It would have to be done property by property.
