### ISSUE TITLE
Watch not working with Mac OS X + Vagrant

### ISSUE THREAD

**Issue by ahomatthew** [brunch/brunch#1012]
Having a similar issue to https://github.com/brunch/brunch/issues/890.  This issue is with Mac OS X + Vagrant running Ubuntu 12.* and 14.* using Brunch 1.8.5. Saving the file on the host does not cause watch to rebuild, saving the file directly in Vagrant does trigger the event. usePolling: true, does fix the issue, however it would be great if the fsevents worked regardless.

**Comment by es128** [comment]
`usePolling` is the only way
