### ISSUE TITLE
node v4 segfaults

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#1013]
fsevents=0.3.8, chokidar=latest, os=elcapitan

```
❯ /usr/local/Cellar/node/4.0.0/bin/brunch watch
[1]    83142 segmentation fault  /usr/local/Cellar/node/4.0.0/bin/brunch watch --server
```

**Comment by paulmillr** [comment]
Also; fsevents=0.8, chokidar=latest

**Comment by es128** [comment]
Seems like it may just be from fsevents not being installed properly or rebuilt when switching node versions. What does it look like when you `npm uninstall -g brunch && npm i -g brunch`?

**Comment by paulmillr** [comment]
Well, i've removed node modules fully and did the brunch reinstall - same stuff here

**Comment by es128** [comment]
Nothing interesting in the installation output?

**Comment by es128** [comment]
Also `npm cache clean` maybe.

See https://github.com/strongloop/fsevents/issues/88 and https://github.com/strongloop/fsevents/issues/85 in case it gives you any hints toward how to resolve

**Comment by dmassiani** [comment]
npm cache clean -f && npm uninstall -g brunch && npm i -g brunch doesn't resolve.

**Comment by paulmillr** [comment]
seems ok with node 4.1
