### ISSUE TITLE
Should 'require' be included in the vendor file?

### ISSUE THREAD

**Issue by row1** [brunch/brunch#1014]
Hi,
I'm using Brunch 1.8.5 on a Mac. Looking at the [guide](https://github.com/brunch/brunch-guide/blob/master/content/en/chapter03-conventions-and-defaults.md#commonjs-module-wrapping) it states that vendor (and Bower files) do not get wrapped in modules. This is correct, but I notice that my vendor file still includes around 110 lines of code to implement `require()`. Can this be turned off? It is also getting included in my `templates.js` file, so I would prefer not to have it repeated 3 times.

Thanks

**Comment by paulmillr** [comment]
Brunch doesn't know about your script order and you can have many .html files too. That's why the require definition is added to all outputs.

You can disable it by specifying the config directive: `config = {modules: {definition: false}}`
