### ISSUE TITLE
TypeError: loaderPath.indexOf is not a function

### ISSUE THREAD

**Issue by magcius** [brunch/brunch#1016]
Hi,

When trying to use Brunch with NPM modules, I hit this error. The issue seems to be that that commonjs-require-definition takes a string, `loaderPath`, as the second parameter to `require` ([see here](https://github.com/brunch/commonjs-require-definition/blob/master/require.js#L68)), but deppack's standard header calls `require` like so: `require(o, !0)` ([see here](https://github.com/yavorsky/deppack/blob/master/src/deppack.coffee#L60)). (it's obfuscated and minified as `a(o,!0)` -- why deppack has a minified header, I'm not sure about).

I'm not sure exactly why deppack passes `true` to require. That doesn't seem to be a supported second parameter in any version of `require` I can find.

I'm using Brunch 1.8.5, on node version v0.10.32, on a Fedora machine. If you need any other info, let me know.

**Comment by paulmillr** [comment]
NPM support is in a bad state right now — yep.

**Comment by magcius** [comment]
Yeah. Almost immediately after this issue (which I hacked around locally by just removing the !0 parameter from both calls), I found https://github.com/yavorsky/deppack/pull/4

Do you have any recommendation of what I should use instead?
