### ISSUE TITLE
Brunch should come with a init command to init new projects with the dead-simple skeleton, out of the box

### ISSUE THREAD

**Issue by marcolz** [brunch/brunch#1024]
That is the only skeleton I really use, as most available skeletons these days are out of date, or never fully suiting me needs.

I'm pretty sure I'm not the only one to always use dead-simple and then start adding custom libraries.

Just an idea.

**Comment by es128** [comment]
You're asking for `brunch init` as an alias for `brunch new brunch/dead-simple`?

**Comment by marcolz** [comment]
Correct. ☺️

**Comment by vendethiel** [comment]
Yeah, I know I'm contributing to this trend... That's also the issue with technologies that come by and go away so fast... Stuff gets outdated really, really rapidly...

**Comment by paulmillr** [comment]
Agree.

**Comment by es128** [comment]
It would be good if we could find a place to hold global settings, so users could pick whatever they want their default skeleton to be for the `init` command.

**Comment by paulmillr** [comment]
The default one is dead-simple since 2.0, closing
