### ISSUE TITLE
Brunch does not concatenate files located in vendor

### ISSUE THREAD

**Issue by ceremcem** [brunch/brunch#1026]
Today I just cloned [my working project](https://github.com/ceremcem/aktos-website) into a Debian Jessie 32bit Virtual machine, reinstalled `npm 4.x`, `npm install -g brunch livescript`, `npm install` and then `brunch b`. When I try to load webpage, it says "ReferenceError: Ractive is not defined". It is true since there is no "Ractive" keyword in `public/javascripts/vendor.js`, which means the `Ractive.js` file is not added to the `vendor.js`. In fact, there is almost no files added to the `vendor.js`. 

Why is that? The same project can be compiled on my other machines. 

# Edit: 

`public.bak` is from my other machine, `public` is generated by `brunch b`: 
```
wc public.bak/javascripts/vendor.js 
  111223  361421 3786383 public.bak/javascripts/vendor.js

wc public/javascripts/vendor.js   
  322 1110 8281 public/javascripts/vendor.js
```

# Edit2: 

on node v4.x and node v0.12 this issue occurs but on node v0.10 brunch works as expected. Nodejs' are installed from https://github.com/nodesource/distributions

**Comment by paulmillr** [comment]
Would be great if you could share `-d` output with us (in a gist)

**Comment by ceremcem** [comment]
Here you are: https://gist.github.com/ceremcem/8f0014bca5c3d13daee4

**Comment by paulmillr** [comment]
@ceremcem are you able to reproduce the issue?
