### ISSUE TITLE
server.indexPath config and it's behavior.

### ISSUE THREAD

**Issue by nob** [brunch/brunch#1027]
I read [configuration file doc](https://github.com/brunch/brunch/blob/master/docs/config.md#server) and tweaked **server.indexPath** value since I need to rename 'index.html' to 'login.html' in public/ directory.
Then I got [this error on my browser](http://d.pr/i/1eDDR)
I also tried to change **server.noPushState** and **server.Slashes**, but had no luck. How I can configure the path to serve when base URL is requested?

The server section in my brunch-config.coffee is currently like this.
```coffeescript
  server:
    indexPath: 'login.html'
    noPushState: true
    stripSlashes: false
```
my current environments are: 
- Brunch v1.8.5
- node.js v0.12.7
- OS X v10.10.3 

Thanks for a great HTML5 build tool.

**Comment by goshakkk** [comment]
The underlying issue seems to be `pushserve` not handling the case when `noPushState` is true and `indexPath` is a custom value. I've submitted https://github.com/paulmillr/pushserve/pull/11 to account for this use case
