### ISSUE TITLE
Brunch extension for Visual Studio is available.

### ISSUE THREAD

**Issue by Bartmax** [brunch/brunch#1028]
I suggested this feature https://github.com/aspnet/Tooling/issues/37 on the aspnet tooling repo and @madskristensen created an extension here:
https://visualstudiogallery.msdn.microsoft.com/de706ad0-8a73-4df3-bef5-867bb9a70d51

I wanted to let you know! this is great news btw.

**Comment by paulmillr** [comment]
Awesome! :+1:

**Comment by goshakkk** [comment]
This is great news indeed, but is there any value in this issue being open? @paulmillr

**Comment by Bartmax** [comment]
my guess is that when this is communicated on readme, documentation or anywhere else it can be closed. right now here is the only place to know about this stuff.

**Comment by paulmillr** [comment]
yep

**Comment by goshakkk** [comment]
Submitted https://github.com/brunch/brunch.github.io/pull/139 to mention this one and also an Atom plugin

**Comment by denar90** [comment]
Should we close this one - https://github.com/brunch/brunch.github.io/issues/137 ?

**Comment by goshakkk** [comment]
@paulmillr close this.
