### ISSUE TITLE
Brunch with html

### ISSUE THREAD

**Issue by go-native** [brunch/brunch#1030]
Brunch works with almost the all template languages and has plugins for them, but I could't work with vanilla HTML. I just want that on every build brunch just copy my html files(wherever they are located) and paste under that appropriate location on public folder. I don't want to use jade, handlebars or whatever I just want to copy clean HTML files without any modification. Is that possible?

**Comment by es128** [comment]
Brunch was designed around the idea that templates would be compiled into html, so the workflow you want is not available in a totally straightforward way. There are workarounds. You could either define the html files as assets or make a plugin that handles writing the dest file on its own. 

The former might look something like `conventions.assets = ['assets/**/*', '**/*.html']`

As for the plugin route, if you search github for html-brunch there are several examples of how to get brunch to funnel html files into a plugin, and from there what you want to do is write them to the appropriate dest path, similar to how jaded-brunch handles jade files intended to be compiled into static html.
