### ISSUE TITLE
conventions ignored.

### ISSUE THREAD

**Issue by Bartmax** [brunch/brunch#1033]
is there any way to add to the ignore conventions instead of replace?

**Comment by es128** [comment]
Copy the defaults into your config. So no, not in the way you mean.

**Comment by Bartmax** [comment]
this are the defaults? I think it would be great to have the patter on documentation at least.

```
  conventions:
      ignored: [
        /[\\/]_/
        /vendor[\\/]node[\\/]/
        /vendor[\\/](j?ruby-.*|bundle)[\\/]/
      ]
```

**Comment by es128** [comment]
yup, PR welcome

**Comment by Bartmax** [comment]
:+1:

**Comment by Bartmax** [comment]
fixed with https://github.com/brunch/brunch/pull/1034
