### ISSUE TITLE
autoRequire for windows users fails for backslash paths

### ISSUE THREAD

**Issue by chrismccord** [brunch/brunch#1035]
In phoenix, we have reports of windows users' application js not loading https://github.com/phoenixframework/phoenix/issues/1319 , we've tracked it down to here:

https://github.com/brunch/brunch/blob/master/lib/fs_utils/generate.js#L172

our brunch-config looks like this:

```javascript
  modules: {
    autoRequire: {
      "js/app.js": ["web/static/js/app"]
    }
  },
```
But for windows users `joinKey` is `"js\app.js"` (note backslash) 

The result is the autoRequire feature is ignored. I'm not familiar enough with node to know if it should be normalizing paths, but I would be happy to send a fix if you could point me in the right direction. Thanks!

**Comment by es128** [comment]
The most obvious solutions to this within brunch could turn out to be problematic for someone else's use case, such as a project developed only by Windows users that already uses backslashes in the path keys.

It's not all that pretty, but a potentially immediate solution to this for a cross-compatible project is

```js
  modules: {
    autoRequire: {
      "js/app.js": ["web/static/js/app"]
      "js\\app.js": ["web/static/js/app"]
    }
  },
```

**Comment by ghostd** [comment]
Hi,

For now, I don't have a windows machine to check that; but could be this related to the slash config replacement?
https://github.com/brunch/brunch/blob/master/lib/helpers.js#L150

By the way, why do we replace '/' by '\' on windows ? According to the node documentation, node handles '/' on windows:
https://nodejs.org/api/path.html#path_path_isabsolute_path

Should not we replace all backslashes by slashes on windows?

(Hoping to not be off topic)

**Comment by es128** [comment]
@ghostd that's a good catch actually. That helper was added to address the equivalent issue in other parts of the config. Having it do the same thing for everything within `autoRequire` should be a good fix.

> Should not we replace all backslashes by slashes on windows?

Then we'd have to do the opposite operation in case users use backslashes in their configs. There's more to it than just whether it would work in a node `fs` or `path` operation, it needs to match up to the paths that are actually read from the file system by chokidar, which come with backslashes. 

Yes, we could probably solve it the opposite way by switching to `require('path').POSIX.normalize` at https://github.com/brunch/brunch/blob/master/lib/fs_utils/file_list.js#L4 and using it in several more places throughout that file, but I'm not sure if we gain a lot of advantage by making that switch at this point. Maybe it would be better though, preventing any future `replaceConfigSlashes` whack-a-mole. @paulmillr wdyt?

**Comment by paulmillr** [comment]
yeah

**Comment by ghostd** [comment]
@es128 imho, it's more natural for "brunch" dev beginners (like me) to handle paths with slashes than the opposite. A couple of days ago, i wanted to write some unit tests and broke the 'replaceConfigSlashes()' spec with my little refactoring. I needed some minutes to understand brunch converted the path into a non posix way.

But, maybe it's too risky/invasive to make this switch now.

**Comment by es128** [comment]
Or maybe you've correctly pointed out that the old approach was a mistake. The next release will be a major version bump, it's a good time to attempt switching it to work the other way.

**Comment by paulmillr** [comment]
Fixed.
