### ISSUE TITLE
How to replace Bower with npm for frontend dependencies in Brunch?

### ISSUE THREAD

**Issue by marcaddeo** [brunch/brunch#1037]
Hey guys,

Now that Bower has [apparently ceased development](https://twitter.com/nachocoloma/status/663622545162280960) and is "dying", how does one go about using `npm` for frontend dependencies like `jquery`, `bootstrap`, etc.?

Is Brunch smart enough to look into `node_modules` and differentiate between things like brunch plugins, sass compilers, etc. and frontends dependencies like `jquery`?

Tried googling around a bit, but didn't find much information on the subject.

**Comment by paulmillr** [comment]
We need to solve a bunch of issues to make this solid. https://github.com/brunch/brunch/issues/1023

**Comment by paulmillr** [comment]
Please keep looking into gh-1023, we'll be focusing on it pretty soon.
