### ISSUE TITLE
NPM: performance with large packages

### ISSUE THREAD

**Issue by milgner** [brunch/brunch#1038]
Brunch: 1.8.5
Node: v3.0.0
Npm: 2.13.3

First the initial problem:

Working on a [Phoenix](http://phoenixframework.org/) project, after adding `material-ui` to my `package.json`, brunch stopped working. I first increased the `nofile` ulimit to 100.000, which then resulted in the error:

```
$ node node_modules/brunch/bin/brunch build
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)
```

Not sure how to go about addressing this. My brunch config is still unchanged from the [default template](https://github.com/phoenixframework/phoenix/blob/master/installer/templates/static/brunch/brunch-config.js).

Sure, the `material-ui` package is quite large, containing 3866 files alone, but it should still be possible to use?

It may be part of the broader issue in #1023 but I'm willing to try anything; let me know if you need additional info.

**Comment by paulmillr** [comment]
I would suggest to use standalone files for now. Performance may definitely be a concern until we rework it.

**Comment by milgner** [comment]
For now I have switched to webpack to get things working, but I wanted to notify you about the problem with large NPM modules. Brunch certainly feels great, keep up the good work!
