### ISSUE TITLE
Add transition for old brunch new

### ISSUE THREAD

**Issue by bigp** [brunch/brunch#1039]
Hey, I'm not super familiar with nodejs / npm and whatnot, but once upon a time brunch used to work.

And now after trying to update my Nodejs installation with NVM (for windows) and reinstalling brunch 2.0, at least now I can see the "brunch -V" version number, but I can't create a new project from any skeleton URL.

See stacktrace error below:

	W:\_WORK\>brunch new "gh:brunch/dead-simple" brunch
	20 Nov 18:38:01 - log: Cloning git repo "https://github.com/brunch/dead-simple" to "gh:brunch/dead-s
	imple"...
	20 Nov 18:38:02 - log: Created skeleton directory layout
	20 Nov 18:38:02 - log: Installing packages...
	C:\Users\Admin\AppData\Roaming\npm\node_modules\brunch\node_modules\init-skeleton\index.js:42
	  process.chdir(rootPath);
			  ^

	Error: ENOENT: no such file or directory, uv_chdir
		at Error (native)
		at install (C:\Users\Admin\AppData\Roaming\npm\node_modules\brunch\node_modules\init-skele
	ton\index.js:42:11)
		at C:\Users\Admin\AppData\Roaming\npm\node_modules\brunch\node_modules\init-skeleton\index
	.js:123:11
		at cb (C:\Users\Admin\AppData\Roaming\npm\node_modules\brunch\node_modules\init-skeleton\n
	ode_modules\ncp\lib\ncp.js:255:23)
		at onError (C:\Users\Admin\AppData\Roaming\npm\node_modules\brunch\node_modules\init-skele
	ton\node_modules\ncp\lib\ncp.js:247:12)
		at C:\Users\Admin\AppData\Roaming\npm\node_modules\brunch\node_modules\init-skeleton\node_
	modules\ncp\lib\ncp.js:159:16
		at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by es128** [comment]
The `brunch new` command has changed in 2.0.

Take a look at the docs at https://github.com/brunch/brunch/blob/master/docs/commands.md#brunch-new

**Comment by bigp** [comment]
Nevermind, apparently I was using the parameters in the wrong order.

It's `brunch new outputDir skeletonURL`.

**Comment by paulmillr** [comment]
@bigp it's `brunch new path -s skeleton`

**Comment by bigp** [comment]
@es128 Thanks just noticed that now.

**Comment by paulmillr** [comment]
although we should probably make this as clear as possible, for folks who are used to old stuff

**Comment by paulmillr** [comment]
@bigp and for the dead-simple you don't need to pass any command. just `brunch new path`

**Comment by marcelotmelo** [comment]
Please change the page at http://brunch.io/skeletons.html. It still has the old style examples (on the top of the page).

```
brunch new <skeleton-URL> [optional-output-dir]
# Example from GitHub
brunch new gh:brunch/dead-simple
# Example from a full URL
brunch new https://github.com/paulmillr/brunch-with-chaplin
```

**Comment by paulmillr** [comment]
@marcelotmelo done

**Comment by Anaphase** [comment]
It looks like [the homepage](http://brunch.io) has also been overlooked in regards to the new skeleton command:

> Create a new Brunch project:
> `brunch new [dir] [--skeleton url]`

**Comment by profoundhub** [comment]
I tried 

> brunch new http://github.com/paulmillr/brunch-with-chaplin -s chaplin

still got the error: 

...\node_modules\brunch\node_modules\init-skeleton\index.js:51
  process.chdir(rootPath);
               ^

**Comment by paulmillr** [comment]
Try this: `brunch new -s chaplin`
