### ISSUE TITLE
Node 4 requirement for Brunch v2 not obvious enough

### ISSUE THREAD

**Issue by MaffooBristol** [brunch/brunch#1042]
Please could you advise, and I may be completely wrong in this, but doesn't v2 introduce ECMA6 language changes that will cause Brunch to break when using node.js? If so, why is this not written in the documentation or on the website anywhere? (the main site says it relies on node)

I had a circleci build, using a node container, that kept failing at the `brunch build --production` stage. On closer inspection, it was throwing out the following errors:

```
/home/ubuntu/nvm/v0.10.33/lib/node_modules/brunch/lib/cli.js:3
const program = require('commander');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/nvm/v0.10.33/lib/node_modules/brunch/bin/brunch:11:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

I've had no problems with the standard `npm install -g brunch` with a node-based npm so far, but now it seems to be installing an incompatible version, which just seems wrong. Either the docs should expressly state that iojs is required or 1.8.5 or lower should be used, or the version installed should depend on whether or not an ECMA6-compatible node build is present/being used.

Please let me know if I'm being thick and have missed something really obvious, but I haven't seen anything mentioning this yet so am a bit baffled.

Thanks!
Matt

**Comment by es128** [comment]
Well, yes, breaking changes, hence the major version bump. The changelog mentions that this version requires node >= 4.0, but I agree it should say so in the readme as well. Also the package.json `engines` field should be utilized to hopefully provide better error messages in this situation.

**Comment by paulmillr** [comment]
1. We should update the site
2. We should update docs
3. We should throw an explicit error for node v4<

**Comment by paulmillr** [comment]
3 done

**Comment by MaffooBristol** [comment]
Ah, it's a later version of node not io.js. I'm clearly quite out-of-date with node releases; I didn't realise it had jumped so many versions/incorporated iojs commits in the past few months.

Thanks for taking the time to address the issue :smile:
