### ISSUE TITLE
Order is not used for requirements

### ISSUE THREAD

**Issue by MartinMuzatko** [brunch/brunch#1046]
Hello there.
After reading the guide and the docs, there are still things unclear.

On first build, I saw that files are not compiled in the correct order.
Then I prepended main.less (which includes all less files in the right order, so brunch doesn't actually have to care about manually compiling each single file.

So I added ```order: before: ['less/main.less']``` to my config.
However, this didn't help to help brunch understand the dependencies for the other less files (like variables, mixins etc)

While I love that Brunch is doing so much for this amount of code, I think it does too much on its own. I write more code to tell brunch what NOT to do than what to do.... urgh.  

**Versions**
Brunch 2.0.1
Node Latest 5.1.0
OS: Windows 7 - x64
**package json**
```json
{
  "name": "simple-brunch",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "javascript-brunch": "^1.8.0",
    "less-brunch": "^1.8.1"
  },
  "dependencies": {
    "clean-css-brunch": "^1.8.0"
  }
}
```

**brunch-config.coffee**
```cson
module.exports = config:
	files:
		stylesheets: 
			joinTo:
				'app.css' : /^less/
			order:
				before: ['less/main.less']
	conventions:
		ignored: [
			/css/
			/js/
		]
```

**Error Log**
```
23 Nov 12:11:54 - error: Compiling of 'app\less\base.less' failed. NameError:variable @colorBackground is undefined in "app\less\base.less:10:13"
23 Nov 12:11:54 - error: Compiling of 'app\less\components.less' failed. NameError:variable @paddingContent is undefined in "app\less\components.less:107:14"
23 Nov 12:11:54 - error: Compiling of 'app\less\grid.less' failed. NameError:variable @cols is undefined in "app\less\grid.less:82:19"
23 Nov 12:11:54 - error: Compiling of 'app\less\layout.less' failed. NameError:variable @colorShadow is undefined in "app\less\layout.less:10:11"
23 Nov 12:11:54 - error: Compiling of 'app\less\forms.less' failed. NameError:.transition is undefined in "app\less\forms.less:9:1"
23 Nov 12:11:54 - warn: 'app\less\main.less' compiled, but not written. Check your stylesheets.joinTo config.
23 Nov 12:11:54 - warn: 'app\less\normalize.less' compiled, but not written. Check your stylesheets.joinTo config.
23 Nov 12:11:54 - warn: 'app\less\variables.less' compiled, but not written. Check your stylesheets.joinTo config.
23 Nov 12:11:54 - error: Compiling of 'app\less\tools.less' failed. NameError:variable @colorFillDark is undefined in "app\less\tools.less:128:8"
23 Nov 12:11:54 - error: Compiling of 'app\less\module\slider.less' failed. NameError:variable @colorFillDark is undefined in "app\less\module\slider.less:4:13"
23 Nov 12:11:54 - warn: 'app\less\vendor\normalize.less' compiled, but not written. Check your stylesheets.joinTo config.
23 Nov 12:11:54 - warn: 'app\less\vendor\progress.less' compiled, but not written. Check your stylesheets.joinTo config.
23 Nov 12:11:54 - warn: 'app\less\vendor\angular-grid.less' compiled, but not written. Check your stylesheets.joinTo config.
23 Nov 12:11:54 - warn: 'app\less\vendor\animate.less' compiled, but not written. Check your stylesheets.joinTo config.
23 Nov 12:11:54 - info: compiled in 1.9 sec
```

**Comment by es128** [comment]
@MartinMuzatko Brunch does not concatenate the source files, only the generated css. It's still up to you to use `@import` statements if your files depend on each other for variables and such. And once you do that, you no longer want Brunch directly compiling the dependency files that will be brought in by other means. Brunch has the convention that you'd name all the include files with an underscore `_` prefix to have them automatically ignored by the regular pipeline. 

There are other methods as well, like you could try `joinTo: 'app.css' : 'less/main.less'`, but that would only be a partial solution that would likely give you the correct end result, but wouldn't suppress the errors and warnings in the log until you also modified your watched paths or something along those lines.

Doesn't look to me like this is a bug though.

**Comment by MartinMuzatko** [comment]
@es128 by default, less concatenates the sources via the @​import keyword. (in the main.less file)
I think this issue belongs to  [less-brunch](https://github.com/brunch/less-brunch), and this existing issue ( https://github.com/brunch/less-brunch/issues/2#issuecomment-5005924 ) already adresses the problem, I think.

I did the same as described in the comment: import all files in their correct order in a single main file.

**Comment by es128** [comment]
@MartinMuzatko that comment is talking about the same thing I tried to explain, but it seems you're not understanding the point.

Your `main.less` is part of the solution, but you still have an issue where Brunch is trying to compile the imported files directly. You need to prevent that by either:

1. renaming each of the imported files to be prefixed with an underscore, such as `app\less\_components.less`; 
2. moving those files outside of the directories Brunch is watching, which is what the comment you linked to explained; or 
3. modify your `paths.watched` in such a way that it watches `main.less`, but not all your other files that get imported.

Another completely different strategy would be to eliminate `main.less`, `@import "variables.less"` in each of your files that needs it along with any other dependencies, and if any ordering requirements remain set it yourself in `stylesheets.order.before`.

It's all about how you want to organize your project, and Brunch is flexible enough to provide you several approaches. If you want to be most closely aligned with Brunch's opinionated structure, you should follow strategy 1 above with the underscore prefixed renaming.

**Comment by MartinMuzatko** [comment]
Alright, thank you for the clarification @es128
