### ISSUE TITLE
`app.js` in `joinTo` includes everything in `vendor`

### ISSUE THREAD

**Issue by jingweno** [brunch/brunch#1049]
I have the following setup:

```coffeescript
  files:
    javascripts:
      joinTo:
        'javascripts/app.js': /^app/
        'javascripts/vendor.js': /^vendor/
```

`app.js` includes everything in `vendor` but `vendor.js` only includes things in `vendor`. The regexp `/^app/` doesn't seem to work properly...

**Comment by es128** [comment]
Use the `--debug` switch to see how brunch is finding and joining files. See if you have a symlink somewhere under `app` that points to `vendor`.
