### ISSUE TITLE
build -p error

### ISSUE THREAD

**Issue by darren131** [brunch/brunch#1056]
When running `brunch b -p` (or `brunch -e production`) I get this massively cryptic error:

`error: [TypeError: Cannot read property 'toString' of undefined]`

Has anyone encountered this – or could point me in the right direction? Thanks!

Here's the contents of my package.json
```javascript
{
  "name": "JointsWP-brunched",
  "version": "4.0.0",
  "description": "A WordPress starter theme using Foundation 6, modified from JointsWP to use brunch and npm",
  "author": "Jeremy Englert, modified by The Fold",
  "license": "",
  "engines": {
    "node": "~0.6.25 || 0.8 || 0.9"
  },
  "dependencies": {
    "auto-reload-brunch": "latest",
    "autoprefixer": "latest",
    "babel-brunch": "^5.1.2",
    "brunch": "^2.0.2",
    "clean-css-brunch": "latest",
    "css-brunch": "latest",
    "foundation-sites": "latest",
    "javascript-brunch": "latest",
    "jquery": "2.1.4",
    "motion-ui": "latest",
    "postcss-brunch": "latest",
    "sass-brunch": "latest",
    "uglify-js-brunch": "latest"
  },
  "devDependencies": {}
}
```

and here's the contents of my brunch-config

```coffee
exports.config =
  # See http://brunch.io/#documentation for docs.
  paths:
    public: 'assets'

  files:
    javascripts:
      joinTo:
        'js/scripts.js': /^(app[\\/]js)/
        # 'js/vendor.js': /^(vendor)/ # uncomment this if you want to use the brunch vendor file/folder/system
    stylesheets:
      joinTo:
        'css/style.css':[
           /^(app[\\/]scss[\\/]style)/
        ]
        'css/login.css':[
           /^(app[\\/]scss[\\/]login)/
        ]

  modules:
    wrapper: false
    definition: false

  plugins:
    sass:
      debug: 'comments' # or set to 'debug' for the FireSass-style output
      mode: 'native' # set to 'native' to force libsass, or 'ruby' for.... ruby!
      allowCache: true

    postcss:
      processors: [
        require('autoprefixer')(['ie > 8, last 2 versions']),
      ]
```

**Comment by paulmillr** [comment]
`-d` output would be great. could you create a gist with that?

**Comment by darren131** [comment]
@paulmillr sure thing – wish I'd known about -d before posting this thread...

Gist here:
https://gist.github.com/darren131/74c1253ccf76d47a859a

Thanks!

**Comment by WeKyle** [comment]
I'm having a similar error when building for production, however I bump into it with Uglify instead of PostCSS.

**Comment by paulmillr** [comment]
Folks, it would be extremely helpful if you could provide a test repo with that. Could you do this please?

**Comment by darren131** [comment]
@paulmillr sure – here's the repo including all the things: https://bitbucket.org/crafttheweb/jointswp (sorry – no github)

**Comment by WeKyle** [comment]
@paulmillr The repository I'm working on is my employer's, not mine, so I created a repository that very simply recreates what I'm running into [here](https://github.com/WeKyle/brunch-error).

Running `brunch b -p` should cause the error.

**Comment by paulmillr** [comment]
@WeKyle @darren131 thanks for this! Fixed.

**Comment by paulmillr** [comment]
2.0.4 is up.

**Comment by darren131** [comment]
@paulmillr you're a bloody legend! Thanks
