### ISSUE TITLE
Upgrade Express Version

### ISSUE THREAD

**Issue by sabrehagen** [brunch/brunch#1060]
Currently your `package.json` specifies express `3.3.0` but the current release of express is `4.13.3`. When writing a custom server this poses an issue as functionality available in express `4.13.3` is not available due to the version specified by your `package.json`. Seeing as express is only being used in your tests to serve static files, this shouldn't pose any breaking changes if you update the version.

**Comment by paulmillr** [comment]
`pushserve` is used with express 4 for "server".

package.json mentions it as devDependency which doesn't really matter, yep

**Comment by paulmillr** [comment]
40c5d6345416d50b2d6e3cb5e125cb4b463be9c7
