### ISSUE TITLE
Need to concatenate styles before running Sass?

### ISSUE THREAD

**Issue by erlandsona** [brunch/brunch#1065]
Is there a way with brunch to concatenate all the .scss files before running them through the sass plugin? And then using the order: before: to put the "sass dependencies" (variables, mixins, etc...) at the top of the file...

I'm trying to migrate a project from folders by type to folders by feature. Read: https://github.com/borisschapira/brunch-with-a-sassy-zigzag/tree/master/app

But given that the styles were setup as folders by type under a styles folder with partials I need more fine grained control over how the styles are being handled.

I want to concatenate all sass files first starting with a dependencies file that imports a couple variables files. then run sass on the output of that then put that file into the public directory? Thoughts?

**Comment by es128** [comment]
Don't want to search for it, but this has been requested in the past. Brunch is not currently set up to allow for pre-compile concatenation. Might be possible with a clever plugin, but it's probably an uphill battle.
