### ISSUE TITLE
Rename to whitelist and blacklist

### ISSUE THREAD

**Issue by ryansobol** [brunch/brunch#1066]
If `npm.packages` and `npm.exclude` are here for a while, is there any chance they could be renamed to `npm.whitelist` and `npm.blacklist` respectively?

https://github.com/brunch/brunch/blob/master/lib/deppack.js#L153

**Comment by paulmillr** [comment]
Good idea. cc @goshakkk

**Comment by paulmillr** [comment]
although we have `off` and `on` for plugins.
