### ISSUE TITLE
brunch 1.8+ build sometimes skip files on Ubuntu

### ISSUE THREAD

**Issue by vmkcom** [brunch/brunch#1072]
I have strange issue with ubuntu 14.04 and brunch 1.8.0+ (include 2.x versions)
Some of my production brunch builds makes a corrupted template .js file. Brunch just build not all of my files in my templates folder. Strange behaviour reproduces only with big folder (128 files) and working great with other small folders

I'm testing brunch build feature with loop command and only one static-underscore-brunch plugin with my /templates folder
```
for i in `seq 100`; do brunch b -P; done
```
and some of iterations do not compile all files. So it's may be a cache (fcache I think).
It's working great with OS X, and it's not working if I make some sleep timeout, or just wait a minute before another rebuild

In my brunch-config.coffee I have
```
	onCompile: (generatedFiles) -> 
		for f in generatedFiles
			if ///\.js$///.test f.path
				console.log f.path, '<-', f.sourceFiles.length + '.html files'
```
and output: 
```
/constructor_desktop.js <- 128.html files
compiled 51 files into constructor_desktop.js in 648ms
/constructor_desktop.js <- 51.html files
compiled 115 files into constructor_desktop.js in 678ms
/constructor_desktop.js <- 128.html files
compiled 115 files into constructor_desktop.js in 655ms
/constructor_desktop.js <- 128.html files
compiled 115 files into constructor_desktop.js in 655ms
/constructor_desktop.js <- 128.html files
compiled 115 files into constructor_desktop.js in 697ms
/constructor_desktop.js <- 51.html files
compiled 67 files and 51 cached into constructor_desktop.js in 176ms
```

With brunch@1.7.20 building working great, so it seems like fcache package has problems with ubuntu 14.04

maybe we can disable caching for --production builds?

**Comment by paulmillr** [comment]
Fcache has nothing to do with it. Could you provide a test repository? I would download ubuntu to a VM and test your case there.

**Comment by vmkcom** [comment]
ok, give me some time, I'll try to prepare some test data

**Comment by vmkcom** [comment]
hm... I can't reproduce that bug with test data, only with production. Seems file size & complexity for brunch has some effect. 

I can't share production templates right now. So we can close issud, I'll try to reproduce bug by myself.

Anyway it would be nice to have option for disable caching for production builds. For me - it's fixes problem

**Comment by paulmillr** [comment]
Which caching? How do you disable it?

**Comment by vmkcom** [comment]
I mean that log string
```
compiled 67 files and 51 cached into constructor_desktop.js in 176ms
```
cached feature was added by 1.8+ version, so I'm just using 1.7.20 version for now. But, if I made brunch 1.8 without caching feature (just copying code from 1.7.20), everything working nice.

Trying to reproduce bug on other plugins (css, js, not templates)

**Comment by paulmillr** [comment]
Brunch 1.8 didn't enable caching. It just started writing down detailed logs of compilation. The caching was there since brunch 1.1 at least.

**Comment by vmkcom** [comment]
I mean https://www.npmjs.com/package/fcache package. Maybe problem with it

**Comment by paulmillr** [comment]
How is 2.2.1 lloking for you @vmkcom ?

**Comment by Florian-R** [comment]
Ran myself into this one (even with 2.2.1).  After some searches, it appears to be a dupe of #889, increasing the `fileListInterval` through an override for production solve the problem with a slow CI.
