### ISSUE TITLE
Wrong handling of cli options

### ISSUE THREAD

**Issue by ghostd** [brunch/brunch#1075]
Hi,

I was testing [flow](http://flowtype.org/) againt brunch and i found this bug in watch.js (options should not be quoted):
```
if (typeof 'options' === 'function') {
```

It seems the bug is here since the start of the feature:
https://github.com/brunch/brunch/commit/a88d5cc8849c0d168675434d78785a8371a19131

So, should we fix it or remove it?

**Comment by paulmillr** [comment]
fix.

**Comment by ghostd** [comment]
https://github.com/brunch/brunch/pull/1076
