### ISSUE TITLE
Specify node version on install?

### ISSUE THREAD

**Issue by jean** [brunch/brunch#1080]
I installed phoenix and created a new app including dependencies:

```
Fetch and install dependencies? [Yn]
* running npm install && node node_modules/brunch/bin/brunch build
```

This completes without error, but results in a broken install:

```
$ mix phoenix.server
[info] Running Splurty.Endpoint with Cowboy using http on port 4000
Error: Brunch 2+ requires node v4.0+. Upgrade node or use older brunch for old node.js: npm i -g brunch@1
```

Suggestion: specify node version in `package.json` (`engines` field).

**Comment by paulmillr** [comment]
`engines` field is deprecated, isn't it?

**Comment by jean** [comment]
AFAICS `enginesStrict` is deprecated, not `engines`.
