### ISSUE TITLE
Minify HTML

### ISSUE THREAD

**Issue by MentalGear** [brunch/brunch#1081]
Is there a minify HTML plugin available for brunch?
Or is it possible to import one from gulp ?

**Comment by MentalGear** [comment]
Mh.. this jade plugin seems pretty sweet (maybe even better than the ones advertised on the official plug-in pages) and allows html min when compiled from jade. Is there a reason this one isn't listed on the brunch plugin page? It's pretty well documented!

https://www.npmjs.com/package/jade-pages-brunch

**Comment by MentalGear** [comment]
Mh.. this jade plugin seems pretty sweet (maybe even better than the ones advertised on the official plug-in pages) and allows html min when compiled from jade. Is there a reason this one isn't listed on the brunch plugin page? It's pretty well documented!

https://www.npmjs.com/package/jade-pages-brunch

**Comment by paulmillr** [comment]
The owner of that plugin haven't added it to the page (it's a manual procedure). We'll need to add it there.
