### ISSUE TITLE
Change convention assets folder - Brunch 2.0.1

### ISSUE THREAD

**Issue by GesJeremie** [brunch/brunch#1084]
From what I saw it's possible to change the folder's name of the **assets** folder, is it possible to change where the folder is (Move it from **app** folder to the **root** folder) ? 

If it's possible, what I need to set in the brunch-config file ? 

Kind regards,

Jérémie

**Comment by paulmillr** [comment]
The first one is `paths.watched`, the second one is `paths.public`. Check out the docs: https://github.com/brunch/brunch/blob/master/docs/config.md

**Comment by GesJeremie** [comment]
In paths.watched how I can say the entity "root" ? Like that ?

```
paths:
  watched: ['']
```

**Comment by paulmillr** [comment]
Not possible i'm afraid.
