### ISSUE TITLE
Add ability to only lint files.

### ISSUE THREAD

**Issue by Florian-R** [brunch/brunch#1101]
Related to #988 in some way

Use-case: I just want to lint my specs with the watcher, but without the extra compile.

Actually, files are linted only if they are watched (or at least it seems so, let me know if I'm wrong).

Problem is that watching specs without putting them in a joinTo cause warns like: 
`warn: test/foo.js compiled, but not written. Check your javascripts.joinTo config`

So I've tried to set my specs in `conventions.ignored`, but in this case, they're not linted anymore, and moreover, this cause an extra compile which is not needed.

I'm not sure of what could be a good API to say: "Watch this files, if they change, just run the linters but don't do anything else". Maybe something simple like `conventions.linted`

* `linted` key: [anymatch set](https://github.com/es128/anymatch#anymatch-). Default value: `/(^test)[\\/]/`. If test gives true, files will be linted but no compile step.

Maybe I miss something but having tested different setup, I couldn't find a way to achieve this yet. Thoughts?

**Comment by paulmillr** [comment]
There are no plans to add 1-to-1 compilation in the near future. You'd need to concatenate everything into 1/2/etc files, or compile the stuff.

Are you able to concatenate specs into one?

**Comment by Florian-R** [comment]
Compiling specs into an extra file even if this is not needed solve it indeed, I' hadn't  thought about this possibility. 

There's always the compilation on spec change which cause trouble in my case, but that's another issue.

Closing for now, will reopen if I find compelling use-case or a better API to fit this case.

Thanks for your input.

**Comment by mikezx6r** [comment]
Question: I believe you're saying add an entry to javascripts.joinTo of nature `'test.js' : /^test/`. Is that correct?

Doesn't that mean there will be an extra file in public? 

If so, how do I easily filter that out as I obviously don't want to deploy/distribute my tests.

**Comment by paulmillr** [comment]
You can specify a separate `joinTo` entry for `environment: production` — so that the test.js wouldn't be built in production.

**Comment by mikezx6r** [comment]
Thank you so much for both Brunch, and the quick response. Just delving deeper into configuration, and didn't think of overrides.
