### ISSUE TITLE
Question: Workflow for different areas.

### ISSUE THREAD

**Issue by Bartmax** [brunch/brunch#1102]
I'm developing a website, public and an admin side. Both "areas" are very different and uses different libraries, on same project.

Is there any recommendation or how one should configure brunch in a way that it handles dependencies for the admin area different than the ones used on the public area ?

For example purposes imagine :

Admin uses: 
- bootstrap 3.3.6
- jquery 2.1.4
- datatables
- holder.js 
- admin/js/admin.js
- and many others libs

While public uses:
- bootstrap 4
- jquery 2.1.4
- font-awesome
- site/js/site.js

**Comment by paulmillr** [comment]
Two ways:

1. Make two Brunch apps, build everything into one folder etc.
2. Make one brunch app, place admin files in `vendor/admin`, concatenate the result to `public/admin/vendor.js` & `public/admin/app.js`; and the public to `site/vendor.js` & `site/app.js`.
