### ISSUE TITLE
Question: Can compile output multiple results?

### ISSUE THREAD

**Issue by bryanjos** [brunch/brunch#1107]
I'm working on a brunch plugin for elixirscript. Currently the elixirscript compiler outputs its standard library along with the user's code compiled to javascript. In the compile function of the brunch plugin, I'm passing in the path to the elixirscript compiler and splitting the output into the separate javascript modules. 

Is it possible to send each compile javascript module into the pipeline as separate items? Right now if I try to execute the callback more than once, only one item is added and passing an array doesn't seem to work either

**Comment by paulmillr** [comment]
See `joinTo` config option. You can specify multiple outputs from the same / similar inputs.

Something like

```
joinTo: {
  'app1.js': /^app\/(hello|whatsup)/,
  'app2.js': /^app\/hello/
}
```

**Comment by bryanjos** [comment]
I'm not 100% sure that's what I'm looking for. In my case now I have something like this:

```js
ElixirScriptPlugin.prototype.compile = function(params, callback) {

  //call compiler using path set in plugin specific settings
  exec("elixirscript '" + this.config.path + "'", function(error, stdout, stderr){
    if(error){
      return callback(error);
    }

    //split up output into separate javascript module code strings
    var codeArr = stdout.split("//---EndFile---//");

    //For each call the callback to add to pipeline
    //Or instead call callback sending array like: callback(null, codeArr);
    codeArr.forEach(function(code){
      callback(null, code);
    });
  });
};
```

I'm just not sure if it's possible to send more than one code result into the pipeline in the same call to compile.

**Comment by es128** [comment]
@bryanjos Brunch does not inherently support that currently, and there wouldn't be a point since everything is getting concatenated anyway. But the plugin *could* take responsibility for writing output files on its own if that is desired (with node code APIs like `fs.writeFile`), with or without also providing separate output back to Brunch to be concatenated.

**Comment by bryanjos** [comment]
@es128 Thanks! I'll look into doing that.
