### ISSUE TITLE
Question: Does Brunch support multiple entry points for ES6 modules?

### ISSUE THREAD

**Issue by JHKennedy4** [brunch/brunch#1110]
I'd like to specify different entry points for different pages so that I only end up requiring the modules I need on those pages. Is there something like joinTo, but for an entry file instead of a directory? I attempted to just set joinTo to point at a file, and then to a directory with just that file in it, but neither of those approaches has worked.

**Comment by es128** [comment]
Brunch does not do module resolution for your code (as opposed to npm modules) nor incorporate the concept of entry points. You need to specify which source files you want concatenated together with `joinTo`
