### ISSUE TITLE
ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by dsiddharth2** [brunch/brunch#1121]
brunch watch —server
/usr/local/lib/node_modules/brunch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/polyfills.js:18
  chdir.call(process, d)
        ^

Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at process.chdir (/usr/local/lib/node_modules/brunch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/polyfills.js:18:9)
  at Promise.all.then.setProp.constructor.application.loadConfig.then.then.initCompilation.initWatcher.chokidar.watch.on.on.absPath.on.compile.assetErrors.forEach.Promise.all.then.then.watch (/usr/local/lib/node_modules/brunch/lib/watch.js:335:15)
  at exports.new.start (/usr/local/lib/node_modules/brunch/lib/index.js:27:10)
  at Command.listener (/usr/local/lib/node_modules/brunch/node_modules/commander/index.js:301:8)
  at emitTwo (events.js:87:13)
  at Command.emit (events.js:172:7)
  at Command.parseArgs (/usr/local/lib/node_modules/brunch/node_modules/commander/index.js:615:12)
  at Command.parse (/usr/local/lib/node_modules/brunch/node_modules/commander/index.js:458:21)
  at Object.keys.forEach.exports.run (/usr/local/lib/node_modules/brunch/lib/cli.js:73:11)
  at loadBrunch (/usr/local/lib/node_modules/brunch/bin/brunch:34:7)
  at /usr/local/lib/node_modules/brunch/bin/brunch:41:7
  at LOOP (fs.js:1534:14)
  at doNTCallback0 (node.js:419:9)
  at process._tickCallback (node.js:348:13)

Everything else is working in brunch command. The command was working and starting the server until one day back. Today it just stopped.

npm -version
2.14.12

brunch -version
2.1.3

Any help would be appreciated.

Thank you.

**Comment by goshakkk** [comment]
Are you using the master version? If not, can you try one? npm install -g
brunch/brunch
On Thu, Jan 21, 2016 at 12:03 PM Siddharth Deshpande <
notifications@github.com> wrote:

> brunch watch —server
>
> /usr/local/lib/node_modules/brunch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/polyfillsjs:18
> chdircall(process, d)
> ^
>
> Error: ENOENT: no such file or directory, uv_chdir
> at Error (native)
> at processchdir
> (/usr/local/lib/node_modules/brunch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/polyfillsjs:18:9)
> at
> PromiseallthensetPropconstructorapplicationloadConfigthentheninitCompilationinitWatcherchokidarwatchononabsPathoncompileassetErrorsforEachPromiseallthenthenwatch
> (/usr/local/lib/node_modules/brunch/lib/watchjs:335:15)
> at exportsnewstart (/usr/local/lib/node_modules/brunch/lib/indexjs:27:10)
> at Commandlistener
> (/usr/local/lib/node_modules/brunch/node_modules/commander/indexjs:301:8)
> at emitTwo (eventsjs:87:13)
> at Commandemit (eventsjs:172:7)
> at CommandparseArgs
> (/usr/local/lib/node_modules/brunch/node_modules/commander/indexjs:615:12)
> at Commandparse
> (/usr/local/lib/node_modules/brunch/node_modules/commander/indexjs:458:21)
> at ObjectkeysforEachexportsrun
> (/usr/local/lib/node_modules/brunch/lib/clijs:73:11)
> at loadBrunch (/usr/local/lib/node_modules/brunch/bin/brunch:34:7)
> at /usr/local/lib/node_modules/brunch/bin/brunch:41:7
> at LOOP (fsjs:1534:14)
> at doNTCallback0 (nodejs:419:9)
> at process_tickCallback (nodejs:348:13)
>
> Everything else is working in brunch command The command was working and
> starting the server until one day back Today it just stopped
>
> Any help would be appreciated
>
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brunch/brunch/issues/1121>.
>
-- 
Cheers,
Gosha

**Comment by dsiddharth2** [comment]
Yeah I will give it a try now.

**Comment by dsiddharth2** [comment]
No Sorry. Could not make it to work. Do you have any other solution. ?

**Comment by goshakkk** [comment]
Can you create a repo with a small app that reproduces the issue?
On Thu, Jan 21, 2016 at 12:24 PM Siddharth Deshpande <
notifications@github.com> wrote:

> No Sorry. Could not make it to work. Do you have any other solution. ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brunch/brunch/issues/1121#issuecomment-173512471>.
>
-- 
Cheers,
Gosha

**Comment by dsiddharth2** [comment]
Hi,

I tried to create a new project using,
brunch new test-project -s https://github.com/oddpixel/brunch-steak

And tried to start server using,
brunch watch --server

And then stopped using control + c in Mac.

Then went back to older project and ran,
brunch watch --server

It worked like a charm.

I think the problem would be rising when I do not stop server using Control + c, But Still I am not sure. Have to try it and see.

Cheers,
Sid

**Comment by paulmillr** [comment]
@dsiddharth2 try removing node_modules and reinstalling packages: `npm install`

**Comment by Calvinp** [comment]
Hi,

I had this same error but for a different reason today. We recently upgraded our Brunch from version 1.x to 2.x, and the option to specify port was changed from -p to -P. Specifying the wrong option caused exactly this issue.

This issue is near the top of Google searches for the ENOENT error, so I'm mainly leaving this comment here to help other people who may come across it that way.

-- Calvin Pomerantz

**Comment by goshakkk** [comment]
@paulmillr this doesn't appear to be a bug as `brunch w -p 80` would try to load the app from a directory named `80`. Perhaps the error message should be updated to warn about the change of the port option?

**Comment by paulmillr** [comment]
Yep

**Comment by goshakkk** [comment]
Submitted https://github.com/brunch/brunch/pull/1149 to address the -p/-P confusion with an error

**Comment by dsignr** [comment]
This issue still persists with NPM version 4.1.2. Downgrading to 3.9.3 fixed my problem.

**Comment by eromoe** [comment]
`brunch watch --server` works fine on node 6.9.5

But `brunch watch --server 0.0.0.0:3333` get this error too.

https://github.com/brunch/brunch/issues/1674
