### ISSUE TITLE
Brunch removes strict mode from modules

### ISSUE THREAD

**Issue by colinbate** [brunch/brunch#1126]
When brunch bundles files together it uses a function in `deppack.js` called `getNewHeader` which adds the line:

    var require = __makeRequire((req), {...});

to the top of each function. This has the side effect of making `'use strict';` the second line of the function (if it was there in `source`) which then means it doesn't execute in strict mode.

This unfortunately causes an infinite loop in `zone.js` v0.5.10. Looking at their source, I believe they've fixed that issue, but the larger concern about strict mode remains. I think Brunch should check if strict mode is invoked in the source and if so, move it up to the top of the function.

Happy to make a pull request unless you'd rather tackle this yourself.

**Comment by goshakkk** [comment]
Opened #1127 to address this

**Comment by colinbate** [comment]
Great thanks.

**Comment by colinbate** [comment]
Any idea when the next version of Brunch will be published with this fix included?

**Comment by paulmillr** [comment]
We would need to adjust this fix and test on all platforms. In a few days probably.
