### ISSUE TITLE
NPM: Support package.json#browser property

### ISSUE THREAD

**Issue by larryhengl** [brunch/brunch#1136]
Love Brunch, glad to use it again.  Thank you for this tool!

Trying the npm feature and hitting an error in the brunch build:
```Resolving deps of node_modules/superagent/lib/client.js failed. Could not load module 'emitter' from 'node_modules/superagent/lib'```

[superagent](https://github.com/visionmedia/superagent) apparently has a [package.json](https://github.com/visionmedia/superagent/blob/master/package.json) file that includes a "browser" key for 'emitter' which redirects to a different dep module called component-emitter.  
```
"browser": {
    "./lib/node/index.js": "./lib/client.js",
    "emitter": "component-emitter",
    "reduce": "reduce-component",
    "./test/support/server.js": "./test/support/blank.js"
  },
```
(same with reduce).

Component-emitter is installed but the client.js file requires 'emitter'.  And that require() call is faking out the brunch dep checker?  Looks like the dep resolution done by brunch does not follow the 'browser' key.  

I found a spec at  https://github.com/defunctzombie/package-browser-field-spec  for whatever that's worth.

Simply changing the require() call fixes it, but doesn't help when the superagent package is re-installed.

**Comment by goshakkk** [comment]
Brunch is actually using [browser-resolve](https://github.com/defunctzombie/node-browser-resolve) to resolve deps and it does have `browser` support. Might be related to this specific package or something... I'm on it

**Comment by daisuke-morita** [comment]
This seems not to be fixed in version 2.4.2. I tried with [superagent](https://github.com/visionmedia/superagent), and then [axios](https://github.com/mzabriskie/axios). Both produced the same "Cannot find module" error.

The axios's case might be a little tricky:

https://github.com/mzabriskie/axios/blob/master/package.json#L61

"Cannot find module" error will occur when calling axios's function.

**Comment by goshakkk** [comment]
@daisuke-morita this seems like a regression of https://github.com/brunch/brunch/commit/8bd5257fc0acde4d1e6c84dedfb723ce1568faf8 (2.4.0–2.4.2)

Can you confirm if superagent and axios are working properly with brunch 2.3.x?

Got it working locally with 2.3.x. Submitting a fix for 2.4

**Comment by goshakkk** [comment]
@daisuke-morita https://github.com/brunch/brunch/pull/1206

**Comment by daisuke-morita** [comment]
> Can you confirm if superagent and axios are working properly with brunch 2.3.x?

I downgraded brunch to 2.3.2 and tried superagent again and it worked without errors, however, axios didn't work and produced the same error when runtime:

```
"Cannot find module \"axios/lib/adapters/xhr\" from \"axios/lib/core/dispatchRequest\""
```

**Comment by goshakkk** [comment]
@daisuke-morita yep, if I was just able to reproduce that by `axios.get`, it is indeed and issue and will be fixed

**Comment by goshakkk** [comment]
@daisuke-morita I've added the fix to that same PR

**Comment by daisuke-morita** [comment]
@goshakkk Wow, thanks for the quick response!

**Comment by kenleytomlin** [comment]
@goshakkk Great thanks for the fix I've just come across this issue myself with superagent and brunch 2.4.2
