### ISSUE TITLE
Getting errors with new process shim

### ISSUE THREAD

**Issue by colinbate** [brunch/brunch#1141]
Somewhere between 2.2.1 and 2.2.2 something happened to cause my modules to have errors. I think there is some invalid code being generated around the npm modules, something do to with the `process` "module".

Uncaught Error: Cannot find module "process" from "/"

I see in my generated vendor.js file I'm getting this is being output near the bottom, just before the auto-reload stuff and the root module for this file. `Reflect` in this case is something I have registered as an `npm.globals`. This is one of the conspicuous diffs from when I generate from 2.2.1

```js
require.register('process/browser', function(exports,require,module) {
    module.exports = require('process');
  });process = require('process');})();window.Reflect = require('es7-reflect-metadata/dist/browser');// shim for using process in browser

var process = module.exports = {};
var queue = [];
var draining = false;
// ... more of what looks to be the process/browser implementation.
```

Let me know if I can help you with anything on this one.

**Comment by paulmillr** [comment]
https://github.com/phoenixframework/phoenix/issues/1493#issuecomment-176734287 may be related

**Comment by colinbate** [comment]
OK I figured out what is happening.

This will only happen if your project path contains the word "brunch" which mine does. It is pretty obscure, but will certainly hit other people. I'll submit a PR.

FYI, while exploring I noticed that you convert full paths to relative paths differently in different places.
```js
// In deppack.js
const makeRelative = path => path.replace(process.cwd() + sysPath.sep, '');
// vs in watch.js
require('path').relative('.', path);
```
