### ISSUE TITLE
Cascading Configuration Sheet

### ISSUE THREAD

**Issue by Velok** [brunch/brunch#1152]
I did some thinking about an alternative implementation of the configuration. I know that brunch will follows the principle convention over configuration but what about a css style cascading config format? The default config could be something like my example which is similar to the standard convention.

**PROPERTIES:**
- compile: compile scripts and styles, e.g jade -> js, scss -> css, ec6 -> js ; the equivalent plugins for the compiling are needed
- wrapping: wraps the files for usage as a module
- uglify: compress the files
- foldercopy: recursively copy folders to the target
- concatorder: integer to determine in which order the files will be concatenate (usage like z-index)
- concatenation: files which are in the same folder on the target side after the copy process will be concatenate
- concatfile: name of the generated file
- mapping: generate sourcemaps
- ignored: the path is ignored and will not be processed or copied at all
- watched: the path is watched

**EXAMPLE:**

Structure:

```
project
  app
    views
    assets
  development
  production
  vendor
```
config.ccs:

```
source = /^\.\/app$/;
vendor = /\..*?vendor\/;
assets = /^\.\/app\/assets$/;
plugins = something that matches all plugins from the bower and node jsons
templates = /^\.\/app\/views$/;


scripts = /.+\.(js|coffee|ts|jade)$/i;
styles = /.+\.(css|scss|LESS)$/i;


development:

* {
  destination: './development';
  ignored: true;
  watched: false;
  foldercopy: false;
  wrapping: false;
  concatenate: false;
  uglify: false;
  mapping: false;
}

source, plugins {
  ignored: false;
  watched: true;
}
assets { foldercopy: true; }

scripts, styles, templates {
  compile: true;
  wrapping: true
  concatenate: true;
  mapping: true;
}

vendor {
  ignored: false;
  watched: true;
  wrapping: false;
  concatenate: true;
}

scripts, templates { concatfile: 'app.js'; }
styles { concatfile: 'app.css'; }

vendor scripts { concatfile: vendor.js }
vendor styles { concatfile: vendor.css }

plugins scripts { concatfile: plugins.js }
plugins styles { concatfile: plugins.css }


production:

* {
  destination: './production';
  uglify: true;
}

scripts, styles { mapping: false; }
```
**INFOS:**

- subfolders inherits options from the parent folder.
Example:  * -> all files and folders ignored
          source -> all subfolders and files not ignored

- the file is parsed from top to bottom,  so be aware of overwritten properties.

- uglify renames the files with .min

**Comment by paulmillr** [comment]
The syntax feels too complex. Sorry.
