### ISSUE TITLE
Assets not being modified during onCompile

### ISSUE THREAD

**Issue by mcfarljw** [brunch/brunch#1154]
I've made a brunch plugin that does string replacements during onCompile, but I noticed recently that they are no longer working with files in the assets directory (ie. index.html, manifest.json). I vaguely recall prior to version 2 this working.

https://github.com/jernung/replace-brunch/blob/master/index.js#L99

I'm just speculating, but it feels like onCompile is now firing before the assets are merged. Thoughts?

**Comment by paulmillr** [comment]
@goshakkk could you check if that works?

**Comment by goshakkk** [comment]
Actually, the behavior of `onCompile` of Brunch `2.x.x` seems to be consistent with that of `1.8.5`, for example. 

The `onCompile` callback is fired even when just an asset is changed, **however**, the paths that are passed to the callback are only *compiled* files, not assets. So, in case you change just an asset file, `onCompile` will receive an empty array.

Related code in 1.8.5 — https://github.com/brunch/brunch/blob/b8b25bc2c0e6dd21a8ad3d2a8e0157e770f3d3d2/src/watch.coffee#L283-L285

A demo repo with brunch 1.8.5 — https://github.com/goshakkk/brunch-onCompile-assets-test

@mcfarljw do you have a demo of that callback receiving paths of assets?

**Comment by mcfarljw** [comment]
No, I don't have an example and it appears my vague recollection was incorrect. I had actually implemented a more complex solution for handling that scenario in the past.

Is there currently a way to get the updated files, not just ones that have been compiled?

**Comment by goshakkk** [comment]
@mcfarljw not yet... @paulmillr do you think we should add it?

**Comment by paulmillr** [comment]
Yep. We can just pass it as a second argument.

**Comment by mcfarljw** [comment]
:thumbsup: Excellent!

**Comment by goshakkk** [comment]
I've created https://github.com/brunch/brunch/pull/1172 to pass changed assets to the callback

**Comment by Sylvareth** [comment]
There appears to be a small issue with the changedAssets parameter for onCompile during brunch w -s. Sometimes it randomly returns an empty array, even though an asset was changed. I traced this back to the "copiedAfter" function in node_modules/brunch/lib/fs_utils/file_list.js. Changing 'asset.copyTime > time' to 'asset.copyTime >= time' fixed this for me.
