### ISSUE TITLE
Bower is required

### ISSUE THREAD

**Issue by skalee** [brunch/brunch#1173]
1. Fresh NodeJS install (installed via Homebrew so npm is present)
2. `$ npm install -g brunch`
3. `$ brunch new project_name`

Resulted with error:
```
 Feb 22:59:52 - error: Error: You need to install Bower and then install skeleton dependencies: `npm install -g bower && bower install`. Error text: /bin/sh: bower: command not found
npm WARN your-app@0.0.1 No license field.
```

Installing bower helped, naturally. But my point is that if Bower is required for Brunch, then it should be installed as a dependency. Or, if it's a bad idea for some reason, the "Getting started" section on the home page should mention it.

**Comment by paulmillr** [comment]
Bower is not required. I have removed bower.json from the default skeleton.
