### ISSUE TITLE
Bower components not integrating with brunch in windows.

### ISSUE THREAD

**Issue by farhan2106** [brunch/brunch#1176]
Hi, 

Brunch not able to generate libraries.js for me in windows. 

However, when I try in Debian, it is generating libraries.js

When I do a npm install at my project root in windows. I get the following. Don't know if it means anything.

> npm WARN package.json brunch-app@0.1.0 No license field.
npm WARN prefer global brunch@2.3.0 should be installed with -g
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global node-gyp@3.2.1 should be installed with -g

> node-sass@3.4.2 install C:\Users\farha\Desktop\sample\node_modules\node-sass
> node scripts/install.js

> node-sass@3.4.2 postinstall C:\Users\farha\Desktop\sample\node_modules\node-sa                                                                                                                ss
> node scripts/build.js

> C:\Users\farha\Desktop\sample\node_modules\node-sass\vendor\win32-x64-46\bindi                                                                                                                ng.node ` exists.
 testing binary.
Binary is fine; exiting.

> spawn-sync@1.0.15 postinstall C:\Users\farha\Desktop\sample\node_modules\spawn                                                                                                                -sync
> node postinstall

This is my brunch-config.coffee
```
exports.config = {
  files: {
    javascripts: {
      joinTo: {
        'libraries.js': /^(?!app\/)/
        'app.js': /^app\//
      }
    },
    stylesheets: {
      joinTo: 'app.css'
    },
    templates:{
      joinTo: 'app.js'
    }
  }
}
```

This is my package.json
```
{
  "name": "brunch-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "devDpendencies": {
    "javascript-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "auto-reload-brunch": "^2.0.0",
    "brunch": "^2.3.0",
    "javascript-brunch": "^2.0.0",
    "sass-brunch": "^2.0.0"
  },
  "dependencies": {}
}
```

This is my bower.json
```
{
  "name": "simple-brunch",
  "version": "0.1.0",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "jquery": "1.*"
  },
  "overrides": {},
  "description": "",
  "main": "",
  "moduleType": [],
  "license": "MIT",
  "homepage": ""
}
```

**Comment by farhan2106** [comment]
I am also using node 4.3.0 and I have also tried it with node 5.3.0

**Comment by goshakkk** [comment]
What you posted are just `npm install` logs with a few warnings and some post-install scripts. There are *no* errors in it.

May I ask what does "not able to generate" mean? Does it generate no libraries.js? Does it generate an empty file for that?

Second, did you not forget to run `bower install` on windows as well?

Third, does the brunch build/watch output anything of interest? Perhaps you can add the `-d` flag and post the full build log here?

**Comment by farhan2106** [comment]
Yes, it is not generating libraries.js

This is my folder structure:
![capture](https://cloud.githubusercontent.com/assets/897173/13063064/40a50408-d47f-11e5-88f8-06c583d72f88.PNG)

And this is what I get when I run with -d

> farha@FARHAN-LAP MINGW64 ~/Desktop/sample2
$ brunch watch --server -d
Mon, 15 Feb 2016 23:32:00 GMT brunch:speed Created BrunchWatcher 494ms
Mon, 15 Feb 2016 23:32:00 GMT brunch:application Trying to load brunch-config
Mon, 15 Feb 2016 23:32:00 GMT brunch:speed Loaded config 550ms
Mon, 15 Feb 2016 23:32:00 GMT brunch:speed Loading plugins 550ms
Mon, 15 Feb 2016 23:32:00 GMT brunch:plugins Loaded plugins:
Mon, 15 Feb 2016 23:32:00 GMT brunch:speed Loaded plugins 551ms
16 Feb 07:32:00 - info: application started on http://localhost:3333/
Mon, 15 Feb 2016 23:32:00 GMT brunch:speed Loaded watcher 556ms
Mon, 15 Feb 2016 23:32:00 GMT brunch:watch add package.json
Mon, 15 Feb 2016 23:32:00 GMT brunch:watch add bower.json
Mon, 15 Feb 2016 23:32:00 GMT brunch:watch add brunch-config.coffee
Mon, 15 Feb 2016 23:32:00 GMT brunch:watch add bower_components\jquery\dist\jquery.js
Mon, 15 Feb 2016 23:32:00 GMT brunch:list Reading bower_components\jquery\dist\jquery.js
Mon, 15 Feb 2016 23:32:00 GMT brunch:speed Starting compilation 582ms
Mon, 15 Feb 2016 23:32:00 GMT brunch:watch add app\README.md
Mon, 15 Feb 2016 23:32:00 GMT brunch:list Reading app\README.md
Mon, 15 Feb 2016 23:32:00 GMT brunch:watch add app\assets\README.md
Mon, 15 Feb 2016 23:32:00 GMT brunch:asset Init app\assets\README.md directory=app\assets\ relativePath=README.md destinationPath=public\README.md
Mon, 15 Feb 2016 23:32:00 GMT brunch:watch add app\assets\app.js
Mon, 15 Feb 2016 23:32:00 GMT brunch:asset Init app\assets\app.js directory=app\assets\ relativePath=app.js destinationPath=public\app.js
Mon, 15 Feb 2016 23:32:00 GMT brunch:watch add app\assets\index.html
Mon, 15 Feb 2016 23:32:00 GMT brunch:asset Init app\assets\index.html directory=app\assets\ relativePath=index.html destinationPath=public\index.html
Mon, 15 Feb 2016 23:32:00 GMT brunch:speed Watcher is ready 595ms
Mon, 15 Feb 2016 23:32:00 GMT brunch:asset Copied app\assets\README.md
Mon, 15 Feb 2016 23:32:00 GMT brunch:asset Copied app\assets\app.js
Mon, 15 Feb 2016 23:32:00 GMT brunch:asset Copied app\assets\index.html
Mon, 15 Feb 2016 23:32:00 GMT brunch:write Writing 0/0 files
16 Feb 07:32:00 - info: copied 3 files in 667ms

Ty, I appreciate the help. I am also running windows 10 64bit

**Comment by goshakkk** [comment]
I just tried that locally with window 7 (though that doesn't seem to be the issue!) using dead-simple skeleton and was able to reproduce it.

The interesting line from the logs is `brunch:write Writing 0/0 files`.

Upon taking a fresh look at basically the codeless folder with just brunch-config and package.json I think I've found the culprit. It's mis-spelt `devDpendencies` in package.json (already submitted a PR to fix that https://github.com/brunch/dead-simple/pull/3/files)

Changing it to `devDependencies` seems to have addressed the issue and everything is written properly now:

<img width="1392" alt="screen shot 2016-02-18 at 3 11 47 pm" src="https://cloud.githubusercontent.com/assets/315596/13142997/05192714-d652-11e5-8d9a-c04bc27103c4.png">


@farhan2106 can you check if that also fixes it for you? Cheers!

**Comment by farhan2106** [comment]
thumbs up! TY! @goshakkk works now...")
