### ISSUE TITLE
Custom server doesn´t work in recent version.

### ISSUE THREAD

**Issue by szathiago** [brunch/brunch#1177]
Custom server doesn´t work in recent version.
brunch-config.coffee
  server:
    command: "php -S 0.0.0.0:3000 -t public"

command: brunch watch -s
 error: Initialization error - ReferenceError: server is not defined

**Comment by szathiago** [comment]
works perfectly on 2.2.3

**Comment by goshakkk** [comment]
Thanks for the report, I'll take a look!

**Comment by szathiago** [comment]
Thanks a bunch!
