### ISSUE TITLE
I get a [TypeError: Cannot read property 'joinTo' of undefined error]

### ISSUE THREAD

**Issue by anoopmd** [brunch/brunch#1182]
### Description

I am trying to compile handlebars using brunch,
I get a [TypeError: Cannot read property 'joinTo' of undefined error]

But the error goes away when I add an empty 
```javascript
javasripts : {
  joinTo : {
  }
}
```
 to my config

### Environment

1. Brunch: 2.3.0
2. Node:5.2.0
3. NPM:3.3.12
4. Operating system: W7

### `package.json` contents
```javascript
{
  "name": "brunch-handlebars-example",
  "version": "0.1.0",
  "devDependencies": {
    "handlebars-brunch": "^2.0.1"
  }
}
```

### brunch config contents
This config gives error
```javascript
exports.config = {
  files: {
    templates: {
      joinTo: 'javascripts/app.js'
    }
  }
};
```
This config WORKS!
```javascript
exports.config = {
  files: {
    javasripts: {
      joinTo: {
      }
    },
    templates: {
      joinTo: 'javascripts/app.js'
    }
  }
};
```

I appreciate your help. Thanks

**Comment by anoopmd** [comment]
Here is the snapshot

![error](https://cloud.githubusercontent.com/assets/9350733/13154239/1556b3de-d69e-11e5-8e69-e904da184c8d.jpg)

**Comment by paulmillr** [comment]
We would need to ignore non-existent entries of `files`.

**Comment by anoopmd** [comment]
BTW, My congrats to the Brunch Developers for hitting the 5000 GitHub Stars.

**Comment by paulmillr** [comment]
Thanks Anoop!
