### ISSUE TITLE
Shorthand version for skeleton does not work

### ISSUE THREAD

**Issue by jacwright** [brunch/brunch#1185]
### Description

Testing out the new `npm` feature I followed the instructions on the `brunch-with-react` page and get an error about the skeleton not existing.
```
$ brunch new react-app -s brunch/brunch-with-react
19 Feb 14:52:46 - error: Error: skeleton 'brunch/brunch-with-react' doesn't exist
```

If I use the full URL
```
$ brunch new react-app -s https://github.com/brunch/brunch-with-react
```
it works just fine.

### Environment

1. Brunch: 2.3.2
2. Node: 5.6.0
3. NPM: 3.6.0
4. Operating system: Mac OSX 10.10.5

**Comment by paulmillr** [comment]
Seems like we broke init-skeleton somewhere. @goshakkk could you take a look @ https://github.com/brunch/init-skeleton/blob/master/index.js ?

**Comment by goshakkk** [comment]
It should be `gh:brunch/brunch-with-react` I guess. Or simply `react`

**Comment by paulmillr** [comment]
no. `brunch/brunch-with-react` should work too. We've been dropping `gh:` somewhere to match `npm`.

**Comment by goshakkk** [comment]
Well actually `gh:` wasn't dropped https://github.com/brunch/init-skeleton/blob/master/index.js#L217

Anyway, I'll make that work too

**Comment by goshakkk** [comment]
@paulmillr should you create a new init-skeletons release that includes https://github.com/brunch/init-skeleton/pull/11, bump it in brunch and close this issue?
