### ISSUE TITLE
Allow extension in module name

### ISSUE THREAD

**Issue by jacwright** [brunch/brunch#1187]
### Description

Apps are becoming more component-based where templates and their JavaScript definition files are put together into the same folder. It would be nice when requiring templates to use the extension. Take the following application structure:

```
app
├── app.js
└── components
    └── user-info
        ├── user-info.js
        └── user-info.html
```

In this case `user-info` is the module name for both `user-info.js` and `user-info.html`. The `user-info.js` module cannot require its template.

Could we have `user-info` be a shortcut with the actual module name being the full file name? Or could we have a setting to make templates keep their extension? I'd like to be able to do this:

```js
app.component({
  template: require('./user-info.html'),
  ...
});
```

**Comment by paulmillr** [comment]
```javascript
// brunch-config.js
config.modules = {nameCleaner: (path) => path}
```

**Comment by paulmillr** [comment]
well no, that won't fix the issue.

**Comment by nblackburn** [comment]
Thanks for getting this done, i have been manually editing the build references upon until now which was a pain.
