### ISSUE TITLE
Add Beep (ASCII BEL \007) sound whenever Brunch throws an error

### ISSUE THREAD

**Issue by anoopmd** [brunch/brunch#1195]
### Description

I have been experimenting with brunch lately.
One of the serious plus that I see when compared to Grunt and Gulp is the speed
at which brunch watches and builds your files.

When working on a project, I usually start brunch in the watch mode and run it as a server
```
brunch watch --server
```

Then I start working and continuously switch between the IDE and the browser.
When I make some error in the code, brunch does not shut down the server, It keeps it alive
and I wonder for 2-3 min, only later to realize that brunch compilation failed, and what I
am seeing on the browser is in fact a previous successful compiled build.

Here are two ways that where we can solve this
*Option 1*. When compilation fails, delete the build in the public directory and put an error file so 
    that the user is notified that brunch compilation failed.
    (Like Laravel 5 error details on the browser)

*Option 2*. Make a beep sound when brunch fails, so that it catches the developers attention.
    (Like Grunt)

Appreciate any feedback or how others solved this problem.

### Environment

1. Brunch: 2.3.2
2. Node: 4.2.6
3. NPM: 3.7.3
4. Operating system: W7

**Comment by paulmillr** [comment]
Brunch integrates Growl notification system into all errors.

You can install Growl for windows and receive system-wide notifications by following these steps: https://github.com/tj/node-growl#windows

After that, you should notice every fail easily.

**Comment by paulmillr** [comment]
Beep sound seems great though. Let's add it too.

**Comment by goshakkk** [comment]
https://github.com/paulmillr/loggy/pull/9

**Comment by goshakkk** [comment]
@paulmillr can this be closed now?
