### ISSUE TITLE
Brunch is concatenating a file twice

### ISSUE THREAD

**Issue by ronnieoverby** [brunch/brunch#1198]
### Description

My entry point `/app/application.js` file is getting concat'd 2 times in the build output (`main.js`). I have found that this is happening only when one of my other modules imports it. 

Strangely, I have also observed that when `brunch watch`ing, if I make changes to '/app/application.js` after the initial build, one instance of the concatenation will lag behind the other.

### Environment

1. Brunch: 2.3.2
2. Node: 3.4.0
3. NPM: v5.1.0
4. Operating system: Windows 10

### `package.json` contents

```json
{
  "repository": {},
  "scripts": {
    "grunt-build-dev-vs": "grunt build:dev-vs --vsconfig=debug",
    "brunch": "brunch build -d"
  },
  "dependencies": {
    "babel-brunch": "^6.0.0",
    "babel-polyfill": "^6.2.0",
    "brunch": "^2.3.2",
    "javascript-brunch": "^2.0.0",
    "less-brunch": "^2.0.0",
    "lodash": "^4.3.0",
    "wu": "^2.1.0"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.1.18",
    "grunt": "^0.4.5",
    "grunt-babel": "^6.0.0",
    "grunt-bower-install-simple": "^0.9.3",
    "grunt-bump": "0.0.15",
    "grunt-changelog": "^0.2.2",
    "grunt-cli": "^0.1.13",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-copy": "^0.5.0",
    "grunt-contrib-htmlmin": "^0.3.0",
    "grunt-contrib-uglify": "^0.5.1",
    "grunt-recess": "^1.0.0",
    "gruntfile-gtx": "^0.3.0",
    "http-server": "^0.6.1",
    "require-directory": "^2.0.0"
  }
}
```

### brunch config contents
```javascript
module.exports = {
    files: {
        javascripts: {
            joinTo: 'main.js',
            order: {
                before: [                
                    '**/EventAggregator.js',
                    '**/jquery.js',
                    '**/jquery.dataTables.min.js',
                    '**/jquery-jvectormap.min.js'
                ]
            }
        },
        stylesheets: {
            joinTo: {
                "app.css": '**\\app.less'
            }
        }
    },
    
    plugins: {
        'babel-brunch': {
            presets: ['es2015'],                  
        }
    },
    
    npm: {
        enabled: true,
        globals: {
            wu: "wu",
        }
    }
};
```

**Comment by goshakkk** [comment]
Interesting. Can you provide a sample repo that demonstrates the issue? That would be of much help. Thanks!

**Comment by ronnieoverby** [comment]
Whew. Maybe.

**Comment by ronnieoverby** [comment]
I ran across this issue again in a different project that is easier to share with you.

https://github.com/ronnieoverby/react-authorquiz/commit/d7515174b499c8ccfa469608e53f18fd780a8a12

React is being concat'd 2 times in the compiled js file:

[js.zip](https://github.com/brunch/brunch/files/150257/js.zip)

You can see this happening. First starting at line 3896, second at line 44987.

**Comment by goshakkk** [comment]
So the issue seems to be because of casing — some places you are requiring `react`, some places `React`, which for some reason resulted in both `node_modules/react/...` AND `node_modules/React/...` (even though the same file) getting added to Brunch. 

The solution, I think, should be raising error when improperly cased instead of getting rid of the dupe. Fwiw, webpack raises an error in this case too. @paulmillr what are your thoughts?

**Comment by ronnieoverby** [comment]
I agree that an error would be handy dandy.

**Comment by paulmillr** [comment]
>  raising error when improperly cased instead of getting rid of the dupe

yep

**Comment by goshakkk** [comment]
Submitted #1214 to address that

**Comment by ronnieoverby** [comment]
@goshakkk Thanks!
