### ISSUE TITLE
Brunch won't compile jsx unless babel is after react in package.json

### ISSUE THREAD

**Issue by webdif** [brunch/brunch#1200]
### Description

Brunch won't compile jsx unless babel is after react in package.json. To be sure it was not a bug from my project, I create a new empty project, but the bug is still there.

With `babel-brunch` before `react`, `react-brunch`, `react-dom`, I get this :
```
$ brunch b
24 Feb 17:23:06 - error: Compiling of app/js/Form.jsx failed. app/js/Form.jsx: Unexpected token (25:9) ; Compiling of app/js/index.jsx failed. app/js/index.jsx: Unexpected token (42:20) 
```

When I move `babel-brunch` after in the package.json, I get :
```
$ brunch b
24 Feb 17:23:18 - info: compiling
24 Feb 17:23:19 - info: compiled 174 files into 3 files, copied 17 in 4.3 sec
```

### Environment

1. Brunch: 2.4.2
2. Node: v5.0.0
3. NPM: 3.3.6
4. Operating system: OS X 10.11.3

### `package.json` contents

```json
{
  "author": "",
  "name": "",
  "description": "",
  "version": "0.0.1",
  "homepage": "",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "build": "brunch build",
    "prod": "brunch build --production",
    "start": "brunch watch --server",
    "test": "brunch test"
  },
  "devDependencies": {
    "autoprefixer": "latest",
    "babel-brunch": "latest",
    "browser-sync-brunch": "latest",
    "brunch": "latest",
    "clean-css-brunch": "latest",
    "coffee-script-brunch": "latest",
    "css-brunch": "latest",
    "groundskeeper-brunch": "latest",
    "imageoptmizer-brunch": "latest",
    "jade-brunch": "latest",
    "javascript-brunch": "latest",
    "json-brunch": "latest",
    "postcss-brunch": "latest",
    "react": "latest",
    "react-brunch": "latest",
    "react-dom": "latest",
    "static-jade-brunch": "latest",
    "stylus-brunch": "latest",
    "uglify-js-brunch": "latest"
  },
  "private": true
}
```

### brunch config contents

```cson
exports.config =
    ###
    # Options des plugins
    ###
    plugins:
        jade:
            pretty: yes
        static_jade:
            path: /app\/html/
            asset: "app/compile"
        imageoptimizer:
            smushit: false
            path: "images"
        postcss:
            processors: [
                require('autoprefixer')
            ]
        browserSync:
            logSnippet: false
            server:
                baseDir: "public"
        babel:
            pattern: /\.jsx$/
    

    ###
    # Plugins Npm pour le front-end
    ###
    npm:
      enabled: true
      whitelist: [
          'react'
          'react-dom'
      ]
    

    ###
    # Builds
    ###
    files:
        javascripts:
            joinTo: 'js/app.js'

        stylesheets:
            joinTo: 'css/app.css'

        templates:
            joinTo:
                'js/app.js': /^app\/templates\/.+\.jade$/
                '.ignore/views.js': /^app\/html\/.+\.jade$/

    conventions:
        assets: /(assets|(compile\/html))\//
        ignored: [
            /\/_/
            /\/import\//
            /\/include\//
            /\/layout\//
        ]
```

**Comment by goshakkk** [comment]
React-brunch is deprecated, you should instead use a Babel react preset.
See https://github.com/brunch/brunch-with-react for a reference.

On Wed, Feb 24, 2016 at 8:29 PM Maxime Vasse <notifications@github.com>
wrote:

> Description
>
> Brunch won't compile jsx unless babel is after react in package.json. To
> be sure it was not a bug from my project, I create a new empty project, but
> the bug is still there.
>
> With babel-brunch before react, react-brunch, react-dom, I get this :
>
> $ brunch b
> 24 Feb 17:23:06 - error: Compiling of app/js/Form.jsx failed. app/js/Form.jsx: Unexpected token (25:9) ; Compiling of app/js/index.jsx failed. app/js/index.jsx: Unexpected token (42:20)
>
> When I move babel-brunch after in the package.json, I get :
>
> $ brunch b
> 24 Feb 17:23:18 - info: compiling
> 24 Feb 17:23:19 - info: compiled 174 files into 3 files, copied 17 in 4.3 sec
>
> Environment
>
>    1. Brunch: 2.4.2
>    2. Node: v5.0.0
>    3. NPM: 3.3.6
>    4. Operating system: OS X 10.11.3
>
> package.json contents
>
> {
>   "author": "",
>   "name": "",
>   "description": "",
>   "version": "0.0.1",
>   "homepage": "",
>   "repository": {
>     "type": "git",
>     "url": ""
>   },
>   "scripts": {
>     "build": "brunch build",
>     "prod": "brunch build --production",
>     "start": "brunch watch --server",
>     "test": "brunch test"
>   },
>   "devDependencies": {
>     "autoprefixer": "latest",
>     "babel-brunch": "latest",
>     "browser-sync-brunch": "latest",
>     "brunch": "latest",
>     "clean-css-brunch": "latest",
>     "coffee-script-brunch": "latest",
>     "css-brunch": "latest",
>     "groundskeeper-brunch": "latest",
>     "imageoptmizer-brunch": "latest",
>     "jade-brunch": "latest",
>     "javascript-brunch": "latest",
>     "json-brunch": "latest",
>     "postcss-brunch": "latest",
>     "react": "latest",
>     "react-brunch": "latest",
>     "react-dom": "latest",
>     "static-jade-brunch": "latest",
>     "stylus-brunch": "latest",
>     "uglify-js-brunch": "latest"
>   },
>   "private": true
> }
>
> brunch config contents
>
> exports.config =
>     ###
>     # Options des plugins
>     ###
>     plugins:
>         jade:
>             pretty: yes
>         static_jade:
>             path: /app\/html/
>             asset: "app/compile"
>         imageoptimizer:
>             smushit: false
>             path: "images"
>         postcss:
>             processors: [
>                 require('autoprefixer')
>             ]
>         browserSync:
>             logSnippet: false
>             server:
>                 baseDir: "public"
>         babel:
>             pattern: /\.jsx$/
>
>
>     ###
>     # Plugins Npm pour le front-end
>     ###
>     npm:
>       enabled: true
>       whitelist: [
>           'react'
>           'react-dom'
>       ]
>
>
>     ###
>     # Builds
>     ###
>     files:
>         javascripts:
>             joinTo: 'js/app.js'
>
>         stylesheets:
>             joinTo: 'css/app.css'
>
>         templates:
>             joinTo:
>                 'js/app.js': /^app\/templates\/.+\.jade$/
>                 '.ignore/views.js': /^app\/html\/.+\.jade$/
>
>     conventions:
>         assets: /(assets|(compile\/html))\//
>         ignored: [
>             /\/_/
>             /\/import\//
>             /\/include\//
>             /\/layout\//
>         ]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brunch/brunch/issues/1200>.
>
-- 
Cheers,
Gosha

**Comment by webdif** [comment]
Damn, it's hard to keep up with the JS ecosystem…
Thanks a lot!
