### ISSUE TITLE
How do I specify a custom public path for the build

### ISSUE THREAD

**Issue by anoopmd** [brunch/brunch#1201]
### Description

How do I specify a custom public path.

The following config is not working on my Win7 machine

```javascript
exports.config = {
  // files, templates options
  paths: {
    public: '../build'
  }
```

### Environment

1. Brunch:1.7.0
2. Node:5.2.0
3. NPM:3.3.2
4. Operating system: Win7 64 Bit

**Comment by goshakkk** [comment]
Please include slightly more details on what 'not working' means: does it
result in some error? Does it finish silently but outputs compiled files
either in a wrong directory, or doesn't output compiled files at all?

If possible, please also include the build log (brunch build -d)

Thanks!
On Wed, Feb 24, 2016 at 10:14 PM Anoop M D <notifications@github.com> wrote:

> Description Description
>
> How do I specify a custom public path.
>
> The following config is not working on my Win7 machine
>
> exports.config = {
>   // files, templates options
>   paths: {
>     public: '../build'
>   }
>
> Environment
>
>    1. Brunch:1.7.0
>    2. Node:5.2.0
>    3. NPM:3.3.2
>    4. Operating system: Win7 64 Bit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brunch/brunch/issues/1201>.
>
-- 
Cheers,
Gosha

**Comment by anoopmd** [comment]
Thanks Gosha for the quick reply

This is strange. It works now.
I guess I had some typo error before.
