### ISSUE TITLE
Brunch is messing up dependency paths with __makeRequire()

### ISSUE THREAD

**Issue by adrianmc** [brunch/brunch#1202]
### Description

I'm trying to use this package: https://github.com/rexxars/react-markdown

It's something that I have used successfully before when I was working with Webpack and Browserify, so I know the package is not at fault. When I add it to my React project (based on the officially recommended React and ES6 skeleton), my React app doesn't build and inside the browser console, I get the following error:

```
Uncaught Error: Cannot find module "entities/maps/xmlon" from "entities/lib/encode"
```

I dug deeper into the problem and found out that it's actually trying to look for `xml.json` instead of `xmlon`. What seems to be happening is that the `__makeRequire()` function is eliminating `.js` out of the string, making the path non-sensical.

```js
var __makeRequire = function(r, __brmap) {
  return function(name) {
    if (__brmap[name] !== undefined) name = __brmap[name];
    name = name.replace(".js", "");
    return r(name);
  }
};
```

More info on where this `__makeRequire()` comes from is located in this issue I found: https://github.com/brunch/brunch/issues/1126

Any suggestions on how to fix this?

### Environment

1. Brunch: 2.4.2
2. Node: 5.0.0
3. NPM: 3.3.6
4. Operating system: OSX 10.11

**Comment by goshakkk** [comment]
The `__makeRequire` snippet that you posted is from brunch 2.0 I think, not 2.4. That said, it's probably still an issue with 2.4 (https://github.com/brunch/brunch/blob/master/lib/deppack/modules.js#L209) 

A more first-class extension handling is currently being considered

For now, I've opened https://github.com/brunch/brunch/pull/1203 to provide a fix

**Comment by adrianmc** [comment]
@goshakkk 

Oh, okay I see. Thanks for taking a look at this!
