### ISSUE TITLE
NPM Integration: Sass

### ISSUE THREAD

**Issue by darren131** [brunch/brunch#1211]
### Description

Sorry if this isn't the correct place for this question, but I'm going to ask it anyway. I'm using npm to manage all my front end assets (a little JS, but mainly Sass) and I'm wanting to know if it's possible to have shortcuts to the sass npm packages. So rather than having to do something like this on my sass file

```sass
@import "../../node_modules/foundation-sites/scss/foundation";
@import "../../vendor/scut/dist/scut";
```

I could simply reference it like this (or similar):

```sass
@import "foundation";
@import "scut";
```

Thanks!

**Comment by darren131** [comment]
I'm sorry – I'm a horrible human being. I just read these docs...
https://github.com/brunch/sass-brunch#options

Which I believe answers my question:
https://github.com/brunch/sass-brunch#options

**Comment by goshakkk** [comment]
That doesn't make you a horrible human being at all :wink: Glad you could find what you wanted.
