### ISSUE TITLE
Can't get Brunch to work with Rx and Cycle.js

### ISSUE THREAD

**Issue by kaisersly** [brunch/brunch#1213]
### Description

I started with brunch-with-es6. I installed rx, @cycle/core and @cycle/dom.

If I try to `require('rx')` it will not find it. If I type `require.list()` in the browser console, it will list it as `'rx/dist/rx.all'`. I can get it to work by adding this to the project's package.json:

`"overrides": { "rx": { "main": "./dist/rx.all.js" } }`

After that, the module is correctly named `'rx'`.

Trying to `require('@cycle/core')` makes brunch crash : it tries to find `@cycle/package.json` which doesn't exist (@cycle is just a scope, not an actual package). I `npm init` in `node_modules/@cycle` (which is kind of hacky) and brunch starts. But the module appears as `@cycle/core/lib/cycle`. I tried the same override (with `./dist/cycle` and `./lib/cycle`) but neither change the module name to just `'@cycle/core'` (it changes it to `'@cycle/dist/cycle'` and `'@cycle/lib/cycle'` respectivelly). I tried overriding `"browser"`, and `"jam"` with the same results. I can use @cycle/core by requiring `'@cycle/dist/cycle'`.

Finally, with @cycle/dom, same thing : it's named `'@cycle/dom/lib/cycle-dom'`. But when I try to require it, it says it `cannot find module 'individual/index' from 'individual/one-version'` in the browser console. If I try to require `@cycle/dom/dist/cycle-dom`, this error appears in the terminal :

`Could not load module './property-map' from 'd:\Learn\brunch-with-es6\node_modules\@cycle\dom\dist'`

### Environment

1. Brunch: 2.4.2
2. Node: 5.5.0
3. NPM: 3.3.12
4. Operating system: MacOs X 10.10.5

### `package.json` contents

{
  "name": "your-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "prod": "brunch build --production"
  },
  "dependencies": {
    "@cycle/core": "^6.0.3",
    "rx": "^4.0.8"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "~6.0.0",
    "babel-preset-es2015": "~6.3.13",
    "brunch": "~2.4.2",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  },
  "overrides": {
    "rx": {
      "main": "./dist/rx.all.js"
    },
    "@cycle/core": {
      "main": "./dist/cycle.js"
    }
  }
}

### brunch config contents

module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/,
        'app.js': /^app/
      }
    },
    stylesheets: {joinTo: 'app.css'}
  },

  npm: {
    enabled: true
  },

  plugins: {
    babel: {presets: ['es2015']}
  }
};

### Other useful files, when present (`bower.json` etc.)

Here is a repo with everything :
https://github.com/kaisersly/debug-brunch-rx-cycle

**Comment by goshakkk** [comment]
Hey, thanks for your report. Brunch currently does not support the `@scope/name` style, but I think we're going to fix it. 

Honestly, up until now, I actually wasn't aware that these existed... :smile:

**Comment by kaisersly** [comment]
Before CycleJS me neither :smile:. Thanks for your work!

**Comment by goshakkk** [comment]
Submitted #1216 to fix that

**Comment by kaisersly** [comment]
It works for me. Thanks a lot ! 
Should (I / you) close this issue ?
