### ISSUE TITLE
Brunch watch doesn't see any changes, doesn't compile, doesn't reload, doesn't do anything after first compilation

### ISSUE THREAD

**Issue by lucian303** [brunch/brunch#1228]
### Description

No changes detected in 2.4.2. Nothing at all in the logs even with the -d option after the initial compilation. No changes are ever detected even to the brunch.config.coffee and usePolling: true doesn't do anything. 1.7.19 works for me. 1.8.5 logs the change events when using `brunch w -d` but doesn't recompile or reload the browser. So definitely between there something got messed up and in 2.4.2 and I assume any other version 2, it doesn't even work at all. I'd test more versions from npm, but npm takes so incredibly long to install. Also, doing npm update obviously has problems and can't be relied upon to install dependencies clean.

### Environment

1. Brunch: 2.4.2, 1.8.5, 1.7.19
2. Node: 4.x and 5.8.0
3. NPM: 2.x, 3.7.3
4. Operating system: Ubuntu 14.04

### `package.json` contents
```
{
  "name": "compliance_dictionary",
  "version": "0.1.0",
  "license": "UNLICENSED",
  "repository": {
    "type": "git",
    "url": "https://bitbucket.org/unifiedcompliance/compliance_dictionary"
  },
  "scripts": {
    "start": "brunch watch",
    "postinstall": "bower install",
    "postupdate": "bower update"
  },
  "engines": {
    "node": ">=0.8.0"
  },
  "dependencies": {
    "babel-brunch": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "brunch": "^2.0.0",
    "css-brunch": "^1.7.0",
    "clean-css-brunch": "^1.8.0",
    "sass-brunch": "^1.9.1",
    "bower": "^1.7.1",
    "ng-annotate-uglify-js-brunch": "^2.0.0",
    "git-digest-brunch": "^1.0.3"
  },
  "devDependencies": {
    "browser-sync-brunch": "^0.0.8"
  }
}
```

### brunch config contents
```
exports.config =
  conventions:
    assets: [
      'app/assets/**'
      'bower_components/font-awesome/**'
      '!bower_components/font-awesome/css/**'
      'bower_components/term-hierarchy/assets/**'
    ]
  modules:
    definition: false
    wrapper: false
  paths:
    watched: [
      'app'
    ]
  files:
    javascripts:
      joinTo:
        'js/app.js': 'app/**'
        'js/vendor.js': 'bower_components/**'
      order:
        before: [
          'bower_components/jquery/jquery.js'
        ]
    stylesheets:
      joinTo:
        'css/app.css': /^(app|bower_components)/
  plugins:
    browserSync:
      notify: false
    sass:
      options:
        includePaths: ['bower_components/bootstrap-sass/assets/stylesheets']
    babel:
      ignore: [
        'bower_components/!(term-hierarchy)/**'
      ]
```

Literally nothing to see in the logs after the initial compilation.

**Comment by lucian303** [comment]
Actually, in my second project, downgraded back to brunch 1.17.19, I see messages in the output with brunch w -d but nothing happens, so I guess even that version doesn't work.

Messages that don't do anything, no recompilation, no reloading:
```
  brunch:watch File 'app/scripts/workflow/control-match-details.controller.js' received event 'change' +8s
  brunch:watch File 'app/scripts/workflow/control-match-details.controller.js' received event 'change' +35s
```

**Comment by paulmillr** [comment]
Try using regexps instead of strings in `jointo`. globs don't work.

**Comment by lucian303** [comment]
As a further note, after downgrading to 1.7.19, it works, but deleting the target directory and running brunch leads only to some directories being copied over while assets are missing and nothing is compiled. On another project on the same server with the same exact dependencies, it works as expected. The dependencies I've pared it down to that work on one project but not another. This is incredible. 

```
  "dependencies": {
    "brunch": "1.7.19",
    "babel-brunch": "~5.0.0",
    "css-brunch": ">= 1.0 < 1.8",
    "auto-reload-brunch": ">= 1.0 < 1.8",
    "clean-css-brunch": ">= 1.0 < 1.8",
    "bower": "~1.7",
    "ng-annotate-uglify-js-brunch": "~1.7.4",
    "git-digest-brunch": "~1.0.3",
    "babel-core": "~5.1.5"
  }
```

**Comment by xdave** [comment]
@lucian303 Missing `javascript-brunch` plugin?  That's the only thing I can think of.  I always included that plugin even though I'm using babel.

**Comment by goshakkk** [comment]
@lucian303 any update on this? Did you try @xdave's suggestion re adding the javascript-brunch plugin?

**Comment by JSisGreat79** [comment]
Hello, 
I am experiencing the same problem. In my case i already have the javascript-brunch installed but the problem still exists. Did anyone manage to solve this kind of problem ?
Thanks for your help ! 
![brunch](https://cloud.githubusercontent.com/assets/16709368/18475334/565d322e-79c6-11e6-8459-4d6215cea833.png)

**Comment by nubunto** [comment]
I am experiencing the same problem ^

**Comment by nubunto** [comment]
Kinda put-off by the fact that this issue was just closed, without explanation.

**Comment by lucian303** [comment]
As a workaround, I just fixed the brunch version to 1.17.19 in package.json.

**Comment by paulhklam1122** [comment]
We are having the same issue with brunch on an older project. It breaks occasionally and we fix it by clearing the cache and doing some voodo magic, only for it to break again.

We were hoping to upgrade brunch to the latest version from `1.17.19` to make this problem go away. I can't even see upgrade guides from 1.0 to 2.0 anywhere. Nor do I see any breaking changes listed anywhere in the changelogs.

Did any of you make any progress on this issues?

**Comment by lucian303** [comment]
I haven't made any progress other than fixing the version. I may try again, but rather than mess with that, if it's necessary in the future, we will probably move to something like webpack or whatever garbage tool the js community is spouting off about at the time. It's too bad cause the config of most other tools looks atrocious but this is js land. You can't expect reasonable tools for developing javascript (or most things) anymore; that's just a fact of life, IMO. @paulhklam1122

**Comment by yagudaev** [comment]
@lucian303 I agree completely. Unlike Ruby/Rails which is another community I'm a part of, NPM, for example, doesn't list versions of dependencies on the website. 

We might just bite the bullet and upgrade to webpack 4.0 as it looks like brunch is dead. Webpack 4.0 has very little config necessary, but still a little bit of work to do
