### ISSUE TITLE
Production joinTo does not seem to have any effect

### ISSUE THREAD

**Issue by ukutaht** [brunch/brunch#1239]
### Description

With the upgrade to 2.5.0, I'm experiencing an issue where the dev/test files are still compiled and generated when running with the `--production` flag. I've written a simple app to exemplify the problem: https://github.com/ukutaht/brunch-jointo-issue. It is similar to an app I use in the real world which excludes files from the production build using `config.overrides.files.javascripts.joinTo`.

Here's the output with brunch 2.4.2:
```shell
$ brunch b --production
17 Mar 10:22:51 - info: compiled prod-file.js into app.js in 358ms
[ 'public/app.js' ]
$ ls public
app.js
```

And 2.5.0
```shell
$ brunch b --production
17 Mar 10:24:14 - info: compiled 2 files into 2 files in 579ms
[ 'public/dev.js', 'public/app.js' ]
$ ls public
app.js dev.js
```

### Environment

1. Brunch: 2.5.0
2. Node: 5.7.0
3. NPM: 3.8.1
4. Operating system: OSX 10.10.5

**Comment by goshakkk** [comment]
https://github.com/brunch/brunch/pull/1243 should address that
