### ISSUE TITLE
Double inclusion of files on Windows

### ISSUE THREAD

**Issue by colinbate** [brunch/brunch#1242]
### Description

It seems that in some cases on Windows files are being included in the bundle twice. It seems to me, that it finds the files on the file system initially with the Windows separator `\` in the path. Then if you require that file using the forward slash `/`, I'm guessing that deppack is adding that as a separate file. From what I can tell anecdotally, it doesn't seem to happen when you require the files relatively, perhaps deppack handles that case differently. Unfortunately I don't have a lot of time to debug this further.

### Environment

1. Brunch: 2.5.0 (happens with 2.4.2 as well)
2. Node: 5.6.0
3. NPM: 3.7.1
4. Operating system: Windows 7 Business

### Reproduction

1. Finds a Window machine
2. Clone https://github.com/brunch/with-react (or use the skeleton)
3. `npm install`
4. `brunch build`

Check `public/app.js` and it should have `component/App` included in there twice.

**Comment by goshakkk** [comment]
@colinbate Indeed. I've opened https://github.com/brunch/brunch/pull/1246 to fix this

**Comment by goshakkk** [comment]
Thanks for reporting
