### ISSUE TITLE
How to know what will brunch do as a next step of compilation in order to understand debug output?

### ISSUE THREAD

**Issue by ceremcem** [brunch/brunch#1257]
### Description

Brunch started to fail compiling after `npm install`. When I run build with `DEBUG="brunch:*" brunch b` command, it stucks at some point, right after copying assets and the last line is: 

```
brunch:file-list Copied asset 'app/assets/projects/uieakluikayl/hiz-test.webm' +2ms
```

Full debug log is [here](https://gist.github.com/ceremcem/cc5bda30ead79bae93f7)

### Environment

1. Brunch: 1.8.3
2. Node: 4.3.0
3. NPM: 3.8.2
4. Operating system: Debian 8 (Linux 4.3)

### `package.json` contents
```
{
  "author": "",
  "name": "",
  "description": "",
  "version": "0.0.1",
  "homepage": "",
  "repository": {
    "type": "git",
    "url": ""
  },
  "engines": {
    "node": "~0.6.10 || 0.8 || 0.9"
  },
  "scripts": {},
  "dependencies": {
    "cheerio": "^0.19.0",
    "clean-css-brunch": ">= 1.0 < 1.5",
    "css-brunch": ">= 1.0 < 1.5",
    "express": "^4.10.2",
    "h2o2": "^4.0.1",
    "hapi": "^8.8.1",
    "inert": "^3.1.0",
    "jade-static-brunch": "git://github.com/lalomartins/jade-static-brunch",
    "javascript-brunch": ">= 1.0 < 1.5",
    "jquery": "^2.1.4",
    "less-brunch": ">= 1.0 < 1.5",
    "livescript": "^1.4.0",
    "livescript-brunch": "git://github.com/brunch/LiveScript-brunch.git",
    "markdown-js": "0.0.3",
    "mjpeg-camera": "^1.5.8",
    "msgpack-js": "^0.3.0",
    "prelude-ls": "^1.1.2",
    "ractive": "^0.7.3",
    "shortid": "^2.2.2",
    "socket.io": "^1.3.6",
    "uglify-js-brunch": ">= 1.0 < 1.5",
    "wreck": "^6.3.0",
    "xml2js": "^0.4.13",
    "zmq": "^2.12.0"
  },
  "devDependencies": {
    "chai": "1.2.0",
    "sinon": "1.4.2",
    "sinon-chai": "2.1.2"
  }
}
```

### brunch config contents
```
exports.config =
  # See http://brunch.readthedocs.org/en/latest/config.html for documentation.
  files:
    javascripts:
      joinTo:
        'javascripts/app.js': /^app/
        'javascripts/vendor.js': /^vendor/
        'test/javascripts/test.js': /^test(\/|\\)(?!vendor)/
        'test/javascripts/test-vendor.js': /^test(\/|\\)(?=vendor)/
      order:
        # Files in `vendor` directories are compiled before other files
        # even if they aren't specified in order.before.
        before: [
          'vendor/base-libraries/jquery-1.11.js',
          'vendor/jquery-ui/jquery-ui.min.js',
          'vendor/flot.min/jquery.flot.min.js'
        ]

    stylesheets:
      joinTo:
        'stylesheets/app.css': /^(app|vendor)/
        'test/stylesheets/test.css': /^test/
      order:
        after: [
          /^app/,
          'vendor/toolbar/toolbar-bootstrap3.fix.css'
        ]

  plugins:
    jadeStatic:
      #compileDebug: true
      locals: {}                    # Locals passed to the template
      formatPath: (path) ->
        console.log "path is: ", path
        try
          p = path.match(/^app(\/|\\)static(\/|\\)([^\\]+)\.jade$/)
          #console.log "path match: ", p
          return p[3]
        catch
          return 'ignore-this-file'

      extension: '.html'            # Extension of compiled templates
      pretty: true                  # Any other Jade API option

```
### Other useful files, when present (`bower.json` etc.)

At the time of committing [this](https://github.com/aktos-io/aktos-scada/tree/365c7fb3db51cfef0c688bc2bb0de96b2b5d9299) version, everything was getting compiled correctly. 

The problematic code is here: https://github.com/aktos-io/aktos-scada/tree/e6c80de2366718f129b955eb676a201a0cf6c94a

**Comment by goshakkk** [comment]
> Brunch started to fail compiling after npm install.

Could you please post the error you see here? Even better if you could include the full debug log (`brunch b -d`)

**Comment by ceremcem** [comment]
Please see my edit (in the description) and the full debug log is here: https://gist.github.com/ceremcem/cc5bda30ead79bae93f7

**Comment by ceremcem** [comment]
Sorry, the error output was not included, it is included now: https://gist.github.com/ceremcem/cc5bda30ead79bae93f7

**Comment by goshakkk** [comment]
This is happening because the jade-static-brunch fork you are using tries to add jade runtime into the bundle and assumes it's in `node_modules/jade-static-brunch/node_modules/jade/runtime.js` (not sure why the *static* compiler needs the runtime though)

NPM 3 tries to produce flatter directory structures which can result in `jade` being located at `node_modules/jade`, not `node_modules/jade-static-brunch/node_modules/jade`. To mitigate that, `require.resolve` should be used instead of hardcoding that path.

In any case, the issue does not lie in brunch itself. You can open the issue on https://github.com/lalomartins/jade-static-brunch or you can fork it or create a PR that either:

a) removes the lines that add the jade runtime into the bundle (https://github.com/lalomartins/jade-static-brunch/blob/master/index.js#L73)
b) make these lines use something like `sysPath.resolve(require.resolve('jade/package.json'), 'runtime.js')`

**Comment by ceremcem** [comment]
Thank you for the detailed answer. This means that if I completely strip out the jade* extension(s) then the compilation would go just normal, right?

If this is the case, result is the same and [here is debug output](https://gist.github.com/ceremcem/bc5f1d05e385aa259c12) for the `brunch b -d` command with the following configuration: 

```
{
  "author": "",
  "name": "",
  "description": "",
  "version": "0.0.1",
  "homepage": "",
  "repository": {
    "type": "git",
    "url": ""
  },
  "engines": {
    "node": "~0.6.10 || 0.8 || 0.9"
  },
  "scripts": {},
  "dependencies": {
    "cheerio": "^0.19.0",
    "clean-css-brunch": ">= 1.0 < 1.5",
    "css-brunch": ">= 1.0 < 1.5",
    "express": "^4.10.2",
    "javascript-brunch": ">= 1.0 < 1.5",
    "jquery": "^2.1.4",
    "less-brunch": ">= 1.0 < 1.5",
    "livescript": "^1.4.0",
    "livescript-brunch": "git://github.com/brunch/LiveScript-brunch.git",
    "markdown-js": "0.0.3",
    "mjpeg-camera": "^1.5.8",
    "prelude-ls": "^1.1.2",
    "ractive": "^0.7.3",
    "shortid": "^2.2.2",
    "socket.io": "^1.3.6",
    "uglify-js-brunch": ">= 1.0 < 1.5",
    "xml2js": "^0.4.13",
    "zmq": "^2.12.0"
  },
  "devDependencies": {
    "chai": "1.2.0",
    "sinon": "1.4.2",
    "sinon-chai": "2.1.2"
  }
}
```
```
exports.config =
  # See http://brunch.readthedocs.org/en/latest/config.html for documentation.
  files:
    javascripts:
      joinTo:
        'javascripts/app.js': /^app/
        'javascripts/vendor.js': /^vendor/
        'test/javascripts/test.js': /^test(\/|\\)(?!vendor)/
        'test/javascripts/test-vendor.js': /^test(\/|\\)(?=vendor)/
      order:
        # Files in `vendor` directories are compiled before other files
        # even if they aren't specified in order.before.
        before: [
          'vendor/base-libraries/jquery-1.11.js',
          'vendor/jquery-ui/jquery-ui.min.js',
          'vendor/flot.min/jquery.flot.min.js'
        ]

    stylesheets:
      joinTo:
        'stylesheets/app.css': /^(app|vendor)/
        'test/stylesheets/test.css': /^test/
      order:
        after: [
          /^app/,
          'vendor/toolbar/toolbar-bootstrap3.fix.css'
        ]
```

**Comment by goshakkk** [comment]
Oh, I see. Jade plugin only caused that error but brunch carried on.

I was able to pinpoint the culprit to the use of github master version of the livescript-brunch plugin. Its master version was updated to a newer plugin API that comes with Brunch 2.

(Even if you want to use a GH version instead of NPM one, it's always safer to specify the tag or commit to avoid issues like that.)

If you wish to remain on 1.8.x, change

```
"livescript-brunch": "git://github.com/brunch/LiveScript-brunch.git",
```

to

```
"livescript-brunch": "git://github.com/brunch/LiveScript-brunch.git#1.8.0",
```

or simply

```
"livescript-brunch": "1.8.0"
```

**Comment by ceremcem** [comment]
Thank you for your answer. [The change](https://github.com/ceremcem/jade-static-brunch/commit/5deb1eba8db2df14f5583548f4f4395b5aad292e) has solved my issue. 

But anyway, I didn't understand how you are able to understand the root of this issue. By trial and error? The problem with brunch is possibly this kind of poor error output.

**Comment by goshakkk** [comment]
@ceremcem the jade error was pretty self-explanatory.

The LiveScript one, well, kind of too... it was the only plugin not locked at specific version, in this case it used the new plugin API and returned a promise, however Brunch 1.8.x only supports passing callbacks to plugins, so in this case, that callback never got called, making Brunch appear "hang"

**Comment by ceremcem** [comment]
I was pretty sure about it was not related with node modules because I copied these modules from an old project into this one and it didn't work that way too. But you get it by guessing.

So you say there is nothing brunch 1.x can do ([produce proper error messages](https://twitter.com/josevalim/status/621933537009246208)) when brunch 2.x compatible plugin is used with brunch 1.x?

If so, we can close this issue and I still appreciate your instructions.

**Comment by paulmillr** [comment]
the problem with restricting plugins to <2.0 is that not every plugin actually conforms to the convention...
