### ISSUE TITLE
Issue with react-intl

### ISSUE THREAD

**Issue by spyl94** [brunch/brunch#1259]
### Description

I tried to use `react-intl` (2.0.0-rc-1) compilation is fine but I get the following error:

`Uncaught Error: Cannot find module 'react-intl/locale-data/index' from 'react-intl/lib/index.js'`.
 
In their package.json, they use: 
 `"browser": {
    "./locale-data/index": false,
    "./locale-data/index.js": false
  }`

If I remove the browser key from:
- `./node_modules/intl-messageformat/package.json`
- `./node_modules/intl-relativeformat/package.json`
- `./node_modules/react-intl/package.json`

Then, the compilation has the same number of files but this time my app works. So it's probably brunch related.

### Environment

1. Brunch: master
2. Node: 5.1.1
3. NPM: 3.5.3
4. Operating system: OSX

### `package.json` contents
````
{
  "name": "react-brunch-demo",
  "version": "2.0.0",
  "description": "It's a demo for react with es6 and brunch.",
  "scripts": {
    "build": "NODE_ENV=development ./node_modules/brunch/bin/brunch build",
    "build:prod": "NODE_ENV=production ./node_modules/brunch/bin/brunch build --production",
    "dev": "NODE_ENV=development ./node_modules/brunch/bin/brunch watch --server"
  },
  "author": "Spyl <adavid@jolicode.com>",
  "license": "MIT",
  "dependencies": {
    "babel-brunch": "^6.0.0",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "bootstrap-stylus": "^0.2.2",
    "brunch": "github:brunch/brunch",
    "events": "^1.1.0",
    "flux": "^2.1.1",
    "react": "^0.14.7",
    "react-bootstrap": "^0.28.4",
    "react-dom": "^0.14.7",
    "react-intl": "^2.0.0-rc-1",
    "stylus-brunch": "^2.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^5.0.0",
    "babel-plugin-react-intl": "^2.1.1",
    "eslint": "^2.4.0",
    "eslint-config-airbnb": "^6.2.0",
    "eslint-config-jolicode": "^0.2.0",
    "eslint-plugin-react": "^4.2.3",
    "fb-flo-brunch": "^1.7.22"
  }
}
```
### brunch config contents
````
exports.config = {
  overrides: {
    production: {
      plugins: {
        off: ['eslint-brunch'],
      }
    }
  },
  conventions: {
    ignored: [
      /[\\/]_/,
      /\-test.js$/,
    ],
  },
  files: {
    javascripts: {
      joinTo: {
        'js/vendor.js': /^node_modules/,
        'js/app.js': /^app/
      }
    },
    stylesheets: {
      joinTo: 'styles/app.css'
    }
  },
  plugins: {
    babel: {
      babelrc: true,
    },
  },
  onCompile: function() {
    require('fs').appendFile('public/js/app.js', '\n\nrequire(\'js/app\');');
  }
};
```
###  Full demo

https://github.com/spyl94/react-brunch-demo use `npm install` then `npm run dev`

**Comment by goshakkk** [comment]
Thanks for your report!

Indeed, we weren't handling local file overrides with false values properly. I've submitted https://github.com/brunch/deppack/pull/5 to make their handling similar to that of module overrides.
