### ISSUE TITLE
Forked processes and extreme memory and CPU usage when building.

### ISSUE THREAD

**Issue by koalalorenzo** [brunch/brunch#1262]
### Description

I am not able to deploy anymore on Heroku, and at the same time ,after re-installing everything and removing node_modules directory, I have discovered that brunch build forked dozens of processes, maxing out both my memory and cpu at the same place.

### Environment

1. Brunch: 2.5.3
2. Node: 4.4.1 and 5.9.1
3. NPM: 2.14.20 and 3.7.3
4. Operating system: OSX, Ubuntu (Heroku)

You can check, build the code available at this repository: https://github.com/koalalorenzo/p2pool-network
Probably this is related to point 2 of #1261

**Comment by paulmillr** [comment]
Does this only happen with `-j` flag?

**Comment by paulmillr** [comment]
Brunch should not fork any processes unless you're using `-j` flag. So, the behavior is weird

**Comment by goshakkk** [comment]
It does currently default to to jobs because of 1 forgotten check in the setdefaults function. https://github.com/brunch/brunch/pull/1263 should fix it

**Comment by koalalorenzo** [comment]
Do we have an ETA for fixing this?

**Comment by paulmillr** [comment]
a few days for 2.6 release
