### ISSUE TITLE
Too many open files when building

### ISSUE THREAD

**Issue by rstacruz** [brunch/brunch#1264]
### Description

When running `brunch b` or `brunch w` with 300+ CSS files, it works but for a period of time, you won't be able to do anything in your system because Brunch opened too many files. For instance:

```
pipe: too many open files in your system
```

...can occur in a shell script running outside Brunch.

Perhaps compilation concurrency should be throttled. Running 300+ compilations at once shouldn't have a perceivable benefit over, say, running 8 at once.

### Environment

1. Brunch:
2. Node:
3. NPM:
4. Operating system:

### `package.json` contents

For this test, I set up brunch with the following packages:

```
"brunch"
"css-brunch"
"javascript-brunch"
"sass-brunch"
"auto-reload-brunch"
```

And I had a Brunch setup with 300 .scss files.

**Comment by paulmillr** [comment]
The answer to these situations is increasing `ulimit`. Can you try that?

**Comment by rstacruz** [comment]
Under OS X 10.11, I tried:

```
sudo launchctl limit maxfiles 65536 unlimited
```

and I still ran into the issue. Also, this happens occasionally too:

```
 →  brunch w
29 Mar 11:07:19 - info: compiled 2 files into app.js in 1.9 sec
29 Mar 11:07:25 - info: compiling
29 Mar 11:07:32 - info: compiling.
29 Mar 11:08:04 - info: compiling..
fish: 'brunch w' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by paulmillr** [comment]
I think the issue is more or less relevant to your system, since i've been working on tons of br projects over the years. Just curious what the issue may be exactly. You haven't noticed Brunch, Node or NPM versions

**Comment by rstacruz** [comment]
oops, sorry:

Node 4.3.0
Brunch 2.5.1
OSX 10.11.3
npm 2.14.12

**Comment by koalalorenzo** [comment]
TBH, I think this is related to #1262 but the OS version may have different settings on users, so I don't have this error on my system.

**Comment by rstacruz** [comment]
YES! Running brunch with `-j 4` fixes the problem and makes it faster. Closing as a dupe of #1262.

**Comment by paulmillr** [comment]
@rstacruz just wanted to mention, some users have been having tons of very weird errors with `npm v2`. If you'll see something strange, could you try upgrading to npm v3.
