### ISSUE TITLE
Brunch watch with awaitWriteFinish

### ISSUE THREAD

**Issue by LeG3nDz** [brunch/brunch#1270]
Hi community,

### Description

I read on other ticket that there was a compilation problem (CSS file and JS module are empty) with some editor. The solution would be to add `awaitWriteFinish: true` in the configuration file.

But I've no results. I tried with Sublime Text disabling "atomic_save", and it works.

I use Brackets editor, and `brunch watch` is run directly on the server, not locally.

### Environment

1. Brunch: 2.5.3
2. Node: 4.4.1
3. NPM: 3.8.3
4. Operating system: Editor on Windows 7, brunch watch on Debian 8.

### `package.json` contents

    {
      "name": "app",
      "version": "1.0.0",
      "description": "",
      "scripts": {
        "start": "brunch watch --server",
        "build": "brunch build --production"
      },
      "author": [
        "test <test@test.com>"
      ],
      "license": "ISC",
      "devDependencies": {
        "auto-reload-brunch": "^2.0.0",
        "clean-css-brunch": "^2.0.0",
        "css-brunch": "^2.0.0",
        "javascript-brunch": "^2.0.0",
        "sass-brunch": "^2.0.0",
        "uglify-js-brunch": "^2.0.0"
      },
      "dependencies": {
        "foundation-sites": "^6.0.4",
        "motion-ui": "^1.1.1"
      }
    }

### brunch config contents

    module.exports = {
        awaitWriteFinish: true,
        paths: {
            public: 'public',
            watched: 'private'
        },
        files: {
            javascripts: {
                joinTo: 'js/app.min.js',
                order: {
                    before: [
                        'node_modules/foundation-sites/js/foundation.core.js'
                    ]
                }
            },
            stylesheets: {
                joinTo: 'css/app.min.css'
            }
        },
        plugins: {
            sass: {
                options: {
                    includePaths: [
                        'node_modules/foundation-sites/scss',
                        'node_modules/motion-ui/src'
                    ]
                }
            }
        }
    }

Do you have idea ?

Thank you !

**Comment by goshakkk** [comment]
So, it works in Sublime but not Brackets?

Network saves can be somewhat nasty wrt detecting changes properly after the writes are finished (not started or in process), and different editors use different techniques for saving.

Can you see if `usePolling: true` (as I suggested in https://github.com/brunch/brunch/issues/1250#issuecomment-200214268) does the trick for you?

If not, it may be worth digging through Brackets documentation to see if it has any flags configuring how it saves the file (akin to `atomic_save` in Sublime for example)

**Comment by LeG3nDz** [comment]
Hi @goshakkk 

I've test `usePolling: true`, but no result :(

I'll look in the doc Brackets, hoping problem comes from there.

Thank you : )

**Comment by paulmillr** [comment]
Try 2.7 and `npm i -g brunch/brunch`

**Comment by LeG3nDz** [comment]
Hi @paulmillr 

After test, no result. My JS module is empty.
