### ISSUE TITLE
brunch new: Install cached NPM modules on network issues

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#1272]
So, Brunch caches all skeletons locally in `.brunch` directory. 

Suppose we have some skeleton but our network connection went down. We're still able to execute `brunch new`, it would copy existing skeleton as-is, but then half-way through it would fail, because NPM would try to make network requests.

The suggested fix is to execute `npm install --cache-min 9999999` whenever we're using cached skeleton. Let's still use `npm install` without `cache-min` if the network is up.

**Comment by goshakkk** [comment]
https://github.com/brunch/init-skeleton/pull/16
