### ISSUE TITLE
Local dependency tracing has broken requires with extensions.

### ISSUE THREAD

**Issue by colinbate** [brunch/brunch#1275]
### Description

Since moving to Brunch 2.6.1, I can no longer import/require a file using its full extension. It is an issue during the dependency resolving since the extension is stripped when going into the `modMap`.

### Environment

1. Brunch: 2.6.1
2. Node: 5.7.0
3. NPM: 3.7.5
4. Operating system: Mac OS X 10.11

### `package.json` contents

```json
{
  "name": "example",
  "version": "1.0.0",
  "description": "Example.",
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build"
  },
  "author": "Colin Bate <colin@colinbate.com>",
  "license": "MIT",
  "devDependencies": {
    "auto-reload-brunch": "^2.1.0",
    "babel-brunch": "^6.0.2",
    "babel-plugin-transform-react-jsx": "^6.7.4",
    "babel-preset-stage-0": "^6.5.0",
    "brunch": "^2.6.1",
    "less-brunch": "^2.6.0"
  },
  "dependencies": {
    "yolk": "^0.10.1"
  }
}
```

### brunch config contents

```js
exports.config = {
  files: {
    javascripts: {
      joinTo: {
        'app.js': 'app/**/*',
        'vendor.js': 'node_modules/**/*'
      },
      order: {
        after: /\.less$/
      }
    },
    stylesheets: {
      joinTo: 'app.css'
    },
    templates: {
      joinTo: 'app.js'
    }
  },
  plugins: {
    less: {
      modules: true
    }
  }
};
```

My debug output is here: https://gist.github.com/colinbate/55ec4fe05d4022b5c8de4bca25693e9b

### Reproduction

1. Create a folder
2. In that folder run `brunch new .`
3. `npm install -D brunch` (if unless you have 2.6.1 globally)
4. Create empty `app/second.js` file.
5. In `app/initialize.js` add `var second = require('./second.js');`
6. `brunch build`

**Comment by goshakkk** [comment]
Seems to be related to https://github.com/brunch/deppack/issues/9

This PR https://github.com/brunch/deppack/pull/12 should fix it

**Comment by colinbate** [comment]
Yes, I'd say it is the same issue :) Thanks @goshakkk 

Should I report these issues to the underlying package like `deppack` if that is where is it located? I usually debug the issues to a specific root cause, but wasn't sure if you prefer a brunch issue or a more specific issue.

**Comment by goshakkk** [comment]
@colinbate it's totally fine to report it here
