### ISSUE TITLE
how to add a stand alone grid system to brunch?

### ISSUE THREAD

**Issue by ohNegative** [brunch/brunch#1280]
### Description

I'm looking to add a stand alone grid system to a standard brunch skeleton. The specific grid I want to add is Jeet (http://jeet.gs/) I've a tried a couple different ways, but Brunch doesn't like the @import feature that Jeet uses. It still compiles, but none of the styling comes through like:

```
@import '_jeet.styl'

edit()

body
	font: 16px Verdana, Arial, sans-serif
section
	center(980px)	
aside
	col(1/3)
article
	col(2/3)
```

I'm already using stylus, so that shouldn't be an issue.

### Environment

1. Brunch: 2.61
2. Node: 4.0.0
3. NPM:
4. Operating system: Windows 7 with Git Shell

### `package.json` contents

```
{
  "name": "your-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "prod": "brunch build --production"
  },
  "dependencies": {
    "stylus-brunch": "^2.6.0",
    "jeet": "6.1.2"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "~6.0.0",
    "babel-preset-es2015": "~6.3.13",
    "brunch": "^2.4.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/,
        'app.js': /^app/
      }
    },
    stylesheets: {joinTo: 'app.css'}
  },

  plugins: {
    babel: {presets: ['es2015']}
  }
};

```

Any ideas on how I can add this to my project and get it working?

Thanks,

Pete

### Other useful files, when present (`bower.json` etc.)

If there's an unexpected error during `brunch build`/`brunch watch`, please attach the compilation log with the debug flag (`-d`).

If something worked with previous versions of brunch, but stopped with a newer one, please include these details as well.

Finally, if at all possible, please create a small demo app on GitHub that demonstrates the issue so it's easier for us to check and debug.

**Comment by paulmillr** [comment]
Try setting this in your brunch config.

```javascript
plugins: {
  stylus: {plugins: ['jeet']}
}
```
