### ISSUE TITLE
Normalize relative paths early

### ISSUE THREAD

**Issue by colinbate** [brunch/brunch#1281]
Currently when running on Windows, the paths for files use backslashes for a part of the workflow, and eventually get normalized into forward slashes when written out as module names. Given the reliance on regular expressions for config and in various other places, I thought it might be a good idea to normalize the relative paths from the beginning in `watch.js` after they come in from `chokidar`.

That way anytime you find yourself writing `/^app\/something/` you don't need to wonder if you need to provide both slashes (or worse not adding both until someone raises an issue about Windows support).

**Comment by paulmillr** [comment]
agree. that's a nice ux improvement. let's see what we can do here.

**Comment by mcfarljw** [comment]
I was having some similar troubles with then with a plugin of mine. I ended up throwing together a quick hack to get it running, but certainly wouldn't be against standardizing it on a higher level.

https://github.com/mcfarljw/replace-brunch/commit/11032a96c2ae40c40c4613f990c8c9737e6e62e4

**Comment by goshakkk** [comment]
Here is my stab on that: https://github.com/brunch/brunch/pull/1346

**Comment by goshakkk** [comment]
@paulmillr we can close this.
