### ISSUE TITLE
Case check broken on Windows

### ISSUE THREAD

**Issue by colinbate** [brunch/brunch#1283]
### Description

Another path separator issue on Windows. This time in `deppack`'s `resolve.js`. The result of `trueCasePath(res)` normalizes the path separators to forward slashes whereas `res` still has backslashes.

It manifests itself in a bunch of "Improperly-cased require" errors.

### Environment

1. Brunch: 2.6.2
2. Node: 5.6.0
3. NPM: 3.7.1
4. Operating system: Windows 7 Business

### Reproduction

1. Create new project with `brunch n .` (on Windows)
2. Add a `second.js` file in `app`.
3. At the top of `initialize.js` add: `var x = require('./second');`
4. Run `brunch build`

**Comment by goshakkk** [comment]
Submitted https://github.com/brunch/deppack/pull/14 to address this.

**Comment by colinbate** [comment]
Thanks. As usual, I appreciate the swift turnaround on this.
