### ISSUE TITLE
How to use `npm.static` config

### ISSUE THREAD

**Issue by dalexj** [brunch/brunch#1288]
### Description
I would like fonts from an npm package to be copied over to my `public` directory. there is an `npm.static` configuration option in https://github.com/brunch/brunch/blob/master/docs/config.md but there's hardly anything about it and I could not figure out how to use it at all.

could I get an example how to go about using this / maybe put that explanation in the documentation as well?

**Comment by goshakkk** [comment]
`static` is a config option to simply let some JS files from node modules to be included as-is, without analyzing their deps or wrapping them into modules.

At the moment brunch does not handle module assets other than stylesheets. But you can easily achieve it with a `postinstall` hook for your app: see https://github.com/brunch/brunch/blob/master/docs/faq.md#how-to-use-bower for reference (never mind "bower" in title, it applies to external static files in general)

**Comment by lydell** [comment]
I thought `npm.assets` would copy over _any_ files too. Thanks for clarifying. I think the docs should be updated to say the option is all/only about JavaScript.

Incidentally, I was also trying to use fonts from an npm package.
I added the following at the bottom of my brunch-config.js. Seems to be working so far.

```js
const recurFs = require('recur-fs') // npm install recur-fs

recurFs.cp(
  'node_modules/font-awesome/fonts/',
  'public/font-awesome',
  false, // Don’t overwrite.
  (error) => {
    if (error) {
      console.error('Failed to copy font-awesome fonts', error)
    }
  }
)
```

(In case somebody searches for "font-awesome" and ends up here: I also use the following:

```scss
$fa-font-path: 'font-awesome';

@import 'node_modules/font-awesome/scss/font-awesome';
```
)

**Comment by colinbate** [comment]
For what it is worth, I use a plugin for this purpose: https://www.npmjs.com/package/copyfilemon-brunch

**Comment by goshakkk** [comment]
Now that it's been resolved, should you close this issue?

**Comment by lydell** [comment]
Before forgetting this issue, I must say that @goshakkk's description in a comment above is much better than in the docs. I suggest adding it to the docs. Something like this:

> `npm.static`: `Array`: a list of javascript files installed from npm to be included as-is, without analyzing their dependencies or wrapping them into modules.

**Comment by goshakkk** [comment]
@lydell 👌 https://github.com/brunch/brunch/pull/1361

**Comment by samme** [comment]
NB `npm.static` values must start with `node_modules/`, not just the module name.

**Comment by clarknelson** [comment]
I had to declare the static file in the `npm.static` section, and then build them into a file with `javascript.joinTo`
