### ISSUE TITLE
Should `config.conventions.assets` apply to npm stuff? / Difficult to use the JS of  the bootstrap-sass npm package

### ISSUE THREAD

**Issue by lydell** [brunch/brunch#1289]
### Description

It’s not possible to `require('bootstrap-sass')` (`bootstrap-sass` is an npm package) using the default Brunch config.

### Environment

1. Brunch: 2.6.5 (both globally and locally)
2. Node: 5.9.1
3. NPM: 3.7.3
4. Operating system: Ubuntu 15.10

### `package.json` contents

```json
{
  "private": true,
  "devDependencies": {
    "brunch": "^2.6.5",
    "javascript-brunch": "^2.0.0"
  },
  "dependencies": {
    "bootstrap-sass": "^3.3.6"
  }
}
```

### brunch config contents

```js
module.exports = {
  files: {
    javascripts: { joinTo: "app.js" }
  }
}
```

### Steps to reproduce

Setup:

```
$ mkdir brunch-test
$ cd brunch-test
$ echo '{"private": true}' >package.json
$ npm i -D brunch javascript-brunch
$ npm i -S bootstrap-sass
$ echo 'module.exports = {files: {javascripts: {joinTo: "app.js"}}}' >brunch-config.js
$ mkdir app
$ echo 'require("bootstrap-sass")' >app/app.js
```

Notice how `bootstrap.js` is copied as an asset instead of being wrapped as a CommonJS module in `public/app.js`:

```
$ brunch b
11 Apr 12:10:54 - info: compiled app.js into app.js, copied bootstrap.js in 400ms
$ grep bootstrap public/app.js
require("bootstrap-sass")
```

bootstrap-sass’s `package.json` contains `"main": "assets/javascripts/bootstrap.js"`. Disabling Brunch’s “assets” convention (or renaming the `assets/` directory in `node_modules/bootstrap-sass/`) gives the result I expect:

```
$ echo 'module.exports = {files: {javascripts: {joinTo: "app.js"}}, conventions: {assets: []}}' >brunch-config.js
$ brunch b
11 Apr 12:11:51 - info: compiled 2 files into app.js in 480ms
$ grep bootstrap public/app.js
require.register("bootstrap-sass/assets/javascripts/bootstrap.js", function(exports, require, module) {
  require = __makeRelativeRequire(require, {}, "bootstrap-sass");
 * Bootstrap v3.3.6 (http://getbootstrap.com)
 * http://getbootstrap.com/javascript/#transitions
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
    var el = document.createElement('bootstrap')
[snip]
require.alias("bootstrap-sass/assets/javascripts/bootstrap.js", "bootstrap-sass");})();
require("bootstrap-sass")
```

Note how `bootstrap.js` isn’t copied anymore, but included in `public/app.js`.

Does it make sense for `config.conventions.assets` to apply npm stuff? To me, it doesn’t. But I might be wrong :)

(While thinking about the answer to the above question, it might be useful to think about if there are other things that shouldn’t apply to npm stuff, such as the other `config.conventions.*` options perhaps?)

**Comment by goshakkk** [comment]
This is a good point, thanks for reporting. Up until now, we haven't actually stumbled into that ourselves but yes, these shouldn't apply to npm stuff. I'll create a PR for that tomorrow

**Comment by goshakkk** [comment]
Here we go https://github.com/brunch/brunch/pull/1291

**Comment by omin** [comment]
Is there a way to override this? I think a better solution would be not ignore anything by default since we have `convention.ignored`. I just spent hours trying to figure out why Brunch is not adding FontAwesome after I added it to `conventions.assets` and finally found out that Brunch 

> Don't categorize node_modules as 'assets' even if they match the regexp
