### ISSUE TITLE
Loading jquery and bootstrap using npm support

### ISSUE THREAD

**Issue by mcfarljw** [brunch/brunch#1295]
### Description

I'm wondering what the proper way of using npm support to load both jquery and bootstrap into the global scope. Bootstrap requires jquery, but it doesn't specifically have a global name since it extends the existing jquery namespace.

### Environment

1. Brunch: 3.6.5
2. Node: 4.4.2
3. NPM: 2.15.0
4. Operating system: OSX 10.11.4

### `package.json` contents

```
"dependencies": {
		"bootstrap": "~3.3.6",
		"jquery": "~2.2.0"
	},
```
### `brunch-config.js` contents

```
npm: {
		enabled: true,
		globals: {
			$: 'jquery/dist/jquery.js'
		}
	},
```

**Comment by goshakkk** [comment]
I *think* `jquery` adds a global variable on its own when you require it. (but don't take my word for it)

As for bootstrap, I'd also like to note that this isn't really brunch-specific — i.e. you do what you normally would expect / do with other tools when you need a module for its side effects. `require('bootstrap')`

So, just add the requires for both of these to the entry point of your application.

(If you prefer, you also have an option of sidestepping the modules exposed by these packages and use the non-module artifacts from these, by using `config.npm.statics`, though it's generally taken as a bad practice to use module-less code when it also comes moduled)

**Comment by mcfarljw** [comment]
Good point. It appears that jquery doesn't automatically add it, but `window.$ = window.jQuery = require('jquery');` seems to have solved the issue.

**Comment by goshakkk** [comment]
Well, if it doesn't, you can safely use `config.npm.globals` (and point it to just `$: 'jquery', jQuery: 'jquery'`) and brunch will write that piece of code for you

**Comment by noxecane** [comment]
is there a way to add custom code globally
