### ISSUE TITLE
Error when using a package with a "browser" option set to false

### ISSUE THREAD

**Issue by dalexj** [brunch/brunch#1297]
### Description

I'm trying to load in a module that uses a `browser` setting set to false in `package.json` like so:

```javascript
  "browser": {
    "buffer": false
  }
```

this will error out when the build file is run with `Uncaught TypeError: Cannot read property 'Buffer' of undefined` since brunch builds this file to something like this:

```javascript
require.register("module/filename.js", function(exports, require, module) {
  require = __makeRelativeRequire(require, {"buffer":false}, "module");
  var Buffer = require('buffer').Buffer;
  ...
```

### Environment

1. Brunch: 2.6.4
2. Node: 5.4.1
3. NPM: 3.3.12
4. Operating system: OSX

### brunch config contents

probably the only thing worth noting is:

```javascript
plugins: {
  babel: {
    presets: ['es2015', 'react'],
    plugins: ['transform-object-rest-spread']
  }
}
```

**Comment by goshakkk** [comment]
Thanks for reporting. https://github.com/brunch/deppack/pull/18 should fix it.

**Comment by dalexj** [comment]
when is this planned for release?

**Comment by paulmillr** [comment]
This or next week. You can use `npm i -g brunch/brunch` for now.
