### ISSUE TITLE
node_modules using new node.js features won't bundle/uglify properly

### ISSUE THREAD

**Issue by xdave** [brunch/brunch#1300]
### Description
(Below is more or less a copy of my comment from babel/babel-brunch#27
I'm posting a proper issue here, because seeing as that issue was closed before I commented, it may fall upon deaf ears (for being unnoticed).)

I'm bundling a dependency, [credit-card](https://github.com/continuationlabs/credit-card) for the browser which relies upon certain JS features that need to be transpiled (by _something_, anything) in order for it to work in all the browsers I'm trying to support. It uses things like `const` and `Object.assign`, which I use babel to polyfill.

For instance, `credit-card` has one dependency, [reach](https://github.com/continuationlabs/reach) that uses template strings.

These features generally are ones that are enabled by default in the recent versions of `node.js`, but obviously do not work in all browsers.

This is a growing trend with `npm` module authors because bundlers such as `browserify` and `webpack` will process these types of modules through their transform pipelines by default.

These dependencies do not come with `dist` versions.

Lots of packages are written in `ES6` with the idea of modularity in mind, such as `RxJS 5`. It makes it (theoretically) possible (with bundlers such as `rollup`) to only import the functions one needs so as not to pull in the entire package and bloat the compiled code.

To work around these problem cases, I've had to internalize these modules into my project, which is a pain, because I use [flow](http://flowtype.org/) in all of my project's modules and rely heavily on the automatic type inference it provides for stuff that's imported from `node_modules`. However, if one imports a local module (not in `node_modules`), the type inference is not so automatic and requires you to provide some type annotations -- which is what I have to do to these internalized-workaround modules.

Enabling `brunch` (or `babel-brunch` as the case may be) to process, perhaps a specific set of modules contained within `node_modules` through the compilation steps, would eliminate many headaches.

### What happens

- When I run `brunch build`, the build succeeds.
- When I run `brunch build --production`, the build fails.
- In either case, the resulting JS does not work on all browsers.

### Environment

1. Brunch: 2.6.6
2. Node: v5.10.1
3. NPM: 3.8.6
4. Operating system: Arch Linux 4.4.5-1-ARCH x86_64

### `package.json` contents
```json
{
  "name": "brunch-test-local-imports",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "build": "brunch build",
    "prod": "brunch build --production"
  },
  "dependencies": {
    "credit-card": "^2.0.0"
  },
  "devDependencies": {
    "babel-brunch": "^6.0.2",
    "babel-preset-es2015": "^6.6.0",
    "brunch": "^2.6.6",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.1"
  }
}
```

### brunch config contents
```javascript
module.exports = {
    files: {
        javascripts: {
            joinTo: {
                'vendor.js': /^(?!app)/,
                'app.js': /^app/
            }
        },
        stylesheets: { joinTo: 'app.css' }
    },
    modules: {
        autoRequire: { 'app.js': ['main'] }
    },
    plugins: {
        babel: Object.assign({}, require('./babelrc.json'), {

        })
    }
};
```
(NOTE: `.babelrc` is a symlink to `babelrc.json` so that I can import it into the config.

### Other useful files, when present (`bower.json` etc.)
`.babelrc`
```json
{
    "presets": ["es2015"]
}
```

### Output of `brunch build --production -d`
```
  brunch:config Trying to load brunch-config +0ms
  brunch:plugins Loaded plugins: babel-brunch, javascript-brunch, uglify-js-brunch +256ms
  brunch:watch add package.json +11ms
  brunch:watch add brunch-config.js +1ms
  brunch:watch add app/main.js +3ms
  brunch:list Reading app/main.js +0ms
  brunch:file Init app/main.js: isntModule=false isWrapped=true +1ms
  brunch:pipeline Compiling app/main.js @ BabelCompiler +2ms
  brunch:pipeline Compiling app/main.js @ JavaScriptCompiler +93ms
  brunch:watch add app/assets/index.html +14ms
  brunch:asset Init app/assets/index.html directory=app/assets/ destPath=public/index.html rel=index.html +0ms
  brunch:asset Copied app/assets/index.html +5ms
  brunch:list Reading node_modules/credit-card/lib/index.js +4ms
  brunch:modules Wrapping main.js @ commonjs +0ms
  brunch:list Compiled app/main.js +1ms
  brunch:file Init node_modules/credit-card/lib/index.js: isntModule=true isWrapped=true +1ms
  brunch:list Reading node_modules/reach/lib/index.js +15ms
  brunch:modules Not wrapping (is vendor file) node_modules/credit-card/lib/index.js +0ms
  brunch:list Compiled node_modules/credit-card/lib/index.js +2ms
  brunch:file Init node_modules/reach/lib/index.js: isntModule=true isWrapped=true +0ms
  brunch:modules Not wrapping (is vendor file) node_modules/reach/lib/index.js +4ms
  brunch:list Compiled node_modules/reach/lib/index.js +0ms
  brunch:write Writing 2/2 files +67ms
  brunch:generate Concatenating [app/main.js] => public/app.js +1ms
  brunch:generate Concatenating [node_modules/credit-card/lib/index.js, node_modules/reach/lib/index.js] => public/vendor.js +2ms
  brunch:generate Optimizing public/app.js @ UglifyJSOptimizer +4ms
  brunch:generate Optimizing public/vendor.js @ UglifyJSOptimizer +62ms
  brunch:generate Writing public/app.js +7ms
18 Apr 20:40:02 - error: JS minification failed on public/vendor.js: Unexpected token: name (_defaults) (line: 156, col: 4, pos: 3951)

Error
  at new JS_Parse_Error (<anonymous>:1526:18)
  at js_error (<anonymous>:1534:11)
  at croak (<anonymous>:2026:9)
  at token_error (<anonymous>:2034:9)
  at unexpected (<anonymous>:2040:9)
  at semicolon (<anonymous>:2060:56)
  at simple_statement (<anonymous>:2240:73)
  at eval (<anonymous>:2113:19)
  at eval (<anonymous>:2073:24)
  at block_ (<anonymous>:2353:20)
  at eval (<anonymous>:2326:25)
  at function_ (<anonymous>:2331:15)
  at expr_atom (<anonymous>:2546:24)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at expr_atom (<anonymous>:2532:26)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at simple_statement (<anonymous>:2240:55)
  at eval (<anonymous>:2125:24)
  at eval (<anonymous>:2073:24)
  at block_ (<anonymous>:2353:20)
  at eval (<anonymous>:2326:25)
  at function_ (<anonymous>:2331:15)
  at expr_atom (<anonymous>:2546:24)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at expr_list (<anonymous>:2565:24)
  at subscripts (<anonymous>:2699:30)
  at subscripts (<anonymous>:2676:20)
  at expr_atom (<anonymous>:2552:20)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at simple_statement (<anonymous>:2240:55)
  at eval (<anonymous>:2113:19)
  at eval (<anonymous>:2073:24)
  at block_ (<anonymous>:2353:20)
  at eval (<anonymous>:2326:25)
  at function_ (<anonymous>:2331:15)
  at expr_atom (<anonymous>:2546:24)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at expr_atom (<anonymous>:2532:26)
  at maybe_unary (<anonymous>:2716:19)
  at expr_ops (<anonymous>:2751:24)
  at maybe_conditional (<anonymous>:2756:20)
  at maybe_assign (<anonymous>:2780:20)
  at expression (<anonymous>:2799:20)
  at simple_statement (<anonymous>:2240:55)
  at eval (<anonymous>:2125:24)
  at eval (<anonymous>:2073:24)
  at eval (<anonymous>:2827:23)
  at Object.parse (<anonymous>:2837:7)
  at /home/dave/src/babel-brunch-es6-modules-test/node_modules/uglify-js/tools/node.js:64:33
  at Array.forEach (native)
  at Object.exports.minify (/home/dave/src/babel-brunch-es6-modules-test/node_modules/uglify-js/tools/node.js:59:15)
  at UglifyJSOptimizer.optimize (/home/dave/src/babel-brunch-es6-modules-test/node_modules/uglify-js-brunch/index.js:40:26)
  at Object.work (/home/dave/src/babel-brunch-es6-modules-test/node_modules/brunch/lib/fs_utils/generate.js:144:8)
  at exports.processJob (/home/dave/src/babel-brunch-es6-modules-test/node_modules/brunch/lib/workers/index.js:20:16)
  at Object.keys.filter.files.forEach.processJob.then (/home/dave/src/babel-brunch-es6-modules-test/node_modules/brunch/lib/fs_utils/generate.js:167:10)
```

### Demo App
https://github.com/xdave/babel-brunch-es6-modules-test

**Comment by goshakkk** [comment]
This does make sense. 

I'm thinking about which mechanism we should use to enable that. 

Should it be some special handling in brunch to allow babel-brunch only to process modules' javascripts?
This one is great because it will *just work* with no setup required from the user. All js files from node_modules will just go through babel-brunch.

Should there be a generally available config option to opt some plugins into compiler processing? Something like

```javascript
exports.config = {
  npm: {
    compile: {
      'credit-card': ['babel-brunch']
    }
  }
}
```

This allows for greater flexibility, but it also means more to configure... finally, can someone think of any cases when you would want to transpile npm modules, other than ES6 -> ES5?

A somewhat related #1309 was opened yesterday, with the OP wanting to enable coffeescript compilation for modules' files... For that, a special config option would do. Conceptually, distributing a module that only contains coffeescript and doesn't itself build into js, seems conceptually wrong, but is it up for brunch to enforce that ideal? Might be not.

cc @es128 @paulmillr

**Comment by paulmillr** [comment]
maybe something simpler or more implicit. not sure

**Comment by xdave** [comment]
I agree with @paulmillr on this one: less config and more convention... just not sure how to go about it.

**Comment by goshakkk** [comment]
https://github.com/brunch/brunch/pull/1318 (and related PRs) should allow to run node_modules/ through babel now. Other js compilers are also fine as long as the source has `.js` extension.

**Comment by xdave** [comment]
So, looks like #1318 has been merged.  Does that mean it's safe to test if this works now?

**Comment by xdave** [comment]
Hmm. Some things look weird here.  It looks like the module is included in the `vendor` bundle as usual (not compiled), but also included in the `app` bundle (compiled).

I've updated the demo app project above to test this.

**Comment by goshakkk** [comment]
Strange, I totally can't reproduce that. The only issue I encountered was that I had to explicitly set `config.plugins.babel.ignore`

```javascript
        babel: { ignore: /^(bower_components|vendor)/ }
```

Working properly otherwise:

![screen shot 2016-04-29 at 6 34 18 pm](https://cloud.githubusercontent.com/assets/315596/14922640/0a9fb864-0e39-11e6-866c-a620289ff5ed.png)

I'm not sure but it *could* be caused by an older version of deppack that is probably cached. Can you remove `node_modules` and `npm install` and see if it happens? (and make sure it's using deppack ver `0.4.3`)

In the meanwhile I'll figure why the default ignore for babel seems to be broken.

**Comment by goshakkk** [comment]
Actually, I think I had an older version of `babel-brunch` cached 😄 Seems to work fine on the latest `6.0.4`

**Comment by xdave** [comment]
I ran `rm -rf node_modules`, changed all of the `dependencies` and `devDependencies` versions to `*`, ran `npm update --save`, then `npm update --save-dev`.

The build still fails for me when running `brunch build --production`, because (it seems) there's still some ES6 in the `vendor.js` file:

`02 May 19:30:47 - error: JS minification failed on public/vendor.js: Unexpected token: name (_defaults) (line: 158, col: 4, pos: 4135)`

**Comment by goshakkk** [comment]
Oops. It actually appears that 2.7.4 was released before the npm deps were added so its support is not yet released. Can you try with the master brunch?

cc @paulmillr should you cut a release with just that and `SourceFile removed/disposed` fixes?

**Comment by goshakkk** [comment]
@xdave so, does it work for you on brunch 2.7.5?

**Comment by xdave** [comment]
@goshakkk It does appear to work; however, I'm encountering another problem while building in production mode with the `replacement-brunch` plugin:

```LOGGY_STACKS=true brunch build --production
06 May 20:06:59 - info: compiled 2 files into 2 files, copied index.html in 836ms
06 May 20:06:59 - error: Path must be a string. Received undefined 
Type  at assertPath (path.js:7:11)
  at Object.extname (path.js:1429:5)
  at useFiles.reduce.e (/home/dave/src/babel-brunch-es6-modules-test/node_modules/replacement-brunch/index.js:65:28)
  at Array.reduce (native)
  at ReplacePlugin.onCompile (/home/dave/src/babel-brunch-es6-modules-test/node_modules/replacement-brunch/index.js:61:27)
  at /home/dave/src/babel-brunch-es6-modules-test/node_modules/brunch/lib/plugins.js:226:31
  at callbacks.forEach.cb (/home/dave/src/babel-brunch-es6-modules-test/node_modules/brunch/lib/plugins.js:238:29)
  at Array.forEach (native)
  at callCompileCallbacks (/home/dave/src/babel-brunch-es6-modules-test/node_modules/brunch/lib/plugins.js:238:15)
  at Promise.all.then.then.data (/home/dave/src/babel-brunch-es6-modules-test/node_modules/brunch/lib/watch.js:301:7)
```

**Comment by xdave** [comment]
BTW, it doesn't look like the `replacement-brunch` problem is directly related to fixes/stuff in this issue... not sure.

**Comment by goshakkk** [comment]
(Heads up: since 2.7.6 you will have to explicitly tell brunch to use `babel-brunch` for npm files, as it being on by default has been causing issues for some people. `config.plugins.npm = ['babel-brunch']`)

Strange. I was able to build the repo just fine:

```
babel-brunch-es6-modules-test(master)$ brunch b -d
  brunch:config Trying to load brunch-config +0ms
  brunch:plugins Loaded plugins: auto-reload-brunch, babel-brunch, javascript-brunch, replacement-brunch +461ms
  brunch:watch add package.json +17ms
  brunch:watch add brunch-config.js +1ms
  brunch:watch add app/main.js +3ms
  brunch:list Reading app/main.js +1ms
  brunch:file Init app/main.js: isntModule=false isWrapped=true +2ms
  brunch:pipeline Compiling app/main.js @ AutoReloader +3ms
  brunch:pipeline Compiling app/main.js @ BabelCompiler +1ms
  brunch:pipeline Compiling app/main.js @ JavaScriptCompiler +186ms
  brunch:watch add app/assets/index.html +27ms
  brunch:asset Init app/assets/index.html directory=app/assets/ destPath=public/index.html rel=index.html +0ms
  brunch:asset Copied app/assets/index.html +6ms
  brunch:list Reading node_modules/credit-card/lib/index.js +11ms
  brunch:modules Wrapping main.js @ commonjs +1ms
  brunch:file Generated source map for 'app/main.js'  +0ms
  brunch:list Compiled app/main.js +5ms
  brunch:file Init node_modules/credit-card/lib/index.js: isntModule=true isWrapped=true +1ms
  brunch:pipeline Compiling node_modules/credit-card/lib/index.js @ BabelCompiler +0ms
  brunch:pipeline Compiling node_modules/credit-card/lib/index.js @ JavaScriptCompiler +199ms
  brunch:list Reading node_modules/reach/lib/index.js +30ms
  brunch:modules Not wrapping (is vendor file) node_modules/credit-card/lib/index.js +1ms
  brunch:list Compiled node_modules/credit-card/lib/index.js +2ms
  brunch:file Init node_modules/reach/lib/index.js: isntModule=true isWrapped=true +0ms
  brunch:pipeline Compiling node_modules/reach/lib/index.js @ BabelCompiler +0ms
  brunch:pipeline Compiling node_modules/reach/lib/index.js @ JavaScriptCompiler +36ms
  brunch:modules Not wrapping (is vendor file) node_modules/reach/lib/index.js +4ms
  brunch:list Compiled node_modules/reach/lib/index.js +1ms
  brunch:write Writing 2/2 files +74ms
  brunch:generate Concatenating [app/main.js] => public/app.js +2ms
  brunch:generate Concatenating [node_modules/credit-card/lib/index.js, node_modules/reach/lib/index.js] => public/vendor.js +9ms
  brunch:generate Writing public/app.js +7ms
  brunch:generate Writing public/vendor.js +2ms
  brunch:generate Writing public/vendor.js.map +5ms
  brunch:generate Writing public/app.js.map +3ms
07 May 13:13:19 - info: compiled 2 files into 2 files, copied index.html in 1.6 sec
```

On both 2.7.5 and the latest 2.7.7. In both production and development environments. 

Looking into compiled files, it does indeed look like the replacement was successful:

```
var results = document.querySelector('#results');
results.innerHTML = JSON.stringify(validation, null, 2);

console.log("TEST_SOMETHING_ELSE");
```

https://github.com/colinbate/replacement-brunch/blob/master/index.js#L58

One of the `useFiles` appears to be undefined, however the try-catch should catch it. `path.extname` on undefined should return `''`. Though this still could be undesired, as the asset file won't be processed. https://github.com/colinbate/replacement-brunch/blob/master/index.js#L59 references `destinationPath` when it actually is `destPath` (https://github.com/brunch/brunch/blob/master/lib/fs_utils/asset.js#L33)

cc @colinbate

**Comment by colinbate** [comment]
The differences between you might be the node version, @xdave you must be using 6+ as they made these `path` functions throw on non-strings from that version.

Looks like `asset` was changed to have `destPath` after I wrote it: 
https://github.com/brunch/brunch/commit/df88f11f4985fa3f94676e825b3e348fcebb6bfd

I'll update that. And while I'm at it I'll guard against this again with a log message.

**Comment by colinbate** [comment]
@xdave I've released 2.0.3 of `replacement-brunch` which will work with Brunch >= 2.6.3

I tested it with node 6.1.0 and confirmed it was broken before and now working. It was broken in node 5 before as well, just silently.

**Comment by xdave** [comment]
@colinbate Wow, I was thinking the same thing, as looking into the source for the plugin, it was crapping out at the `path.extname()` call, etc; so, I thought it could be a new node thing, but wasn't sure if/when they had changed it to throw.

In any case, thanks for the update(s) everyone and for helping resolve these issues!

**Comment by xdave** [comment]
I've confirmed that the test project builds (at least for me), along with the other projects I was working on that were having these issues.  So, I believe this issue can be closed.

**Comment by cxw42** [comment]
Note for others who find this issue: per the [changelog](https://github.com/brunch/brunch/blob/55cbbe75ef3e8c9e1b2389cfbc340bed6d5148a2/CHANGELOG.md), as of 2.8, to run babel-brunch on node_modules, include

    npm: {
        compilers: ['babel-brunch'],
    },

in your Brunch config.
