### ISSUE TITLE
Issue with relative paths

### ISSUE THREAD

**Issue by nblackburn** [brunch/brunch#1301]
### Description

As of 2.6.x, any imports with relative paths seem to prevent brunch from compiling them along with their dependencies.

```javascript
import loading from '../../../components/loading.vue';
```

> This application is under NDA so only very limited details can be shared.

### Environment

1. Brunch: 2.6.2
2. Node: 5.10.1
3. NPM: 3.8.3
4. Operating system: Mac OS X El Capitan (10.11.3)

### `package.json` contents

```json
{
  "scripts": {
    "watch": "brunch watch --server",
    "build": "brunch build --production"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel": "^6.5.2",
    "babel-brunch": "^6.0.2",
    "babel-core": "^6.7.4",
    "babel-polyfill": "^6.6.1",
    "babel-preset-es2015": "^6.6.0",
    "brunch": "2.6.6",
    "chai": "^3.5.0",
    "es6-promise": "^3.1.2",
    "eslint-brunch": "^3.5.0",
    "less-brunch": "^2.0.0",
    "mocha": "^2.4.5",
    "phantomjs-polyfill": "0.0.2",
    "uglify-js-brunch": "^2.0.1",
    "vue-brunch": "^1.0.0",
    "vue-hot-reload-api": "^1.3.2"
  }
}
```

### brunch config contents

```javascript
module.exports = {
    files: {
        javascripts: {
            joinTo: 'assets/scripts/app.js'
        },
        stylesheets: {
            joinTo: 'assets/styles/app.css'
        },
        templates: {
            joinTo: 'assets/scripts/app.js'
        }
    },
    plugins: {
        babel: {
            presets: [
                'es2015'
            ]
        },
        uglify: {
            compress: {
                warnings: false
            }
        }
    }
};
```

If something worked with previous versions of brunch, but stopped with a newer one, please include these details as well.

Was working without a hitch in 2.5.2

**Comment by goshakkk** [comment]
I have just tried to use a relative import with `../` on a react skeleton and it worked perfectly. The details you have provided don't seem to be enough to allow for troubleshooting.

First, let me clarify if the error you are getting is `Could not load module '${mod}' from '${src}'` in the terminal?

Second, we don't ask you share your application entirely. What we do ask, though, is that you create a minimal subset of your app that does reproduce the issue. 

As I mentioned, I couldn't reproduce it with a relative parent require which means there could be more things that factor into it in your specific case. An isolated sample app would be ideal to help us fix this. Doesn't have to leak any private info. Is this something you can please spend some time recreating?

**Comment by nblackburn** [comment]
I am working on getting something more sufficient prepared for you but wanted to get the issue up first in case it was known.

**Comment by nblackburn** [comment]
So i tried again to find it started working now for some reason.

**Comment by goshakkk** [comment]
That is nice to hear!

**Comment by nblackburn** [comment]
Figured out what it was, i was messing around with entryPoints which caused the following error...

```node
Resolving deps of app/initialize.js failed. Could not load module '../config/anychart'
```

I then removed it from my config and for some reason the error persisted until i reinstalled brunch.

**Comment by goshakkk** [comment]
Weird. If you do spot an issue with entryPoints that you think shouldn't happen — feel free to open an issue for that :)

**Comment by nblackburn** [comment]
It's the Mac, i cloned my project elsewhere and it's fine, no idea what is going on but it's acting weird lately.

**Comment by nblackburn** [comment]
Going to take a closer look at home on a reliable machine as something isnt right here.

**Comment by nblackburn** [comment]
Yup, we got an issue: https://github.com/nblackburn/brunch-bug

**Comment by goshakkk** [comment]
This seems to be windows-only issue though. For some reason, relative deps resolution is producing slightly different results on windows... I'm on it.

On OS X though, everything works just fine.

**Comment by goshakkk** [comment]
https://github.com/brunch/brunch/pull/1305 should fix this issue on Windows. Sorry about that. We were even normalizing the path to use proper slashes but kind of forgot to pass these to one of the calls... which in the end resulted in the error you were experiencing.

**Comment by goshakkk** [comment]
If it was also happening on OSX/Linux, it could have been related to https://github.com/brunch/brunch/issues/1304

I already submitted a PR for that as well https://github.com/brunch/deppack/pull/20

**Comment by nblackburn** [comment]
@goshakkk Nice one, thanks for the prompt fix!
