### ISSUE TITLE
Can't indirectly use modules that start with `@` character

### ISSUE THREAD

**Issue by xdave** [brunch/brunch#1310]
### Description

For instance, the [socrates](https://github.com/matthewmueller/socrates) package is completely unusable.  Some of its dependencies' names start with the `@` character.

Brunch builds successfully, without error, but the browser outputs the following:
`Uncaught Error: Cannot find module '@f/combine-reducers' from 'socrates/lib/tree.js'`

### Environment

1. Brunch: 2.6.6
2. Node: v5.10.1
3. NPM: 3.8.6
4. Operating system:

### `package.json` contents
```json
{
  "devDependencies": {
    "auto-reload-brunch": "^2.2.0",
    "brunch": "^2.6.6",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.1"
  },
  "dependencies": {
    "socrates": "^1.0.2"
  }
}
```

### `brunch-config.js` contents
```javascript
module.exports = {
    server: {
        hostname: '0.0.0.0'
    },
    files: {
        javascripts: {
            joinTo: {
                'vendor.js': /^(?!app)/,
                'app.js': /^app/
            }
        }
    },
    modules: {
        autoRequire: {
            'app.js': ['main']
        }
    }
};
```

### `app/main.js` contents
```javascript
var socrates = require('Socrates');
```

**Comment by goshakkk** [comment]
Nice catch! At-scoped requires were added re https://github.com/brunch/brunch/issues/1213 but the then-introduced check if a required component is optional didn't take this special case into account. I have submitted https://github.com/brunch/deppack/pull/22 to fix this, and I can confirm that with it `socrates` require adds `@f/...` to the bundle & requires them properly.
