### ISSUE TITLE
`require.register` always being added to output file

### ISSUE THREAD

**Issue by omnibs** [brunch/brunch#1315]
### Description

I'm trying to build some scripts with [Phoenix Channels](https://www.npmjs.com/package/phoenix-socket) and without modules (the target webpage has polluted window.require with something not compatible with commonjs).

### Expected behavior

Adding `modules: false, definition: false` to the `brunch-config.js` should output a file without any `window.require`.

### Actual behavior

The output `app.js` contains this on the top:

```javascript
(function() {
var global = window;
var __makeRelativeRequire = function(require, mappings, pref) {
  var none = {};
  var tryReq = function(name, pref) {
    var val;
    try {
      val = require(pref + '/node_modules/' + name);
      return val;
    } catch (e) {
      if (e.toString().indexOf('Cannot find module') === -1) {
        throw e;
      }

      if (pref.indexOf('node_modules') !== -1) {
        var s = pref.split('/');
        var i = s.lastIndexOf('node_modules');
        var newPref = s.slice(0, i).join('/');
        return tryReq(name, newPref);
      }
    }
    return none;
  };
  return function(name) {
    if (name in mappings) name = mappings[name];
    if (!name) return;
    if (name[0] !== '.' && pref) {
      var val = tryReq(name, pref);
      if (val !== none) return val;
    }
    return require(name);
  }
};

require.register("phoenix-socket/dist/socket.js", function(exports, require, module) {
  require = __makeRelativeRequire(require, {}, "phoenix-socket");
  (function() {
    "use strict";
```

Notice the `require.register` on the 4th line from bottom to top. Since the target page has polluted require with something not compatible with commonjs it blows up right in that 4th line.

I've put a very simple repo with the code here: https://github.com/omnibs/brunch-require-weirdness

### Environment

1. Brunch: 2.1.3, 2.2.3 and 2.7.2
2. Node: 5.6.0
3. NPM: 3.6.0
4. Operating system: Windows 10 x64

### `package.json` contents

```json
{
  "name": "brunch-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "phoenix-socket": "^1.1.3"
  },
  "devDependencies": {
    "javascript-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "auto-reload-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```javascript
module.exports = {
  // See http://brunch.io for documentation.
  files: {
    javascripts: {joinTo: 'app.js'},
    stylesheets: {joinTo: 'app.css'},
    templates: {joinTo: 'app.js'}
  },
  modules:{
    wrapper: false,
    definition: false
  },
  npm: {
    enabled: true,
    whitelist: ["phoenix-socket"],
    globals: {
      socket: 'phoenix-socket'
    }
  }
}
```

**Comment by goshakkk** [comment]
This happens due to `npm` integration being enabled. Sorry, you can't have it both ways — no CommonJS **plus** npm integration. Either adopt modules, or drop npm.

I think an error message in this case would be helpful, warning that you really can't have it both ways.

**Comment by goshakkk** [comment]
Submitted https://github.com/brunch/brunch/pull/1316 to throw an error early on and provide details on how to resolve it.

**Comment by omnibs** [comment]
Thanks for the quick answer and for adding the error message @goshakkk! =]

**Comment by jahbini** [comment]
Workaround -- put an alias in your brunch_config

**Comment by English3000** [comment]
I think I'm having a similar issue: https://github.com/absinthe-graphql/absinthe-socket/issues/21

Tried removing the `npm` object from `brunch-config.js`, but didn't work.
