### ISSUE TITLE
prod bundle build issue since 2.7.2

### ISSUE THREAD

**Issue by ysle** [brunch/brunch#1321]
ok so seems like `brunch b -p` doesn't create a distro/prod build anymore. no minification, and still creates the sourcemap etc

if i install 2.7.1 as `npm i brunch@2.7.1 -g`, it's start working again. i can reproduce this with the dead simple skeleton as well, without any changes on it. so just by typing the `brunch new`command as usual. but this is the same for the ts skeleton too

### Expected behavior
should have a prod build by the -p switch

### Actual behavior
doesn't 

### Environment

1. Brunch: 2.7.2 and above
2. Node: 5.10.1
3. NPM: 3.8.3
4. Operating system: win10

and no errors given

**Comment by goshakkk** [comment]
Wow, sorry! Appears to be a bad on our part, something that was introduced when I implemented the config validation... anyways, https://github.com/brunch/brunch/pull/1322 should fix it.

Thanks for your report 👍
