### ISSUE TITLE
Add --no-color option to build output

### ISSUE THREAD

**Issue by colinbate** [brunch/brunch#1324]
This is more of a feature request. Would it be possible to add a ``--no-color`` option to `brunch build` and similar to tidy up the output on terminals without color. Like the Visual Studio output panel. Or perhaps it is possible to detect the color ability. Either way would be fine.

**Comment by paulmillr** [comment]
We don't need an option for that probably. That may be adjustable already via *loggy* config settings.

**Comment by colinbate** [comment]
Great. I hoped it might be something that `loggy` could handle already. Is there a way to trigger no colour mode from brunch?

**Comment by paulmillr** [comment]
@goshakkk can we expose more loggy options?

**Comment by goshakkk** [comment]
I think so, yeah. The thing with color is that it's not project-specific but rather machine specific, and it probably makes little to no sense to put it into the `brunch-config` (same as with the number of workers), and either a flag or automatic detection (or both) would fit the bill better... don't you think?

**Comment by colinbate** [comment]
Yea, this would be per execution, not per project. Even on the same machine, when I run brunch from the console, I'd like color, but when I add brunch to my `csproj` file as a build task, it would be nice to specify no color since the Visual Studio build output doesn't support color.

![image](https://cloud.githubusercontent.com/assets/1060912/14886748/d664df7c-0d28-11e6-9e9e-08b52e6c4c64.png)

**Comment by paulmillr** [comment]
The better way to do this is to detect the env automatically.

**Comment by goshakkk** [comment]
https://github.com/paulmillr/loggy/pull/14 will make loggy try to detect whether color is supported by the terminal (adapted from another npm package). `FORCE_NO_COLOR` can also be used to disable the color regardless
