### ISSUE TITLE
brunch watch doesn't recognize new file created until restart sometimes

### ISSUE THREAD

**Issue by dalexj** [brunch/brunch#1328]
### Description

if using `brunch watch`, and you try to require a new file: `require('./new-file')`, brunch sometimes doesn't pick up the new file existing until `brunch watch` restart

### Expected behavior

new file is required

### Actual behavior

```
01 May 00:02:49 - error: Resolving deps of app/initialize.js failed. Could not load module './new-file' from '/path/to/proj'. Make sure the file actually exists.
```

and the compiled file errors out unable to require the initialize file

### Environment

1. Brunch: 2.7.4
2. Node: 5.1.1
3. NPM: 3.3.12
4. Operating system: OSX

**Comment by paulmillr** [comment]
can you try upgrading to the latest nodejs?

**Comment by dalexj** [comment]
I get the same issue with node 6.0

**Comment by goshakkk** [comment]
Can't seem to reproduce it.

Tried to:

* run a watcher
* create an `app/foo.js` file
* add a `require('./foo')`

several times but still couldn't catch that.

What I did get to err is: first add a require, then create a file. In which case, even after the file was created the error was still throwing. 

But if the file existed prior to adding a require, it does work smoothly, at least on my end.

Could there be more specifics as to how to get that to reproduce? Can you get this to reproduce consistently?

**Comment by dalexj** [comment]
running through your steps, all the steps have the same behavior you described. that would make a lot of sense as to why I only saw this happen some of the time. 

I can also fix the error with this:

* run a watcher
* add a require('./foo')
* `error` (correct error)
* create an app/foo.js file
* `error` (this is my issue)
* comment out require('./foo')
* uncomment require('./foo')
* error fixed

**Comment by goshakkk** [comment]
But in your very case, is the file created first and then the require added?

**Comment by goshakkk** [comment]
@dalexj ping?

**Comment by dalexj** [comment]
trying on brunch 2.7.7

adding `require` first and creating the file second still errors

creating the file first and adding `require` second works fine

**Comment by goshakkk** [comment]
That should be fixed on master when the deppack dependency is bumped to `~0.6.0` (https://github.com/brunch/brunch/pull/1360)
