### ISSUE TITLE
Brunch Upgrading

### ISSUE THREAD

**Issue by javajosh** [brunch/brunch#1329]
### Description

Not sure where to put this, but I had some trouble starting a new project with brunch, mainly because both node and brunch itself was out of date, as was my knowledge about it's CLI changes, in particular the deprecation of the -s switch. 

I went to start a new project today and unhappily get a `error: unknown option `-s'` error. 

Thinking that perhaps my version was out of date, I did:

```bash
$ npm install brunch -g && echo DO NOT ACTUALLY DO THIS
/usr/local/lib
└─┬ simple-brunch@0.1.1
  └─┬ csscomb-brunch@1.7.0
    └─┬ csscomb@2.0.5
      ├── commander@2.0.0
      ├── gonzales-pe@2.0.2
      ├─┬ minimatch@0.2.12
      │ ├── lru-cache@2.7.3
      │ └── sigmund@1.0.1
      ├── vow@0.4.4
      └─┬ vow-fs@0.3.2
        ├─┬ glob@3.2.8
        │ └── inherits@2.0.1
        ├── node-uuid@1.4.0
        └── vow-queue@0.3.1
```

This was actually the wrong command. It should have been `npm update brunch -g`. And anyway, I needed to update my node too, I tried a `brew upgrade node` (from memory) but that failed; it's nodejs.  Anyway I ended up doing this to upgrade node:

```bash
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

BTW the instructions in your readme refer to the --skeleton command line.

1. Brunch: 1.8.5 (now 2.7.4)
2. Node: 5.8.0 (now 6.0.0)
3. NPM: 3.7.3  (now 3.8.6)
4. Operating system: OSX 10.11.4

**Comment by goshakkk** [comment]
Which command did you run? There weren't any troubles with the new app from skeleton issues recently.

Just to make sure, are you running something like

```
brunch new my-app -s react
```

?

If you do, and it doesn't work, some more details would be appreciated.

**Comment by moviedo** [comment]
I'm using the following and it works fine for me:
Brunch: 2.7.4
Node: v4.2.6
NPM: 3.7.5
Operating system: OSX 10.11.4 through vagrant Ubuntu 14.04

I'm not to confident with using Node > v4 because v5 didn't work for me when I was using Brunch: 2.0.0.

**Comment by goshakkk** [comment]
@moviedo  I'm a contrib and I do use node 5, at Hell Yeah we also do use node 5 and everything is fine. 4 and 5 both are good, 6 probably too

**Comment by goshakkk** [comment]
@javajosh ping
