### ISSUE TITLE
AVA same method is deprecated

### ISSUE THREAD

**Issue by denar90** [brunch/brunch#1336]
### Description

In AVA `t.same` is deprecated and in console I can see smth like 
`DEPRECATION NOTICE: same() has been renamed to deepEqual() and will eventually be removed. See https://github.com/jamestalmage/ava-codemods to help upgrade your codebase automatically.`
`same()` has to be replaced by `deepEqual()` in [fs_utils.common.js](https://github.com/brunch/brunch/blob/571ea17e07bc8159bda621d7738f49e849c16944/test/fs_utils.common.js), [fs_utils.generate.js](https://github.com/brunch/brunch/blob/571ea17e07bc8159bda621d7738f49e849c16944/test/fs_utils.generate.js), [helpers.js](https://github.com/brunch/brunch/blob/571ea17e07bc8159bda621d7738f49e849c16944/test/helpers.js)

Should I create PR for this?

**Comment by paulmillr** [comment]
yes

**Comment by denar90** [comment]
Created PR #1339
