### ISSUE TITLE
Race-condition question

### ISSUE THREAD

**Issue by bigp** [brunch/brunch#1337]
This is mostly an inquiry, but do you know off-hand which parts of Brunch's processes work asynchronously / in parallel?

I've customized it quite a bit for my multiple-output setup, but often times when I run a production build it seems like some resources don't get included / inlined in their respective *.html file outputs. But after a few attempts, eventually it "gets it" and compiles correctly.

Does this sound like anything you've encountered or would know the cause of?

**Comment by paulmillr** [comment]
Are you using `-j` option?

**Comment by bigp** [comment]
No, not aware of it.

**Comment by bigp** [comment]
Could it be caused my too many file-read / -write operations that I'm making before / after compilations (preCompile / onCompile)?

**Comment by bigp** [comment]
I usually use the sync'ed methods of the FileSystem module (fs) to do the file read / writes, even if that means it must hang Brunch a bit just to be sure every steps compiles exactly in the order the custom scripts tells it to.

Maybe I took the wrong approach though. :frowning:

**Comment by paulmillr** [comment]
it's possible. What happens if you comment out pre-compile and oncompile methods?
