### ISSUE TITLE
Vendor css from node_modules

### ISSUE THREAD

**Issue by pcattori** [brunch/brunch#1338]
### Description

I have some vendor `css` files within `node_modules` and wanted to create a `vendor.css` containing all of that `css` using the `stylesheets.joinTo`

I also tried following the directions on the [FAQ](https://github.com/brunch/brunch/blob/master/docs/faq.md) , but it says to use `file.styles` key when using `css` from NPM packages. The `styles` key is not recognized: `warn: config.files.styles: unrecognized key: styles; expected either of javascripts, templates, stylesheets; perhaps you meant stylesheets`

### Expected behavior

Brunch should compile styles in NPM packages to `vendor.css`

### Actual behavior

`brunch build` compiles my `main.css` and `main.js` files but does not build the `vendor.css` file.

### Environment

1. Brunch: 2.7.4
2. Node: 5.10.1
3. NPM: 3.8.3
4. Operating system: OSX 10.11.4

### `package.json` contents

```json
{
  "name": "spend-demo",
  "author": "fe@tamr.com",
  "version": "1.0.0",
  "description": "Spend Demo",
  "main": "jsx/application.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Datatamer/spend-demo.git"
  },
  "license": "SEE LICENSE IN README.md",
  "bugs": {
    "url": "https://github.com/Datatamer/spend-demo/issues"
  },
  "homepage": "https://github.com/Datatamer/spend-demo#readme",
  "dependencies": {
    "react-router": "^2.0.0",
    "tamr-taxonomy-ui": "0.1.12",
    "tamr-ui-components": "0.1.57"
  },
  "devDependencies": {
    "babel-brunch": "^6.0.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "brunch": "^2.7.4",
    "css-brunch": "^2.6.1",
    "javascript-brunch": "^2.0.0",
    "sass-brunch": "^2.6.2"
  }
}
```

### brunch config contents

```javascript
module.exports = {
  paths: {
    public: 'build/'
  },
  files: {
    javascripts: {joinTo: {
      'main.js': /^app/
    }},
    stylesheets: {joinTo: {
      'main.css': /^app/,
      'vendor.css': /^node_modules/
    }}
  },
  plugins: {
    babel: {presets: ['es2015', 'react']},
    sass: {options: {includePaths: [
      'app/stylesheets', 'node_modules/', 'app/scripts/shared/components'
    ]}}
  }
};
```

**Comment by pcattori** [comment]
actually seems to work when I follow the instructions on the FAQ, but use `stylesheets.joinTo` instead of `styles.joinTo`. Typo in the FAQ perhaps?

**Comment by paulmillr** [comment]
yes
@goshakkk

**Comment by goshakkk** [comment]
That's a typo indeed, thanks! https://github.com/brunch/brunch/pull/1340
