### ISSUE TITLE
switch from webpack to brunch

### ISSUE THREAD

**Issue by bang88** [brunch/brunch#1341]
RT
Just a few things confuse me now

- How can i define a global variable like `DefinePlugin` do 
- we use `require.ensure()` with `webpack` but how to handle this in `brunch` way

**Comment by goshakkk** [comment]
* defining global variables from the config is not something we currently support. We do however bridge `process.env.*` from node to the browser, if that's what you are after

* you probably don't need this in brunch anyway. Our "code splitting" is basically splitting which source files get compiled to which output files. Usually it's `app.js` with app code and `vendor.js` with the deps et cetera. In the browser then both are loaded with a script tag and `require('initialize')` (or something like that) is evaluated to load the entry point.

These files contain all the modules there are; they're all loaded synchronously.

Brunch does not do "on demand" module loading.

**Comment by bang88** [comment]
Get it,but we do need this functionality things like code split our `routes` `reducers `,and env vars at development case,`brunch` is faster than `webpack` nice work,if we can solve the above points that should easy switch `webpack` to `brunch`

**Comment by goshakkk** [comment]
Webpack-style code splitting is not available in Brunch. Can you describe your use case?

It is possible to have brunch create several js bundles that originate from different files (e.g. `app/file1.js` and its deps; `app/file2.js` and its deps; and so on; via entry points)

That said, it still is going to be synchronous module loading from a single monolithic bundle. If that doesn't work for you, Brunch probably isn't what you would want to use.

**Comment by bang88** [comment]
I see,a use case is we need load module dynamically , a route config like below

```js

 export default (store) => ({
  breadcrumbName: "Repository",
  path: 'repo',
  getComponent(nextState, next) {
    require.ensure([], (require) => {
      /*  These modules are lazily evaluated using require hook, and
          will not loaded until the router invokes this callback. */
      const Repo = require('./containers/RepoContainer').default 
      const reducer = require('./modules/repo').default

      store.injectReducer({ key: 'repo', reducer })

      next(null, Repo)
    })
  }
})
```
FYI,I got an answer now,maybe `brunch` is not fit my use case .But i do like the speed...  so said .

**Comment by goshakkk** [comment]
Hm, maybe I'm just not on the same page... there does not seem to be any async loading from the server in the example you have given.

My webpack-fu is at its minimum, I previously understood the purpose of `require.ensure` as of something that fetches said modules from the server or something like that... is my understanding correct? In your case, it actually doesn't seem to do anything useful

With brunch all the modules are included in your bundle, which means all require calls are synchronous, hence I don't see the need for `require.ensure`

Modules are **only** evaluated when required. Nothing is automatically loaded for you. In your example, that would be when the `getComponent` callback is called... so what's the problem with just dropping that `ensure` call?

**Comment by bang88** [comment]
Yep,we just need load the route's file on demand,don't want include all files in a bundle,so `require.ensure` give us a try and we need it.

**Comment by goshakkk** [comment]
Well, then yeah, you are out of luck with brunch in this scenario. We don't have async module loading from the server and as far as I know, aren't planning on having one (cc @paulmillr @es128) 

It would complicate things quite a bit, and brunch's speed is in part due to its conventions and opinions and solving the common use cases well.

**Comment by goshakkk** [comment]
So if that is **critical** for you, yeah, you would be better off staying with webpack.

**Comment by bang88** [comment]
Hm,thanks for you reply,Haha

**Comment by tarciozemel** [comment]
Seizing the opportunity, @goshakkk says

> We do however bridge `process.env.*` from node to the browser

However, I already did try to `export` some vars and also use `FOO=bar brunch watch --server` to use `process.env.*` in code, but neither have worked... There's some special config to this?

**Comment by DNNX** [comment]
> However, I already did try to export some vars and also use FOO=bar brunch watch --server to use process.env.* in code, but neither have worked... There's some special config to this?

I'm having the same problem.
