### ISSUE TITLE
Resolving deps failed

### ISSUE THREAD

**Issue by nblackburn** [brunch/brunch#1342]
### Description

When updating brunch to `2.7.5` from `2.6.0` everything works fine while the watcher is working but if i restart the watcher, i am greeted with the following issue...

```
05 May 11:22:14 - error: Resolving deps of app/initialize.js failed. Could not load module '../config/anychart' from '/Users/[USER]/Workspace/[FOLDER]/app'. Make sure the file actually exists. 
05 May 11:22:14 - error: Resolving deps of app/views/[FILE].vue failed. Could not load module '../../api/messages' from '/Users/[USER]/Workspace/[FOLDER]/app/views'. Make sure the file actually exists. 
```

> **NOTE**: You should be able to reproduce this with my skeleton: https://github.com/nblackburn/brunch-with-vue

### Steps

- git clone https://github.com/nblackburn/brunch-with-vue.git brunch-1342
- cd brunch-1342
- npm install
- npm run watch
- change brunch version from `2.6.0` to `2.7.5` in `package.json`
- watcher should reload and install version without issues
- kill watcher
- npm run build
- build should fail with above messages

### Environment

1. Brunch: 2.7.5
2. Node: 5.10.1
3. NPM: 3.8.3
4. Operating system: Mac OS X El Capitan

**Comment by goshakkk** [comment]
First, obviously the upgrade won't take effect if you don't restart the watcher.

Are you using the actual 2.7.5 release or are you on the master version? I can seem to reproduce that on master but not 2.7.5

**Comment by nblackburn** [comment]
2.7.5 according to node_modules/brunch/package.json

**Comment by nblackburn** [comment]
I have updated the issue with more details.

**Comment by goshakkk** [comment]
Hm, I can't reproduce that one. Can you see if brunch from this PR https://github.com/brunch/brunch/pull/1344 will fix it for you? 

```
npm install hellyeah/brunch#abs-reg-fix
```

**Comment by nblackburn** [comment]
@goshakkk Thanks for the npm, sadly i don't have permission to install it. 😢

**Comment by nblackburn** [comment]
It was some weird pathing issue from older issues where a path that should resolve was being resolved which has since been fixed that was giving me hassle.
