### ISSUE TITLE
`this` converted to `undefined`

### ISSUE THREAD

**Issue by designermonkey** [brunch/brunch#1373]
### Description

When using pre-compiled versions of scripts, for example Modernizr, and many jQuery plugins, `thi` is always replaced with `undefined` in the compiled JavaScript.

### Expected behavior

I'm not sure what should be done here, but I think that when `this` is encountered it should be left alone, and the wrapping function should be bound to the `window` context.

### Actual behavior

Here is an example:

```javascript
window.Modernizr = function (window, document, undefined) {
    // Some code here
}, this, this.document);
```

is converted to:

```javascript
window.Modernizr = function (window, document, undefined) {
    // Some code here
}, undefined, undefined.document);
```

### Environment

1. Brunch: 2.77
2. Node: 6.0.0
3. NPM: 3.8.6
4. Operating system: OS X 10.11.4

### `package.json` contents

```json
{
  "devDependencies": {},
  "dependencies": {
    "auto-reload-brunch": "^2.7.0",
    "autoprefixer": "^6.3.6",
    "babel-brunch": "^6.0.0",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "brunch": "^2.7.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "hmr-brunch": "^0.1.0",
    "javascript-brunch": "^2.0.0",
    "postcss-brunch": "^0.5.0",
    "sass-brunch": "^2.6.2",
    "uglify-js-brunch": "^2.0.0"
  }
```

### brunch config contents

```javascript
exports.config = {
  // See http://brunch.io/#documentation for docs.
  files: {
    javascripts: {
      joinTo: {
        "js/app.js": /^app\/assets\/js/,
        "js/plugins.js": /^app\/assets\/plugins/,
        "js/polyfills.js": /^app\/assets\/polyfills/,
        "js/vendor.js": /^app\/assets\/vendor/,
      },
      order: {
        before: [
        'app/assets/js/vendor/jquery-*',
        'app/assets/js/vendor/jquery-ui.js',
        'app/assets/js/vendor/jquery.*',
        'app/assets/js/vendor/*.js'
        ]
      }
    },
    stylesheets: {
      joinTo: {
        "css/styles.css": /^app\/assets\/sass/
      }
    }
  },

  conventions: {
    assets: /^(app\/assets\/static)/
  },

  paths: {
    // Dependencies and current project directories to watch
    watched: [
      "app/assets"
    ],

    // Where to compile files to
    public: "public/assets"
  },

  // Configure your plugins
  plugins: {
    babel: {
      // Do not use ES6 compiler in vendor code
      ignore: [
        /app\/assets\/js\/vendor/
      ],
      presets: [
        'es2015'
      ],
    },
    sass: {
      mode: 'native'
    },
    postcss: {
      processors: [
        require('autoprefixer')
      ]
    }
  }
};
```

I know this isn't an ideal simple setup, this is an iteration of an app from a really horrible old gulp setup.

**Comment by goshakkk** [comment]
Looks like it's caused by Babel processing these files — which shouldn't actually happen with the `plugins.babel.ignore`, something must be off here... (If you are up to it, you can open an issue on https://github.com/babel/babel-brunch regarding this, a small repo that demonstrates the issue would be ideal.)

In general though, files not matched by the [`vendor` convention](https://github.com/brunch/brunch/blob/master/docs/config.md#conventions) *are* going to be (tried to be) compiled. Babel's ignore is more to let you bypass babel for some of your app code. With vendor files, you will probably never need to have these compiled, so might be worth to set it:

```javascript
  conventions: {
    vendor: /(^bower_components|node_modules|app\/assets\/js\/vendor)[\\\/]/
  }
```

**Comment by goshakkk** [comment]
@paulmillr can this be closed?
