### ISSUE TITLE
Brunch build - bus-error

### ISSUE THREAD

**Issue by aghosh47** [brunch/brunch#1380]
### Description

Getting a bus error on brunch build , on debian 8 amd64 bit

### Expected behavior

Should have build successfully.

### Actual behavior

I have a react project, I have my frontend js and jsx files inside a `lib` directory.
```
.
+-- lib
|  +-- js
|       +-- components
|           +-- App.react.jsx
|       +-- api
|            +-- App.js
|  +-- scss
|       +-- main.scss
|       +-- _app.scss
+-- package.json
+-- bower.json
+-- brunch-config.json
```

Here is the link to my [package.json, bower.json and brunch-config.js](https://gist.github.com/aghosh47/0b82bbffdd87ccb8f0f596818d000629)

Basically I want to output my `react`, `redux` etc into `vendor.js`, my `lib/js` into `app.js`, and `stylesheets` into `styles.min.css` and put them in the dist folder

### Environment

1. Brunch: 2.8.0
2. Node: 4.2.x
3. NPM: 2.14.x
4. Operating system: Debian 8, 64 bit

brunch:config Trying to load brunch-config +0ms
[1]    5237 bus error  brunch build -d

If there's an unexpected error during `brunch build`/`brunch watch`, please attach the compilation log with the debug flag (`-d`) **and** stack traces enabled (`export LOGGY_STACKS=true`).

If something worked with previous versions of brunch, but stopped with a newer one, please include these details as well.

**Comment by goshakkk** [comment]
It does look like a system error on your machine. Maybe your storage failed... Does a reboot help?

Also, please try removing node_modules and bower packages and installing them afresh.

**Comment by aghosh47** [comment]
ok, trying a fresh install .. after reboot .. its gonna take some time. will be back. and one more question, do I need to exclude the devDependencies or its ok to keep things as it is

**Comment by goshakkk** [comment]
What do you mean exclude devDependencies? Leave them as is, I guess

**Comment by aghosh47** [comment]
ok, I rebooted and removed node_modules and bower_components and I don't get a bus error now. I have one more question, I have removed that vendor.js file because it was taking all the node_modules like request, airbrake and concatenating them into vendor I guess. so I only have `'app.js': /^(lib\/js)/` this line .. even then why does it go it lib/tests ? I have tried `'app.js': 'lib/js'` as well

**Comment by goshakkk** [comment]
Only the things you `require` and their deps get into bundled files — so if you didn't require `airbrake`, it should not have appear in the output file.

By default brunch watches `app`, `test` and `vendor`, which could be the cause in your case if the server side code is in `app` or something.

You can tell brunch with directories to watch by setting `paths.watched` in config (should be an array of string paths — like `lib/js`, for example)

>  so I only have 'app.js': /^(lib\/js)/ this line .. even then why does it go it lib/tests ? I have tried 'app.js': 'lib/js' as well ..

This is strange, that regexp should not match `lib/tests/anything`... care to create a repo that reproduces that?

**Comment by aghosh47** [comment]
no, it wasn't lib/test , it was just test. thanks for your help. will close the issue

**Comment by aghosh47** [comment]
how I fix these
```
lib/brunch-config.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/autoprefixer/lib/autoprefixer.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/babel-polyfill/lib/index.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/react/react.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/intl/index.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/react-dom/index.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/react-router/lib/index.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/history/lib/index.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/react-redux/lib/index.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/intl/lib/core.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/brunch/node_modules/deppack/node_modules/browser-resolve/empty.js compiled, but not written. Check your javascripts.joinTo con
```
its not writing to the `dist/` folder

**Comment by goshakkk** [comment]
> lib/brunch-config.js compiled, but not written. Check your javascripts.joinTo config

Hmm, do you have two brunch configs, one in root and one in `lib`? Why?

```
7 May 09:27:22 - warn: node_modules/autoprefixer/lib/autoprefixer.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/babel-polyfill/lib/index.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/react/react.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/intl/index.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/react-dom/index.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/react-router/lib/index.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/history/lib/index.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/react-redux/lib/index.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/intl/lib/core.js compiled, but not written. Check your javascripts.joinTo config
27 May 09:27:22 - warn: node_modules/brunch/node_modules/deppack/node_modules/browser-resolve/empty.js compiled, but not written. Check your javascripts.joinTo con
```

— because none of your output files match `node_modules/`. It looks like you are using react, redux, etc on the front-end, and to let brunch add them to the output somewhere, you could change the regexp to something like `/^(lib\/js|node_modules)/`

> its not writing anything to the dist/ folder

Right, because by default brunch is configured to write into `public`. You can change that using `config.paths.public` — http://brunch.io/docs/config.html#-paths-

Note that in this case, your `joinTo` config won't need to have `dist/` in keys then, i.e. be something like `'app.js': /regexp/`.

**Comment by aghosh47** [comment]
cool, I thought adding node_modules would add all the libs from node_modules.

**Comment by aghosh47** [comment]
I have added this
```
conventions: {
    assets: [ /img[\\/]/, /svg[\\/]/]
  }
```
I have the images and svg inside `lib/img` and `lib/scss` , so is it possible to add the files to their respective directories.. like `dist/img`

```
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'js/app.js': /(lib\/js)|(node_modules)|(bower_components)/
      }
    },
    stylesheets: {
      joinTo: {
        'css/styles.min.css': /^(bower_components)|(lib\/scss)/
      }
    }
  },
  conventions: {
    assets: [ /img[\\/]/, /svg[\\/]/]
  },
  paths: {
    watched: [
      "lib"
    ],
    public: "dist/"
  },
  plugins: {
    babel: {presets: ['es2015', 'react', 'stage-2']},
    postcss: {processors: [require('autoprefixer')]}
  }
}
```

**Comment by aghosh47** [comment]
For the time being I have done it like this:

```
module.exports = {
  conventions: {
    assets: [/lib[\\/]/],
    ignored: [
      /scss[\\/]/,
      /config\.rb/
    ]
  }
}
```

**Comment by aghosh47** [comment]
presently no node_modules or jsx files are getting concatenated inside app.js .. I have added this pattern babel: {presets: ['es2015', 'react', 'stage-2'], pattern: /\.(jsx?)$/},

**Comment by goshakkk** [comment]
It could be because you are declaring all of `lib/` as assets — in which case, they won't be compiled, analyzed for node dependencies, and concatenated. Could this be it?

If it's not... debug outputs would help quite a bit, we are no mind readers.

**Comment by aghosh47** [comment]
Yeah, you are awesome, its because the whole directory was being treated as assets

**Comment by aghosh47** [comment]
@goshakkk 
Hi, 
This is my brunch config,

```
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'js/app.js': /(lib\/js\/|node_modules\/|bower_components\/)/
      }
    },
    stylesheets: {
      joinTo: {
        'css/styles.min.css': /(bower_components\/|lib\/scss\/)/
      }
    }
  },
  conventions: {
    assets: [/lib\/assets\//]
  },
  paths: {
    watched: [
      "lib/js",
      "lib/scss"
    ],
    public: "dist/"
  },
  plugins: {
    babel: {presets: ['es2015', 'react', 'stage-2'], pattern: /\.(jsx?)$/},
    postcss: {processors: [require('autoprefixer')]}
  } 
}
```
Now the problem is, its not copying stuff from app/assets to dist/ ? and when I do brunch build -d, it concatenates the javascript and stylesheets and then its paused there, it doesn't end until I do a Ctrl + C . what is happening?
