### ISSUE TITLE
jQuerys .animate() is not supported

### ISSUE THREAD

**Issue by simeg** [brunch/brunch#1382]
### Description

The watcher throws an error when I use `.animate()`.

### Expected behavior

`.animate()` should be acceptable as it is widely supported by all browsers.

### Actual behavior

The watcher throws an error saying:

`error: Compiling of app/initialize.js failed. app/initialize.js: Unexpected token (28:24)`

### Environment

1. Brunch: 2.8.0
2. Node: 4.4.0
3. NPM: 3.8.2
4. Operating system: OS X

### My code

```javascript
let popup = $("#popup");
popup.animate({"top", "0"});
```

### Error logging using `-d` flag
```
  brunch:watch change app/initialize.js +6s
  brunch:list Reading app/initialize.js +0ms
  brunch:pipeline Compiling app/initialize.js @ AutoReloader +2ms
  brunch:pipeline Compiling app/initialize.js @ BabelCompiler +0ms
  brunch:list Compiled app/initialize.js +12ms
29 May 07:24:53 - error: Compiling of app/initialize.js failed. app/initialize.js: Unexpected token (28:24) 
29 May 07:24:53 - error: Compiling of app/initialize.js failed. app/initialize.js: Unexpected token (28:24) 
```

**Comment by goshakkk** [comment]
I don't think the issue is this specific function at all. There does appear
to be a syntax error in your code and brunch just points it out.

Is the pasted snipped located on line 28?

It could be that you are not using object literal properly. Shouldn't it be
`{top: 0}` instead of `{top, 0}`?
On Sun, May 29, 2016 at 10:27 AM Simon Egersand <notifications@github.com>
wrote:

> Description
>
> The watcher throws an error when I use .animate().
> Expected behavior
>
> .animate() should be acceptable as it is widely supported by all browsers.
> Actual behavior
>
> The watcher throws an error saying:
>
> error: Compiling of app/initialize.js failed. app/initialize.js:
> Unexpected token (28:24)
> Environment
>
>    1. Brunch: 2.8.0
>    2. Node: 4.4.0
>    3. NPM: 3.8.2
>    4. Operating system: OS X
>
> My code
>
> let popup = $("#popup");popup.animate({"top", "0"});
>
> Error logging using -d flag
>
>   brunch:watch change app/initialize.js +6s
>   brunch:list Reading app/initialize.js +0ms
>   brunch:pipeline Compiling app/initialize.js @ AutoReloader +2ms
>   brunch:pipeline Compiling app/initialize.js @ BabelCompiler +0ms
>   brunch:list Compiled app/initialize.js +12ms
> 29 May 07:24:53 - error: Compiling of app/initialize.js failed. app/initialize.js: Unexpected token (28:24)
> 29 May 07:24:53 - error: Compiling of app/initialize.js failed. app/initialize.js: Unexpected token (28:24)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/brunch/brunch/issues/1382>, or mute the thread
> <https://github.com/notifications/unsubscribe/AATQzAwQwKCBDIJiAyv20LwzCj3hmkjNks5qGT_rgaJpZM4IpO7M>
> .
>
-- 
Cheers,
Gosha

**Comment by simeg** [comment]
Wow, I totally missed that. Thanks, it's working now!
