### ISSUE TITLE
Modification of a SASS file triggers a full page reload

### ISSUE THREAD

**Issue by afrz** [brunch/brunch#1385]
Hello Brunch Team ! First of all, I want to thank you all for the fantastic job on the Brunch tool ! :+1: 
... Unfortunately, I get a problem using the latest version.

### Description

Modification of a SASS **_imported/partial_** file trigger a full page reload, instead of just CSS repaint.

### Expected behavior

Such modification shall just trigger a stylesheet injection (as it was done in previous versions)

### Actual behavior

Command : **````brunch w -s````**
In app/styles/directory :
File _layout.scss
File main.scss (containing @import 'layout')

**Modification of main.scss** (*ex : change color of body background*)
=> CSS repaint with following log :
 ````
  brunch:watch change app/styles/main.scss +4s
  brunch:list Reading app/styles/main.scss +3ms
  brunch:pipeline Compiling app/styles/main.scss @ SassCompiler +6ms
  brunch:pipeline Dependencies app/styles/main.scss @ SassCompiler +162ms
  brunch:file Generated source map for 'app/styles/main.scss'  +206ms
  brunch:list Compiled app/styles/main.scss +44ms
  brunch:write Writing 1/3 files +91ms
  brunch:generate Concatenating [app/styles/main.scss] => public/build/app.css +1ms
  brunch:generate Writing public/build/app.css +56ms
  brunch:generate Writing public/build/app.css.map +17ms
  brunch:write Writing 0/0 static files, removing 0 +5ms
31 May 12:58:34 - info: compiled main.scss into app.css in 587ms
 ````

**Modification of _layout.scss** (*ex : change color of body background*)
=> full page reload with log :
````
  brunch:watch change app/styles/base/_layout.scss +3s
  brunch:list Reading app/styles/base/_layout.scss +2ms
  brunch:write Writing 0/3 files +83ms
  brunch:write Writing 0/0 static files, removing 0 +3ms
31 May 12:59:52 - info: compiled in 85ms
````

### Environment

1. Brunch: 2.8.0
2. Node: 4.1.1
3. NPM: 3.6.0
4. Operating system: Windows 7

### `package.json` contents

```
{
  "dependencies": {
    "bootstrap-sass": "^3.3.6",
    "jquery": "^2.2.4",
    "react": "^15.1.0",
    "react-bootstrap": "^0.29.4",
    "react-dom": "^15.1.0",
    "react-redux": "^4.4.5",
    "react-router": "^2.4.1",
    "react-router-bootstrap": "^0.23.0",
    "redux": "^3.5.2",
    "redux-thunk": "^2.1.0",
    "spinkit": "^1.2.5"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.7.1",
    "babel-brunch": "^6.0.4",
    "babel-preset-react": "^6.5.0",
    "brunch": "^2.8.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.6.1",
    "digest-brunch": "^1.5.1",
    "eslint": "^2.11.1",
    "eslint-plugin-react": "^5.1.1",
    "javascript-brunch": "^2.0.0",
    "sass-brunch": "^2.6.3",
    "uglify-js-brunch": "^2.0.1"
  }
}

```

### brunch config contents

```
module.exports = {
  config: {
    files: {
      javascripts: {
        joinTo: {
          'build/lib.js': /^(vendor|bower_components|node_modules)/,
          'build/app.js': /^app/
        }
      },
      stylesheets: {
        joinTo: {
          'build/lib.css': /^(vendor|bower_components|node_modules)/,
          'build/app.css': /^app/
        }
      },
      templates: {
        joinTo: 'build/app.js'
      }
    },
    npm: {
      globals: {
        '$': 'jquery',
        'jQuery': 'jquery'
      }
    },
    plugins: {
      babel: {
        presets: ['es2015', 'react'],
        ignore: /^(bower_components|vendor|node_modules)/,
        pattern: /\.js(x?)$/
      },
      sass: {
        //need for boostrap pixel rendering
        precision: 8
      }
    }
  }
};

````

### Other useful files, when present (log, `bower.json` etc.)

Exact same test using 
````
    "auto-reload-brunch": "^2.0.0",
    "brunch": "^2.5.3",
````
was working as expected. All other dependencies are exactly the same.

After try to debug, it seems that the ````changedFiles```` param in onCompile hook (auto-reload-brunch) is empty when modifing the SASS imported/partial file.

**Comment by rstacruz** [comment]
Try it with the latest version of [auto-reload-brunch](https://www.npmjs.com/package/auto-reload-brunch). I'm not sure what you're using, but ^2.0.0 seems pretty old (it's at 2.7.1 now).

**Comment by afrz** [comment]
It works with brunch 2.5.3 + auto-reload-brunch 2.0.0
but fails with brunch 2.8.0 + auto-reload-brunch 2.7.1

I'll try to create a demo project to reproduce the issue.

**Comment by afrz** [comment]
Demo repo using latest version 

https://github.com/afrz/brunch-issue-1385

**Comment by paulmillr** [comment]
@goshakkk

**Comment by rstacruz** [comment]
Thanks for the detailed issue report. Btw, I'm the one who contributed a refactor recently to auto-reload-brunch :)

**Comment by goshakkk** [comment]
This appears to be a Windows-only issue, https://github.com/brunch/brunch/pull/1387 should address it

**Comment by afrz** [comment]
I just test again using ````"hellyeahllc/brunch#file-deps-windows"````

Works fine now :+1: 
Thanks  @goshakkk
