### ISSUE TITLE
Brunch fail to find module with period in its main file.

### ISSUE THREAD

**Issue by Florian-R** [brunch/brunch#1388]
### Description

This is somehow related to #1307. If a module like [backbone.nativeajax](https://github.com/akre54/Backbone.NativeAjax) have a `main` in its package.json field with a period without extension, Brunch can't find it.

This boil down to this [regexp](https://github.com/brunch/deppack/blob/4f02aeefacd8650a6d7cd9093d9835a8951a80eb/lib/modules.js#L107) in deppack which incorrectly consider that the main file has an extension.

Happy to submit a PR if welcome, but I really have no idea how we can fix this, without broking others build.

This is really an edge-case, and I'll open a PR in the nativeajax repo, but I preferred to document here, just in case.

Feel free to close if you feel this is unsupported scenario.

### Actual behavior

Module is not found with this error : 

```
warn: main file for module 'backbone.nativeajax' does not exist (node_modules/backbone.nativeajax/backbone.nativeajax), assuming index.js
```

It is excluded of the build.

### Environment

1. Brunch: 2.8.0
2. Node: 6.2.1
3. NPM: 3.9.5
4. Operating system: Ubuntu 16.04

**Comment by goshakkk** [comment]
https://github.com/brunch/deppack/pull/35
