### ISSUE TITLE
Error when using tape

### ISSUE THREAD

**Issue by SteveALee** [brunch/brunch#1391]
### Description

I copied and adapted your basic ES6 template. But when I run I always get the following error in the browser console:

```
default_stream.js:5 Uncaught Error: Cannot find module 'through' from 'tape/lib/default_stream.js'
```
### Expected behavior

I should see the test results output to consol
### Actual behavior

Get the above error
See https://github.com/OpenDirective/spikes/tree/master/kinvey-tests
### Environment
1. Brunch: 2.8.0
2. Node:  4.4.3
3. NPM: 2.15.1
4. Operating system: windows 10 and using git for windows bash
### `package.json` contents

https://github.com/OpenDirective/spikes/blob/master/kinvey-tests/package.json
### brunch config contents

https://github.com/OpenDirective/spikes/blob/master/kinvey-tests/brunch-config.js
### Other useful files, when present (log, `bower.json` etc.)

it simply says compiling 35 files into 3 and takes 5 seconds !!

The tape version and test file worked fine with a [simpler browserify config](https://github.com/OpenDirective/spikes/tree/master/aws-cognito-user-pool-sync)

Thanks

**Comment by SteveALee** [comment]
Here's the code form vendor.js causeing the problem

```
require.register("tape/lib/default_stream.js", function(exports, require, module) {
  require = __makeRelativeRequire(require, {}, "tape");
  (function() {
    var through = require('through');
var fs = require('fs');
```

I see it's a dynamic require - does that cause brunch problems? Ie does it only do static analysis?

**Comment by SteveALee** [comment]
More info.

this seems to be the call that should resolve and so return rather than drop through to the throw causing the exception

```
    if (has.call(modules, path)) return initModule(path, modules[path]);
```

I can see ```through/index.js``` in the modules map and path is ```"tape/node_modules/defined"```

**Comment by goshakkk** [comment]
Actually the `through` require is static so Brunch should be able to handle it.

I've just cloned your repo locally and was able to build and run in the browser from the `brunch` folder successfully:

<img width="215" alt="screen shot 2016-06-11 at 8 44 45 am" src="https://cloud.githubusercontent.com/assets/315596/15983446/d78a22ae-2fb0-11e6-9dbb-54518a39b1ec.png">

That's on OS X. But a similar one seems to happen on Windows (w/o Bash), albeit with the `stream` shim (used by `through`) due to an alias for it not being set for some reason (I'm on it; but this doesn't seem to be related)

Could you please upload your public folder somewhere so I could run your locally and try to debug? As I can't seem to reproduce your issue...

**Comment by goshakkk** [comment]
Actually could it be related to the fact you're using NPM 2? We require NPM 3 currently, so that could be what gives, too

**Comment by SteveALee** [comment]
@goshakkk I'm, 99% sure I tried with npm 3 and node 5, once I realised that was the issue. I think this and the speed problem did not change. Ditto using cmd. I'll re check everything when back on my pc.

**Comment by SteveALee** [comment]
hmm, the skellaton's index.html is missing an opening html tag but that doesn't seem to matter here

**Comment by goshakkk** [comment]
Yep, this one is what I mentioned in my comments. I'll get around to seeing where it comes from this weekend

**Comment by SteveALee** [comment]
I sent a PR for the with-es6 skelleton

**Comment by SteveALee** [comment]
@goshakk dud you find anything interesting for solving this? I would like to try brunch but this is a deal breaker for me.

Thanks

**Comment by paulmillr** [comment]
@goshakkk

**Comment by SteveALee** [comment]
Thanks Paul! The mobile github experience sucks
