### ISSUE TITLE
How to put captured regex group to OutputFilePath?

### ISSUE THREAD

**Issue by ngonam22** [brunch/brunch#1392]
### Description

Hey guys, is there anyway to put the captured regex group from outputFilePath value to outputFilePath in JoinTo Javascript?

### Expected behavior
```
javascripts: {
    joinTo: {
        '${1}.js': /app\/(\w+)\//
    }
  },
```
So if i have a sub folder name 'beta1', all the Js files in that folder will be merged to beta1.js (the sub-folder name)
### Actual behavior
All js files in subfolders are in $1.js file. Its supposed to be in each Subfolder_name.js

### Environment

1. Brunch: 2.8.0
2. Node: 4.4.3
3. NPM: 2.15.1
4. Operating system: Mac OSX 10.11

### `package.json` contents

```
{
  "name": "your-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "prod": "brunch build --production"
  },
  "dependencies": {},
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "~6.0.0",
    "babel-preset-es2015": "~6.3.13",
    "brunch": "^2.4.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0",
    "brunch-typescript": "^1.8.0"
  }
}
```

### brunch config contents

```
module.exports = {
	files: {
		javascripts: {
			joinTo: {
				'vendor.js': /^(?!app)/,
				'${1}.js': /app\/(\w+)\//
			},
			sourceMap: false
		},
		stylesheets: {joinTo: 'app.css'}
	},
	plugins: {
		babel: {presets: ['es2015']}
	}
};
```

**Comment by es128** [comment]
Not currently

**Comment by goshakkk** [comment]
Yes, not supported.

What you can do as of now is either manually list each of these, or create the `joinTo` object programmatically by manually listing `app/` and iterating over its sub-folders

**Comment by ngonam22** [comment]
thank you!!!

**Comment by goshakkk** [comment]
Can this be closed then? @paulmillr
