### ISSUE TITLE
Running very slow on Windows

### ISSUE THREAD

**Issue by SteveALee** [brunch/brunch#1393]
### Description

I install the es6 skeleton and build takes 4.6 Sec to process 2 files!? 
I have a i7 and SSD Surface Pro 4

### Expected behavior

should take milliseconds according to the docs

### Actual behavior

As above

### Environment

1. Brunch: 2.8.0 (project local install)
2. Node: 4.4.3
3. NPM: 2.15.1
4. Operating system: Windows 10

### `package.json` contents

as created by es6 skeleton - I noticed some package versions are not latest

### brunch config contents

as created by es6 skeleton

### Other useful files, when present (log, `bower.json` etc.)

None

**Comment by afrz** [comment]
I think you should try with **npm 3**
Babel 6 is known to be super slow combined with npm 2.

https://phabricator.babeljs.io/T3067
https://phabricator.babeljs.io/T2706

Do not forget to re-install all your node_modules afterwards.

**Comment by SteveALee** [comment]
I'll give it ago. I did try updating npm to 3 from the version with node but it failed with nvm-windows. I'll have to dig further.

**Comment by paulmillr** [comment]
Yeah. We don't support NPM v2.

**Comment by SteveALee** [comment]
So I upped to the latest stable node (5.1.10) and supplied npm (3.8.3) and it's definitely better. I'll use those for now on and forget about LTS

```bash
C:\projects\spikes\brunch>node_modules\.bin\brunch build
11 Jun 17:39:36 - info: compiled 33 files into 2 files, copied index.html in 1.8 sec
```

thanks for your help. And sorry for ignore the clear message.
