### ISSUE TITLE
Error accessing Node Buffer API from starter project

### ISSUE THREAD

**Issue by pizza2code** [brunch/brunch#1394]
### Description

I was evaluating Brunch as a replacement for our current Gulp setup.  An important part of this is the ability to use Node modules on the front end.

After installing brunch globally, I installed the starter "brunch new" project, and made a small test change to the init.js file:

``` javascript
document.addEventListener('DOMContentLoaded', function() {
  // do your setup here
    var Socket = require('net').Socket;
    var Buffer = require('buffer').Buffer;
});
```

After doing a "brunch build", when I visit the page in any browser I get:
`Uncaught Error: Cannot find module 'base64-js' from 'brunch/node_modules/buffer/index.js'`

Oddly, it gets past `require('net').Socket` which seems to imply that Brunch _does_ support the native Node API.  Is Buffer also supposed to work?
### Environment
1. Brunch: 2.8.0
2. Node: v5.9.0
3. NPM: 3.7.3
4. Operating system: RedHat Enterprise 6

**Comment by pizza2code** [comment]
I see a similar error in issue #1293.  I installed Brunch locally as mentioned in that thread, and that does fix the module resolution.

But as I installed, NPM warned that Brunch should be installed globally.  So it seems this is not desired behavior

**Comment by goshakkk** [comment]
Actually since Brunch 2, the encouraged approach is to install Brunch locally.

We've got around to finally remove that warning yesterday https://github.com/brunch/brunch/pull/1396
