### ISSUE TITLE
Ordering of require aliases

### ISSUE THREAD

**Issue by colinbate** [brunch/brunch#1399]
### Description

The ordering of the `require.alias` calls at the end of generated JavaScript bundles is not consistent between subsequent runs of `brunch build`. If you are generating a hash of the contents to append to the filename, this means it will be different each time regardless if something has actually changed.

### Expected behavior

Given the same input code, Brunch would generate the same output files.

### Actual behavior

The `require.alias` calls can appear in different order on subsequent runs on the same code base.

### Environment

1. Brunch: 2.8.0
2. Node: 6.1.0
3. NPM: 3.7.5
4. Operating system: Mac OSX El Capitan

### Reproduction

You can probably see this with most projects. You should be able to see it with the `with-redux` skeleton.

**Comment by goshakkk** [comment]
https://github.com/brunch/deppack/pull/36 should address this
