### ISSUE TITLE
javascripts - vendor - multiple buffer packages

### ISSUE THREAD

**Issue by modmanx** [brunch/brunch#1401]
I have a weird issue that I am not sure how to solve. I am using npm module lodash in my project and somewhere in main js code I do require('lodash'). While lodash library loads, it emits error:

```
frontend.js:3Uncaught Error: Cannot find module 'buffer' from 'src/web/static/frontend/js/frontend.js'
```

Therefore I created new project with `brunch new proj -s es6` command and installed lodash npm module as-well. Lodash works in new project.

I investigated a little bit and what I see is that vendor.js from my project looks like

```
// more content
require.register("node-browser-modules/node_modules/buffer/index.js", function(exports, require, module) {
  require = __makeRelativeRequire(require, {}, "node-browser-modules/node_modules/buffer");
// more content
```

and vendor.js from new (empty) project looks like

```
// more content
require.register("buffer/index.js", function(exports, require, module) {
  require = __makeRelativeRequire(require, {}, "buffer");
// more content
```

What is different is a package that's resolved to buffer.

Both projects have `node-browser-modules/buffer` and `buffer` packages in `node_modules` folder

How should I debug this?

**Comment by goshakkk** [comment]
Did you install anything else in the new project? Are you on npm3? 

What could be causing it is your `package.json` [indirectly] depends on several packages that need `buffer` pkg. What NPM3 will do is try to install only one instance of it, but if different versions of a package are needed, there will be several copies of it in `node_modules`.

I have just tried this and I'm getting only one `buffer` package (in the root of node_modules)

---

node-browser-modules depends on buffer to provide a shim. If nothing else needs buffer, or if the needed versions of buffer match, there will only be one, in the root.

However, if the node-browser-modules has buffer in it, and there's also buffer in root... it could be a sing that some of your other deps uses a different version of buffer. If that's the case, then the behavior you are receiving (two buffer modules) is correct as it would include both different versions of buffer.

**Comment by goshakkk** [comment]
@modmanx ping?

**Comment by modmanx** [comment]
I will take a look on this issue today. Sorry for delay in response.

**Comment by HangingClowns** [comment]
same. having a problem with this. Looks like it should require `module.id`, not just the string buffer.

**Comment by franbenz** [comment]
Hi @modmanx , @HangingClowns. Did you resolve this? Did you find a workaround?

**Comment by HangingClowns** [comment]
forgot, i think my node and npm was too old.

**Comment by franbenz** [comment]
I just upgraded node and npm. These are some version numbers I get when I do `npm version` :
```
npm: '3.10.9',
ares: '1.10.1-DEV',
http_parser: '2.7.0',
icu: '57.1',
modules: '48',
node: '6.9.1',
openssl: '1.0.2j',
uv: '1.9.1',
v8: '5.1.281.84',
zlib: '1.2.8'
```
But still no luck.

**Comment by franbenz** [comment]
I checked on a different machine where this issue isn't happening. It has older versions of node and npm. The generated vendor.js contains an alias for the buffer module:
`require.alias("brunch/node_modules/deppack/node_modules/node-browser-modules/node_modules/buffer/index.js", "buffer");`
This kind of aliasing for `buffer` doesn't appear on vendor.js from the setup where this issue appears.

**Comment by newpdv** [comment]
Having a problem with this too. Did someone solve the problem?
npm installs two identical versions to root and brunch subDependencies:
+-- brunch@2.10.17
| `-- deppack@0.8.0
|   `-- node-browser-modules@0.1.0
|     `-- buffer@4.3.1
`-- buffer@4.3.1
