### ISSUE TITLE
preCompile not called during watched dir compile passes?

### ISSUE THREAD

**Issue by nompute** [brunch/brunch#1406]
This is on Brunch 2.8.0.  I'm trying to write a plugin/use a preCompile hook to run a compile that doesn't do 1:1 compiling of files to js.  However, it looks like while the preCompile hooks (plugin and otherwise) are called when running `brunch build`, or when watchers are reloaded when `brunch-config.js` changes, if a watched file/dir is change, those hooks don't seem to get called on live recompiles.  Is this expected behavior?

(Side note, preCompile doesn't show up anywhere in the docs.)

In case it matters, I'm doing this in the context of a Phoenix Framework project.

**Comment by goshakkk** [comment]
As it is, preCompile is only called once. @paulmillr @es128 would it make sense to have it run before every compilation instead?

**Comment by es128** [comment]
In the original implementation it was called every time a build cycle was triggered iirc. I would consider that the correct behavior. 

Now that we have `hooks` though maybe it's worth having a separate hook for each way.

**Comment by nompute** [comment]
Submitted a PR for this.  Does not currently add a "run-once" hook as suggested by @es128.
