### ISSUE TITLE
wrapper behaviour

### ISSUE THREAD

**Issue by michahell** [brunch/brunch#1409]
Currently, for new brunch users, it is REALLY, REALLY, REALLY unclear why your ```app.js``` is not being executed.
Apparently, this has to do with 'wrapping behaviour', which is an awesome feature. 
But not really explained that without setting this to ```false``` in your ```brunch-config``, nothing will ever happen :)

Imo, that is a big blocker (on behalf of new brunch users) to even getting started with brunch.

I refer to this SO post: http://stackoverflow.com/questions/18145790/javascript-not-displaying-brunch-io-brunch-with-brunch

and the brunch documentation, which mentions modules as being a 'less common option' ([wat?](http://i0.kym-cdn.com/photos/images/newsfeed/000/588/697/1d2.jpg))
http://brunch.io/docs/config#-modules-

**Comment by goshakkk** [comment]
What you really want to do is NOT disable the modules, but add `<script>require('entry-file-name')</script>` to your HTML, or add an `autoRequire`

Modules are useful for app code organization, also without modules you won't be able to use Brunch's npm integration.

**Comment by tolyo** [comment]
@michahell All the more recent skeletons support modules with the proper set up and come in various flavors. Use them as an entry point/

**Comment by paulmillr** [comment]
Yeah. Almost every skeleton specifies the correct behavior. We may want to highlight the thing in docs

**Comment by goshakkk** [comment]
@paulmillr opened https://github.com/brunch/brunch.github.io/pull/154 for that

**Comment by michahell** [comment]
> Modules are useful for app code organization, also without modules you won't be able to use Brunch's npm integration.
Yes, I know about the first. The second thing I didn't notice, because for a quick test I only had a jquery = require('jquery'); and it seemed to work, but this was due to a lingering CDN script tag.
Anyway, ```<script>require('entry-file-name')</script>``` seems ok to me now. I still think it's weird (but apparently it works like this). Because you also don't include your main CSS like this:
```<style>@import main.css<style>``` right ?
Thanks for opening an issue for this!

**Comment by goshakkk** [comment]
CSS is different altogether. Styles are global.

Without you giving it an entry, where would it start? It could also be the case you have several entries you would want in different cases. Even webpack relies on you specifying where it starts, it just makes sense.

**Comment by tolyo** [comment]
... and CSS doesn't need a `main` method because it is declarative DSL. Javascript does. You want specificity as to when and where your program runs. `require(module)` allows you to do precisely that.

**Comment by michahell** [comment]
of course, you are both missing the point. ```<script src="main.js">``` or ```<script src="app.js">``` as is usual, is just as clear as entry point and is probably what everyone is doing in the first place. And then finding out that this does not work, and figuring out that they've missed a VERY important piece of documentation.

**Comment by paulmillr** [comment]
We have the docs now. I think we can stop this.
