### ISSUE TITLE
Provide Globals As a Required Package Similar to externals of Webpack

### ISSUE THREAD

**Issue by ferhatelmas** [brunch/brunch#1415]
Is there a way to provide globals as a required package similar to `externals` of Webpack?

For example, we can add React from CDN via a script tag. However, npm packages requiring React would give error while bundling because there is no React package installed. It should be somehow possible to expose global React to them.

**Comment by goshakkk** [comment]
Currently there is none.

Also, I'm not 100% sure, but if React from CDN is loaded before your bundle, won't the React bundle create its own `require`? Therefore not giving a chance for Brunch to bootstrap its own `require?

**Comment by robert-zaremba** [comment]
+1

> Also, I'm not 100% sure, but if React from CDN is loaded before your bundle, won't the React bundle create its own require? Therefore not giving a chance for Brunch to bootstrap its own `require?

The problem is during package building (not loading in the browser).
