### ISSUE TITLE
adding library from package.json to build

### ISSUE THREAD

**Issue by alec-c4** [brunch/brunch#1418]
Hi,
i'd like to create brunch skeleton with support of http://mithril.js.org/ but could you please tell me - how to correctly include mithril.min.js from node_modules/mithril to main html template?

**Comment by paulmillr** [comment]
It is not recommended to include minified files since brunch does the minifying in production env and because minified files are hard to debug.

If you just use `require('mitril')` or whatever the name of the package on NPM is, that should do the trick.
