### ISSUE TITLE
Brunch build hangs on sass-compilation

### ISSUE THREAD

**Issue by nicohvi** [brunch/brunch#1419]
### Description

Whenever I try to build my sass files the build doesn't exit properly, it just hangs basically.

### Environment

1. Brunch: 2.1.3
2. Node: 6.2.0
3. NPM: 3.8.9
4. Operating system: OSX El Capitan

### `package.json` contents

```json
{
  "repository": {},
  "devDependencies": {
    "babel-brunch": "~6.0.0",
    "brunch": "~2.1.3",
    "clean-css-brunch": "~1.8.0",
    "css-brunch": "~1.7.0",
    "javascript-brunch": "~1.8.0",
    "phoenix": "file:deps/phoenix",
    "phoenix_html": "file:deps/phoenix_html",
    "sass-brunch": "^2.6.3",
    "uglify-js-brunch": "~1.7.0"
  }
}
```

### brunch config contents

```javascript
exports.config = {
  files: {
    javascripts: {
      joinTo: "js/app.js"
    },
    stylesheets: {
      joinTo: "css/app.css"
    }
  },

  conventions: {
    assets: /^(web\/static\/assets)/
  },

  paths: {
    watched: [
      "web/static",
      "test/static"
    ],

    public: "priv/static"
  },

  plugins: {
    babel: {
      ignore: [/web\/static\/vendor/]
    }
  },

  modules: {
    autoRequire: {
      "js/app.js": ["web/static/js/app"]
    }
  },

  npm: {
    enabled: true,
    whitelist: ["phoenix", "phoenix_html"]
  }
};
```

### Other useful files, when present (log, `bower.json` etc.)
This is what `brunch b -d` looks like.

![screen shot 2016-06-22 at 09 52 01](https://cloud.githubusercontent.com/assets/430875/16258633/05b553ae-385f-11e6-80dc-7474db798006.png)

**Comment by nicohvi** [comment]
The problem was actually the fact that I was trying to load a dependency from a file with an incorrect path, but it seems the error was swallowed by  `brunch-sass` and caused it to enter an endless loop (the node process would eventually rack up a lot of CPU). 

Removing the incorrect paths solved the problem.

**Comment by shvaikalesh** [comment]
For better experience and performance, please consider upgrading to Brunch 2.8. Among other nice features, we have recently added console warnings for plugins that take too long to process.
