### ISSUE TITLE
Is there a way to modify/rewrite import in Brunch?

### ISSUE THREAD

**Issue by webdif** [brunch/brunch#1420]
I'm currently working on a react app with brunch. I'm doing server-side rendering with a express app, and I want to avoid this rendering to come across some front-end feature such as `window`. I did something like this (silly example, but that's the idea):

In `app.js`:
```es6
import window from 'adaptors/server/window';
// ...
window.addEventListener(/* ... */)
```

In `adaptors/server/window`:
```es6
export default {
  addEventListener: function() {},
  // ...
};
```

In `adaptors/client/window`:
```es6
export default window;
```

The express app is rendering my react app correctly, as my `app.js` is importing `adaptors/server/window`. Now, I want to tell Brunch to render, but with  `adaptors/client/window` instead.

I understand that it is possible to do this with browserify, with [aliasify](https://github.com/benbria/aliasify). Is it possible with Brunch?

Thanks for the help!

**Comment by shvaikalesh** [comment]
Yes, it is possible with `npm.aliases` as of Brunch 2.3: [example](https://github.com/paulmillr/brunch-with-chaplin/blob/master/brunch-config.coffee#L17).

We will add it to the [docs](http://brunch.io/docs/config#-npm-) shortly.

**Comment by webdif** [comment]
Great! Thanks a lot, it works 👍
