### ISSUE TITLE
Inline source maps

### ISSUE THREAD

**Issue by jacksonrayhamilton** [brunch/brunch#1424]
### Description

Outputting source maps to separate files seems to cause race conditions when watching those files.

### Expected behavior

When using `brunch watch` with Karma (running it in a separate terminal tab via `karma start`), `karma-sourcemap-loader`, and the following `karma.conf.js` configuration:

```js
module.exports = function (config) {
  config.set({
    files: [
      {pattern: 'public/**/*.map', included: false, watched: false},
      'public/app.js'
    ],
    preprocessors: {
      '**/*.js': ['sourcemap']
    },
    frameworks: ['mocha'],
    browsers: ['Chrome']
  });
};
```

Then I expect Karma to load app.js and it's source map whenever I make a change to app.js.

### Actual behavior

Sometimes when I make a change to a file, the source map is loaded successfully. But quite often, when the source map is read, it is blank; I am guessing this is due to a race condition where app.js gets saved before app.js.map is completely written to disk.

The stack trace I get in Karma is as follows:

```
28 06 2016 13:17:38.845:INFO [watcher]: Changed file "/project/public/app.js".
28 06 2016 13:17:38.884:ERROR [karma]: SyntaxError: Unexpected end of JSON input
  at Object.parse (native)
  at sourceMapData (/project/node_modules/karma-sourcemap-loader/index.js:12:29)
  at /project/node_modules/karma-sourcemap-loader/index.js:51:11
  at /project/node_modules/graceful-fs/graceful-fs.js:78:16
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

`SyntaxError: Unexpected end of JSON input` is due to the ".js.map" file's contents being blank.

I am guessing this problem could be avoided by making it possible to include source maps inline in app.js, so external watchers couldn't end up reading another file in the midst of it being written; i.e., we could use source maps of the style `//@ sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW...`

Here is a demonstration of this error: [jacksonrayhamilton/brunch-karma-source-map-demo](https://github.com/jacksonrayhamilton/brunch-karma-source-map-demo)

### Environment

1. Brunch: 2.8.2
2. Node: 6.2.1
3. NPM: 3.9.3
4. Operating system: Mac OS El Capitan (v10.11.4)

### `package.json` contents

```json
{
  "scripts": {
    "start": "brunch watch",
    "test": "karma start"
  },
  "devDependencies": {
    "brunch": "^2.8.2",
    "javascript-brunch": "^2.0.0",
    "karma": "^1.1.0",
    "karma-chrome-launcher": "^1.0.1",
    "karma-mocha": "^1.1.1",
    "karma-sourcemap-loader": "^0.3.7",
    "mocha": "^2.5.3"
  }
}
```

### brunch config contents

```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'app.js': /.*/
      }
    }
  }
};
```

**Comment by jacksonrayhamilton** [comment]
I added inline source map support here: https://github.com/jacksonrayhamilton/brunch/commit/157e90fcc191a7088d77603d49fb1017f1f0b5fa Afterwards, after quite a few attempts to reproduce the race condition, I couldn't, so I assume this does fix my issue. Would you be willing to accept a pull request with this feature?

**Comment by shvaikalesh** [comment]
Hey @jacksonrayhamilton, please go ahead and send the PR, I will do the review.
