### ISSUE TITLE
Running watch on docker does not work

### ISSUE THREAD

**Issue by drFabio** [brunch/brunch#1428]
Running inside a docker container with:
```shell
 brunch watch --server -P 9000 
```
on which 9000 is a shared port does not works.
Inside the container the content is correctly served, outside of it it does not work.
I tried with 
```shell
 brunch watch --server -P 9000:0.0.0.0
```
To allow access to all ip's but it did not work as well

**Comment by paulmillr** [comment]
try brunch from the github and `-n` option.

**Comment by drFabio** [comment]
That did it . Thanks
