### ISSUE TITLE
"Cannot find module" Error when using react-quill

### ISSUE THREAD

**Issue by daisuke-morita** [brunch/brunch#1433]
### Description

I got the following error in the browser console when using [react-quill](https://github.com/zenoamaro/react-quill):

```
Uncaught Error: Cannot find module 'react-dom/server' from 'react-quill/src/toolbar.js'
```
### Actual behavior

You can reproduce the error with https://github.com/ubicast/brunch-test
### Environment
1. Brunch: 2.8.2
2. Node: 5.4.1
3. NPM: 3.3.12
4. Operating system: Mac OS X 10.9.5
### `package.json` contents

https://github.com/ubicast/brunch-test/blob/master/package.json
### brunch config contents

https://github.com/ubicast/brunch-test/blob/master/brunch-config.js

**Comment by chrisdopuch** [comment]
This may be related to this issue: https://github.com/facebook/react/issues/8556
It also has to do with another React-related module trying to load a react-dom module in a brunch environment
