### ISSUE TITLE
Fail to use file build (module __globals__ not found)

### ISSUE THREAD

**Issue by baptistedonaux** [brunch/brunch#1436]
### Description

I build my TypeScript file without disable npm/modules support. When I try to require my package built in an other file I have this fail.

```
Error: module "___globals___" not found
```

I use Gulp and Browserify to build my project.
### Environment
1. Brunch: 2.8.2
2. Node: 6.2.2
3. NPM: 3.9.5
4. Operating system: Debian via Docker
### `package.json` contents

``` json
{
  "main": "./dist/development/autocomplete.js",
  "devDependencies": {
    "brunch": "2.8.*",
    "brunch-typescript": "1.8.*",
    "less-brunch": "2.6.*",
    "uglify-js-brunch": "2.0.*"
  },
  "scripts": {
    "brunch": "brunch"
  }
}
```
### brunch config contents

``` javascript
'use strict';

module.exports.config = {
    paths: {
        'public': 'dist',
        'watched': [
            'src'
        ]
    },
    files: {
        stylesheets: {
            joinTo: {
                'autocomplete.css': /^src/
            }
        },
        javascripts: {
            joinTo: {
                'autocomplete.js': /^src/
            }
        }
    },
    modules: {
        definition: "commonjs",
        wrapper: "commonjs"
    }
};

```
### Other useful files, when present (log, `bower.json` etc.)

[The project is available here.](https://github.com/autocompletejs/autocomplete.js)

Something to know about CommonJS wrapper ?

**Comment by paulmillr** [comment]
You don't need to do the config.modules thing, default values *are* commonjs.

**Comment by baptistedonaux** [comment]
Yes, commonjs is the default value used. Without ```config.modules``` I have the same result.

brunch-config.js
```js
'use strict';

module.exports.config = {
    paths: {
        'public': 'dist',
        'watched': [
            'src'
        ]
    },
    files: {
        stylesheets: {
            joinTo: {
                'autocomplete.css': /^src/
            }
        },
        javascripts: {
            joinTo: {
                'autocomplete.js': /^src/
            }
        }
    }
};
```

**Comment by baptistedonaux** [comment]
@paulmillr Sorry to be insistent, do you use a custom wrapper ?

**Comment by paulmillr** [comment]
no. Can you check if that also happens to non-typescript files. I think it may be a ts problem
