### ISSUE TITLE
Cannot require files from `app/` directory within sibling directories

### ISSUE THREAD

**Issue by jacksonrayhamilton** [brunch/brunch#1441]
### Description

When I try to require files from the `app/` directory using a relative path while in a directory which is a sibling to `app/`, the module can't be found.

For instance, I have `/app/` and `/test/`, and from `/test/foo.test.js` I try to require `/app/foo.js` with `require('../app/foo')`.

### Expected behavior

I expect that I can require the file at the relative path.

### Actual behavior

Instead I get `Uncaught Error: Cannot find module 'app/foo' from 'test/foo.test.js'`

I originally created this demo repo for another issue, but it can also demonstrate this one: https://github.com/jacksonrayhamilton/brunch-karma-source-map-demo/blob/master/test/foo.test.js

After `cd`-ing into that project's directory, try running `npm start` and `npm test` in separate terminal tabs. Notice how `require('foo')` resolves the module fine. But change that expression in `foo.test.js` to `require('../app/foo')`, and you will see the error.

I have a feeling this is due to the way module definitions are generated; `app/foo.js` gets the header `require.register("foo.js", ...)`, whereas `test/foo.test.js` gets the header `require.register("test/foo.test.js", ...)`. If I manually edit the generated `public/app.js` to change `app/foo.js` header to `require.register("app/foo.js", ...)`, then I can require it using the relative path which I expect should work.

### Environment

1. Brunch: 2.8.2
2. Node: 6.2.1
3. NPM: 3.9.3
4. Operating system: Mac OS El Capitan (v10.11.4)

### `package.json` contents

```json
{
  "scripts": {
    "start": "brunch watch",
    "test": "karma start"
  },
  "devDependencies": {
    "brunch": "^2.8.2",
    "javascript-brunch": "^2.0.0",
    "karma": "^1.1.0",
    "karma-chrome-launcher": "^1.0.1",
    "karma-mocha": "^1.1.1",
    "karma-sourcemap-loader": "^0.3.7",
    "mocha": "^2.5.3"
  }
}
```

### brunch config contents

```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'app.js': /.*/,
        'tests.js': /^test\//
      }
    }
  },
  modules: {
    autoRequire: {
      'tests.js': ['test/run']
    }
  }
};
```

**Comment by tolyo** [comment]
`module.exports = 'foo';`  so `require('foo');` === `foo`. Fix to `bar` and your test shall pass.

**Comment by jacksonrayhamilton** [comment]
Sorry, that error is a distraction. Please re-read this issue's description, and you will see I am referring to an error with `require`:

> After `cd`-ing into that project's directory, try running `npm start` and `npm test` in separate terminal tabs. Notice how `require('foo')` resolves the module fine. But change that expression in `foo.test.js` to `require('../app/foo')`, and you will see the error.

**Comment by tolyo** [comment]
Well that error is resolved by creating `/app/app/foo.js`. Ideally you would have your tests under the `app` folder anyway as they are part of the app.

**Comment by jacksonrayhamilton** [comment]
Regardless of how I organize my files, I found it peculiar that the generated definitions only sometimes mirror the filesystem; this is different from other CommonJS implementations.

**Comment by jacksonrayhamilton** [comment]
Am I the only one experiencing this bug? Because it seems like it would be an "obvious" problem with `require` for anyone who steps outside `app`.

**Comment by paulmillr** [comment]
Brunch automatically removes `app` from the module name — this is done by purpose; since in most brunch apps the code usually resided inside `app` — it would be tedious to type the redundant prefix every time.

This behavior can be disabled by setting [config.modules.nameCleaner](http://brunch.io/docs/config#-modules-) to this: `function(name) {return name}`.

**Comment by jacksonrayhamilton** [comment]
@paulmillr, thanks for the explanation. However, I am having trouble getting your suggestion to work. I get the same error as before, even with `nameCleaner`. The generated code in `public/` also still omits the "app/" prefix. [See here](https://github.com/jacksonrayhamilton/brunch-require-demo) for the use case.

**Comment by jacksonrayhamilton** [comment]
Also, allow me to explain further why I created this issue: I am accustomed to Node's CommonJS model, where `require` always resolves modules relative to the current directory, or it resolves from `node_modules/`:

```js
// This file is /src/file.js
require('./nearby-file'); // exists at /src/nearby-file.js
require('installed-package'); // exists at /node_modules/installed-package/index.js
```

```js
// This file is /src/subdir/subfile.js
require('./nearby-subfile.js'); // exists at /src/subdir/nearby-subfile.js
require('../nearby-file.js'); // exists at /src/nearby-file.js
require('installed-package'); // exists at /node_modules/installed-package/index.js
```

It's unusual to me that I can do `require('nearby-file')` (without "./"). It also seems like that could cause confusion if there were also an installed npm package with the same name as a file in `app/`.

But maybe I need to change the way I think about `require` when I use Brunch? That is, should I think in terms of the project, rather than the module? That is, does Brunch expect me to use `require` in the following manner, instead?

```js
// This file is /src/file.js
require('nearby-file'); // exists at /src/nearby-file.js
require('installed-package'); // exists at /node_modules/installed-package/index.js
```

```js
// This file is /src/subdir/subfile.js
require('subdir/nearby-subfile.js'); // exists at /src/subdir/nearby-subfile.js
require('nearby-file.js'); // exists at /src/nearby-file.js
require('installed-package'); // exists at /node_modules/installed-package/index.js
```

What confuses me is that both of the above models for using `require` seem to work in Brunch (as Brunch supports both relative paths and "absolute relative from the project root" paths), _except_ in the case that I have highlighted in this bug report.

**Comment by paulmillr** [comment]
You have two `modules` properties.

https://github.com/jacksonrayhamilton/brunch-require-demo/blob/master/brunch-config.js#L2
https://github.com/jacksonrayhamilton/brunch-require-demo/blob/master/brunch-config.js#L15

**Comment by jacksonrayhamilton** [comment]
Thanks, that fixed it.

**Comment by jacksonrayhamilton** [comment]
Is anyone from the Brunch team able to confirm or deny [my understanding](https://github.com/brunch/brunch/issues/1441#issuecomment-241272030) of how `require` in Brunch is intended to be used?

**Comment by paulmillr** [comment]
I agree — this is an unconventional decision, but so far it did not bring us any issues. So, this exists mostly for backwards compatibility.
