### ISSUE TITLE
brunch watch command warning

### ISSUE THREAD

**Issue by kockok** [brunch/brunch#1443]
This message appears when brunch is in watching mode.

`12 Jul 12:46:18 - warn: config.hot: perhaps you meant npm, hooks`

### Environment

1. Brunch: 2.8.2
2. Node: 6.2.2
3. NPM: 3.9.5
4. Operating system: OSX 10.11.5

**Comment by paulmillr** [comment]
could you show us your config?

**Comment by kockok** [comment]
the default config:

```
exports.config = {
  hot: true,

  files: {
    javascripts: { joinTo: 'app.js' },
    stylesheets: { joinTo: 'app.css' }
  },

  plugins: {
    babel: { presets: ['es2015', 'react'] }
  }
};

```

**Comment by ferologics** [comment]
? ... have the same thing

**Comment by cayman** [comment]
I have the same errorwarn: config.hot: perhaps you meant npm, hooks
brunch  "version": "2.8.2"

**Comment by shvaikalesh** [comment]
@cayman Please, try using Brunch from master.

**Comment by cayman** [comment]
Brunch is the best!!!

**Comment by cayman** [comment]
Аfter switching on the master branch:
error: Linting of app/initialize.js failed. Path must be a string. Received [Function]

In version 2.8.2 is no error
