### ISSUE TITLE
Brunch + ES6 + Cycle.js Diversity = Cannot find module 'snabbdom-to-html' from '@cycle/dom/lib/makeHTMLDriver.js'

### ISSUE THREAD

**Issue by nicoespeon** [brunch/brunch#1449]
### Description

Brunch doesn't build properly the default Cycle.js Diversity + ES6 application.

Set up a new project from Brunch ES6 skeleton (`brunch new proj -s es6`) + update the `initialize.js` code with the [standard Cycle.js Diversity example](http://cycle.js.org/#example) = served app doesn't work as it can't find module 'snabbdom-to-html' used.

<img width="680" alt="capture d ecran 2016-07-17 a 14 36 07" src="https://cloud.githubusercontent.com/assets/1094774/16900722/441628ee-4c2d-11e6-8fc9-af6de09446a8.png">

### Expected behavior

The app should have been served properly.

I wonder for a long time if that was an issue from Cycle.js or from Brunch. But I think the Cycle.js example should be working for people who simply use babel or typescript and that's a edge case that Brunch might not handle yet. Please correct me if I'm wrong 😉 

### Actual behavior

The app doesn't work.

I set up a repo to reproduce this specific issue so you can see for yourself: <https://github.com/nicoespeon/cyclejs-diversity-brunch>

### Environment

1. Brunch: v2.8.2
2. Node: v4.0.0
3. NPM: v3.10.2
4. Operating system: OSX v10.11.5

### `package.json` contents

```json
{
  "name": "your-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "prod": "brunch build --production"
  },
  "dependencies": {
    "@cycle/dom": "10.1.0",
    "@cycle/xstream-run": "3.0.3",
    "xstream": "5.2.1"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "~6.0.0",
    "babel-preset-es2015": "~6.3.13",
    "brunch": "^2.4.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/,
        'app.js': /^app/
      }
    },
    stylesheets: {joinTo: 'app.css'}
  },

  plugins: {
    babel: {presets: ['es2015']}
  }
};
```

### Other useful files, when present (log, `bower.json` etc.)

I set up a repo to reproduce this specific issue so you can see for yourself: <https://github.com/nicoespeon/cyclejs-diversity-brunch>

---

Let me know if anything is missing!
Thanks 😃

**Comment by paulmillr** [comment]
cc @shvaikalesh

**Comment by savuori** [comment]
The problem seems to be the "browser" -property in snabbdom-to-html's package.json. There's a line "browser": "lib/" whose exact meaning I haven't been able to find out but if you remove that line from the package.json it seems to work.

**Comment by savuori** [comment]
According to [this spec](https://github.com/defunctzombie/package-browser-field-spec) snabbdom-to-html is using the browser-property incorrectly.

**Comment by savuori** [comment]
And [this commit](https://github.com/acstll/snabbdom-to-html/commit/c0a5a77827cc6dee478e459eb171d01e31419854) seems to have removed it. So, newer snabbdom-to-html should work as is.

**Comment by nicoespeon** [comment]
Hi @savuori and thanks for debugging =)

If I correctly understand, this is related to https://github.com/acstll/snabbdom-to-html/issues/8. 

Is there anything I could do to help − other than waiting a newer release of [@cycle/dom](https://github.com/cyclejs/cyclejs/tree/master/dom) to depend on a version of snabbdom that has the problem fixed?

**Comment by mew109** [comment]
Hi! 

I've recently found some  amazing information, you might  like  and I think it is  worth reading! Just take a look <http://release.enlightenedperspectives.com/e7fezqho>

Regards, mew1091

**Comment by mew109** [comment]
Hey! 

I wanted to tell you how much I miss  you, here are some fresh  photos  from me and my family, please take a look <http://matter.fiveminutefollies.com/e7nicv>

Cheers, mew1091

**Comment by mew109** [comment]
Yo! 
I've been looking for some  interesting info  when I found this stuff, please tell me what you think <http://chance.missioncreep.info/e7skomc>
Rushing, mew1091

**Comment by mew109** [comment]
Greetings, 

I've been  looking  for something on the web when I suddenly came across these ironic comments under your photo, have you seen them? Here is  the  link <http://into.ausarauset40th.info/e7vzfaeb>


Best wishes, mew1091

**Comment by mew109** [comment]
Hey! 

Surprise! I've got a new  hairstyle! It's so cool! Just take  a look  <http://luck.nakedfowl.com/e7guj>


Bests, mew1091
