### ISSUE TITLE
Recursive processing with sub-folders (for sub-domains)

### ISSUE THREAD

**Issue by KrishnaPG** [brunch/brunch#1452]
Is it possible to run brunch recursively, with each sub-folder having its own configuration file (and its own output folder)?

We have this scenario:

```
   Root - index.html
       |- services
       |- products
       |- blogs
```

Now, each of those are actually mapped as sub-domains and have their own site structure (styling, content so on) and the root itself has its own landing page and what not.

The problems we are facing:  
- Currently, we have `brunch-config.js` in each of those sub-folders, but we have to manually go and build each one separately. Is there a way to trigger build on the root and all sub-folder automatically gets built?
- We do not see much of support for debug vs release specification in the configuration file. Would like to specify different paths for debug mode and release mode in the configuration files - how to do that easily? Maintaining two different configuration files is not easy (even if possible)

**Comment by paulmillr** [comment]
>We do not see much of support for debug vs release specification in the configuration file. Would like to specify different paths for debug mode and release mode in the configuration files - how to do that easily? Maintaining two different configuration files is not easy (even if possible)

Brunch has the environments concept — you can totally use it. In release just specify different `joinTo` paths.

Take a glance here, section "overrides" http://brunch.io/docs/config#overrides

**Comment by paulmillr** [comment]
>Currently, we have brunch-config.js in each of those sub-folders, but we have to manually go and build each one separately. Is there a way to trigger build on the root and all sub-folder automatically gets built?

There is no way of doing that right now, maybe something worth considering.
