### ISSUE TITLE
Allow configuring server.publicPath?

### ISSUE THREAD

**Issue by mateomurphy** [brunch/brunch#1453]
Currently, brunch sets the path that is served to be the same as `paths.public`, but in my particular use case i'd like to set it to something different. Currently I'm doing so with a customer `brunch-server` file but I wouldn't need to do so if `publicPath` was added to the supported server config variables.

Is there any interest in allowing this? I can create a PR if so.

**Comment by paulmillr** [comment]
Afraid `publicPath` needs to reflect the actual path. We're cool with the current behavior.

**Comment by mateomurphy** [comment]
I understand, and perhaps by trying to change my `publicPath` I'm trying to go about solving my problem the wrong way. 

The problem I'm actually trying to solve is that assets are copied directly into the path, and I need them in a subdirectory. I am getting around that by setting my path to the subdirectory, and serving the directory above it. But having more control over where static assets are copied would be even better, perhaps there's a plugin that will help me with that. 

Thanks
