### ISSUE TITLE
Evaluate offline-first options

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#1454]
https://github.com/GoogleChrome/sw-precache

**Comment by denar90** [comment]
It will be really cool if brunch support offline first approach. I've been thinking about making this option (e.g. `offlineFirst`) always switched on. Why? Offline first became a way how app has to look tomorrow. So working offline it's going to be requirement for apps.

By default brunch using `sw-precache` will cache all files in `public` (destination) folder.
`offlineFirst` also can get all `sw-precache` params and more.
We can kinda add some our configuration options. Like: 
 - `swFileName` - name of generated service worker file.
 - `swAutoInclude` (true/false) - automatically includes SW into `index.html` page or all pages which are in `public` dir.

**Comment by denar90** [comment]
I created [sw-precache-brunch](https://github.com/denar90/sw-precache-brunch) plugin instead.
@Florian-R @shvaikalesh thank you for suggestions 👍

**Comment by denar90** [comment]
@paulmillr can we close this issue?
