### ISSUE TITLE
Make a digest plugin that uses new APIs

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#1455]
https://github.com/mutewinter/digest-brunch is pretty meh.

**Comment by nblackburn** [comment]
@paulmillr Is this something you are working on or is this open to everyone?

**Comment by paulmillr** [comment]
Not working right now. 

Just simplicity. Maybe autoreplace <digest> in html and append the digest to filename automatically.

**Comment by vifreefly** [comment]
Is there any progress on this?

I think Brunch can have `contanthash` feature out of box without any plugins. Similar to how it in Webpack https://webpack.js.org/guides/caching/ .

**Comment by paulmillr** [comment]
https://github.com/nerevu/cachebust-brunch
