### ISSUE TITLE
How to set a file to be compiled as is and others used as commonjs modules?

### ISSUE THREAD

**Issue by lunks** [brunch/brunch#1456]
Hi, I'm trying to have a setup similar to how `module.wrappers: false` would work but only for one file.

I have a file called `app.js` that I want javascript to actually run when added in a script tag i.e. if I set an `alert('Hello');` it would pop me an alert. Any files I `import/require` from there would keep their normal behavior as requirejs modules. What I want to accomplish is a single entry-point which would look something like this:

``` javascript
// app.js
import myCoolFunction from 'other_file';

myCoolFunction(); // this actually runs if I add this file to a script tag on HTML
alert('woot'); // this also runs if I add this file to a script tag on HTML
```

When I allow my files to be wrapped by brunch using commonjs modules and after I clean their names, requiring/importing them does seem to work, but this main file is never ran. What am I missing? Can I let this single entry-point file without the commonjs module?

My directory structure is simlar to:

```
app/brunch/javascripts
|_ app.js <-- file shown above
|_ other_file.js <-- file being imported
```

They get compiled to `vendor/assets/javascript/brunch/app.js`. I've tried `joinTo`/`entryPoints` in several different ways but I'm not really sure what should I set them to.

My config file:

``` javascript
// See http://brunch.io for documentation.
module.exports = {
  paths: {
    watched: ['app/brunch/'],
    public: 'vendor/assets',
  },

  files: {
    javascripts: {
      entryPoints: { 'app/brunch/javascripts/app.js': 'javascripts/brunch/app.js' }
    },
    stylesheets: { joinTo: 'stylesheets/brunch/app.css' },
  },

  modules: {
    // wrapper: false,
    nameCleaner: (path) => path.replace(/^app\/brunch\/javascripts\//, '')
  },

  plugins: {
    postcss: {
      processors: [
        /* eslint-disable global-require, import/no-extraneous-dependencies */
        require('autoprefixer'),
        require('postcss-filter-gradient'),
        /* eslint-enable global-require, import/no-extraneous-dependencies */
      ],
    },
    sass: {
      mode: 'native',
    },
  },
};
```

**Comment by goshakkk** [comment]
Require it in your HTML: `<script>require('app')</script>` or look into `config.modules.autoRequire`

**Comment by tgodfrey** [comment]
I have a similar issue. I'm using the Bing Maps Javascript Control, which uses a callback in the URL to initialize usage: 

```
<script type='text/javascript' src='http://www.bing.com/api/maps/mapcontrol?branch=release&callback=loadAddressLookup' async defer></script>
```

I define the function in `app.js` thusly: 

```javascript
function loadAddressLookup() {
    Microsoft.Maps.loadModule('Microsoft.Maps.AutoSuggest', {
        callback: onLoad,
        errorCallback: onError,
        credentials: 'Bing API Key Here'
    });
    function onLoad() {
        var options = { maxResults: 5 };
        var manager = new Microsoft.Maps.AutosuggestManager(options);
        manager.attachAutosuggest('#searchBox', '#searchBoxContainer', selectedSuggestion);
    }
    function onError(message) {
        document.getElementById('printoutPanel').innerHTML = message;
    }
    function selectedSuggestion(suggestionResult) {
        document.getElementById('printoutPanel').innerHTML =
            'Suggestion: ' + suggestionResult.formattedSuggestion +
            '<br> Lat: ' + suggestionResult.location.latitude +
            '<br> Lon: ' + suggestionResult.location.longitude;
    }
}
```

Brunch then modularizes it, and I can't seem to get the callback to fire. I get an error from the Bing library saying that the callback is invalid.

I have a workaround where I have put the code defining the callback function in a JS file under vendor. This works well, but it means that I have non-vendor code in vendor, which isn't very tidy.

Is there a better way to be doing this?

**Comment by paulmillr** [comment]
Not quite.
