### ISSUE TITLE
dynamic module loading with brunch

### ISSUE THREAD

**Issue by huochunpeng** [brunch/brunch#1457]
Right now I am using jspm for my work because we really need dynamic module loading. jspm got some rough edges, so I begin looking into webpack v2 which added systemjs for dynamic loading.

I came across brunch, very impressed about how simple it is. Understanding brunch is just a packaging tool (like webpack v1), I need to use script tag to load all compiled javascript files to make modules visible.

Is there a solution/example in brunch for dynamic module loading? If not, is this feature on the foreseeable roadmap?

Thx.

**Comment by paulmillr** [comment]
>Is there a solution/example in brunch for dynamic module loading? If not, is this feature on the foreseeable roadmap?

No. We purposefully don't want to add this feature, since it complicates the workflow a lot.
