### ISSUE TITLE
Append hash to build filenames

### ISSUE THREAD

**Issue by denar90** [brunch/brunch#1458]
I propose to add support for appending hash to build filenames like: 'app.css' -> 'app.hasCode.css'.
This feature will be automatically search references in '*.html' files (which are in `public` dir) and replace 'app.css' by 'app.hasCode.css'.
I'm not sure if it's necessary feature for brunch but I'll give it a shot. 
Gulp, Grunt has some plugins for doing this. Maybe it also can be plugin for brunch...

**Comment by acautin** [comment]
there is one already but not properly maintained for what I have seen https://www.npmjs.com/package/digest-brunch
I am having issues with the onCompile iterations which in turn is being called multiple times overriding the manifest file.
If you find a better alternative or end up with your own solution please let me know

**Comment by Florian-R** [comment]
You can track progress on this in #1455

**Comment by denar90** [comment]
Oh thanks, sorry for duplicate.

**Comment by nblackburn** [comment]
@denar90 May as well close this and subscribe to #1455
