### ISSUE TITLE
updating the redux skeleton

### ISSUE THREAD

**Issue by ferologics** [brunch/brunch#1463]
It'd be awesome if someone could update the redux skeleton on a regular basis. React especially because it's moving fast. I'd also add stage-0 babel to it, await / async is awesome.

**Comment by shvaikalesh** [comment]
async/await are on stage 3, so no need for `stage-0`. You are welcome to send a PR to appropriate repo:
https://github.com/brunch/with-redux
https://github.com/brunch/with-react

**Comment by ferologics** [comment]
oh nice. For sure, once hit any barriers in my project I'll have to PR. thanks ❤️

**Comment by shvaikalesh** [comment]
There is `peerDependencies` for this stuff, because constantly updating repos is not quite fun. But there are also compat risks implementing it.

**Comment by ferologics** [comment]
@shvaikalesh btw I'm also having issue #1443 with this skeleton

**Comment by shvaikalesh** [comment]
Will take a look at it shortly.
