### ISSUE TITLE
Resolving file extensions: Files with the same name but different extensions.

### ISSUE THREAD

**Issue by adrianmc** [brunch/brunch#1467]
### Description

I currently have CSS Modules turned on, and I'm having some issues referring to files with the same name but different extensions. Unfortunately, I am not too familiar with how modules work with Brunch.

I have an `App.js` and an `App.css`, both in a folder named `src`. In the parent folder, I have `initialize.js` which looks like this:

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import App from 'src/App';

document.addEventListener('DOMContentLoaded', () => {
  ReactDOM.render(<App />, document.getElementById('root'));
});
```

### Expected behavior

The expected behaviour is that `import App from 'src/App'` should refer to `App.js`.

### Actual behavior

The actual behaviour is that `import App from 'src/App'` refers to `App.css`. This obviously breaks the app because React will try to render it as if it's a React component, but it is not.

You can see for yourself here: https://github.com/adrianmc/cra-with-brunch/tree/master/app

The current workaround is to write the extension in explicitly:

```jsx
import App from 'src/App.js';
```

Unfortunately this is not ideal and it would be nice if it would resolve to the js file automatically.

### Environment

1. Brunch: 2.8.2
2. Node: 6.2.2
3. NPM: 3.8.7
4. Operating system: OS X 10.11

### `package.json` contents

```json
{
  "name": "your-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "react": "~15.3.0",
    "react-dom": "~15.3.0"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "~6.0.0",
    "babel-preset-es2015": "~6.9.0",
    "babel-preset-react": "~6.11.1",
    "brunch": "^2.8.2",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  }
}

```

### brunch config contents

```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/,
        'app.js': /^app/
      }
    },
    stylesheets: {joinTo: 'app.css'}
  },

  plugins: {
    babel: {presets: ['es2015', 'react']},
    css: {modules: true}
  },

  paths: {
    public: 'build'
  }
};

```

**Comment by paulmillr** [comment]
Just need a default extension order. js > css.

**Comment by adrianmc** [comment]
@paulmillr 

defaultExtension seems to be undocumented in the current docs. But I did find a v1.2 manual that mentioned it. Would you mind giving me an example of how to configure this?

**Comment by adrianmc** [comment]
Just tried defaultExtension and defaultExtensions. It seems to be deprecated.

**Comment by adrianmc** [comment]
Fixed thanks to @colinbate and his example [here](https://github.com/colinbate/inline-css-brunch):

```js
exports.config = {
  files: {
    javascripts: {
      order: {
        after: [/\.css$/]
      }
    }
  }
}
```
