### ISSUE TITLE
Question: Does brunch support npm packages with css modules?

### ISSUE THREAD

**Issue by tony-g** [brunch/brunch#1473]
### Description

Sample repo: https://github.com/tony-g/brunch-npm-cssmodules

I'm trying to use an npm module that imports its own bundled css modules. e.g.

``` css
/* their-module/css/styles.css */
.some-styles {
  color: red;
}
```

``` es6
/* their-module/js/app.js */
import '../css/styles.css';
```

I turned on css modules in the brunch config (see config below or in the sample repo).
### Expected behavior

Would be nice if brunch `require.register`'d `[npm-package]/css/styles.css` with the css modules info.
### Actual behavior
- brunch is appending `module.exports = { [cssModulesInfo ... ]}`
- but it's not wrapping it in `require.register`
- so `module` isn't defined when the statement executes, and you get js errors.

I was thinking about working around it with a plugin - the plugin has the file path so I could conditionally wrap npm packages styles in `require.register` - but I'm not super familiar with the brunch internals so I wasn't sure just how bad of an idea that was! :)
### Environment
1. Brunch: 2.8.2
2. Node: 4.4.7
3. NPM: 3.3.6
4. Operating system: OSX 10.11.6
### `package.json` contents

``` json
{
  "name": "brunch-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "react": "^15.3.0",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-notifications": "^2.1.1"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "^6.0.5",
    "babel-preset-react": "^6.11.1",
    "brunch": "^2.8.2",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "../css-brunch",
    "javascript-brunch": "^2.0.0"
  }
}
```
### brunch config contents

``` javascript
module.exports = {
  // See http://brunch.io for documentation.
  files: {
    javascripts: {joinTo: 'app.js'},
    stylesheets: {joinTo: 'app.css'},
    templates: {joinTo: 'app.js'}
  },
  plugins: {
    babel: {
      presets: ['es2015', 'es2016', 'react']
    },
    css: {
      modules: true
    }
  }
}
```

**Comment by paulmillr** [comment]
No support for now.

**Comment by kockok** [comment]
@paulmillr just wondering if `require css` in js files works as of today?

**Comment by fbukevin** [comment]
I used element-ui and got the same problem.

I use `import 'element-ui/lib/theme-default/index.css'` in my app.js and add the `stylesheets.joinTo` in brunch-config.js as following:

```javascript
stylesheets: {
            joinTo: { // vendor is for 3rb party lib, app is for custom lib
                'vendor.css': /^(?!app)/
            }
        },
```

The generated `vendor.css` correctly contains content of `element-ui/lib/theme-default/index.css`, but when browse the page it still said that `Cannot find module 'element-ui/lib/theme-default/index.css' from 'index.js'`.

[This](https://github.com/brunch/brunch/issues/1669) answer implies to set `npm styles` in brunch-config.js. I did it like these but both of them still not work:

```
    npm: {
        styles: { elementUiStyle: ['element-ui/lib/theme-default/index.css'] },
    },
```

and

```
    npm: {
        styles: { elementUiStyle: ['element-ui/lib/theme-default/index.css'] },
        globals: { elementStyle: 'element-ui' }
    },
```
(in fact, I have no idea how to use this declaration in app.js.)

**Comment by ijcd** [comment]
I was struggling with this as well. The thing that fixed it for me was realizing (mostly accidentally, but with some help from this: https://gist.github.com/taiansu/c68e7aefe8163637998acdf532d15da4), that the npm.styles paths seem to be relative to the node_modules/<package>/ directory, not to node_modules/ like the globals seem to be?:

```
  npm: {
    enabled: true,
    styles: {
      unpoly: ["dist/unpoly.css"]
    }
  },
  files: {
    stylesheets: {
      joinTo: {
        "css/app.css": /^css/,
        "css/vendor.css": /^(?!css)/
      }
    },
    ...
```

I hope it helps someone.

**Comment by MiniDude22** [comment]
@ijcd Thanks so much. That was the problem.

**Comment by vindarel** [comment]
@fbukevin could you post an example with element-ui ? Didn't figure it out… thanks !

**Comment by arguino** [comment]
to answer @vindarel and for anyone else that stumbles upon this, here's the way I made it work:
**brunc-config.jss**
```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/, // Files that are not in `app` dir.
        'app.js': /^app/
      }
    },
    templates: {
      joinTo: 'app.js'
    },
    stylesheets: {
         joinTo: {
           "css/app.css": /^css/,
           "css/vendor.css": /^(?!css)/
         }
       }
 },
 npm: { 
      enabled: true,
      styles: {
        "element_ui": ["/lib/theme-chalk/index.css"]
      }
   }
}
```

then I simply put this import in my **index.js** which references the style in the npm scope inside brunch-config.js
```
import 'element-ui'
```
