### ISSUE TITLE
elm skeleton alias doesn't work when creating a new app

### ISSUE THREAD

**Issue by sircharleswatson** [brunch/brunch#1477]
### Description

When running `brunch new -s elm` I get a warning that brunch couldn't interpret 'elm' as a hosted git url

### Expected behavior

it should be able to clone the skeleton

### Actual behavior

cloning the repo fails.

```
19 Aug 09:20:27 - warn: Couldn't interpret 'elm' as a hosted git url
19 Aug 09:20:27 - log: Cloning git repo "elm" to "/Users/Charles/.brunch/skeletons/8bcb59f2d8da5c3ab8c138e30f8c52340444ebaa"...
19 Aug 09:20:27 - error: Error: Git clone error: fatal: repository 'elm' does not exist
```

### Environment

1. Brunch: 2.8.2
2. Node: 6.0.0
3. NPM: 3.8.6
4. Operating system: OS X 10.11.6

**Comment by paulmillr** [comment]
@sircharleswatson hey — i've fixed the issue. Should be working fine now; you'll need to update your brunch.
