### ISSUE TITLE
converting gulp angular app to brunch

### ISSUE THREAD

**Issue by jmls** [brunch/brunch#1479]
so, I'm wanting to use brunch instead of the mess of gulp , wrench and bower that I have now

I am slightly (!) confused about how to convert my project to use brunch, so would appreciate some guidelines & help

most of my controllers, services, factories and "other" live in their own .js file. I also have separate js files for the config, run, and initial module loads

this is my _index.module.js_ file
```
/* global angular */
(() => {
    'use strict';
    angular
    .module('myApp', ['ui.router','ct.ui.router.extras','ngResource', 'pascalprecht.translate', 'uuid4','js-data','decipher.history'])
})();
```

and my _index.run.js_ file

```
/* global angular */
(() => {
    'use strict';

    /** @ngInject */
    function runBlock($rootScope, $translate) {
        $rootScope.$on('$translatePartialLoaderStructureChanged', () => {
            $translate.refresh();
        });
    }

    angular
        .module('myApp')
        .run(runBlock);
})();
```
etc etc

what would i need to change to make this work in brunch.io ? If a service is defined in a <service.js> file , I would currently only need to put this into _myfactory.js_

```
/* global angular */
/* global JSData */
/* global DSLocalStorageAdapter */
/* global _ */

(() => {
    'use strict';
    /** @ngInject */
    function myFactory() {
        let store = new JSData.DS();

        store.registerAdapter('localstorage', new DSLocalStorageAdapter(), { "default": true });

        return store;
    }
[snip]
    angular
        .module('myApp')
        .factory('myFactory',myFactory)

```

and then in _mycontroller.js_ have
```
/* global angular */
/* global _ */
/* global $window */

(function() {
    'use strict';
    angular
        .module(myApp')
        .controller('myController', myController);

    /** @ngInject */
    function myController(myFactory) {

```
Again, I was wanting to understand what I need to change in all of these files to make it work with brunch

many thanks - looking forward to using this good-looking tool

**Comment by paulmillr** [comment]
Hey!

Suppose you are using your own module system. In this case just put everything inside `app` directory — and disable modules by setting `config.modules = {wrapper: false, definition: false}`.

In this case the files would be concatenated into one result output — with your own module system.

**Comment by jmls** [comment]
it's not that I have my *own* module system, it's just currently wiredep and wrench figure out what is needed (and in what order) when serving for dev & production. 

I'll have a play and see what happens ;)

**Comment by jmls** [comment]
ok, so this dumb old man is struggling with concepts ;) 

In my simplified *old* build system (gulp), I had 3 files

application.js (main module entry point)
```
/* global angular */
(() => {
    'use strict';
    angular
    .module('myApp', []);
    console.log("started myApp");
    require('components')
})();
```
application.run.js (the angular run block)
```
/* global angular */
(() => {
    'use strict';
    /** @ngInject */
    function runBlock($rootScope) {
        console.log("yo");
    }
    angular
        .module('myApp')
        .run(runBlock);
})();
```
and application.controller.js (the main controller)
```
(function() {
    'use strict';
    angular
        .module('myApp')
        .controller('IndexController', IndexController);
    /** @ngInject */
    function IndexController($state,$rootScope) {
        var vm = this;
    }
})();
```

now, when I did a "gulp build" these files were all concatenated into a single app.js file, and the world was good.  Apart from bower. I hate bower, I wanted to use NPM . And brunch then came into view

so, with brunch, all these files do get concatenated into a single app.js file, but  I can't seem to get stuff working

In my index.html I have this
```
<!DOCTYPE html>

<html ng-app="myApp">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <!-- WARNING: for iOS 7, remove the width=device-width and height=device-height attributes. See https://issues.apache.org/jira/browse/CB-4323 -->
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi" />
        <title>Dead simple skeleton</title>
        <script src="/vendor.js"></script>
        <script src="/application.js"></script>
        <script>
            require('initialize');
            require('application');
        </script>
    </head>

    <body>
<p>IT WORKS....</p>
        <div ui-view flex layout="column" class="container"></div>

    </body>

</html>
```
now, this does indeed fire up the app, and start angular, and I get a "started myApp", but it *doesn't* run the application.run script - does that mean I have to require() that myself ?

If so, does that then mean I would have to require() **each file in folder structure** ? What if I have separated my app into a couple of hundred files (1 file per function , ie each controller, factory, service etc is in it's own file)

I must be missing something obvious, and would appreciate some guidance ;)

**Comment by jmls** [comment]
If I turn off modules

```
 modules: {
		definition: false,
		wrapper: false
	},
```

and disable npm

```
npm: {
        enabled: false
}
```

then things work as I expected, with the exception that I have to use bower

**Comment by rcpaul** [comment]
I was struggling with the same problem. I wanted to have all Angular related files separated and keep automatically include npm dependencies but I didn't want to use bower or maintain index.js files.

I found two solutions. The first one is to alter `conventions.vendor` in your Brunch configuration so that it matches a directory that contains all your Angular files. This stops Brunch from wrapping them so you don't need to use require().

Another is to just walk the registered modules in your main JavaScript file and automate calls to require(). Something like this:

```javascript
(function() {
  var registered = window.require.list();
  for (var i=0; i<registered.length; i++) {
    var module = registered[i];
    if (module.startsWith("js/angular-stuff")) {
      require(module);
    }
  }
})();
```

**Comment by jmls** [comment]
oh! oh! Very interested in option #1, as that means I don't have to alter my existing js code. Any new code could be put in another folder.

What changes need to be made to conventions.vendor ?

Many thanks!

**Comment by rcpaul** [comment]
It defaults to `/(^bower_components|node_modules|vendor)[\\/]/` (see [conventions](http://brunch.io/docs/config#-conventions-)). When you have angular related files in a folder named _angular-stuff_, this should be something like `/(^bower_components|node_modules|vendor|angular-stuff)[\\/]/`. As simple as that.

**Comment by jmls** [comment]
that's awesome. Thanks.
