### ISSUE TITLE
Brunch writes output file before all source files are processed; possible race condition?

### ISSUE THREAD

**Issue by wiltzius** [brunch/brunch#1480]
### Description

We recently upgraded to Brunch 2.8.2 from the 1.x branch. Almost everything worked seamlessly, but we have one intermittent but very troubling problem.

Some JS files (in this case, files containing Angular components, but I don't believe that's relevant) are being omitted from our compiled build output when building in "production" mode.

Frustratingly, the problem only happens in very specific situations. We have only been able to reproduce the issue when:

- building in production mode
- on Linux
- building with a non-empty target directory (i.e. with any previous builds in the target directory; removing the entire output directory seems to work OK... but removing the individual bad file (the app.js bundle in our case) still produces an incorrect result) 

### Expected behavior

All files would consistently be represented in the built, minified output

### Actual behavior

Some files are missing from the compiled app.js bundle. Which files seems somewhat arbitrary, but is consistent as long as we don't change the source.

I have only these small clues:

- the missing files seem to be files deeper in the filesystem hierarchy
- no files are missing when we remove our entire output directory and re-build. If we leave old built files there, the problem manifests
- the brunch build output looks strange. It varies from run to run, even with the same source files. See below for an example of a strange-looking run. The output is not always the same, it seems to print the "compiled" lines at different points a different number of times each run. But why does it print that it's done compiling multiple different times? Why is it using cached files when this is a build, not a watch?

```
$ ./node_modules/brunch/bin/brunch b --production
19 Aug 21:17:11 - info: compiling
19 Aug 21:17:16 - info: compiling.
19 Aug 21:17:17 - info: compiled 42 files into 2 files in 11.1 sec
19 Aug 21:17:25 - info: compiling
19 Aug 21:17:26 - info: compiled 203 files and 19 cached into app.js, copied 103 in 10 sec
19 Aug 21:17:34 - info: compiled 169 files and 223 cached into app.js, copied 215 in 8.1 sec
19 Aug 21:17:35 - info: compiled 13 files and 393 cached into app.js in 1.6 sec
```

I wish I could create a smaller repro, but the problem seems to only occur when we compile the entirety of our application which has ~500 source files in it; smaller ones don't seem to have any problem (or running on OS X, or building in non-production mode).

However, I have managed to trim down our brunch config and package.json to try to narrow down the culprit (see below). There are very few plugins left that seem relevant, and they're only "official" brunch plugins with default settings... which is why I believe this to be a brunch issue rather than a plugin issue, but I could be wrong about that.

**Here's a vague theory**: could there be a race condition somewhere in brunch's plugin pipeline? Basically while processing this large, deep hierarchy of source files at some point does it prematurely think it's finished and start the next phase of the pipeline (e.g. JS minification / optimization) even though it isn't actually done processing all source files yet? This might explain why some random files deep in the hierarchy are getting omitted, and also maybe why the build output prints that its done compiling app.js multiple times.

### Environment

1. Brunch: 2.8.2
2. Node: 4.5.0
3. NPM: 3.10.6
4. Operating system:  Amazon Linux (CentOS-based) `Linux ((hostname)) 4.4.15-25.57.amzn1.x86_64 #1 SMP Wed Jul 27 22:37:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

### `package.json` contents

```json
{
  "name": "<our app>",
  "version": "0.0.1",
  "description": "",
  "author": "<our company>",
  "private": true,
  "devDependencies": {
    "babel-brunch": "6.0.4",
    "bower": "1.7.9",
    "brunch": "2.8.2",
    "javascript-brunch": "2.0.0",
    "css-brunch": "2.6.1",
    "sass-brunch": "2.6.3",
    "clean-css-brunch": "2.0.0"
  }
}
```

### brunch config contents

```coffeescript
module.exports = config:
  conventions:
    assets: [
      /^client\/assets/,
      /echidna\/shared\/assets/
    ]
  paths:
    public: '_publish'
    watched: ['client', '../echidna']
  files:
    javascripts:
      joinTo:
        'scripts/bowerfiles.js': /^bower_components/
        'scripts/app.js': [/^client/, /echidna\/shared/]
        'scripts/airbrake.js': /vendor\/airbrake/
        'scripts/modernizr.js': /vendor\/modernizr/
      order:
        before: [
          # jquery needs to come before everything else to make sure that Angular will use jQuery instead of jqLite
          'bower_components/jquery/dist/jquery.js',
          # and angular needs to come before everything but jquery to make sure it's defined when misc directives load
          'bower_components/angular/angular.js',
          # moment-timezone needs to come after moment
          'bower_components/moment/moment.js',
          'bower_components/moment-timezone/builds/moment-timezone-with-data-2010-2020.js',
          'bower_components/quill/dist/quill.js',
          # and one of our specific globals needs to come before any other code
          /echidna\/shared\/js\/InjectedCtrl/
        ]
    stylesheets:
      joinTo:
        'styles/app.css': [/^client/, /echidna\/shared/]
        'styles/bowerfiles.css': /^bower_components/
  modules:
    wrapper: false
    definition: false
  npm:
    enabled: false
```

### Other useful files, when present (log, `bower.json` etc.)

I can attach our bower.json if it would help, but there is no problem with the compiled bower JS files, only our app files.

This issue did not appear prior to our brunch upgrade; we were using brunch 1.8.5 on node 0.12 with npm 2.x

Lastly, I've attached the output from a `brunch b --production -d` run. It's quite long, but it's the output from one of the "bad" builds.

[out.txt](https://github.com/brunch/brunch/files/427952/out.txt)

If there's anything at all I can do to help debug this please let me know. I've spent an entire day trying to figure this out, and at this point will likely need to downgrade us back to brunch 1.8.5 so we can continue deploying successfully. I'm a big fan of brunch and would like to be on the latest and greatest, so happy to help in any way I can. Thanks!

**Comment by wiltzius** [comment]
Note I did search for previous issues; the only one I could find that seemed similar was #1337 but it doesn't seem to have come to any resolution...

**Comment by wiltzius** [comment]
Another point I should make: an example file that's missing in the output app.js but _is_ present in the debug log would be `client/scripts/ctrl/patient_action/mch/summary_report_ctrl.js`

So it isn't like it's somehow getting skipped by the file match sometimes.

**Comment by wiltzius** [comment]
Aha, and that gives another clue! If you look at the debug output, the final "compiled" line happens right after it writes "app.js" and some other files. But then after that there are about a dozen or so additional JS files that are processed... but there's never another "compiled" print.

So somehow brunch is writing the final output before its done actually processing the input files. They are however added with brunch:list and brunch:watch, so they're being picked up somehow...

**Comment by paulmillr** [comment]
Interesting. Do you think you'd be able to provide a demo "repo" with the problem? It's hard to debug this remotely — but thinking here that this appeared sometimes before. Does using github:brunch/brunch help?

**Comment by wiltzius** [comment]
I tried using github:brunch/brunch instead of 2.8.2 and unfortunately the same effect.

The issue seems even more timing-dependent than I realized yesterday. I've now observed that even with identical source files and brunch/package.json config it sometimes happens, sometimes doesn't. It also is not exclusive to `--production` mode, that just seems to make it more likely.

I'm trying right now to replace closed-source parts of our app with something innocuous that still demonstrates the problem. It's difficult to isolate since it seems very timing-dependent; I'm not sure if it'll still produce the issue if the contents are different.

Does the debug output look strange to you, too, or is the ordering not necessarily a problem?

**Comment by paulmillr** [comment]
Looking into the output.

I will gladly debug this issue with your collaboration. Going to create a new branch in a bit — you'll need to install it locally.

**Comment by wiltzius** [comment]
Great, thank you. I'm happy to collaborate, including trying out a new
branch.

I realize it's very difficult to debug without a public repro, so I spent
some time today replacing all of our source file contents with random
console logs and it still reproduced the problem. I have some cleanup to
do, but then can post that publicly which will hopefully provide a repro
you can try. That will take me about another day or so to complete.

**Comment by wiltzius** [comment]
I have a public repro. Because it's so timing dependent it may only happen in some environments, but at least this is a start.

https://github.com/wiltzius/race-condition-brunch

Steps:
- `npm install && bower install`
- `./node_modules/brunch/bin/brunch b`
- examine output file at `_publish/scripts/app.js`
- on some runs app.js will be missing the contents of e.g. `./components/67_14/13_1/12_0/11_5.js` (and if that one is missing, usually the other JS files in the same directory are missing too).

This reproduces about 50% of the time for me currently on an m3.medium AWS instance running latest Amazon Linux (CentOS-based). I don't believe all of the brunch plugins are necessary for the repro, but it seemed to happen less of the time if I removed more of them.

At this point I'm out of ideas to try, so will wait for any advice or instructions. Thank you again for taking the time to look at it.

**Comment by paulmillr** [comment]
Thanks for setting this up — really useful!

**Comment by paulmillr** [comment]
I still always see the 11_5 thing — but three compilations (on my machine) instead of one is error-prone. WIll investigate how we could reduce this.

**Comment by paulmillr** [comment]
cc @shvaikalesh

**Comment by paulmillr** [comment]
@wiltzius what happens if you set `config.fileListInterval` to 100, 200, 300?

**Comment by paulmillr** [comment]
Nevermind — this one should fix it.

**Comment by wiltzius** [comment]
Fantastic, thank you!
