### ISSUE TITLE
Add section on renaming "app" folder in docs

### ISSUE THREAD

**Issue by jmls** [brunch/brunch#1481]
I have started to use brunch with the "brunch new" command

This builds fine with _brunch build_ - no errors

However, when I execute the _brunch watch --server_, I get the errors

```
Uncaught error: cannot find module 'process' from '/'
```

and

```
uncaught error: cannot find module 'initialize' from '/'
```

I would that thought that these errors should not be in the console

What am I missing / not set up / do not understand ;) ?

thanks
### Environment
1. Brunch: _2.8.2_
2. Node: _v4.2.0_
3. NPM: _3.3.8_
4. Operating system: _Ubuntu 16.04_
### `package.json` contents

``` json
{
  "name": "brunch-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {},
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  }
}

```
### brunch config contents

``` javascript
module.exports = {

    paths: {
        "public": './dist',
        'watched': ['src/myApp']
    },

    files: {
        javascripts: {
            joinTo: {
                'myApp.js': /^src\/myApp/,
                'vendor.js': /^(?!src\/myApp)/
            }
        },

        stylesheets: {
            joinTo: {
                'myApp.css': /^src\/myApp/,
                'vendor.css': /^(?!src\/myApp)/
            }
        },
        templates: {
            joinTo: 'myApp.js'
        }
    },
    server: {
        port: 3000,
        hostname: '0.0.0.0',
        stripSlashes: true
    }
};

```

**Comment by jmls** [comment]
And, of course, the *second* I post this something comes to mind

if I change the index.html to read *require('src/myApp/initialize')* instead of *require('initialize')* then the errors go away

Is this the right thing to do ? Is there an option to not have to specify the 'src/myApp' path ?

**Comment by jmls** [comment]
bugger. If I put some code into **initalize.js**, I get the _process_ error back again  :(

**Comment by jmls** [comment]
This has to be because I've got a "src/myApp" folder structure instead of "app". If I change to "app" then all errors go away. 

So I must be missing a setting somewhere. Can anyone tell me what it is ?

**Comment by goshakkk** [comment]
To ger rid of the process error, make sure your HTML loads vendor before app.

The default directory for app code is `app`. In case you want to change that to `src` but keep requires as `initialize` instead of `src/myApp/initialize`, change the `config.modules.nameCleaner` to replace `src/myApp/` to `''` (http://brunch.io/docs/config#-modules-)

**Comment by jmls** [comment]
perfect! - thanks

Is there a "howto" section / wiki  anywhere ? For example, if I want to change **app** to **src** I have to 

- add src as a "watch" folder in paths (that tidbit is buried in some paragraph)
- either change all "requires" to src/foo _or_ use namecleaner
- anything else ?

it would be useful for bruncher noobs to get to grips

**Comment by paulmillr** [comment]
We should create such a page on https://github.com/brunch/brunch.github.io. Good point

**Comment by brettdewoody** [comment]
Loading `vendor.js` before `app.js` resolved it for me. Even though our file structure is different from default I did not need to setup a `nameCleaner` in config.
