### ISSUE TITLE
Forcing wss

### ISSUE THREAD

**Issue by jmls** [brunch/brunch#1483]
### Description

We have a setup where nginx is proxying all traffic secured using a dynamic "let's encrypt" https connection over to a docker container

In this docker container we are running a plain **npm start** in a brunch-enabled project

### Actual behavior

This causes a problem, as the client is using a https connection, but the auto-reload code has crafted a ws:// connection as the *server* is running as http. 

### Solution

The simple "solution" is for auto-reload to always use **wss://** even when running http. This, of course, will break the normal non-https server.

I have added a flag **forcewss** to the plugins->autoReload- key - and modified **index.js** of auto-reload to use wss if this flag is set

Is this something that you would want as a PR ? ( I know it's a bit of an edge-case, but there may be other users with nginx and let's encrypt and docker)

**Comment by paulmillr** [comment]
yep
