### ISSUE TITLE
Assets subfolders are ignored?

### ISSUE THREAD

**Issue by samuelgozi** [brunch/brunch#1490]
I don't know if this is a bug or not, but in my `assets` folder i have some other subfolders, it looks kinda like this:

```
app
 |── assets
 |     └─ styles
 |          └─img
 |          └─fonts
 └─ styles
 |    └─scss //Exports to public/styles/style.css
 └─ scripts
```

The issue is that `assets/styles/*` doesn't get copied to the public folder, but i do get the css files.

**Comment by paulmillr** [comment]
they should get copied. What's your brunch ver, config, package.json?

**Comment by samuelgozi** [comment]
I'm running brunch version 2.8.2.
brunch-config.js
```
module.exports = {
	// See http://brunch.io for documentation.
	conventions: {
		ignored: [
			/^app\/vendor/
		],
	},
	files: {
		javascripts: {
			joinTo: {
				'js/init.js': /^app\/scripts\/[\w|\-]+\.js$/
			}
		},
		stylesheets: {
			joinTo: {
				'style/style.css': /^app\/style\/scss\/[\w-]+\.scss$/
			}
		}
	},
    autoRequire: {
      'js/init.js': ['initialize']
    }
}
```
packages.json
{
  "name": "brunch-with-samuel",
  "description": "Samuel's personal boilerpale based on H5BP",
  "author": "Samuel Elgozi",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/samuelgozi/brunch-with-samuel"
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "sass-brunch": "^2.6.3"
  },
  "devDependencies": {
    "brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "auto-reload-brunch": "^2.0.0"
  }
}
