### ISSUE TITLE
Jquery / Bower

### ISSUE THREAD

**Issue by jmls** [brunch/brunch#1491]
### Description

jQuery not being included in vendor.js

### Expected behavior

jQuery is included in vendor.js

### Actual behavior

angular, angular-translate, jquery etc are installed with bower. When building, jquery is not included - but the other libs are

what are the rules / requirements for bower_components to be included in the build ?

It looks to me at first glance, that it's only the libs specified in the module definition that are being included. How do I include non-angular libs from bower ?

**Comment by paulmillr** [comment]
Seems to work here. I see jQuery in browser. We'll need more info.

```
zz ❯ bower i -S jquery
bower cached        https://github.com/jquery/jquery-dist.git#3.1.0
bower validate      3.1.0 against https://github.com/jquery/jquery-dist.git#*
zz ❯ cat bower.json 
{
  "name": "brunch-app",
  "description": "Description",
  "main": "",
  "authors": [
    "Your Name"
  ],
  "license": "MIT",
  "homepage": "",
  "dependencies": {
    "jquery": "^3.1.0"
  }
}
zz ❯ bws
22 Aug 19:34:08 - info: application started on http://localhost:3333/
22 Aug 19:34:08 - info: compiled 3 files into app.js, copied 2 in 773ms
```

**Comment by jmls** [comment]
ah, bugger. jQuery *is* included .. but **after** angular - despite  having been specified in bower.json as such:

```
"dependencies": {
    "jquery": "2.0.3",
    "angular": "~1.5.0",
    "angular-resource": "~1.5.0",
    "angular-ui-router": "^0.2.18",
    "ui-router-extras": "^0.1.2",
    "angular-translate": "^2.10.0",
    "angular-translate-loader-url": "^2.10.0",
    "angular-translate-loader-partial": "^2.10.0",
    "angular-uuid4": "^0.3.1",
    "js-data": "^2.9.0",
    "js-data-localstorage": "^2.3.2",
    "js-data-angular": "^3.2.1",
    "angular-history": "^0.8.1",
    "change-case": "3.0.1-2",
    "angular-uuids": "^0.0.4",
    "lodash": "3.10.1",
    "chance": "^1.0.3",
    "pluralize": "^3.0.0"
  },
  "resolutions": {
    "jquery": "2.0.3",
    "angular": "~1.5.0",
    "lodash": "3.10.1"
  }
```

Shouldn't the inclusion of libs be in the order specified in bower.json ?

**Comment by paulmillr** [comment]
Use `config.files.javascripts.order.before` to specify the order.

**Comment by jmls** [comment]
thanks. I did that, and jQuery is being included first - but I am still getting my original error 

```
angular.js:4659 Uncaught TypeError: $q.spawn is not a function
﻿```

so it must be a problem with jquery & angular now. 

thanks again

**Comment by jmls** [comment]
oh, forget it ! my stupid stupid fault. it's not jquery ($) it's $q .. my eyesight is failing. sorry
