### ISSUE TITLE
Optimizers: Add support for binary file handling

### ISSUE THREAD

**Issue by squaresurf** [brunch/brunch#1492]
Original Title: "Question: Are there any plans to support image compression?"

It's just the one question :smile:

**Comment by shvaikalesh** [comment]
Hey @squaresurf, thanks for the question. Image compression/resize/crop can be done with a plugin, like [this one](https://github.com/steffenmllr/imageoptmizer-brunch). Hope this helps.

**Comment by squaresurf** [comment]
Thank you! @shvaikalesh! I wonder why that plugin isn't on this page: http://brunch.io/plugins

**Comment by shvaikalesh** [comment]
Plugins list is updated manually: we happily accept PRs from plugin authors to list their modules.
https://github.com/brunch/brunch.github.io/pull/186

**Comment by squaresurf** [comment]
We may also want to update this page: http://brunch.io/docs/why-brunch#brunch-vs-webpack

> What Brunch can't do that Webpack can:
> 
> asynchronous module loading / code splitting — brunch does have entry points functionality and can produce several js bundles though
> have clever processing of non-js/non-css assets

That is what led me to believe that brunch couldn't process images.

**Comment by squaresurf** [comment]
@shvaikalesh should I open a new issue regarding these updates or reopen this issue?

**Comment by shvaikalesh** [comment]
Thanks for pointing that out, @squaresurf. I believe the new issue is the way to go.

Please, let me explain the reasoning behind:

> have **clever** processing of non-js/non-css assets

Brunch reads files with `utf-8` encoding, and always passes strings (not `Buffer` instances) to `compile` methods of plugins, so it would be a bit inefficient to process non-text formats this way.
`imageoptmizer-brunch` is not quite like regular plugins: it has to take care of reading and writing files to `public` directory manually.

In the future, we may support binary files in Brunch.

**Comment by shvaikalesh** [comment]
Strings were chosen for simplicity, changing them to Buffers may lead to backwards-compatibility issues.

**Comment by shvaikalesh** [comment]
Related: https://github.com/brunch/brunch/issues/840

**Comment by squaresurf** [comment]
What should we do with this issue now that it is a duplicate of #840?

Also, should the docs really be updated or should they wait will brunch supports binary files?

Regarding creating a new issue for:

> Please, let me explain the reasoning behind:
> 
> > have clever processing of non-js/non-css assets
> 
> Brunch reads files with utf-8 encoding, and always passes strings (not Buffer instances) to compile 
> methods of plugins, so it would be a bit inefficient to process non-text files this way.
> imageoptmizer-brunch is not quite like regular plugins: it has to take care of reading and writing files to public directory manually.
> 
>

**Comment by paulmillr** [comment]
We'll wait until someone would spare their time to work on it. That's mostly it.

**Comment by squaresurf** [comment]
Perfect. Thank you both!
