### ISSUE TITLE
minification issue using template strings

### ISSUE THREAD

**Issue by jmls** [brunch/brunch#1494]
### Description

brunch build --production fails with minification error

### Expected behavior

the build process should complete with no errors

### Actual behavior

when performing a `brunch build --production` the compile fails with a
`error: JS minification failed on dist/vendor.js: Unexpected character "`"` 

However, running `brunch build` or `npm start` and the compile completes successfully

### Environment

1. Brunch: *2.8.2*
2. Node: *4.2.0*
3. NPM: *3.3.8*
4. Operating system: Ubuntu

### `package.json` contents

```json
  "devDependencies": {
    "babel-brunch": "^6.0.6",
    "brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  },

```

the file it is failing on is this:

```js
window.brunch = {
    "auto-reload": {
        host: `wss-${window.location.hostname.replace('preview-','')}`,
        port: "443"
    }
};

```

As you can see, I am using template strings to replace the hostname for the live reload socket (because I have to :) )

So, normal compile works, but this fails on minification

**Comment by tkesgar** [comment]
Normal compile works because `uglify-js-brunch` by default doesn't work on `--production` (unless you configure it in config). As far as I know, UglifyJS currently does not support ES6, so perhaps it tries to compress the script and fails.

Maybe you did not put the script in files that will be compiled by `babel`?

**Comment by jmls** [comment]
that's probably it - how do I specify that the script needs to be zapped by babel before being uglified ?

**Comment by tkesgar** [comment]
Might be good to check the [documentation][http://brunch.io/docs/config], but usually all files in `app` folder will be compiled, i.e. zapped by babel.

**Comment by jmls** [comment]
ah, that would explain it - that particular script is outside app. thanks

**Comment by jmls** [comment]
ok, so now I added it to the app folder, which was a mistake ;) The brunch "runtime" is inserted into vendor.js, which is included before my app.js, so this script is now included after the websocket service is started.

Does babel have a config to specify which folders / files to transpile ? It's not exactly clear in the docs

**Comment by paulmillr** [comment]
plugins.babel.ignore

babel bergen brunch
