### ISSUE TITLE
plugins, caching and compiling

### ISSUE THREAD

**Issue by jmls** [brunch/brunch#1495]
I have been using the angular-template plugin, and reviewing the code produced. From what I can see, the code produced is a result of the way that brunch is passing files.

For example, I have 2 templates: form1 and form2. This plugin produces the following:

```js
(function() {
    var module;

    try {
        // Get current templates module
        module = angular.module('myModule');
    } catch (error) {
        // Or create a new one
        module = angular.module('myModule', []);
    }

    module.run(["$templateCache", function($templateCache) {
        $templateCache.put('myApp/components/form1.html', '<html here>');
    }]);
})();

(function() {
    var module;

    try {
        // Get current templates module
        module = angular.module('myModule');
    } catch (error) {
        // Or create a new one
        module = angular.module('myModule', []);
    }

    module.run(["$templateCache", function($templateCache) {
        $templateCache.put('myApp/components/form2.html', '<html here>');
    }]);
})();
```

When you have a larger set of html, this can get very unwieldy. I would very much prefer to see & use

```js
(function() {
    var module;

    try {
        // Get current templates module
        module = angular.module('myModule');
    } catch (error) {
        // Or create a new one
        module = angular.module('myModule', []);
    }

    module.run(["$templateCache", function($templateCache) {
        $templateCache.put('myApp/components/form1.html', '<html here>');
        $templateCache.put('myApp/components/form2.html', '<html here>');
    }]);
})();
```
ie have a single run statement for all of the templates. However, this got me thinking about the way that brunch works.

If I were to modify form1, the current plugin would (presumably) return the script **for that modified form only**, so how does brunch work out what to inject into the scripts, and how does caching work ? 

Would it be possible to write a plugin that would produce the optimised output shown above ?

Just curious, as from what I can read about plugins, the _compile_ function is only passed the modified file(s)

**Comment by paulmillr** [comment]
It is possible to write the plugin — but you would probably need to do some heavy lifting like parsing the js AST.

Basically it's complex and hard.
