### ISSUE TITLE
process types of file in order

### ISSUE THREAD

**Issue by jmls** [brunch/brunch#1496]
Is it possible to process certain types of files before others ? 

In my scenario, I am using the angular-templates plugin, but want to join it to my main app.js file - but I want all of the $templatecache functions to be at the end, grouped together

At the moment, it seems that all of the files in a folder are read, and each file sent to the compile function of the appropriate plugin. Is there a way of configuring the system to send all .js files first, then all .html etc ?

**Comment by paulmillr** [comment]
You can specify this in config:

```
files: {javascripts: {
  order: {before: [/\.html$/], after: [/\.js$/]}
}}
```
