### ISSUE TITLE
Documentation: anymatch 

### ISSUE THREAD

**Issue by mryarbles** [brunch/brunch#1500]
### Description

The document  for anymatch is basically useless. The Brunch docs point to their documentation repeatedly, but offer no real explanation about how the configuration objects relate to anymatch. Super duper frunstrating.

Brunch might have better uptake if they didn't link to anymatch repo for explanation.

**Comment by denysdovhan** [comment]
Hi, thanks for reaching out! I'll be glad to help you.

Would you like to see a new section in docs? Or would it be better to write better docs for anymatch itself?

**Comment by shvaikalesh** [comment]
Hello there, @mryarbles. Thanks for the tip.

Fixed by https://github.com/brunch/brunch.github.io/pull/210.
