### ISSUE TITLE
Brunch build blocks for a few seconds after compilation

### ISSUE THREAD

**Issue by solarsailer** [brunch/brunch#1502]
### Description

When I use the `brunch build` command (with Brunch 2.8), my shell is locked for a few seconds, even if the compilation is already done.

The problem only arises with Brunch 2.8. I tried with Brunch 2.7, and there's no problem.

I create an empty folder, `brunch new` inside it, then run `brunch b`. That's all.

### Expected behavior

`brunch build` should complete as soon as the compilation is over.

### Actual behavior

Here is a small video illustrating the problem, and showing the difference between Brunch 2.7 (b27) and Brunch 2.8 (b28): http://d.pr/v/sMMs

### Environment

1. Brunch: 2.8.2
2. Node: 4.4.4 or 4.2.6
3. NPM: 3.10.6 or 3.5.2
4. Operating system: macOS 10.11.6 or Linux 16.04.1 x64

### `package.json` contents

The dead-simple skeleton.

### brunch config contents

The dead-simple skeleton.

### Other useful files, when present (log, `bower.json` etc.)

There's nothing more than the dead-simple skeleton files.

**Comment by paulmillr** [comment]
Try brunch from github. Does it help?

**Comment by solarsailer** [comment]
No problem with the latest commit from master. 👍

**Comment by paulmillr** [comment]
Great.
