### ISSUE TITLE
Should process/browser.js be included in build due to require('jquery')?

### ISSUE THREAD

**Issue by crisperdue** [brunch/brunch#1503]
### Description

Coincidence caused me to notice that the Node.js process/browser module is included
in my brunch build.  I have isolated it to use of jquery, though I see no request for "process"
anywhere.  Running "brunch b" puts a copy in public/app.js and also inserts the following right around the end of the file: 

require.alias("process/browser.js", "process");process = require('process');

Is inclusion of "process" correct behavior by brunch, or at least to be expected?  This does not seem right to me, but I am new to brunch, so it makes me wonder if I am doing something wrong.

Here is information about my test case:

### Environment

1. Brunch: 2.8.2
2. Node: 6.5.0
3. NPM: 3.10.3
4. Operating system: Debian/jessie

### package.json contents

```json
{
  "name": "brunch-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "jquery": "^3.1.0"
  },
  "devDependencies": {
    "brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "auto-reload-brunch": "^2.0.0"
  }
}
```

### brunch-config.js contents

```javascript
exports.files = {
  javascripts: {joinTo: 'app.js'},
  stylesheets: {joinTo: 'app.css'},
  templates: {joinTo: 'app.js'}
};
```

### app/initialize.js contents

```javascript
// Test inclusion of jquery in the project:
var jq = require('jquery');

document.addEventListener('DOMContentLoaded', function() {
  // do your setup here
});
```

**Comment by paulmillr** [comment]
Could you try using Brunch from GitHub? Is it any different?

**Comment by crisperdue** [comment]
OK, I have used the instructions in CONTRIBUTING.md to:

1. Clone brunch from github.
2. cd to the local brunch clone.
3. sudo npm link
4. In my test project directory, npm link brunch
5. Remove files in test-project/public
6. brunch build

The result is effectively the same. process/browser.js is concatenated before jquery.js, but the
same calls to require.alias and require() appear as before, right at the end of the generated
app.js.

**Comment by paulmillr** [comment]
I think what happens here is `require('process')` or `process` variable are mentioned in the jquery code — which causes brunch to add it to the build. Should not be a big deal though.

**Comment by crisperdue** [comment]
I do see a few references to a variable named "process" in jquery. In any case, it's not really a problem for me if it seems basically OK to you.  Thanks for looking into it.

**Comment by LMS007** [comment]
I have this same issue but its causing an js error in the console which is not ideal. I'm also using an older version of jquery than the one mentioned here.

**Comment by pnmcosta** [comment]
@LMS007 adding `/node_modules\/process\/browser.js/` to **ignored** in **conventions** seems to have worked for me:

```
  conventions:
    # we don't want javascripts in asset folders to be copied like the one in
    # the bootstrap assets folder
    assets: /assets\/(?!javascripts)/
    ignored: [
      /\/_/,
      /vendor\/(node|j?ruby-.+|bundle)\//,
      /node_modules\/process\/browser.js/
    ]
```

this is my setup on Win 10

```
  "dependencies": {
    "bootstrap-datepicker": "^1.6.4",
    "bootstrap-sass": "latest",
    "font-awesome": "^4.7.0",
    "fotorama": "^4.6.4",
    "fullcalendar": "^3.2.0",
    "jquery": "^3",
    "jquery-deparam": "^0.5.1",
    "jquery-socialshare": "latest"
  },
  "devDependencies": {
    "auto-reload-brunch": "~2.7.1",
    "brunch-static": "~1.2.1",
    "copycat-brunch": "~1.1.0",
    "grunt": "~1.0.1",
    "html-brunch-static": "~1.3.2",
    "pleeease-brunch": "~3.0.0",
    "sass-brunch": "~2.10.4",
    "uglify-js-brunch": "~2.10.0",
    "brunch": "~2.10.10"
  }
```

**Comment by LMS007** [comment]
@pnmcosta 

Thanks! I'll give it a try :)

**Comment by pnmcosta** [comment]
Umm, strangely when building on Win, the require('process') is not added to the globals, only the alias.

Whereas on Linux, it does add it and caused the error.

So rather than ignore it, I just include process/browser.js with the concatenated jquery file.

this prevents the console error in the browser as it's included in the first js file I request on my app.

**Comment by devinrhode2** [comment]
It appears that certain TabFern configs build fine on windows, but on macOS (High Sierra), the built output has some different code..
At the end, after `;require.alias("path-browserify", "path")`, we get a newline plus: `;require.alias("process/browser.js", "process");process = require('process')` inserted
(before `;require.register("___globals___", function(exports, require, module) {`)

In the beginning, we get `var process;` added..
```js
 (function() {
 var global = typeof window === 'undefined' ? this : window;
+var process;
 var __makeRelativeRequire = function(require, mappings, pref) {
 ```

**Comment by aleybovich** [comment]
@devinrhode2 I have the same issue on Linux - have you figured out a fix?
