### ISSUE TITLE
Angular2: No Metadata found for AppModule

### ISSUE THREAD

**Issue by AGoodnight** [brunch/brunch#1504]
### Description

Angular 2 component metadata seems to be lost during compile.

### Expected behavior

Metadata should be compiled before exporting the module, however decorators might be getting lost.

### Actual behavior

after compile, console in browser thows error: 
`compiler.umd.js:13850 Uncaught Error: No NgModule metadata found for 'AppModule'.(…)`

I have encountered in the past, where the Angular2 Brunch build throws an error in the browser console that seems to hint that it did not properly incorporate 'import 'es6-reflect-metadata shim' when using Angular2 RC.6.

### Environment

1. Brunch
2. Angular2 RC.6
3. Various packages, see below

### `package.json` contents
```
{
  "name": "ng2-brunch",
  "description": "Brunch with Angular 2",
  "author": "Colin Bate <colin@colinbate.com>",
  "version": "0.6.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/colinbate/ng2-brunch"
  },
  "scripts": {
    "start": "brunch watch --server",
    "postinstall": "typings install",
    "build": "brunch build",
    "build:prod": "brunch build --production",
    "test": "tsc --noEmit && tslint app/**/*.ts app/*.ts"
  },
  "license": "MIT",
  "keywords": [
    "brunch",
    "skeleton",
    "angular",
    "ng2",
    "angular2",
    "typescript",
    "starter",
    "template",
    "generator"
  ],
  "dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/compiler-cli": "0.6.0",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.6",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.11",
    "zone.js": "^0.6.17",
    "angular2-in-memory-web-api": "0.0.18",
    "bootstrap": "^3.3.6",
    "copyfilemon-brunch": "3.3.0",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.35.0",
    "purecss": "0.6.0",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "auto-reload-brunch": "2.7.1",
    "brunch": "2.6.0 - 2.8.0 || >2.8.1",
    "brunch-typescript": "1.8.1",
    "sass-brunch": "2.6.3",
    "clean-css-brunch": "^2.0.0",
    "codelyzer": "0.0.23",
    "environment-brunch": "^1.0.0",
    "inline-css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "tslint": "^3.11.0",
    "typescript": "^1.8.10",
    "typings": "^1.1.0",
    "uglify-js-brunch": "^2.0.1"
  }
}
```

### brunch config contents

```
exports.config = {
  // See http://brunch.io/#documentation for docs.
  files: { 
    javascripts: {
      joinTo: {
        'vendor.js': /^(node_modules|bower_components)/, // <-- import javascript libraries
        'main.js': /^app/
      },
      order: {
        after: [/\.html$/, /\.css$/]
      }
    },
    stylesheets: {
      joinTo: 'app.css' // <-- dictate exported resource
    },
    templates: {
      joinTo: 'main.js' // <-- dictate exported resource
    }
  },
  plugins: {
    sass:{
      options:{
        includePaths:[
          './app/scss'/*,
          './node_modules/angular-material'*/ // <-- compile and inject custom styles, [ we are importing bootstrap-sass through here ]
        ]
      }
    },
    copyfilemon:{
      '.':['./node_modules/purecss/build/pure.css']
    },
    inlineCss: { // <-- allows Angular 2 to use your stylesheets
      html: true,
      passthrough: [ 'app/global.css'] // <-- Don't add these
    }
  }
};
```

### Other useful files, when present (log, `bower.json` etc.)
Problem Occurs when one tries to transform this:

`document.addEventListener('DOMContentLoaded', function main() {
  bootstrap(AppComponent, [
    HTTP_PROVIDERS,
    APP_ROUTER_PROVIDERS,
    disableDeprecatedForms(),
    provideForms(),
    provide(LocationStrategy, { useClass: PathLocationStrategy }),
    provide(GameService, {useClass:GameService })
  ])
  .catch(err => console.error(err));
});`

into this:

```
@NgModule({
	imports:[
		platformBrowserDynamic,
		HTTP_PROVIDERS,
		LocationStrategy,
		disableDeprecatedForms,
	],
	declarations:[
		AppComponent,
		HighlightDirective,
		ROUTER_DIRECTIVES, 
		NavBarComponent
	],
	providers:[
		GameService
	],
	bootstrap:[
		AppComponent
	]
});
```

**Comment by sqlsolver** [comment]
@AGoodnight I resolved this error by removing now deprecated items, such as HTTP_PROVIDERS and 'provide' in various components. I do see HTTP_PROVIDERS in your description above. See [Change Log](https://github.com/angular/angular/blob/master/CHANGELOG.md)

**Comment by AGoodnight** [comment]
I implemented the changes suggested by @sqlsolver. I also discovered the there were quite a few of breaking changes between the bet rc4 and the official release. I also discovered Angular throws an error if you try to set an exported component class to default.

`export default class NavBarComponent`

So I tracked down that bug too. 
Brunch works great with Angular 2 so far!

Thanks!

**Comment by SmartFactory** [comment]
@AGoodnight I found that `export default class AdministrationModule` will throw error if you point it directly for example in:
 `loadChildren: 'app/pages/administration/administration.module#AdministrationModule'`. But in this case will work without the `default`.

And viceversa; 
If you use `default` it will work if you don't put it explicitly in the loadChildren:
 `loadChildren: 'app/pages/administration/administration.module'`.

I supose that if you DON'T tell is the Default class, you must specify it, buti f it's the default one, you should not specify as it will allways use the Default class.

By the way I saw a coment by @zigzag95 where he said:
> Don't do default class on not lazy loaded module

Hope that could help
