### ISSUE TITLE
Why just app.js is executed ? 

### ISSUE THREAD

**Issue by overallduka** [brunch/brunch#1505]
Hi everyone, this is not an issue, probrably, but i am searching for many and many days for this solution maybe just here i can have some answer.

I have an app and everyone know just app.js is executed, all other files are wrapped into modules. 
Ok, my doubt is, i want to an app2.js and use this in other part of my application, what i cant found is an way to this app2.js be executed without being wrapped into module.
This script will be called not for my HTML views but for any user of my application.
So this: 
```
<script href="www.mysite.com/app2.js"></script> 

```
should work.
To be clear, i not want to give up of `import` functions, i just want some code in app2.js execute and not be wrapped, actually all files are wrapped into modules and none code is executed. What im trying to say is:

"This file i not want turn module, is arbitrary js but i want use modules and be compiled as es6"

In fact `app.js` in my application do exactly this, but i need this app2.js that do the same.

**Comment by webdif** [comment]
Do you create a `app2.js` file? With a conf like:

```
exports.config =
	/* ... */
	files:
		javascripts:
			joinTo:
				'app2.js': /* ... */
```

Then, you can configure that this file will automatically require a file. Your code will still be turned into module, but it will be required right away, as "regular js".

```
exports.config =
	/* ... */
	modules:
		autoRequire:
			'app2.js': ['init.js']
```

**Comment by overallduka** [comment]
Works perfectly =D. Thanks a lot, this is super important to me.
