### ISSUE TITLE
Build command is slow to exit

### ISSUE THREAD

**Issue by doryphores** [brunch/brunch#1506]
### Description

When I run the `build` command on a skeleton project, compilation is fast and takes ~600ms (as stated by output) but the command then waits ~15s before exiting.

### Expected behavior

I expect the command  to exit immediately after compilation ends.

### Actual behavior

Here's what I get when timing the build command:

```
➜  testing.brunch /usr/bin/time -p brunch build
12 Sep 16:24:37 - info: compiled initialize.js into app.js, copied 2 in 534ms
real        15.61
user         0.62
sys          0.07
```

As you can see, it hangs for 15 seconds after compiling and then exits.

### Environment

1. Brunch: 2.8.2 (also tried with latest from master)
2. Node: 6.5.0
3. NPM: 3.10.3
4. Operating system: OSX 10.11.6

### `package.json` contents

Created with a simple `brunch new` command:

```json
{
  "name": "brunch-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {},
  "devDependencies": {
    "brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "auto-reload-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```javascript
exports.files = {
  javascripts: {joinTo: 'app.js'},
  stylesheets: {joinTo: 'app.css'},
  templates: {joinTo: 'app.js'}
};
```

**Comment by troygilbert** [comment]
I think you're seeing this: https://github.com/brunch/brunch/issues/273

**Comment by doryphores** [comment]
I think I messed up when I tried the latest from master. I installed brunch globally from github master branch but not locally. When I installed latest master locally, then the `build` command stopped hanging. I'm closing this.
