### ISSUE TITLE
Investigate modularizing brunch even further

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#1507]
Concat, module wrapping, etc could all be on-by-default plugins

**Comment by goshakkk** [comment]
To make it possible, we'll have to thoroughly think of and add several new API methods.

Somewhat of a concern would be inter-plugin dependencies and interaction, as deppack directly needs our default module wrapping, and the module wrapper hooks into deppack.

A plugin architecture therefore needs to be flexible enough to allow this, and not break anything.
