### ISSUE TITLE
Compiling from several files

### ISSUE THREAD

**Issue by Ximik** [brunch/brunch#1511]
I'm creating a simple plugin to build webfont from SVGs. For now it just like

``` javascript
class WebfontBrunch {
  constructor(config) {
    ...
  }

  onCompile() {
    ...
    webfontsGenerator(config, function(error) {
      if (error) {
        throw ('webfont-brunch ' + error);
      }
    });
  }
}

WebfontBrunch.prototype.brunchPlugin = true;

module.exports = WebfontBrunch; 
```

So the issue is webfont is being recompiled every time something changes. And it can be really slow sometimes.

Possible solution here is some more logic changes for plugins. I have several ideas
1. Add some option like `bunchCompile` so compile with receive all files which match `pattern` on one of them was changed.
2. Add a new `type` like `bunch` with custom `concat` logic. 

P.S. Seems like it's not my specific issue. Same problem is with this plugin
https://github.com/mllrsohn/sprite-brunch

**Comment by paulmillr** [comment]
Will discuss this in plugin-specific feature issues.
