### ISSUE TITLE
Cannot override: "Don't categorize node_modules as 'assets' even if they match the regexp"

### ISSUE THREAD

**Issue by charleshan** [brunch/brunch#1514]
The following doesn't seems to be working.

```
conventions: {
  ignored: () => false, // override defaults for no ignored files
}
```

Related to #1289

**Comment by denispeplin** [comment]
I'll use copycat-brunch
But there are other options: http://cloudless.studio/articles/21-front-end-packages-with-phoenix-and-brunch
