### ISSUE TITLE
Precss processing issues

### ISSUE THREAD

**Issue by yinonov** [brunch/brunch#1515]
Hi!
This is the first time I'm using brunch and i'm having some issue which - I guess - should be simple to solve but i couldn't find much documentation on this specific topic.

the following code is part of my project's brunch-config.js

```
postcss: {
     processors: [
        require('autoprefixer'),
        require('precss'),
        require('postcss-cssnext'),
        require('cssnano')
    ]
}
```

the issue i'm having is in the precss processor.
my app/styles folder contain the application.css file and a 'partials' folder which contains other css files of which i try to import from application.css to form into 1 file

```
@import "partials/variables";
@import "partials/normalize";
@import "partials/base";
@import "partials/components";
@import "partials/modules";
@import "partials/mixins";
```

thing is - upon transpiling it keeps showing this error: _ENOENT: no such file or directory, open '...\public\css_variables.css'_

why is it looking in the public folder (which is the final build folder) and not the pre transpiled relative app/styles location?

when manipulating the url to forcely look in the right folder like this >  `@import "../../app/styles/partials/variables";` it imports but its looks ugly
1. Brunch: ^2.4.0
2. Node: 4.5.0
3. NPM: 2.15.9
4. Operating system: windows 10

`package.json` devDependencies contents

```
 "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "~6.0.0",
    "babel-preset-es2015": "~6.9.0",
    "babel-preset-react": "~6.11.1",
    "brunch": "^2.4.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "autoprefixer": "^6.0",
    "postcss-brunch": "^0.5",
    "postcss-cssnext": "^2.8.0",
    "precss": "^1.4.0",
    "cssnano": "^3.7.4",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  }
```

**Comment by denysdovhan** [comment]
Thanks for reporting! Let's see how can I help you.

Do you aware of this [postcss-import](https://github.com/postcss/postcss-import)'s restriction?:

> This plugin should probably be used as the first plugin of your list. This way, other plugins will work on the AST as if there were only a single file to process, and will probably work as you can expect.

Also, are your partials _-prefixed? If so, you might need to use [postcss-easy-import](https://github.com/trysound/postcss-easy-import).

Can you create a repo that reproduce this behavior? That would help me a lot.
