### ISSUE TITLE
Lib built with Browserify and NPM integration

### ISSUE THREAD

**Issue by Florian-R** [brunch/brunch#1517]
### Description

Brunch try to resolve relative `require` calls inside an already bundled lib.
### Expected behavior

Skip relative require in libs already browserified. TBH I don't know if it's possible, but I've seen some libs already bundled like this in the wild.
### Actual behavior

Steps to reproduce : 
-  Init a new brunch project with chaplin skeleton (with brunch and bower globally installed)

``` bash
brunch new -s chaplin 
```
- Bump Brunch to latest (FWIW, this is also present on master)

``` bash
npm i --save --save-dev brunch@2.8.2
```
-  Check that all is fine

``` bash
npm start
#everything is ok
```
- Bump Chaplin to latest

``` bash
npm i --save chaplin@1.2.0
```
- Relaunch Brunch

``` bash
npm start
```
- Output

``` bash
05 Oct 15:37:51 - info: application started on http://localhost:3333/
05 Oct 15:37:51 - error: DEPS_RESOLVE_FAILED of node_modules/chaplin/chaplin.js failed. Could not load module '../mediator' from '/home/florian/Bureau/repro/node_modules/chaplin'. Make sure the file actually exists. 
05 Oct 15:37:51 - info: compiled 28 files into 3 files, copied index.html in 1.2 sec

```

I've tried to debug this a bit, and it seems that deppack try to resolve this [require in Chaplin](https://github.com/chaplinjs/downloads/blob/1.2.0/chaplin.js#L329), which obviously fail.
I'd happily send a PR, just need to know where to start in the first time.
### Environment
1. Brunch: 2.8.2
2. Node: 6.7.0
3. NPM: 3.10.8
4. Operating system: Ubuntu 16.04.1 LTS

**Comment by noonien** [comment]
Have you managed to solve this issue?

**Comment by Florian-R** [comment]
Nope, for now I do some hacky stuff to circumvent it (I pull Chaplin from Github and compile myself the source in a postinstall script).

Didn't had much time to dig the source neither.

**Comment by designermonkey** [comment]
We're seeing the following and I wonder if it's the same thing:

> Uncaught Error: Cannot find module 'inherits' from 'stream-browserify/index.js'

This happens only on ubuntu (works fine on Mac OSX). I have tried tracking it down and it seems that for some reason the brunch require and function that create a relative require, just won't resolve the dependency, even though it is all in the packaged vendor.js file.

Is this the same thing?
