### ISSUE TITLE
brunch asset target retaining folder structure

### ISSUE THREAD

**Issue by fatcop** [brunch/brunch#1519]
Greetings, apologies if this is out of order, but I have posted this question tagged with #brunch on stackoverflow and just not getting any response for approaching a week now. So thought maybe here is better.

I am trying to convert an existing JS project currently using Grunt for building project over to Brunch.

I'm initially trying to make brunch work using existing directory structure.

```
app
- images
- less
- scripts

```

I want to copy the images into public directly (ie. as assets). I know I could move them to app/assets/images but I prefer not to change the structure yet.

brunch-config.js:

```
module.exports = {
  conventions: {
    assets: [ '^(?:app)/(images/**/*)' ],
    // assets: [ /(?:^app\/images[\\/])/ ],
    // assets: [ '(images/**/*)' ],
    //assets: /images[\\/]/,
  }
}
```

I want the image files to get copied to public/images. ie. keep the "images" directory name

But the best I can seem to manage (using that uncommented assets value) is copying to public/app/images.

The other attempts just copy the contents of app/images to public. ie. so i get app/image.jpg instead of app/images/image.jpg

I was hoping the using the non-captureing grouping of the "app" part in the regex would maybe make it work, but didn't.

Any ideas ? Thanks

Ref: https://stackoverflow.com/questions/39790942/brunch-asset-target-retaining-folder-structure

**Comment by tkesgar** [comment]
How about using [`onCompile`](http://brunch.io/docs/config) hook to manually copy the images after each compilation? You can also use [`copy`](https://www.npmjs.com/package/copy) to make it easier.

The problem with this is the `images` folder is not watched, so the compilation won't kick in if the content of `images` is changed. However, if you don't need that (for example, if the folder is not changed often), I think it is the simplest way.

**Comment by fatcop** [comment]
Thanks a lot.

I guess I could do that. I think since app/images is still in the default watch path any change to that nested images folder should trigger that hook I guess. Seemed to in quick test I just did.

But yeah I guess it would mean copying all images (and other static assets) that were inside app folder every time.

Guess I really just have to restructure my files so assets are in a separate non-nested folder to get full benefits.

Cheers

**Comment by shvaikalesh** [comment]
In Brunch `2.10`, plugins can change path of assets. Please, check out https://github.com/brunch/brunch/blob/master/lib/fs_utils/asset.js#L77
