### ISSUE TITLE
Process undefined in Vue-2.0

### ISSUE THREAD

**Issue by shiningshisa** [brunch/brunch#1520]
### Brunch seems to compile my Vue/vuex/vue-router 2.x project correctly but will always give an error saying "uncaught ReferenceError: process undefined...". It appears to relate to a Vue environment

variable  (process.env.VUE_ENV) but I don't see a way to set this environment variable in my brunch config. 

works fine with 1.x series of Vue suite so I may have come here prematurely as I know 2.0 has just been released

link to original post in Vue Forum. They seem to think it's more to do with Brunch than Vue

[http://forum.vuejs.org/t/process-undefined-in-console-blank-page-vue-2-vuex-2-vrouter2/914?u=shiningshisa](url)

Apologies if the format of this issue is difficult to reason about. Please let me know I'll do my best to make things as clear as possible

**Comment by Florian-R** [comment]
Are you on WIndows? This seems to be the same bug than brunch/deppack#44

**Comment by nblackburn** [comment]
@shiningshisa As @Florian-R said, this is related to #44 which i am waiting for a response on.

**Comment by shiningshisa** [comment]
Thanks all, I was unable to find a solution even with [this npm module for environments](https://github.com/JohnnyCrazy/node-browser-modules/tree/windowsFix). Alas, will have to wait until the deppack issue is reloved

**Comment by JohnnyCrazy** [comment]
@shiningshisa Did you install the `#windowsFix`-branch in your project directory? I tested it with 2 projects, worked fine. But I'm gonna try it with a fresh project tomorrow.

**Comment by shiningshisa** [comment]
@JohnnyCrazy Unless I installed incorrectly (npm install --save <your module>) using the aforementioned module didn't work for me. I'll try again on a fresh project and update the thread on what happens

**Comment by JohnnyCrazy** [comment]
@shiningshisa 
Just tested this with a fresh install, works after some modifications:

```
brunch new brunch_test -s es6
cd brunch_test
npm install vue vue-brunch johnnycrazy/node-browser-modules#windowsFix --save

//This should be your brunch-config.js
//https://gist.github.com/0bb7a9fb94cd84f38277a610114e87dd

// root.vue inside /app/
// https://gist.github.com/734100d74200ff84cfa62292b920ae4b

//You may need to move <scripts> to the bottom inside index.html
```

**Comment by nblackburn** [comment]
@paulmillr Would you be able to take a look at this as it prevents me from pushing Vue 2.0 support to vue-brunch?.

**Comment by shiningshisa** [comment]
Will upload my working config later tonight. It does work with the #windowsFix module after all just had to change a few other things in the structure of my project

**Comment by matteocontrini** [comment]
Anything new?

**Comment by nblackburn** [comment]
@matteocontrini Sadly not no, i am not sure on the best way of fixing this.
