### ISSUE TITLE
Source map generated in production mode doesn't include the sources content

### ISSUE THREAD

**Issue by waj** [brunch/brunch#1523]
### Description

When building in production mode, the generated source map (enabled in the config with an override) doesn't include the source code contents.
### Expected behavior

The source map should include the sources just like when building in non-production mode.
### Actual behavior

I uploaded this sample app to reproduce the issue: https://github.com/waj/brunch-test-sourcemaps
It's just an empty project created with `brunch new` and with a config override to enable source maps in production.

When I execute the build with `npm run build` it generates the source map with the `sourcesContent` empty:

``` json
{
"version":3,
"sources":["app/initialize.js"],
"names":["require","register","exports","module","document","addEventListener"],
"mappings":"01CAAAA,SAAAC,SAAA,gBAAA,SAAAC,EAAAF,EAAAG,GAAAC,SAAAC,iBAAA,mBAAA",
"file":"public/app.js.map",
"sourcesContent":[null]
}
```

I found the issue #856 has a similar problem, but this time the `source-map` package is the latest version.
### Environment
1. Brunch: 2.8.2
2. Node: v6.7.0
3. NPM: 3.10.7
4. Operating system: OS X 10.11.6

**Comment by waj** [comment]
Nothing? Not even a hint to find the problem? :(

**Comment by paulmillr** [comment]
Fixed.
