### ISSUE TITLE
Add Brunch info to the webpack site

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#1524]
https://github.com/webpack/webpack.js.org/pull/236

**Comment by denysdovhan** [comment]
Is this issue still actual? webpack/webpack.js.org#236 is merged.

**Comment by shvaikalesh** [comment]
>  I'd love to get this merged in and if @paulmillr and gang want to help contribute to their column then that would be awesome but I don't think it should block this from landing.

**Comment by denysdovhan** [comment]
Got it. It is.
