### ISSUE TITLE
Bug when building with only one third-party vendor

### ISSUE THREAD

**Issue by phzbox** [brunch/brunch#1525]
### Description

vendor.js keeps jquery from previous build.
### Actual behavior

npm install --save jquery
require('jquery') in initialize.js
brunch compile

public/vendor.js contains jquery

remove the require('jquery') line in initialize.js
brunch compile

public/vendor.js still contains jquery

Note, I think this only happens when there's only one plugin, probably because vendor.js isn't being written but isn't deleted?

**Comment by paulmillr** [comment]
you sure you don't have jquery anywhere in your app? what's your brunch config?

**Comment by phzbox** [comment]
brunch-config:
```
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/,
        'app.js': /^app/
      }
    },
    stylesheets: {joinTo: 'app.css'}
  },

  plugins: {
    babel: {presets: ['es2015']}
  }
};```

Initialize.js:
```
document.addEventListener('DOMContentLoaded', () => {
  console.log('Initialized app');
});
```

This includes jquery in vendor because previously I had require('jquery') in initialize.js.

Note that if I had require('React') and require('jquery') then there's no bug since it seems vendor gets rewritten.

Or here's another way to show it (with the previous initialize):

```
$ brunch build
  17 Oct 07:33:57 - info: compiled 2 files into 2 files, copied index.html in 948ms
$ wc -l public/vendor.js
    4344 public/vendor.js
$ rm public/vendor.js
$ brunch build
$ wc -l public/vendor.js
wc: public/vendor.js: open: No such file or directory
```

Basically it's just that public/vendor.js doesn't get deleted. If there's no vendor, it just copy index.html and app.js. If I add a third-party, then it will copy also vendor.js and override the one that I had before.

Maybe it could remove all files in public/ before building?

**Comment by paulmillr** [comment]
#977
