### ISSUE TITLE
Show terminal errors in the browser

### ISSUE THREAD

**Issue by phzbox** [brunch/brunch#1528]
### Description

Is there a way to show the terminal such as:

```
17 Oct 07:55:01 - error: Compiling of app/meh.jsx failed. SyntaxError: app/meh.jsx: Unexpected token, expected , (14:0)
```

in the browser instead of in the terminal? I.e. in an overlay or something.

If not, I'd like to write a plugin for it but I'm not sure where to "catch" those errors?

Thanks

**Comment by paulmillr** [comment]
No.

**Comment by Florian-R** [comment]
@paulmillr Would you be ok to add some plugin API for that? I've tried some stuff with create-react-app lately, and the behaviour described by @phzbox is really convenient.

**Comment by paulmillr** [comment]
Sure thing.

Is this a basic built-in feature in CRA?

**Comment by Florian-R** [comment]
> Is this a basic built-in feature in CRA? 

Yap, this is basically what you've got during a build error

![error](https://cloud.githubusercontent.com/assets/1374176/19558277/da1e2238-96c9-11e6-9615-3eb02a445e4a.png)

I don't think Brunch should do the heavy lifting, just allow to overrides in some way it's logger, the rest is up to a plugin.

**Comment by fatcop** [comment]
is there any progress or ways to accomplish this in brunch ?

**Comment by shvaikalesh** [comment]
Hey @fatcop. We have not yet started to implement this. It requires exposing new methods to plugins. API design is the thing I would like not to rush. Please 👍 on original post so I can prioritize this.
