### ISSUE TITLE
can't install brunch on windows?

### ISSUE THREAD

**Issue by heinhoang** [brunch/brunch#1531]
### Description
$ brunch new proj -s es6
'brunch' is not recognized as an internal or external command,
operable program or batch file.

### Environment
1. Brunch: ???
2. Node: v5.9.0
3. NPM: 3.7.3
4. Operating system: win8

**Comment by kgcreative** [comment]
Brunch needs to be installed before you can run it. `NPM install -g brunch`

**Comment by heinhoang** [comment]
I installed by that command
1. npm install -g brunch
2. brunch new proj -s es6
 but it's not working.

**Comment by goshakkk** [comment]
Could be that global NPM binaries are not on your `PATH`
