### ISSUE TITLE
Documentation: Video is outdated and using old `new` syntax

### ISSUE THREAD

**Issue by davidmaxwaterman** [brunch/brunch#1534]
### Description
Just trying brunch...want to start an angular2 project, so trying it with ng2-brunch skeleton.

I'm trying :

```
brunch new https://github.com/colinbate/ng2-brunch
```

### Expected behavior
IINM, it should install the skeleton...I'm just working through the 'A Quick Demo' video on brunch.io.

### Actual behavior
I get an error after `Installing packages...` :

```
/home/maxw/.nvm/versions/node/v6.9.1/lib/node_modules/brunch/node_modules/init-skeleton/index.js:51
  process.chdir(rootPath);

Error: ENOENT: no such file or directory, uv_chdir
     at Error (native)
etc
```

### Environment

1. Brunch: *(make sure you're on the latest release!)*
I just installed it...2.8.2
2. Node:
I just updated from 6.6.0 to 6.9.1
3. NPM: *(npm v2 is not supported)*
3.10.8
4. Operating system:
ubuntu 16.04
### `package.json` contents
n/a

### brunch config contents
n/a

### Other useful files, when present (log, `bower.json` etc.)
no files output - cwd is empty

**Comment by davidmaxwaterman** [comment]
Aha, the problem is that I'm following the directions in the video on the brunch home page, and it looks like they're out of date.

Can I suggest the video is removed/replaced, and/or the brunch script made to catch this issue to warn the user?

**Comment by paulmillr** [comment]
yes — good point

**Comment by paulmillr** [comment]
Actually already doing this.
