### ISSUE TITLE
Brunch 2.9.0 optimizing assets in development

### ISSUE THREAD

**Issue by razor-x** [brunch/brunch#1537]
### Description

Brunch is minifying assets in non-production mode.

### Expected behavior

```
$ git clone https://github.com/brunch/with-es6.git
$ cd with-es6
$ echo "body {\n background: green;\n}" > app/main.css
$ npm install
$ npm start
```

JS and CSS assets in `public` should not be optimized (minified).

### Actual behavior

`public/app.css` and `public/app.js` are minified.

### Environment

1. Brunch: 2.9.0
2. Node: 6.8.1
3. NPM: 3.10.8
4. Operating system: Linux

**Comment by shvaikalesh** [comment]
Hey @razor-x, thanks for the report. Fixed in `2.9.1`. Very sorry I've missed that.
