### ISSUE TITLE
Q: Make Brunch compile dependencies without source files

### ISSUE THREAD

**Issue by joallard** [brunch/brunch#1542]
### Description

More of a question, I posted on SO: [Make Brunch compile dependencies without source files](http://stackoverflow.com/q/40226586/720164). I'm not getting `brunch build` to compile my dependencies. (Feel free to close here and go answer there)
### Expected behavior

Dependencies are built into output file.
### Actual behavior

Built file is empty.
### Environment
1. Brunch: 2.9.1
2. Node: 6.7.0
3. NPM: 3.10.7
4. Operating system: OS X 10.11
### `package.json` contents

``` json
```
### brunch config contents

``` javascript
// See http://brunch.io for documentation.
module.exports = {
  paths: {
    watched: ['app/brunch'],
    public: 'vendor/assets'
  },

  modules: {
    wrapper: false,
    autoRequire: {
      'javascripts/brunch/app.js': [
        'lodash'
      ]
    }
  },

  files: {
    javascripts: {joinTo: 'javascripts/brunch/app.js'},
    stylesheets: {joinTo: 'stylesheets/brunch/app.css'}
  },

  plugins: {
    on: ['javascript-brunch']
  }
}

```
### Other useful files, when present (log, `bower.json` etc.)

If there's an unexpected error during `brunch build`/`brunch watch`, please attach the compilation log with the debug flag (`-d`) **and** stack traces enabled (`export LOGGY_STACKS=true`).

If something worked with previous versions of brunch, but stopped with a newer one, please include these details as well.

**Comment by denysdovhan** [comment]
Hey, @joallard, could you please pack this up in single repo with steps to reproduce? I'm gonna find out what's going wrong here. Will be glad to help you.
