### ISSUE TITLE
Incremental build/watch/reload for npm link-ed modules.

### ISSUE THREAD

**Issue by 32bitkid** [brunch/brunch#1548]
Is there any way to get brunch to watch/reload symlinked modules?

Adding it directly to `brunch-config` under, doesn't seem to work right:

```
paths: { watched: ['app', 'test', 'vendor', 'node_modules/symlinked-module'] }
```

It causes it to want to compile that module directly.

For reference, I'm starting to use brunch to build a large-ish application, and really would like to module-ify a collection of re-useable components. However, they are both in development at the same time. For other more node-centric projects, I've enjoyed using `npm link` to symlink multiple development projects across the same environment. I'd love to do this with brunch, but I can't seem to be able to get those modules to reload correctly when they change.

**Comment by paulmillr** [comment]
why are you adding the module to paths.watched? `require('module')` doesn't work? This way it'll be reloaded.

**Comment by 32bitkid** [comment]
Sorry, I didn't explain it very well. My bad, so here is a better/complete explanation of what I'm seeing:

I've got two projects

1) is a electron application that is built using another toolset.
2) is a browser application that is built using brunch

There is enough different between them that it doesn't really make sense to bundle them into the same module/repo. The both import a collection React components which are modules themselves. They basically look like this:

```js
import React from 'react';
export default class CommonWidget extends React.Component {
  render() { /* do stuff */ }
}
```

However, I'm developing all of these at same time. However, in the brunch project I have `npm link` the `common-widget` module. And just using `brunch b` works great. However, when using `brunch w`, if I change `CommonWidget` the watcher doesn't recompile, and even if I change another file that is watched by brunch and it recompiles. It seems to use the previously compiled version of the file. The only way to get it to recompile/detect changes to the `npm link`-ed repository is to stop watching and start again.

Putting the module in watch was a _cargo-cult_ attempt at getting to detect changes _within_ `node_modules`.

I get why modules within `node_modules` normally are not part of the watcher, but it seems like symlinked modules could be an exception to that. I am wondering if this is expected or unexpected behavior, or if there is a way around it when using `brunch watch`.

Thanks, and sorry again.

**Comment by champeng** [comment]
+1
