### ISSUE TITLE
Issue with babel-plugins which are not following the babel-plugin-*plugin-name* naming convention

### ISSUE THREAD

**Issue by dropfen** [brunch/brunch#1549]
### Description

The _babel-root-import_ plugin doesn't work with brunch. 
### Expected behavior

_bable-root-import_ allows to use a a prefix to resolve modules from your project structure.

instead of 

`import Foo from '../../components/Foo.jsx'`

you can use

`import Foo from '@/components/Foo'`

However, to do this, the plugin must be included.
### Actual behavior

The problem is, that when I define the plugin in the babel configuration as

`"babel-root-import": {}`

brunch is looking for 

`"babel-plugin-babel-root-import"`

which doesn't exists.

Actually this is very useful, and could be added to brunch itself. Where you can define the root src path in your project structure.

**Comment by denysdovhan** [comment]
Hi, @dropfen!

Thanks for reporting! Let's see how can I help you.

**Comment by denysdovhan** [comment]
Well, first of all, [babel-root-import](https://github.com/michaelzoidl/babel-root-import) have inconsistent name. That's not in common plugin's name convention. I'm going to open an corresponding issue in its repo.

**Comment by denysdovhan** [comment]
Hey, @dropfen! Seems like I've fixed this issue by https://github.com/babel/babel-brunch/issues/45.

Can you, please, check with my changes and verify that everything is OK?

**Comment by shvaikalesh** [comment]
Fixed in `babel-brunch/master`.

**Comment by dropfen** [comment]
@denysdovhan & @shvaikalesh Thanks guys, I've checked the changes should be fine, but I could't check it because I updated React at the same time and this problem happened https://github.com/brunch/brunch/issues/1591
