### ISSUE TITLE
Directory with the same name as an npm module causes trouble

### ISSUE THREAD

**Issue by lydell** [brunch/brunch#1551]
### Description

If you name a (toplevel?) directory the same as an npm module, compilation fails – in a bad way.

### Expected behavior

Either a good error message, or successful compilation. I’m not sure if you are allowed to name a directory the same as an npm module or not, but it is an easy error to make.

### Actual behavior

```
$ brunch b
(node:30221) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): BrunchError: Failed to read file app/react.
Error: EISDIR: illegal operation on a directory, read
02 Nov 10:00:05 - info: compiling
02 Nov 10:00:09 - info: compiling.
02 Nov 10:00:13 - info: compiling..
02 Nov 10:00:17 - info: compiling...
02 Nov 10:00:21 - info: compiling
02 Nov 10:00:25 - info: compiling.
02 Nov 10:00:29 - info: compiling..
02 Nov 10:00:33 - info: still compiling...
02 Nov 10:00:37 - info: compiling
02 Nov 10:00:41 - info: compiling.
02 Nov 10:00:45 - info: compiling..
02 Nov 10:00:49 - info: compiling...
02 Nov 10:00:53 - info: compiling
02 Nov 10:00:57 - info: compiling.
02 Nov 10:01:01 - info: compiling..
02 Nov 10:01:05 - info: compiling...
02 Nov 10:01:09 - info: compiling
^C⏎
```

In other words, a bad error message is shown and then brunch gets stuck "compiling" forever.

**Test repo:** https://github.com/lydell/brunch-module-name-bug

### Environment

1. Brunch: 2.9.1
2. Node: 6.9.1
3. NPM: 3.10.8
4. Operating system: Ubuntu 16.04

### `package.json` contents

```json
{
  "private": true,
  "devDependencies": {
    "brunch": "^2.9.1",
    "javascript-brunch": "^2.0.0"
  },
  "dependencies": {
    "react": "^15.3.2"
  }
}
```

### brunch config contents

```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: 'app.js'
    }
  }
}
```

### Other useful files

app/main.js:

```js
var component = require('./react/SomeComponent')

console.log('component', component)
```

app/react/SomeComponent.js:

```js
var React = require('react')

module.exports = function SomeComponent(props) {
  return React.createElement("span", null)
}
````

### Background

I recently added React to a single page of an existing project. I figured I’d put all React components in a directory called "react". Then I ran into this problem. I ended up simply renaming that directory to "react-components" to avoid the problem. This was not a good experience.

**Comment by cdman** [comment]
This seems to also happen for me, although for a different reason (as far as I can tell) - I don't have any directories named the same as my dependencies.

## Environment

- Brunch: 2.9.1
- Node: 4.2.6
- NPM: 3.5.2
- Operating system: Ubuntu 16.10

I'm not really a frontend / JS person (this is happening on our build server and locally, on our machines, everything works as expected), so any pointers as to how to debug this would be greatly appreciated.

**Comment by Fohlen** [comment]
This also happens for us with the following setup

- Node: 6.9.1
- Brunch: 2.8.2
- NPM: 3.10.8
- Mac OS Sierra, 10.12.1

**Comment by denysdovhan** [comment]
Hi, @lydell, @Fohlen and @cdman! Thanks for reaching out!

Your issue is related to problems with [`deppack` module](https://github.com/brunch/deppack).
Here are other issues: [`deppack` related issues](https://github.com/brunch/brunch/issues?q=is%3Aissue+is%3Aopen+label%3Adeppack).

We're working on it. I believe we will fix that as soon as it possible.

**Comment by Fohlen** [comment]
@denysdovhan upgrading to `brunch 2.10.0` resolved the issue for me.

**Comment by denysdovhan** [comment]
👍🏻

**Comment by lydell** [comment]
Happens in 2.10.8 as well: https://github.com/lydell/brunch-module-name-bug

**Comment by denysdovhan** [comment]
Okay, gonna take a look at this asap.

**Comment by Betree** [comment]
Any news on this subject ?
