### ISSUE TITLE
Ubuntu vs Ubuntu building differently

### ISSUE THREAD

**Issue by designermonkey** [brunch/brunch#1552]
We are experiencing disparate builds on two separate ubuntu 16.04.1 machines. Our local vagrant is using a `bento/ubuntu-16.04` box, and our remote is using a default Linode Ubuntu 16.04 LTS distribution.

We have verified the kernel versions are also the same (in case it was related).

Everything is updated using apt, and all the same packages are installed. We have even gone through and verified version numbers for node packages:

- nodejs: 4.2.6
- npm: 3.5.2
- brunch: 2.9.1

The main issue is that the `vendor.js` file is built completely differently, and the aliases at the end of the file are always very different. On the server the file is always missing aliases.

We have even copied the node_modules directory from the vagrant machine to the server, and it still builds the file wrong.

Instead of attaching stuff here, it is all in this gist: https://gist.github.com/designermonkey/4a72e7842f62093dde6a08ae9375f12e

**Comment by c0b** [comment]
can't reproduce?
