### ISSUE TITLE
Slim (Slm) templates pre-processing

### ISSUE THREAD

**Issue by sintro** [brunch/brunch#1554]
Is it possible to connect https://github.com/slm-lang/slm template engine with Brunch, or it is necessary to make special brunch-plugin line jade-brunch?

**Comment by carere** [comment]
Hello sintro :)

All you need to do is create a brunch plugin (eg. slim-brunch). The documentation is really good and quite obvious :) [http://brunch.io/docs/plugins](url)

 And you can also look the implementation from other plugins ([https://github.com/brunch/eslint-brunch](url)) which is incredibily obvious too. Pretty much 2 functions to implement :)

Best regards.

**Comment by shvaikalesh** [comment]
Please, send us a PR to https://github.com/brunch/brunch.github.io, I am really excited to see Slim templates support in Brunch without Ruby stuff.

**Comment by sintro** [comment]
Ok, I did some really alpha-version of this plugin, look here:
https://github.com/sintro/slm-brunch
Please, feel free to make PR to help me to implement TODO stuff. 
Also look at some problems, noted in README

**Comment by denar90** [comment]
Can we close this when https://github.com/sintro/slm-brunch/pull/1 will be merged?

**Comment by sintro** [comment]
Sure

**Comment by shvaikalesh** [comment]
Hey @sintro, I will close this one not since it is not issue with Brunch.
