### ISSUE TITLE
Changes in ignored folders are detected but not compiled

### ISSUE THREAD

**Issue by alinnert** [brunch/brunch#1556]
### Description

My project structure looks like this:

- `app/main.css`: contains `@imports`
- `app/_stylesheets/**/*.css`: are files being imported by `main.css`

So basically same situation as with SCSS in #1389. But I'm using postcss and `postcss-easy-import` (with globs) for imports.

Now when I run `brunch watch` and change a file (e. g. `app/_stylesheets/anything.css`) brunch detects that a file has been changed but the log outputs something like this:

~~~
12 Nov 20:00:03 - info: compiled in 66 ms
~~~

And the output file `app.css` doesn't change.

The first build of `brunch watch` and using `watch build` work as expected and output this on the console:

~~~
12 Nov 19:59:55 - info: compiled main.css into app.css in 145 ms
~~~

### Expected behavior

`main.css` should be compiled again after changing files in the `_stylesheets` folder.

### Actual behavior

Brunch detects that a file has been changed and starts compiling in theory but it doesn't seem to compile anything for real.

My idea is that brunch doesn't know that `main.css` and `_stylesheets/**/*.css` belong together. Is there anything I can do about that?

### Environment

1. Brunch: 2.9.1
2. Node: 6.8.1
3. NPM: 3.10.8
4. Operating system: Windows 10

### `package.json` contents

```json
{
  "dependencies": {
    "axios": "^0.15.2",
    "babel-brunch": "^6.0.6",
    "postcss-brunch": "^2.0.5",
    "postcss-cssnext": "^2.8.0",
    "postcss-easy-import": "^1.0.1"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```javascript
module.exports = {
    paths: {
        public: 'dist/public'
    },
    files: {
        javascripts: {joinTo: 'app.js'},
        stylesheets: {joinTo: 'app.css'},
        templates: {joinTo: 'app.js'}
    },
    plugins: {
        postcss: {
            processors: [
                require('postcss-easy-import')({glob: true}),
                require('postcss-cssnext')()
            ]
        }
    }
};
```

**Comment by shvaikalesh** [comment]
Hey, @alinnert. Thanks for bringing this up.

https://github.com/es128/progeny/pull/30 should fix that as soon as it will be merged and released.

Also, we recommend (changed docs like yesterday) including Brunch plugins like

```
    "babel-brunch": "^6.0.6",
    "postcss-brunch": "^2.0.5",
    "postcss-cssnext": "^2.8.0",
    "postcss-easy-import": "^1.0.1"
```

as `devDependencies` (which they are :) )

Hope this helps!

**Comment by shvaikalesh** [comment]
`"progeny": "~0.11.1"` was released, please try it out and reopen if it won't help.

**Comment by clarknelson** [comment]
did you find a solution?
