### ISSUE TITLE
npm modules, bootstrap and css

### ISSUE THREAD

**Issue by jmls** [brunch/brunch#1558]
### Trying to use npm modules to install bootstrap

I am getting errors when using bootstrap stylesheets from npm

### Environment

1. Brunch: 2.9.1
2. Node: 7.0.0
3. NPM: 3.10.8
4. Operating system: ubuntu

### `package.json` contents

```json
  "devDependencies": {
    "angularjs-templates-brunch": "^1.0.0",
    "assetsmanager-brunch": "^1.8.1",
    "auto-reload-brunch": "https://github.com/brunch/auto-reload-brunch.git",
    "babel-brunch": "^6.0.6",
    "babel-plugin-transform-async-to-generator": "^6.8.0",
    "brunch": "^2.0.0",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.6.1",
    "eslint": "^2.13.1",
    "eslint-config-loopback": "^4.0.0",
    "inject-this-brunch": "^4.0.0",
    "javascript-brunch": "^2.0.0",
    "mocha": "^3.1.2",
    "nsp": "^2.1.0",
    "postcss-brunch": "^2.0.5",
    "sass-brunch": "^2.6.3",
    "uglify-js-brunch": "^2.0.0"
  },
```
my `npm` section in brunch-config.js is

```json
 npm: {
            enabled: true,

            globals: {
                $: 'jquery'
            },

            styles: {
                bootstrap: ['dist/css/bootstrap.css']
            }
        },
```

if I exclude the bootstrap key above, bootstrap.css does not get included in vendor.css
when I run  `npm start`, I get loads of errors similar to this

```
13 Nov 16:57:38 - error: Source map generation failed for node_modules/bootstrap/dist/css/less/carousel.less:  ENOENT: no such file or directory, open '/home/ubuntu/workspace/node_modules/bootstrap/dist/css/less/carousel.less'
```

which is very odd, as there is no `less` directory in `node_modules/bootstrap/dist/css`

![image](https://cloud.githubusercontent.com/assets/929523/20247396/18c8c20c-a9c3-11e6-837c-3602a9d41251.png)

However, despite the errors, the bootstrap.css is included in the vendor.css file

What am I missing / misconfigured ?

**Comment by stelmakh** [comment]
@jmls Removing postcss-brunch seems to fix the issue. Not an option if you are using any postcss plugins though. Will investigate it further.

**Comment by jmls** [comment]
thanks - I've been fighting with this, and I've found that if you remove the `xxx.map` files (in dist/css, for example) then the compile completes without errors.

Hopefully that will give you some clues ;)

**Comment by stelmakh** [comment]
Well, that's a good catch, thanks)

**Comment by stelmakh** [comment]
@jmls try adding this to your brunch-config. This option tells postcss to ignore previously generated source maps. Fixed the issue for me.
`  
plugins: {
  postcss: {
    map: {prev: false}
  }
}
`

**Comment by jmls** [comment]
worked for me too. thanks a brunch ;)
