### ISSUE TITLE
npm overrides

### ISSUE THREAD

**Issue by jmls** [brunch/brunch#1559]
### Is there a way of overriding the "main" key of a npm package during compilation

I am trying to npm install `jquery-ui-dist` to use in npm modules. However. it seems as if the distribution of jquery-ui-dist has an incorrect main file

```
warn: main file for module 'jquery-ui-dist' does not exist (node_modules/jquery-ui-dist/ui/widget.js), assuming index.js
```

The correct file is actually `jquery-ui.js`

I tried adding the following to the `npm` section

```json
overrides": {
          "jquery-ui-dist": {
            "main": "jquery-ui.js"
          }
        },
```

but it didn't work - neither did putting `overrides` in the main section

Is there a way of overriding npm information in brunch-config.js ?

**Comment by lydell** [comment]
I guess you could use `require('jquery-ui-dist/whatever/file-you-want')` instead of `require('jquery-ui')` in your code (as a workaround?).

**Comment by jmls** [comment]
Yes, indeed I can - discovered that by accident ! It works perfectly, thanks.

**Comment by jmls** [comment]
sorry, hit the wrong button

**Comment by oskarkook** [comment]
I think this issue should be re-opened. By overriding `main` in 2.9.1, the module will be bundled in, but you can't just do `import "module"` - which I feel like is the expected behaviour - but have to do `import "module/main"`. I spent a good hour on figuring out what is the exact problem here.
