### ISSUE TITLE
Destructuring assignment problem

### ISSUE THREAD

**Issue by sintro** [brunch/brunch#1560]
There is strange problem with your example from Brunch/Config page:
```
// Add namespacing to a project.
const {name} = require('./package.json');
modules: {nameCleaner: path => path.replace(/^app/, name) }
```
This `const {name} = require('./package.json');` string is doing **Destructuring assignment **, which is part of ES6, and this is almost the same as  `const name = require('./package.json').name;`
The problem is if I usу `const {name} = require('./package.json');` I get `error: Initialization error - Cannot read property '1' of null Cannot read property '1' of null` - the const name is not assigned (the second option with .name works fine). It is even more strange, because `nameCleaner: path => path.replace(/^app/, name)` works fine also, and this is the proof that ES6 transiles fine to general JS. What can be the reason of this bug?

**Comment by shvaikalesh** [comment]
Hey @sintro, what is your Node.js version? Destructuring works without flag only on v6+.

**Comment by sintro** [comment]
Insta hit the target! 
For some reason had v. 4, updated to last 6.9 and now everything is fine!
