### ISSUE TITLE
Double error logging when going from valid to invalid

### ISSUE THREAD

**Issue by lydell** [brunch/brunch#1561]
### Description

After `brunch watch` has compiled everything once without errors, when you introduce an error in a file, that error is logged _twice_ (and I get double notifications). Not a showstopper, but a bit annoying :)

### Expected behavior

The error should only be logged (and notified) _once._

### Actual behavior

The error is logged (and notified) _twice._

### Environment

1. Brunch: 2.9.1
2. Node: 6.9.1
3. NPM: 3.10.8
4. Operating system: Ubuntu 16.04

### `package.json` contents

```json
{
  "private": true,
  "devDependencies": {
    "brunch": "^2.9.1",
    "javascript-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: 'app.js'
    }
  }
}
```

### Other useful files, when present (log, `bower.json` etc.)

app/app.js:

```js
console.log('Hello, world')
```

```
$ brunch watch &
14 Nov 09:12:42 - info: compiled app.js into app.js in 319 ms

$ sed --in-place 's/)//' app/app.js 
14 Nov 09:12:45 - error: Compiling of app/app.js failed. Line 3: Unexpected end of input 
14 Nov 09:12:45 - error: Compiling of app/app.js failed. Line 3: Unexpected end of input 
```

**Comment by sfexample** [comment]
The same behavior.

### Environment

1. Brunch: 2.9.1
2. Node: 6.9.1
3. NPM: 3.10.8
4. Operating system: Xubuntu 16.04.1
5. Sublime 3 editor

### package.json

```
{
  "name": "simple-brunch",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "auto-reload-brunch": "^2.7.1",
    "brunch": "^2.9.1",
    "coffee-script-brunch": "^2.1.0",
    "pugjs-brunch": "^2.8.5",
    "sass-brunch": "^2.7.0"
  }
}
```

### brunch-config.coffee
```
module.exports = 
	files:
  	javascripts: 
  		joinTo: 'app.js'
  	stylesheets: 
  		joinTo: 'app.css'
```

### Intentionally broken file application.coffee
```
8App = init: ->
  console.log 'App initialized.'
  return
module.exports = App
```

### Output
```
$ brunch w -s -d
14 Nov 14:09:14 - info: application started on http://localhost:3333/
14 Nov 14:09:14 - info: compiled 4 files into 2 files in 923 ms
rejecting for 0:1 [stdin]:1:2: error: unexpected identifier
8App = init: ->
 ^^^
14 Nov 14:09:29 - error: Compiling of app/application.coffee failed.  
14 Nov 14:09:29 - error: Compiling of app/application.coffee failed.
```
