### ISSUE TITLE
Error is still appears even if the .jade file without syntax issues

### ISSUE THREAD

**Issue by sfexample** [brunch/brunch#1562]
### Description

After fixing the syntax issue, that occurred in .jade file, the `brunch watch --server` doesn't recompile the updated file correctly. 
The previous syntax error appears even if file without issues. Any other updates doesn't change this state.
I need to stop the `brunch watch --server` and run once again for appropriate result.

### Expected behavior

The fixes in the .jade files must updated and compiled automatically.

### Actual behavior

The compilation error appears even if .jade file without issues.
For reproducing please run the `brunch watch --server` and apply the syntax issue in the .jade file.
You will see the compilation error. Next, undo the changes in the .jade file. The same error is still appears.
Also please see attachment for more info:
![20161114_155205](https://cloud.githubusercontent.com/assets/1274660/20267346/f220451a-aa82-11e6-86bb-2768ae434217.gif)

### Environment

1. Brunch: 2.9.1
2. Node: 6.9.1
3. NPM: 3.10.8
4. Operating system: Xubuntu 16.04.1
5. Sublime 3 editor

### `package.json`

```
{
  "name": "simple-brunch",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "auto-reload-brunch": "^2.7.1",
    "brunch": "^2.9.1",
    "coffee-script-brunch": "^2.1.0",
    "pugjs-brunch": "^2.8.5",
    "sass-brunch": "^2.7.0"
  }
}
```

### `brunch-config.coffee`
```
module.exports = 
	files:
  	javascripts: 
  		joinTo: 'app.js'
  	stylesheets: 
  		joinTo: 'app.css'
```

### Output
```
$ export LOGGY_STACKS=true && brunch w -s -d
14 Nov 15:22:15 - info: application started on http://localhost:3333/
14 Nov 15:22:15 - info: compiled 4 files into 2 files in 909 ms
14 Nov 15:22:30 - error: Compiling of app/assets/index.jade failed. assets/index.jade:12:4
    10| 			|A simple application
    11| 	p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo sed officia voluptatem dolor consequuntur! Ducimus veritatis est tempore distinctio modi in id numquam! Hic?
  > 12| 	ul*error
-----------^
    13| 		li
    14| 			a(href="#") Link 11
    15| 		li

unexpected text "*erro" 

```

**Comment by paulmillr** [comment]
Thanks for the video, it's useful. Will try to reproduce the issue locally

**Comment by shvaikalesh** [comment]
Hello there, @sfexample. I was able to reproduce the issue. Will fix ASAP.

Thanks for reaching out.

**Comment by shvaikalesh** [comment]
The problem persists in `2.8.2`, `2.9.1` and `master`. Ouch.

**Comment by sfexample** [comment]
Hello, @shvaikalesh
Thank you for your response.
Please let me know if any additional information is needed from my side.
