### ISSUE TITLE
Proposal: Add a postprocessor step

### ISSUE THREAD

**Issue by kuon** [brunch/brunch#1565]
### Description

At present, there is the compile step, which compile for example `a.ts` to `a.js` and there is the optimizer step.

It is desirable to add a step after the compile step to add postprocessing, but before files are concatenated and bundled.

This would solve the issue plugin like `postcss` has.

What do you think?

#### References

- Optimize is not a good option for post processors, because it is run on the concatenated file: <https://github.com/brunch/postcss-brunch/pull/24>
- Fixing postcss with sass: <https://github.com/brunch/postcss-brunch/pull/33>

**Comment by nblackburn** [comment]
I think this would be good and allow for a potential solution in one of my plugins.

**Comment by lydell** [comment]
I think this is possible using brunch 2.10.0 and later by adding `FooCompiler.prototype.targetExtension = 'js'` to plugins, for example.

**Comment by paulmillr** [comment]
#749
