### ISSUE TITLE
Static inclusion of multiple files from single package fails

### ISSUE THREAD

**Issue by bigsweater** [brunch/brunch#1569]
### Description

Brunch fails to include multiple JS files from the same folder in one package.

### Expected behavior

I expect both files declared in the `static` array to be included in my `vendor.js` file.

### Actual behavior

It looks like only the first one is included.

I created [a demo repository](https://github.com/bigsweater/brunch-include-test) shows the problem in action.

Using jQuery as a global and `jquery-validation` as a static include, vendor.js compiles fine. However, adding `additional-methods.js` (which lives in the `dist` dir of the `jquery-validation` package alongside `jquery.validate.js`) causes Brunch to just use `additional-methods.js`, and leave out `jquery.validate.js`. 

Brunch doesn't log any errors during `watch` or `build`.

### Environment

1. Brunch: 2.9.1
2. Node: 7.0.0
3. NPM: 3.10.9
4. Operating system: macOS 10.12.1

### `package.json` contents

```json
{
  "name": "brunch-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "jquery": "^3.1.1",
    "jquery-validation": "^1.15.1"
  },
  "devDependencies": {
    "brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "auto-reload-brunch": "^2.0.0"
  }
}

```

### brunch config contents

```javascript
// See http://brunch.io for documentation.
module.exports = {
  files: {
    javascripts: {
      joinTo:  {
        'app.js':/^app/,
        'vendor.js': /(?!app)/
      }
    },
    stylesheets: {joinTo: 'app.css'},
    templates: {joinTo: 'app.js'},
  },

  npm: {
    globals: {
      jQuery: 'jquery'
    },

    static: [
      'node_modules/jquery-validation/dist/jquery.validate.js',
      'node_modules/jquery-validation/dist/additional-methods.js'
    ]    
  }
};
```

**Comment by bigsweater** [comment]
I actually just tried this with another, totally separate file, and it didn't work; only one of the files is being statically included.

**Comment by thiagomajesk** [comment]
Brunch 2.10.10 seems to be working (concat-wise)... 
I have something similar:

```
 static: [
            "node_modules/jquery-validation/dist/jquery.validate.js",
            "node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js",
            "node_modules/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"
        ]
```
