### ISSUE TITLE
Separation of node server and brunch app

### ISSUE THREAD

**Issue by baldmountain** [brunch/brunch#1572]
### Description

It looks like everything in the node_modules directory gets included in the generated vendor.js file. In my project I have a hapi server as well as a react front end app. I've worked around this with a *VERY* long regex in the brunch-config.js setting in {javascripts: { joinTo: { 'vendor.js': long_regex}}}. Without this regex I get hapi, mocha, chai, etc in my vendor.js file.

### Expected behavior

Is there a setting I'm missing to specify what JS modules should go into vendor.js rather than everything in node_modules?

### Environment

1. Brunch: 2.4.0
2. Node: 6.9.1
3. NPM: 3.10.8
4. Operating system:

**Comment by yavorsky** [comment]
Hi! Thanks for your issue, let's resolve it!
Where are your hapi server's files located?
Are you requiring/importing these modules somewhere in the `/app` directory? If no, provide please your current brunch-config.

**Comment by baldmountain** [comment]
Hi,

My server files are in a directory named /lib in the root of the project. (Where /app is located.)

The hapi node modules are in the node_modules directory along with the ones for /app. In other words my package.json file includes node modules used in /app as well as the hapi server in /lib. (The /app modules are specified as devDependencies since they will be compiled into /public/app.js. The hapi files are specified as dependencies since they will be needed when the server runs in production.)

My brunch-config.js

`'use strict';

module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^node_modules\/(react|fbjs|process|loose-envify|object-assign|js-tokens|core-js|isomorphic-fetch|promise|ua-parser-js%|invariant|history|hoist-non-react-statics|loose-envify|warning|query-string|strict-uri-encode|jquery|moment)/,
        'app.js': /^app/
      }
    },
    stylesheets: {joinTo: 'app.css', order: {before: ['app/less/app.less']}}
  },
  paths: {
    watched: ['app', 'test', 'verndor']
  },
  plugins: {
    babel: {presets: ['es2015', 'react']}
  },
  server: {
    command: 'nodemon lib/service.js'
  }
};
`

**Comment by yavorsky** [comment]
@baldmountain Even if you are specify just `node_modules` in `vendor.js` field, brunch must compile only packages that was required/imported in watched directories. Is there any chances that you requiring some of back-end modules in **test** or  **ve~r~ndor** directories ?

**Comment by baldmountain** [comment]
Ah, that's it! My server tests load stuff in the test directory. :)

Just curious as to why the test directory is watched. Seems like it would be hard to write tests without an assertion library of some sort and that would end up in your vendor.js. For transpilers maybe?

I'm going to mark this closed since my issue is resolved. Thanks for the help!
