### ISSUE TITLE
Elm-brunch issue

### ISSUE THREAD

**Issue by stelmakh** [brunch/brunch#1573]
Brunch plugins are designed to compile each file separately on change. `elm-brunch`, however, runs `elm-make` for elm modules instead. That's why brunch cache is not being updated properly, which results in redundant error messages.

[StackOverflow issue](http://stackoverflow.com/questions/40822312/elm-brunch-watch-is-missing-some-of-my-elm-file-changes)

Brunch: 2.9.1

**Comment by stelmakh** [comment]
Created a [PR](https://github.com/madsflensted/elm-brunch/pull/30) in `elm-brunch` that should fix the issue.

**Comment by shvaikalesh** [comment]
I will close this one because it is an issue with the plugin, not Brunch itself. PR is nice. Thanks @stelmakh.
