### ISSUE TITLE
How to use brunch deal with image?

### ISSUE THREAD

**Issue by l3ve** [brunch/brunch#1579]
like base64, any plugin?

**Comment by shvaikalesh** [comment]
Hey @l3ve, thanks for the question.

Could please clarify, do you want to a) require an image from fs as `base64` to your component or b) optimize images with Brunch?

**Comment by l3ve** [comment]
Just b)

**Comment by denysdovhan** [comment]
@l3ve take a look at [steffenmllr/**imageoptmizer-brunch**](https://github.com/steffenmllr/imageoptmizer-brunch).

**Comment by denysdovhan** [comment]
@l3ve also, if you need to find a plugin for Brunch, you can use [plugins registry](http://brunch.io/plugins).

**Comment by l3ve** [comment]
is that brunch don't  focus on image, i feel  brunch is useless in this respect.
or just no one to write the plugin.

**Comment by shvaikalesh** [comment]
We are working on it: https://github.com/brunch/brunch/pull/1571 brought us quite close. Progress can be tracked here: https://github.com/brunch/brunch/issues/840.
