### ISSUE TITLE
Bower support not working?

### ISSUE THREAD

**Issue by sjaase** [brunch/brunch#1580]
I'm trying to use Brunch for a project but run into several issues using it. One them is the following:
 
I want the javascript files in the bower_components (wwwroot/lib) folder to be concatenated into a libs.js file. But what I end up with is a giant libs.js file including every js file in bower_components directory and not just the main files.

Not sure if I'm using this tool wrong or if it is a bug.

```
 module.exports = {
    files: {
        javascripts: {
            joinTo: {
                'app.js': 'wwwroot/app/**',
                'libs.js': 'wwwroot/lib/**'
            },
            order: {
                before: ['**/*.module.js']
            }
        },
        stylesheets: {
            joinTo: {
                'app.css': 'wwwroot/**'
            }
        }
    },
    paths: {
        watched: ['wwwroot/app', 'wwwroot/content', 'wwwroot/lib'],
        public: 'wwwroot/dist'
    },
    modules: {
        definition: false,
        wrapper: false
    },
    npm: {
        enabled: false
    },
    conventions: {
        vendor: /wwwroot\/lib\//
    }
}
```

**Comment by denysdovhan** [comment]
Hi @sjaase! Thanks for noticing!

I will be glad to help you, but can you, please, make a GitHub repo that reproduce this bug? That would be much more easier for me to fix that problem.

**Comment by denysdovhan** [comment]
Also, keep in mind that Brunch uses [`read-components`](https://www.npmjs.com/package/read-components#why) module internally. Take a look at [“Component JSON file must have `main` property.”](https://www.npmjs.com/package/read-components#component-json-file-must-have-main-property) section and make sure all your packages are work properly.
