### ISSUE TITLE
 Compilation failure when using babel-brunch to transpile NPM dependencies.

### ISSUE THREAD

**Issue by afrz** [brunch/brunch#1582]
### Description

Compilation failure (with brunch version 2.9.1) when using ``babel-brunch`` to transpile NPM dependencies.

### Expected behavior

Transpilation should run without error (as it was in 2.8.2).

### Actual behavior

Brunch 2.9.1 configured to transpile NPM dependencies (but configured to ignore/skip ``nodes_modules``)
=> compilation fails on a  ``es6.object.to-string.js`` file (which is emtpy) from `` core-js `` package.

### Environment

1. Brunch: 2.9.1
2. Node: 4.1.1
3. NPM: 3.6.0
4. Operating system: Win7 x64

### `package.json` contents

```
{
  "name": "brunch-issue",
  "description": "brunch-issue",
  "dependencies": {
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-bootstrap": "^0.30.7"
  },
  "devDependencies": {
    "babel-brunch": "^6.0.6",
    "babel-preset-react": "^6.16.0",
    "brunch": "^2.9.1",
    "javascript-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```
    config: {
        files: {
            javascripts: {
                joinTo: 'app.js'
            }
        },
        npm: {
            compilers: ['babel-brunch']
        },
        plugins: {
            babel: {
                presets: ['es2015', 'react'],
                ignore: /^node_modules/
            }
        }
    }
```

### Other useful files, when present (log, `bower.json` etc.)

```
brunch b -d
09 Dec 13:46:22 - error: Compiling of node_modules/babel-runtime/node_modules/core-js/library/modules/es6.object.to-string.js failed. File node_modules/babel-runtime/node_modules/core-js/library/modules/es6.object.to-string.js data is invalid.

09 Dec 13:46:22 - info: compiled 118 files into app.js, copied index.html in 1.6 sec
```

Compilation was sucessful in brunch 2.8.2.

**Comment by afrz** [comment]
Demo repo using latest versions and minimal configuration

https://github.com/afrz/brunch-issue-1582

When removing completely **config.plugins.babel.ignore** option, it works as expected... but then I cannot transpile some of my NPM dependencies.
I do not understand what is going on exactly...

**Comment by tkesgar** [comment]
I managed to build your demo on node 7.0.0, npm 3.10.8 with this config. Try it with your node and npm version.

```js
module.exports = {
    config: {
        files: {
            javascripts: {
                joinTo: 'app.js'
            }
        },
        plugins: {
            babel: {
                presets: ['es2015', 'react']
            }
        }
    }
};
```

The line `compiler` and `ignore` should be unneccessary; Brunch is *smart*.

**Comment by afrz** [comment]
Indeed Brunch is smart :+1:   Thanks for having a look at the sample.

But I need the **npm.compiler** option to transpile some of my NPM ES6 dependency (my real use case). 

To make it works : 
* Do not override **plugin.babel.ignore** option and lets **babel-brunch** transpile ALL the NPM deps (will take longer to compile and will transpile unnecessary stuff).
* Use the **plugin.babel.pattern** option to filter exactly what shall be transpiled by **babel-brunch**

I close the issue, nevertheless, it still seems a minor regression from 2.8.2.

**Comment by shvaikalesh** [comment]
Hey @afrz, thanks for the issue.

Indeed, that was a regression and I've just fixed it in `master`. Test repo builds without config changes.

As I understand, you have long regexp in `ignore` to compile only specific dependencies.
I think it is cool that library authors give opportunity to compile ES6 ourselves (only for browsers we support and transpilers we like), so I feel like we can improve `npm.compilers` in Brunch.

This is what I have in mind:

```js
compilers: {
  'document-promises': 'babel-brunch',
}
```

Would love to hear any feedback.

**Comment by afrz** [comment]
> As I understand, you have long regexp in ignore to compile only specific dependencies.

Exactly ! 

I just test with ``latest`` **brunch** commit and NPM dependencies compilation are fixed : 
* in the sample projet
* in my real world project

So thanks you @shvaikalesh !

Regarding your proposal, it would indeed be nice if instead ignoring packages in **babel-brunch** plugin options, we could declare which dependencies shall be taken into account by **npm.compilers**

But defining packages one by one seems tedious, especially if ES6-only packages tends to grow : why not using a regex or [anymatch ](https://github.com/es128/anymatch)?

```
compilers : {
  'babel-brunch' : anymatch
}
````

**Comment by afrz** [comment]
When using `latest` **brunch** commit with my app, I found an unexpected warning, telling that *Markdown* file are *brunched*... No big deal but just for info.

`15 Dec 14:19:53 - warn: app/locales/README.md compiled, but not written. Check your undefineds.joinTo config`

**Comment by shvaikalesh** [comment]
Hello @afrz.

Thanks for pointing that out, should be fixed by https://github.com/brunch/brunch/pull/1601.

Regarding the proposal:

Allowing `anymatch` is OK, but I would prefer enumerating package names to be default way of listing files to transpile like:

```js
compilers : {
  'babel-brunch': [
    'document-promises',
    'some-other-lib',
  ]
}
```

So users won't even try constructing regular expressions like `node_modules\/(document-promises|some-other-lib)`.

**Comment by shvaikalesh** [comment]
And if we special-case strings, it won't be *just* `anymatch` any more :)

**Comment by afrz** [comment]
After a second thought, I agree with you.

I was too close of my use case where I own the modules I transpile. So, as I manage their names, I can manage a fairly easy regular expression. But in real world, packages names are heterogeneous... and so the regex will become 'wild'...

Your last example seems good for me 👍 
```
compilers : {
  'babel-brunch': [
    'document-promises',
    'some-other-lib',
  ]
}
```

**Comment by nwallis** [comment]
Hi... what is the status of npm.compilers?  I don't see it in the brunch docs.  I have no issue with naming which dependencies should use which compiler.  But it appears that npm.compilers is expecting an Array, which rules out the option of me being able to specify which dependencies belong to a compiler. 

I have written a dependency in ES6 (import and export at top level of course) and having the same issue.  The only other solution is precompile this and set 'main' in package.json to the compiled source instead?
