### ISSUE TITLE
Question: How to know if in production mode

### ISSUE THREAD

**Issue by designermonkey** [brunch/brunch#1589]
I want to be smart, maybe too smart.

I have a google analytics module that I only want to report page views when on the production site, or at least when the code is compiled as production.

Is there any easy way to leverage the `--production` flag of brunch inside my own code to test whether I have compiled that way?

I bet this is really easy isn't it.

**Comment by shvaikalesh** [comment]
Hi there, @danny-andrews.

Right you are, that is easy.

`process.env.NODE_ENV` will be replaced with strings `'production'` or `'development'` during build time. Relevant sources: https://github.com/brunch/deppack/blob/master/lib/explore.js#L88

We will add it to the docs.

**Comment by designermonkey** [comment]
Lovely, thanks.

**Comment by denysdovhan** [comment]
@designermonkey added to tips in https://github.com/brunch/brunch.github.io/pull/214

**Comment by designermonkey** [comment]
Thanks guys.
