### ISSUE TITLE
CSS not compiling

### ISSUE THREAD

**Issue by ruskibenya** [brunch/brunch#1598]
I've been trying to figure this out for awhile now. I have my stylesheet under app/styles/main.css. 

My brunch-config looks like this:

`      stylesheets: {
        joinTo: {
                "app.css": [/^vendor/, /^bower_components/, /^app/]
            },
            order: {
                before: [/^app/]
            }`

When I run Brunch my terminal says that main.css is compiled but is not used in browser and styles revert to default. 

Here is a link to the repo: https://github.com/ruskibenya/DolDem/tree/working

Thank you for all help.

**Comment by shvaikalesh** [comment]
Hey @ruskibenya, how is your day going?

Brunch does not perform any magic on html, so you have to manually add

```html
<link rel=stylesheet href=app.css>
```

Does that help?

**Comment by denysdovhan** [comment]
You didn't include your stylesheet [here](https://github.com/ruskibenya/DolDem/blob/working/app/index.html#L10-L12). Please, check it out.

**Comment by ruskibenya** [comment]
Wow. Can't believe I missed something so simple. I've tried to add the stylesheet but it still seems to not compile in browser.


It should look something like this:

![screen shot 2016-12-22 at 6 08 12 pm](https://cloud.githubusercontent.com/assets/18274428/21444297/c1aa47c0-c871-11e6-99a7-c2df50491e94.png)


Instead it looks like this in browser:

![screen shot 2016-12-22 at 6 07 50 pm](https://cloud.githubusercontent.com/assets/18274428/21444312/d61f8ecc-c871-11e6-9fd5-4d46cf1aef4b.png)

And the styles tab on chrome, where it seems to be using the material.min.css stylesheet instead of mine:

![screen shot 2016-12-22 at 6 07 59 pm](https://cloud.githubusercontent.com/assets/18274428/21444335/fb47afa4-c871-11e6-8755-fa8540ae96aa.png)



Thank you all for your help!

**Comment by denysdovhan** [comment]
@ruskibenya shit happens ¯\_(ツ)_/¯

**Comment by shvaikalesh** [comment]
@ruskibenya with Brunch you also configure `order` in which styles are concatenated. Please see http://brunch.io/docs/config for more info.

I will close this one, but feel free to contact us if you have another issue.

**Comment by ruskibenya** [comment]
@shvaikalesh thank you. Would my stylesheets come before or after the material design?

**Comment by shvaikalesh** [comment]
@ruskibenya vendor files always come first

**Comment by ruskibenya** [comment]
@shvaikalesh I think the problem I'm running into is that material design lite isn't really a vendor file. I'm just linking to a cdnjs of it and including it as a stylesheet in my index. 

I've tried messing around with the jointo order but can't get brunch to correctly compile my own css file.

Am I correct that this is what's causing brunch to ignore my css file? Is the only solution to install CDL into my project as an actual vendor file? I was hoping to avoid adding the extra size.

**Comment by ruskibenya** [comment]
@shvaikalesh Spasibo for all the extra help!
