### ISSUE TITLE
Brunch recompiles when ignored file is saved

### ISSUE THREAD

**Issue by joshvillbrandt** [brunch/brunch#1599]
### Description

I'm trying to update all of the dependencies in my app so that the addition of `babel-brunch` doesn't fail. Everything is peachy in the `package.json` below except that hitting `ctrl-s` in sublime on an "ignored" file causes the brunch compile and auto-reload to happen which is not the desired behavior.

To verify that the ignored files are indeed still being ignored, I commented out one of the `config.conventions.ignored` lines and noted `compiled, but not written` errors as expected. So it seems brunch is correctly ignoring the files during compile, but is triggering a recompile for no reason... Any ideas?

Note that this was all working as expected with much older versions of everything. (See old package.json excerpt below.)

### Environment

1. Brunch: 2.9.1
2. Node: 6.9.2
3. NPM: 3.10.9
4. Operating system: OSX 10.10.5

### `package.json` contents

```json
  "devDependencies": {
    "angularjs-templates-brunch": "~1.0.0",
    "auto-reload-brunch": "~2.7.1",
    "babel-brunch": "~6.0.6",
    "bower": "~1.8.0",
    "brunch": "~2.9.1",
    "clean-css-brunch": "~2.0.0",
    "css-brunch": "~2.6.1",
    "javascript-brunch": "~2.0.0",
    "keyword-brunch": "git://github.com/urosgruber/keyword-brunch.git#5ee50ec4cbce7f70af32bbca10d3368e90af3e29",
    "less-brunch": "~2.7.1",
    "package-brunch": "~0.3.1"
  },
```

### brunch config contents

```javascript
exports.config = {
  npm: {
    enabled: false
  },
  conventions: {
    assets: /(^app\/assets|font)/,
    ignored: [
      /^(.*?\/)?[_]\w*/,
      /\.spec\.js$/,
      /\.interface\.js$/,
    ],
  },
  modules: {
    definition: false,
    wrapper: false
  },
  paths: {
    'watched': ['app', 'vendor'],
    'public': '_public'
  },
  files: {
    javascripts: {
      joinTo: {
        'js/app.js': /^app((?!\.spec\.js)(?!\.interface\.js).)*$/,
        'js/vendor.js': /^bower_components|^vendor/
      },
      order: {
        before: [
          'app/utilities/lodash-mixins.js',
        ],
      }
    },
    stylesheets: {
      joinTo: {
        'css/app.css': /^app/
      },
      order: {
        before: ['app/styles/app.less']
      }
    },
    templates: {
      joinTo: {
        'js/templates.js': /^app/
      },
      order: {
        before: ['app/scripts/app.js']
      }
    }
  },
  plugins: {
    // include sentry URL in
    keyword: {
      extraFiles: ['_public/js/app.js'],
      map: {
        THING: process.env.THING || '',
      },
    },
    // include package.json so that we can grab it in app/services/environment.js
    package: {
      fileName: '../js/package.js',
      fileSource: 'package.json',
      nameSpace: 'node',
    },
    // remove app/ from path strings since it applies to all templates
    angular_templates: {
      path_transform: function(path) {
        return path.replace(/app\//, '');
      }
    },
    // Enable or disable minifying of result js / css files.
    // minify: true
  },
};

```

### Other useful files

This previously worked with a set of very old dependencies and node 0.12. Here is the relevant package.json bit:

```json
  "devDependencies": {
    "aang-template-brunch": "~1.7.6",
    "auto-reload-brunch": ">= 1.0 < 1.8",
    "bower": "~1.3.5",
    "brunch": "~1.7",
    "clean-css-brunch": ">= 1.0 < 1.8",
    "css-brunch": ">= 1.0 < 1.8",
    "javascript-brunch": ">= 1.0 < 1.8",
    "keyword-brunch": "1.7.8",
    "less-brunch": ">= 1.0 < 1.8",
    "package-brunch": "^0.3.1"
  },
```

**Comment by denysdovhan** [comment]
Hey, @joshvillbrandt!

Could you wrap this up in single repo? That would help me a lot on the way of resolving this issue. I' guessing I know where is the root of problem.

**Comment by joshvillbrandt** [comment]
Hmm, is this perhaps the desired behavior? The [current docs](http://brunch.io/docs/config#-conventions-) for `ignored` makes me think that it might be:

> ignored key: matching pattern. Will check against files that should be ignored by brunch compiler, but are still watched by the watcher. For example, when you have common.styl file that you import in every stylus file, common.styl will be compiled on its own too which will result in duplicated code. When prefixing it with underscore (_common.styl) you are still able to import it in dependent files, but it won’t be compiled twice. The feature is very similar to Sass partials. By default, files and directories that start with underscore (_) will be ignored, as well as anything under the vendor/node/, vendor/ruby-*/, vendor/jruby-*/, and vendor/bundle/ directories.

I also tried out the [ionic-brunch-es6-seed](https://github.com/tolyo/ionic-brunch-es6-seed) which has embedded spec and scenario files like I do with a matching line in the config/ignored section. It too, however, re-compiles when one of the ignored files is saved. (@denysdovhan, try this repo to reproduce the issue! I saved `app/modules/playlists/playlists.spec.js` to reproduce the undesired compile behavior.)

If this is the desired behavior, then is there another way that I can prevent compiling when those files change? The paths/watched key in the config seems to be ideal, but it doesn't look like that key supports regex...

The issue for me is that my app concatenates some fixtures to the end of app.js before running protractor. Since our previous version of brunch didn't have this new behavior, our test flow is broken when the the app recompiles and throws out our fixtures.

**Comment by joshvillbrandt** [comment]
One way that I could get around this issue is to automatically call our `build-protractor` npm script as a part of our `protractor` npm script. This would mean that the developer has to wait for the entire app to re-build even if the only change was a quick `.spec.js` fix which is not ideal.

Thoughts??

**Comment by denysdovhan** [comment]
Well, first of all, update your dependencies and Brunch to the latest versions and try again. Does it help?

Second, yeah, seems like it's desired behavior. Brunch will always recompile parent dependencies even when ignored files are saved. That's the feature (which is necessary for Sass partials prefixed by `_`).

The solutions for you is updating the dependencies. There shouldn't be a problems with that in the latest versions of plugins and Brunch itself.

**Comment by joshvillbrandt** [comment]
My dependencies are all up to do date (at least as of Thursday when the issue was opened.) Make sure you are looking at the top `package.json` in the original comment. The bottom `package.json` was an older version that demonstrated the behavior of _not_ recompiling when ignored files were saved.

If recompiling is the desired behavior, then updating dependencies is _not_ the solution for me, correct? It is clear that this isn't an issue with brunch then, however I am still not sure how to prevent losing angular mocks and fixtures when a test spec is saved. Any ideas for that?

**Comment by joshvillbrandt** [comment]
Alrighty. I was able to get option 3 to work using [http-server](https://github.com/indexzero/http-server) and this additional package.json script:

```javascript
// the line below was added
"start-protractor": "(npm run build-protractor) && node node_modules/.bin/http-server _public -p 3333",

// the line below already existed in the app
"build-protractor": "(npm run build) && (printf '\n' >> ./_public/js/app.js) && (cat ./test/protractor-app.js >> ./_public/js/app.js) && (printf '\n' >> ./_public/js/app.js) && (cat ./bower_components/angular-mocks/angular-mocks.js >> ./_public/js/app.js) && (printf '\n' >> ./_public/js/app.js) && (cat ./bower_components/ArchitectJS/fixtures/*.js >> ./_public/js/app.js)",
```

This option basically avoids brunch entirely... I'll close the issue, but I'd still like to learn of a way to do this with Brunch directly.

Thanks for your help, @denysdovhan!

**Comment by denysdovhan** [comment]
UR welcome @joshvillbrandt!

**Comment by joshvillbrandt** [comment]
Hmm, actually, `http-server` does not support html5 push-state urls, so I actually had to do use [a yet-to-be-merged patch](https://github.com/indexzero/http-server/pull/194) to http-server, which has been released on npm as `spa-http-server`. The resulting package.json script looks like this:

```javascript
// the line below was added
"start-protractor": "(npm run build-protractor) && node node_modules/.bin/http-server _public -p 3333 -s --push-state",
```

**Comment by denysdovhan** [comment]
@joshvillbrandt one suggestion: scripts from `node_modules/.bin` are available in npm scripts, so there is no need to write whole path. Parentheses aren't necessary too (exit code will be correct). Your script might be simplified:

```json
"start-protractor": "npm run build-protractor && http-server _public -p 3333 -s --push-state",
```

**Comment by joshvillbrandt** [comment]
That still doesn't help me use brunch the way I'd like to, but thanks for the tip.
