### ISSUE TITLE
Brunch not showing syntax errors

### ISSUE THREAD

**Issue by ocalde** [brunch/brunch#1606]
### Description

When i run brunch development server in watch mode, and i save a js or jsx file with syntax errors, brunch doesn't show me the detailed message (like in which line of code the problem is). In a previous brunch version it did show that, but from a time until now, it doesn't show it anymore. For instance, if i have a file with errors, it only shows this: 

`29 Dec 07:50:15 - error: Compiling of app/components/AsciiFacesList.jsx failed.`

I added the -d option to my brunch command for debug mode, but no difference. 

### Expected behavior

To get detailed information about syntax errors in my source files

### Actual behavior

Doesn't show syntax errors when i save a file and brunch development server is running in watch mode.

### Environment

1. Brunch: 2.9.1
2. Node: 7.3.0
3. NPM: 3.10.10
4. Operating system: Windows 10 Professional Edition

### `package.json` contents

```{
  "name": "your-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
      "start": "brunch watch -d --server",
      "prod": "brunch build --production"
  },
  "dependencies": {
    "axios": "^0.15.3",
    "react": "~15.3.0",
    "react-dom": "~15.3.0"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "~6.0.0",
    "babel-preset-es2015": "~6.9.0",
    "babel-preset-react": "~6.11.1",
    "brunch": "^2.4.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'js/vendor.js': /^(?!app)/,
        'js/app.js': /^app/
      }
    }
  },
  server: {
    port: 1234,
    hostname: "0.0.0.0"
  },
  plugins: {
    babel: {presets: ['es2015', 'react']}
  }
};

```

### Other useful files, when present (log, `bower.json` etc.)

If there's an unexpected error during `brunch build`/`brunch watch`, please attach the compilation log with the debug flag (`-d`) **and** stack traces enabled (`export LOGGY_STACKS=true`).

If something worked with previous versions of brunch, but stopped with a newer one, please include these details as well.

**Comment by denysdovhan** [comment]
Hey, @ocalde!

Try to update to the latest version of Brunch. Would be great if you try the latest version from master. Personally, I've fixed the problem with debug messages in #1596. Error messages have got improvement in #1605.

Hope, this will fix your problem.

**Comment by lydell** [comment]
The problem here is that the latest babel-brunch version on npm is broken. A new release including [this commit](https://github.com/babel/babel-brunch/commit/ef2fbb80c9c841b699ba0ea38102c699fde0910c) needs to be done. For the time being, I've put this in my package.json:

```json
"babel-brunch": "github:babel/babel-brunch#95298bc0d68b12d8c61269d1730e08a029b718b9"
```

**Comment by ocalde** [comment]
Thanks @lydell , that solved the problem. Now i'm getting desired "stacktrace" :P : 
```
> brunch watch -d --server

01 Jan 22:29:51 - info: application started on http://192.168.1.4:1234/ (Wi-Fi)
01 Jan 22:29:51 - info: application started on http://127.0.0.1:1234/ (Loopback Pseudo-Interface 1)
01 Jan 22:29:55 - warn: app/styles/application.css compiled, but not written. Check your stylesheets.joinTo config
01 Jan 22:29:55 - error: Compiling of app/components/App.jsx failed. SyntaxError: app/components/App.jsx: Unexpected token, expected ; (34:22)
  32 |             $(window).scroll(function() {
  33 |                 let docHeight = component.getDocHeight();
> 34 |                 wrong code
     |                       ^
  35 |                 let amountScrolled = $(window).scrollTop() + $(window).height();
  36 |                 if(amountScrolled >= (docHeight - 10) && amountScrolled <= (docHeight + 10)) {
  37 |                    //alert("bottom!");
01 Jan 22:29:55 - info: compiled 174 files into 2 files, copied index.html in 5.8 sec
```
I'll be waiting for the new release. Thank you very much.
