### ISSUE TITLE
brunch v2.9.x is missing dependencies returned by plugin compile()

### ISSUE THREAD

**Issue by bmatcuk** [brunch/brunch#1607]
In previous versions of brunch, it was possible for a plugin to return file dependencies from the `compile()` method. This does not work in v2.9.x. The problem lies around here: [pipeline.js:82](https://github.com/brunch/brunch/blob/5268d242b6ccb5522c88d50d402b0552bdc846ef/lib/fs_utils/pipeline.js#L82). The code is checking for `result.dependencies`, but then it never does anything with it.

In the previous version of brunch (v2.8.2), the code was fairly different, but it follows the same basic layout. However, we can see around [pipeline.js:130](https://github.com/brunch/brunch/blob/ed1c42f8c1c636de913ba3c611216b6c5fd75610/lib/fs_utils/pipeline.js#L130) that the dependencies returned by `compile()` are being passed to the `getDependencies` method, which then returns those dependencies ([here](https://github.com/brunch/brunch/blob/ed1c42f8c1c636de913ba3c611216b6c5fd75610/lib/fs_utils/pipeline.js#L67)) if the plugin doesn't implement `getDependencies` so that these dependencies are not lost.

**Comment by shvaikalesh** [comment]
Hello there, @bmatcuk.

Thanks for reporting this and digging up the sources. Indeed, this is a regression that should be fixed by #1609. Would love to hear any feedback on the fix.

**Comment by bmatcuk** [comment]
Hey, @shvaikalesh. The fix looks good to me! Thanks for the quick reply.
