### ISSUE TITLE
Brunch + Sass + postcss?

### ISSUE THREAD

**Issue by hmontes** [brunch/brunch#1619]
Hi

Brunch + Sass + postcss don't work. Postcss don't change scss files.

Bourbon removes the autoprefixer propierties. So, i need to made the conversions (display: flex, per example) with autoprefixer.

Can i use autoprefixer with scss?

Thank you

**Comment by kgcreative** [comment]
tl;dr: they are working on this. See https://github.com/brunch/postcss-brunch/issues/31

**Comment by hmontes** [comment]
Thank you @kgcreative for the information. I'll wait while i work in the design :)

**Comment by PragTob** [comment]
FWIW  brunch/sass-brunch#135 was reverted so this is still pretty much an issue, the best rundown of what's up that I found is brunch/postcss-brunch#33
