### ISSUE TITLE
A 'joinTo' file named 'vendor.js' eats `npm.static` scripts

### ISSUE THREAD

**Issue by lydell** [brunch/brunch#1621]
### Description

I updated brunch (to a specific commit after the 2.9.1 release), and one of my scripts broke. That script uses the `npm.static` config to include a script from npm as-is. However, that npm script ended up in another file instead: vendor.js. Workaround: I renamed vendor.js to something else.

### Expected/Actual behavior

Here’s the example repo: https://github.com/lydell/brunch-npm-static-bug

```
$ rm -rf public/

$ brunch b
10 Jan 13:54:50 - info: compiled 2 files into css.js in 362 ms

# Expected public/css.js output:
$ grep loadCSS public/css.js 
window.loadCSS('path/to/mystylesheet.css')
/*! loadCSS: load a CSS file asynchronously. [c]2016 @scottjehl, Filament Group, Inc. Licensed MIT */
  /* exported loadCSS */
  var loadCSS = function( href, before, media ){
      // By default, loadCSS attempts to inject the link after the last stylesheet or script in the DOM. However, you might desire a more specific location in your document.
    exports.loadCSS = loadCSS;
    w.loadCSS = loadCSS;

# Expected files in public/:
$ ls public/
css.js  css.js.map

$ echo 'Uncomment line in brunch-config.js'
Uncomment line in brunch-config.js

$ brunch b
10 Jan 13:55:20 - info: compiled 2 files into 2 files in 362 ms

# code from npm missing in public/css.js!
$ grep loadCSS public/css.js 
window.loadCSS('path/to/mystylesheet.css')

# ... public/vendor.js has eaten it!
$ grep loadCSS public/vendor.js
/*! loadCSS: load a CSS file asynchronously. [c]2016 @scottjehl, Filament Group, Inc. Licensed MIT */
  /* exported loadCSS */
  var loadCSS = function( href, before, media ){
      // By default, loadCSS attempts to inject the link after the last stylesheet or script in the DOM. However, you might desire a more specific location in your document.
    exports.loadCSS = loadCSS;
    w.loadCSS = loadCSS;

# This is the newest commit that works as I expect:
$ npm i -D brunch/brunch#71727b66ed5606c9b285888c4ac20440ce3560b7
...snip...

$ rm -r public/

$ brunch b
10 Jan 13:56:38 - info: compiled 2 files into css.js in 389 ms

$ grep loadCSS public/css.js 
window.loadCSS('path/to/mystylesheet.css')
/*! loadCSS: load a CSS file asynchronously. [c]2016 @scottjehl, Filament Group, Inc. Licensed MIT */
  /* exported loadCSS */
  var loadCSS = function( href, before, media ){
      // By default, loadCSS attempts to inject the link after the last stylesheet or script in the DOM. However, you might desire a more specific location in your document.
    exports.loadCSS = loadCSS;
    w.loadCSS = loadCSS;

$ ls public/
css.js  css.js.map
```

### Environment

1. Brunch: commit 110e9a9d9336f0e518e8c75eea8f967cfb8714b5
2. Node: v6.9.1
3. NPM: 3.10.8
4. Operating system: Ubuntu 16.04

### `package.json` contents

```json
{
  "private": true,
  "dependencies": {
    "fg-loadcss": "^1.2.1"
  },
  "devDependencies": {
    "brunch": "github:brunch/brunch#110e9a9d9336f0e518e8c75eea8f967cfb8714b5",
    "javascript-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```javascript
module.exports = {
    files: {
        javascripts: {
            joinTo: {
                'css.js': /^app\/css\.js|^node_modules\/fg-loadcss\//,
                // Uncomment this line to trigger the bug:
                // 'vendor.js': 'mohaha',
            },
        },
    },

    npm: {
        static: [
            'node_modules/fg-loadcss/src/loadCSS.js',
        ],
    },
}
```

**Comment by shvaikalesh** [comment]
Hey @lydell. Thanks for testing out `master` and exhaustive bug report. This is definitely a priority. Will fix within a few days.

**Comment by shvaikalesh** [comment]
Hmm, `vendor` is indeed special-cased to consume all files. Code: https://github.com/brunch/brunch/blob/master/lib/utils/config.js#L108.

I believe it should ignore `npm.static`.
@lydell, can you tell me please from what Brunch version you upgraded?

**Comment by lydell** [comment]
While renaming `vendor.js` to something else works in the example repo, it didn't make any difference in my real project, so I ended up pinning brunch to commit 71727b66ed5606c9b285888c4ac20440ce3560b7. I haven't been able to narrow it down. I believe any commit from 2.9.1 to commit 71727b66ed5606c9b285888c4ac20440ce3560b7 works as expected.

**Comment by lydell** [comment]
Actually, I just managed to narrow it down: lydell/brunch-npm-static-bug@6ef6531e9bc175f71db9b8fb8d566079ae27a69a

So the name `vendor` does not seem to be the _only_ problem.

**Comment by shvaikalesh** [comment]
That helped a lot, thanks! Could you please review #1632 and test out `hellyeahllc/brunch#fix-jointo` if you feel like you want to?

**Comment by lydell** [comment]
`hellyeahllc/brunch#fix-jointo` seems to work in my real project as well. Thanks! 👍

**Comment by shvaikalesh** [comment]
You are welcome, will release `2.10.3` very soon.
