### ISSUE TITLE
inferno alias doesn't work when creating new project

### ISSUE THREAD

**Issue by rafaelkallis** [brunch/brunch#1623]
### Description

When running `brunch new -s inferno` I get a warning that brunch couldn't interpret 'inferno' as a hosted git url

### Expected behaviour

it should be able to clone the skeleton

### Actual behaviour

cloning the repo fails.

```
$ brunch new -s inferno
13 Jan 17:52:47 - warn: Couldn't interpret 'inferno' as a hosted git url
13 Jan 17:52:47 - log: Cloning git repo "inferno" to "/Users/rafaelkallis/.brunch/skeletons/792883c4eebc3b69fa15b94e87456cf2c566c202"...
13 Jan 17:52:47 - error: Error: Git clone error: fatal: repository 'inferno' does not exist
```
Environment

* Brunch: 2.9.1
* Node: 6.9.1
* NPM: 4.1.2
* Operating system: macOS 10.12.2

**Comment by paulmillr** [comment]
Published a new version of `skeletons` which fixes that.
