### ISSUE TITLE
Does brunch _need_ to be a devDependency of a brunch project?

### ISSUE THREAD

**Issue by 32bitkid** [brunch/brunch#1628]
### Description

Seemingly, prior to `brunch@2.10.0`, as long as you had brunch installed globally, then you could build a brunch project _without_ having brunch installed in _local_ `node_modules`.

For example, with the skeleton `brunch/dead-simple`.

```
$ npm uninstall --save-dev brunch
$ npm install --save react
$ echo "require('react');" > app/initialize.js
```

### Expected behavior

 With `brunch@2.9.1`, everything builds…

### Actual behavior

With `brunch@2.10.0`, the browser console shows the following exception:

```
Uncaught Error: Cannot find module 'process' from '/'
    at require (app.js:62)
    at initialize.js:1
    at initialize.js:1
````

It seems some shims from `brunch/deppack` aren't getting packed if brunch isn't there, but I don't know why…  However, if `brunch@2.10.0` _is_ installed locally in `node_modules` then this issue goes away. I've noticed that some skeletons (like `brunch/dead-simple`) define a brunch as a dependency, however, not _all_ of them do. Is this an intended change/requirement?

### Environment

1. Brunch: 2.10.0
2. Node: v6.9.3
3. NPM: 3.10.10
4. Operating system: macos 10.12.2

### `package.json` contents

```json
{
  "name": "brunch-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "react": "^15.4.2"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```javascript
exports.files = {
  javascripts: {joinTo: 'app.js'},
  stylesheets: {joinTo: 'app.css'},
  templates: {joinTo: 'app.js'}
};
```

**Comment by denysdovhan** [comment]
Just for notice, it's better to have `brunch` in `devDependencies`, because it's actually a dependency for development. That's might be needed for Travis builds, for example.

In any case, gonna take a look at your problem.

**Comment by denysdovhan** [comment]
@32bitkid this issue is related to #1593. It's a part of common problems with [`deppack` module](https://github.com/brunch/deppack) and we're working on it. I believe it will be fixed soon.

[Here is an explanation](https://github.com/brunch/brunch/issues/1593#issuecomment-269223215) why this happens. I can suggest you to list Brunch in your `devDependencies` until we fix this problem — that will be the simplest solution for you by now.

**Comment by paulmillr** [comment]
It does not need to be a devDependency. This is a high-priority bug.

**Comment by lydell** [comment]
@shvaikalesh This needs to be re-opened since the changes in the commit that closed this issue has been reverted.

**Comment by denysdovhan** [comment]
@lydell I've send another PR: #1643
