### ISSUE TITLE
The automatic npm install fails sometimes.

### ISSUE THREAD

**Issue by lydell** [brunch/brunch#1636]
### Description

The automatic npm install fails sometimes.

### Expected/Actual behavior

1. Create the following files.

   package.json:

   ```json
   {
     "private": true,
     "devDependencies": {
       "brunch": "^2.10.2",
       "javascript-brunch": "^2.0.0"
     }
   }
   ```

   brunch-config.js:

   ```js
   module.exports = {
     files: {
       javascripts: {
         joinTo: 'app.js'
       }
     },
   }
   ```

2. Run `npm install`.

3. Add the following to package.json:

   ```json
   "dependencies": {
     "jquery": "^3.0.0"
   },
   ```

4. Add the following to brunch-config.js:

   ```js
   npm: {
     globals: {
       jQuery: 'jquery'
     }
   }
   ```

5. Run `brunch build`. Output:

   ```
   19 Jan 21:36:02 - error: Initialization error - Could not load global module 'jquery'. Possible solution: run `npm install`. Could not load global module 'jquery'. Possible solution: run `npm install`. 
   Stack trace was suppressed. Run with `LOGGY_STACKS=true` to see the trace.
   ```

6. Run `brunch build` again. Output:

   ```
   19 Jan 21:36:30 - info: compiled 2 files into app.js in 535 ms
   ```

So jquery does seem to be installed in step 5 (since everything works in step 6), but I'd expect the build to succeed in step 5, with the usual messages:

```
19 Jan 21:31:36 - info: Using outdated versions of jquery, trying to update to match package.json versions
19 Jan 21:31:36 - info: Installing packages with npm...
```

### Environment

1. Brunch: 2.10.2
2. Node: 6.9.1
3. NPM: 3.10.8
4. Operating system: Ubuntu 16.04

### `package.json` contents

Shown above.

### brunch config contents

Shown above.

**Comment by shvaikalesh** [comment]
Hello, @lydell. Thanks for step-by-step reproduction guide, helped me a lot. #1639 should fix that, would be cool if you could confirm that.

**Comment by shvaikalesh** [comment]
Is it a regression? [Brunch before refactorings](https://github.com/brunch/brunch/tree/ffb15b35a3f06711b306fb575f2bebcf59f54413/lib) had the same logic: `deppack` calls `browser-resolve` before `check-dependencies`.

**Comment by lydell** [comment]
Thanks for the quick response!

I can confirm that #1639 fixes the problem.

(It is not a regression. I just tried 2.9.1 as well, and it had the same problem.)
