### ISSUE TITLE
Vendor pattern ignoring other vendor directories 

### ISSUE THREAD

**Issue by mcfarljw** [brunch/brunch#1641]
### Description

I noticed when upgrading from 0.9.x to 0.10.x vendor directories outside of the root directory are not getting compiled. It is possible to get around this issue by manually declaring the vendor conventions. I'm not sure if new behaviors is intended or not.

### Expected behavior

I would expect all vendor directories like `vendor` and `core/vendor` to be handled the same as in previous versions.

### Actual behavior

Only the root directory vendor directory gets compiled and all others are ignored.

### Environment

1. Brunch: 0.10.2
2. Node: 6.9.4
3. NPM: 3.10.10
4. Operating system: macOS 10.12.2

**Comment by shvaikalesh** [comment]
Hey, @mcfarljw. Thanks for the issue and sorry for the trouble. `vendor` pattern was intentionally made more specific in `2.10`. It still seems like a good idea for me, but not for `2.x.` time. Use `master` for now.
