### ISSUE TITLE
Is there some way to compile javascript with charset iso-8859? 

### ISSUE THREAD

**Issue by leonardotessaroalves** [brunch/brunch#1644]
i've got some errors when i use http requests.
may someone help me to solve.
thx.

**Comment by shvaikalesh** [comment]
We recommend `utf-8`. Please, make sure you have `<meta charset=utf-8>` in you HTML. If Brunch server will cause troubles after that, please report back. Currently, python's `SimpleHTTPServer` have troubles with non-ascii characters in JS some people actually use. That is nasty. `serve-brunch` should not crash on that.
