### ISSUE TITLE
[2.10.3] Handlebars runtime missing.

### ISSUE THREAD

**Issue by devel-pa** [brunch/brunch#1647]
Not added to vendor.js at all. Previous versions are OK.

Extra: All versions after 2.8.2 (including plugins) have issues that makes them unusable.

**Comment by devel-pa** [comment]
Probably a hint in case it's the issue: Windows

**Comment by shvaikalesh** [comment]
Hmm, that will help a lot. I think I've got an idea on a fix. Thanks.

**Comment by devel-pa** [comment]
I've tried something, but didn't worked.

**Comment by denar90** [comment]
I've tried to run on windows 10 using latest master of `brunch` and `handlebars-brunch`, works totally fine.
@devel-pa can you share with us config and your `package.json`?

**Comment by devel-pa** [comment]
Hi,
I can't share everything, but:

all dependencies:
```
"devDependencies": {
    "auto-reload-brunch": "~2.7.1",
    "autoprefixer": "6.7.0",
    "brunch": "2.8.2",
    "chai": "^3.5.0",
    "clean-css-brunch": "~2.0.0",
    "css-brunch": "~2.6.1",
    "express": "*",
    "glob": "^5.0.5",
    "handlebars-brunch": "~2.0.0",
    "http-proxy": "*",
    "javascript-brunch": "~2.0.0",
    "jshint-brunch": "~2.0.0",
    "json-brunch": "~1.5.4",
    "less-brunch": "~2.7.1",
    "mocha": "2.5.3",
    "mocha-phantomjs": "4.1.0",
    "postcss-brunch": "0.5.0",
    "replace-brunch": "2.0.0",
    "sinon": "1.17.6",
    "sinon-chai": "^2.8.0",
    "uglify-js-brunch": "~2.0.1"
  }
```

and have in vendor something like this:

```
Handlebars.registerHelper('t', function(key, options) {
});
```

So yes, probably I had to mention that. Sorry

**Comment by devel-pa** [comment]
Of course, this stack doesn't exist anymore as I revert it back to 2.8.2 and company

**Comment by denar90** [comment]
You should use `"handlebars-brunch": "~2.10.0"`. It's kinda latest one https://github.com/brunch/handlebars-brunch/releases/tag/2.10.0
Can you provide use with results of using it?

**Comment by devel-pa** [comment]
Already told you that I'm using that version.
But for the sake of testing, this is the result:
`ReferenceError: Can't find variable: Handlebars`
Same as when I submitted the issue.

**Comment by mvinni** [comment]
I think I have the same problem on Linux. 2.10.2 works, 2.10.3 doesn't.

I get this warning message with the failing version:

```
$ brunch b
26 Jan 16:03:43 - warn: node_modules/handlebars-brunch/dist/handlebars.runtime.js compiled, but not written. Check your javascripts.joinTo config
26 Jan 16:03:43 - warn: node_modules/handlebars-brunch/ns.js compiled, but not written. Check your javascripts.joinTo config
26 Jan 16:03:44 - info: compiling
26 Jan 16:03:44 - info: copied 2607 files in 1.3 sec
26 Jan 16:03:44 - info: compiled 136 files into 6 files, copied 2794 in 4.9 sec
26 Jan 16:03:45 - info: copied 2502 files in 1.4 sec
```

Bisecting points to https://github.com/brunch/brunch/commit/9658a1f15d7d3360e3e8834d07cad82e619c0f46 and further to
```
fd88bd6893959085c452048d1d1f0f340ad9cfd8 is the first bad commit
commit fd88bd6893959085c452048d1d1f0f340ad9cfd8
Author: Aleksey Shvayka <shvaikalesh@gmail.com>
Date:   Thu Jan 19 09:06:38 2017 +0200

    fix isHelper
```
https://github.com/hellyeahllc/brunch/commit/fd88bd6893959085c452048d1d1f0f340ad9cfd8

Same issue and bisect result with handlebars-brunch 2.10.0 and 2.0.1.

**Comment by devel-pa** [comment]
I have none of the warnings, but both files missing from the build

**Comment by denar90** [comment]
Can't reproduce this one, here is my config
```
exports.config = {
  paths: {
    watched: ['app', 'specs']
  },
  files: {
    javascripts: {
      joinTo: {
        'javascripts/app.js': /^app/,
        'javascripts/specs.js': /^specs/,
        'javascripts/vendor.js': /^(?!app|specs)/
      }
    },
    stylesheets: {
      joinTo: 'stylesheets/app.css'
    },
    templates: {
      joinTo: 'javascripts/app.js'
    }
  },
  npm: {
    styles: {
      bootstrap: ['dist/css/bootstrap.css']
    },
    globals: {
      $: 'jquery',
      Marionette: 'backbone.marionette',
      Backbone: 'backbone'
    }
  },
  plugins: {
    babel: {
      presets: ['es2015'],
      ignore: [
        /^(node_modules)/
      ]
    }
  },
  modules: {
    autoRequire: {
      'javascripts/app.js': ['initialize']
    }
  },
}
```

deps in `package.json`

```
"dependencies": {
    "jquery": "~1.12.2",
    "backbone": "~1.3.3",
    "underscore": "~1.8.1",
    "backbone.radio": "~2.0.0",
    "backbone.marionette": "3.1.0",
    "bootstrap": "4.0.0-alpha.2"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "babel-brunch": "~6.0.0",
    "babel-preset-es2015": "~6.3.13",
    "brunch": "^2.10.3",
    "clean-css-brunch": "^2.0.0",
    "coveralls": "~2.11.6",
    "css-brunch": "^2.0.0",
    "handlebars-brunch": "github:brunch/handlebars-brunch",
    "javascript-brunch": "^2.0.0",
    "karma-brunch": "~1.0.0",
    "uglify-js-brunch": "^2.0.0"
  }
```

**Comment by mvinni** [comment]
Hmm, it seems that for me the fix is this in the config:

```
   files:
     javascripts:
       joinTo:
         'javascripts/app.js': /^app/
-        'javascripts/vendor.js': /^(vendor|bower_components)/
+        'javascripts/vendor.js': /^(vendor|bower_components|node_modules)/
         'test/javascripts/test.js': /^test[\\/](?!vendor)/
         'test/javascripts/test-vendor.js': /^test[\\/](?=vendor)/
```

Maybe the code is nowadays more strict about having `node_modules` match the glob or regular expression. It used to work without...

**Comment by devel-pa** [comment]
Unfortunately I'm already loading tests files from node modules. Adding node modules to vendor adds also all the files for test.

**Comment by shvaikalesh** [comment]
@devel-pa @mvinni Please, confirm #1651 works. `brunch: "hellyeahllc/brunch#fix-is-helper-fix"`

**Comment by denar90** [comment]
@devel-pa @mvinni thanks, guys!

**Comment by devel-pa** [comment]
Same issue with both 2.10.4 and master.

**Comment by mvinni** [comment]
#1651 doesn't fix my case either.

**Comment by shvaikalesh** [comment]
Hey @devel-pa @mvinni. #1656 should fix that.

Plugin helpers have special handling when it comes to joining files. They either use `javascripts.pluginHelpers`, or first entry with `vendor` or first entry. Detection of this helpers was broken because normalization (relative to `paths.root`) was missing and Brunch compared absolute paths to relative ones.

**Comment by mvinni** [comment]
This one seems to do the trick for me. Thanks.

**Comment by devel-pa** [comment]
Thank you, issue fixed.
