### ISSUE TITLE
[2.10.x] Chains of plugins has issues

### ISSUE THREAD

**Issue by devel-pa** [brunch/brunch#1648]
To fix the issue looks like keeping the original file name in the compile parameter will do.

https://github.com/brunch/less-brunch/pull/43

https://github.com/brunch/postcss-brunch/pull/39

https://github.com/brunch/sass-brunch/pull/135

If chained from brunch-less at 
https://github.com/brunch/postcss-brunch/blob/master/index.js#L55
`file.path` is the new CSS file that in fact doesn't exists and should be the original LESS one.

**Comment by shvaikalesh** [comment]
Related: https://github.com/brunch/brunch/issues/1635

**Comment by devel-pa** [comment]
Indeed, hopefully it will solve all the other issues, and I'm pretty sure is related to Brunch, not with plugins.
I'll bet with this, too:
https://github.com/brunch/postcss-brunch/issues/37

**Comment by devel-pa** [comment]
@shvaikalesh I'm searching for a solution and I realize that I can't make any difference between `css-brunch` and `postcss-brunch`, but if I'm removing `css-brunch` it's working as expected. Those two not working together?

**Comment by shvaikalesh** [comment]
I suppose because of source maps. `css-brunch` will be deprecated soon. Brunch `2.10` works with CSS without it. You can safely remove it.

**Comment by devel-pa** [comment]
Then I'll prepare a PR with a code example
