### ISSUE TITLE
[2.10.2] preCompile file manipulation triggers a watch

### ISSUE THREAD

**Issue by devel-pa** [brunch/brunch#1649]
Until 2.8.2 didn't.
I have tests on `onCompile` and makes them fail as I'm copying a file in test folder.
Due to the copy of the file whole chain is running twice (including `preCompile`).

**Comment by shvaikalesh** [comment]
Hey @devel-pa, thanks for the report. Would love if you could verify #1659 fixes your issue.

**Comment by devel-pa** [comment]
Thank you, issue fixed.
