### ISSUE TITLE
Spread operator problem

### ISSUE THREAD

**Issue by hmontes** [brunch/brunch#1654]
### Description

Spread operator problem in a reducer (React & Redux). I put this in my reducer file:

```import { FETCH_BLOG_POSTS } from '../actions/index';

const INITIAL_STATE = { all: [] };

export default function(state = INITIAL_STATE, action) {
  switch(action.type) {
    case FETCH_BLOG_POSTS:
      return { ...state, all: action.payload.data };

    default:
      return state;
  }
}

```

But when i put in the console: "brunch watch --server" this produces a syntax error. This works in others build tools.

### Expected behavior

The code should have been okey

### Actual behavior

Tell us what actually happens.

```
27 Jan 16:09:43 - error: Compiling of app/reducers/reducer_blog_posts.js failed.
   SyntaxError: app/reducers/reducer_blog_posts.js: Unexpected token (8:15)
      6 |   switch(action.type) {
      7 |     case FETCH_BLOG_POSTS:
   >  8 |       return { ...state, all: action.payload.data };
        |                ^
      9 |
     10 |     default:
```

### Environment

1. Brunch: 2.10.3
2. Node: 6.9.2
3. NPM: 3.10.9
4. Operating system: macOS sierra (10.12.2)

### `package.json` contents

```{
  "name": "brunch-app",
  "description": "Description",
  "author": "Your Name",
  "version": "0.1.0",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "axios": "^0.15.3",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-redux": "^5.0.2",
    "react-router": "^3.0.2",
    "redux": "^3.6.0",
    "redux-promise": "^0.5.3"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.7.1",
    "babel-brunch": "^6.0.6",
    "babel-preset-react": "^6.22.0",
    "brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "hmr-brunch": "^0.1.1",
    "javascript-brunch": "^2.0.0",
    "sass-brunch": "^2.9.0",
    "uglify-js-brunch": "^2.0.0"
  }
}

```

### brunch config contents

```// See http://brunch.io for documentation.
exports.config = {
  hot: true,

  files: {
    javascripts: {joinTo: 'app.js'},
    stylesheets: {joinTo: 'app.css'},
  },

  plugins: {
    babel: {
      presets: ['es2015', 'es2016', 'react']
    }
  }
};

```

Thank you

**Comment by hmontes** [comment]
Temporary fix:

obtained from: http://stackoverflow.com/questions/40126537/spread-operator-equivalent-of-object-assign and http://babeljs.io/docs/plugins/preset-stage-3/

1. Install Stage 3 preset from babel ( npm install --save-dev babel-preset-stage-3 )
2. Add to presets in brunch.config. In my case:

```
plugins: {
    babel: {
      presets: ['es2015', 'es2016', 'react', 'stage-3']
    }
  }
```

And works. But it's not a definitive solution i think.

**Comment by beznosd** [comment]
Hi @hmontes 

Unfortunately `object rest spread transform` is not included to the **es2015** and **es2016** presets, so if you want to use this feature you have to use **stage 3 preset** which includes this one or if you don't need all features of stage 3 you can install and use only `object rest spread transform`
http://babeljs.io/docs/plugins/transform-object-rest-spread/

More details about all babel presets and what they include you can see here
http://babeljs.io/docs/plugins/#presets
