### ISSUE TITLE
Change entry point

### ISSUE THREAD

**Issue by sospedra** [brunch/brunch#1657]
Maybe it's a stupid question but I cannot find the solution.
Coming from a fresh start: `brunch new fresh -s brunch/with-react`

How to rename `app/initialize.js` to `app/App.js`?

I tried with `javascript:entryPoints` config but then `joinTo` stop bundling.

In the same way, not 100% related: How to change opinionated directories such as `app/assets`? For example, for move it to root-level.

Thanks.

**Comment by shvaikalesh** [comment]
Hey @sospedra, thanks for the issue.

> How to rename app/initialize.js to app/App.js?

Rename it in FS and in HTML.

> How to change opinionated directories such as app/assets? For example, for move it to root-level.

`config.paths.watched: ['app', 'test', 'vendor', 'assets']`

**Comment by sospedra** [comment]
Awesome
