### ISSUE TITLE
Unable to create project using "brunch new" [Windows 10 64bit]

### ISSUE THREAD

**Issue by llapresi** [brunch/brunch#1665]
Using brunch 2.10.5 installed via npm.

Regardless of directory "brunch new -s [x]" is ran in, the skeleton git is cloned to "C:\Users\[username]\.brunch\skeletons\[long string of numbers]" folder, which remains empty.

No new files are created after the "bunch new" command and both the directory where it is ran, and the .brunch folder in the user folder remain empty.

Downloading the skeleton as a .zip from the GitHub website and proceeding from there seems to work fine, however.

**Comment by denysdovhan** [comment]
@llapresi hi! Thanks for reaching us out! I'm trying to reproduce and fix your problem right now. Stay in touch.

**Comment by denysdovhan** [comment]
Works fine for me on **macOS Siera** and **Windows 10** with brunch@2.10.5. Certainly you're using Windows. Could you, please, tell us what version of Windows do you use?

Also, would be useful if you tell more about your environment: what terminal emulator do you use? Do you use Bash or something else? Other additional information would be useful too.

**Comment by llapresi** [comment]
Windows 10 Pro x64 Version 1607 Build 14393.693

Git version 2.11.0.windows.3
Node version 6.3.1
NPM version 3.10.3

I'm using the default Command Prompt

**Comment by james1293** [comment]
I'm having a similar problem.
Windows 7 x64 SP1
git version 2.10.1.windows.1
Node version 4.6.0
npm version 4.0.5

Same problem in normal Windows Command Prompt and Git For Windows command prompt.

**Comment by jcoc611** [comment]
Same problem on Windows 10 x64, brunch 2.10.9
