### ISSUE TITLE
Improve error reporting for plugins

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#1666]
In 2.10.6 we'll introduce a new API for plugins that improves error output.

Basically, if a plugin returns a javascript  `Error` object, it should also include `line` and `col` properties on the object. This way we'll show the information in Terminal and a user would see standardized feedback any time he types an error.

```javascript
compile(file) {
  const error = new Error('Invalid syntax');
  error.line = 6;
  error.col = 10;
  return Promise.reject(error)
}
```

Many languages provide a way to get the line & col from the output — we just want to make it universal.

### Remaining items

- [ ] Think how we should display plugin, which breaks the compilation process. I was thinking about changing `loggy`'s `Brunch error` notification title to `Brunch uglify-js error`
- [x] All main plugins need to be updated & checked for **good output**. We don't want any garbage & repetition — for example let's make sure we don't mention any file `paths` twice in the output.

### Main plugins that may require updating

- [x] coffee-script-brunch support
- [x] babel-brunch support
- [x] stylus-brunch support
- [x] uglify-js-brunch support
- [x] sass-brunch support
- [x] less-brunch support
- [ ] typescript-brunch once we standardize the package

**Comment by denysdovhan** [comment]
Gonna standardize **typescript-brunch**. Probably move this package to the org.

**Comment by shvaikalesh** [comment]
`col` and `line` may be zero-based if they are for internal use to display fancy error messages like PostCSS/Babel does. We should research the topic better. Let's not rush API design.
