### ISSUE TITLE
import vendor css?

### ISSUE THREAD

**Issue by srodriki** [brunch/brunch#1669]
### Description

I'm using brunch to process a css file provided in one of the node modules my project depends on. (Specifically, vue-material). If I just specify I want the css files compiled to, say, vendor.css, no content at all will be put into the vendor.css file generated by brunch. 

If I, by instance, do the following in my index.js file (main entry point for my project):

```javascript
import 'vue-material/dist/vue-material.css'
``` 

vue-material's css gets compiled into my vendor file, but I get a js runtime error when I try loading my app in the browser, saying "vue-material/dist/vue-material.css" can't be found. 

### Expected behavior

I would expect one of the following to be true:
1. Without any "import" sentence in my js code, brunch should compile vue-material's css into "vendor.css". 
2. OR, the file should be import-able from my index.js file without errors in the browser at runtime

### Actual behavior

I get the following error in my browser's console:

Uncaught Error: Cannot find module 'vue-material/dist/vue-material.css' from 'index.js'

If at all possible, please create a small demo app on GitHub that demonstrates the issue so it's easier for us to check and debug.

### Environment

1. Brunch: *2.10.6*
2. Node: v6.2.2
3. NPM: *4.3.0*
4. Operating system: MacOS

### `package.json` contents

```json
{
  "name": "production-manager-client",
  "version": "1.0.0",
  "description": "ui for the production manager",
  "main": "app/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://gitlab.com/srodriki/production-manager.git"
  },
  "keywords": [
    "vue",
    "brunch",
    "production",
    "management",
    "manager"
  ],
  "author": "Rodrigo Juliani <srodriki@gmail.com>",
  "license": "GPL-3.0",
  "bugs": {
    "url": "https://gitlab.com/srodriki/production-manager/issues"
  },
  "homepage": "https://gitlab.com/srodriki/production-manager#README",
  "devDependencies": {
    "babel-brunch": "^6.0.6",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-es2016": "^6.22.0",
    "babel-preset-latest": "^6.22.0",
    "brunch": "^2.10.6",
    "postcss-brunch": "^2.0.5",
    "vue-brunch": "^2.0.0",
    "vueify": "^9.4.0"
  },
  "dependencies": {
    "axios": "^0.15.3",
    "store": "^1.3.20",
    "vue": "^2.1.10",
    "vue-material": "^0.7.1",
    "vue-router": "^2.2.0",
    "vuex": "^2.1.2"
  }
}

```

### brunch config contents

```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/, // Files that are not in `app` dir.
        'app.js': /^app/
      }
    },
    stylesheets: {
      joinTo: {
        'vendor.css': /^(?!app)/
      }
    },
    templates: {
      joinTo: 'app.js'
    }
  },
  plugins: {
    babel: {
      presets: ['es2015']
    },
    vue: {
      extractCSS: true
    }
  }
}

```

### Other useful files, when present (log, `bower.json` etc.)
I've attached my whole project to help you debug. Hope it helps! 

[Archive.zip](https://github.com/brunch/brunch/files/768046/Archive.zip)

**Comment by shvaikalesh** [comment]
See `config.npm.styles`: http://brunch.io/docs/config#-npm-

We don't consider overloading js `import` for every thing like webpack does is a good idea.

**Comment by srodriki** [comment]
Thanks @shvaikalesh for your answer! I had completely forgotten about brunch 's npm configuration. That solved my issue.

**Comment by vovkats** [comment]
@srodriki Please write how you solved it with brunch ?

**Comment by meneerprins** [comment]
I normally use the sass plugin (when you use sass)

```javascript
plugins: {
    sass: {
      options: {
        includePaths: [
          'node_modules/bourbon/app/assets/stylesheets/',
          'node_modules/perfect-scrollbar/css',
          'node_modules/cropperjs/dist'
        ]
      }
    },
```

and then just in app.scss: import 'bourbon'; etc

**Comment by jrspitz** [comment]
I wanted to try out this very same vue-material library. The brunch config that worked for me:
```
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/,
        'app.js': /^app/
      }
    },
    stylesheets: {
      joinTo: {'vendor.css': /^node_modules/}
    },
    templates: {
      joinTo: 'app.js'
    }
  },
// Below is the magic.
  npm: {
    enabled: true,
    styles: {
      'vue-material': ['dist/vue-material.min.css']
    }
  },
  plugins: {
  }
}
```

Also, the babel-brunch plugin was also broken for me, so save your sanity and just use a .babelrc file instead of the broken babel-brunch plugin.
