### ISSUE TITLE
brunch build returns with segmentation fault

### ISSUE THREAD

**Issue by mlankenau** [brunch/brunch#1670]
### Description

I use brunch with elixir/phoenix. I suddenly started to crash on my main work mac book pro with a segmentation fault. I used node 7.5, tryed 7.4. and now 6.9.5. No difference they all crash. On my old mac book air it still works with node 6.5. The same setup.

### Expected behavior

It should not crash

### Environment

1. Brunch: 2.10.6
2. Node: 6.9.5
3. NPM: 3.10.10
4. Operating system: mac OS Sierra 10.12.1

### `package.json` contents

```json
{
  "repository": {},
  "license": "MIT",
  "scripts": {
    "deploy": "brunch build --production",
    "watch": "brunch watch --stdin"
  },
  "dependencies": {
    "babel-plugin-transform-runtime": "^6.15.0",
    "bootstrap-sass": "^3.3.7",
    "ekko-lightbox": "^5.0.0",
    "es6-promise": "^4.0.5",
    "extract-gettext": "0.0.4",
    "jquery": "^3.1.1",
    "moment": "^2.17.0",
    "numeral": "^2.0.4",
    "phantomjs-polyfill-object-assign": "0.0.2",
    "phoenix": "file:../../deps/phoenix",
    "phoenix_html": "file:../../deps/phoenix_html",
    "promise-polyfill": "^6.0.2",
    "sass": "^0.5.0",
    "vue": "^2.1.3",
    "vue-gettext": "^2.0.5",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.1.0",
    "vuex": "^2.0.0",
    "source-map": "mlankenau/source-map"
  },
  "devDependencies": {
    "babel-brunch": "~6.0.0",
    "brunch": "2.10.6",
    "clean-css-brunch": "~2.0.0",
    "copycat-brunch": "^1.1.0",
    "css-brunch": "~2.0.0",
    "javascript-brunch": "~2.0.0",
    "node-sass": "^3.13.0",
    "sass-brunch": "^2.9.0",
    "uglify-js-brunch": "~2.0.1",
    "vue-brunch": "^1.2.3",
    "vueify": "^9.3.0",
    "vueify-insert-css": "^1.0.0"
  }
}
```

### brunch config contents

```javascript
exports.config = {
  // See http://brunch.io/#documentation for docs.
  files: {
    javascripts: {
      joinTo: "js/app.js"

      // To use a separate vendor.js bundle, specify two files path
      // http://brunch.io/docs/config#-files-
      // joinTo: {
      //  "js/app.js": /^(web\/static\/js)/,
      //  "js/vendor.js": /^(web\/static\/vendor)|(deps)/
      // }
      //
      // To change the order of concatenation of files, explicitly mention here
      // order: {
      //   before: [
      //     "web/static/vendor/js/jquery-2.1.1.js",
      //     "web/static/vendor/js/bootstrap.min.js"
      //   ]
      // }
    },
    stylesheets: {
      joinTo: "css/app.css",
      order: {
        after: ["web/static/css/app.css"] // concat app.css last
      }
    },
    templates: {
      joinTo: "js/app.js"
    }
  },

  conventions: {
    // This option sets where we should place non-css and non-js assets in.
    // By default, we set this to "/web/static/assets". Files in this directory
    // will be copied to `paths.public`, which is "priv/static" by default.
    assets: /^(web\/static\/assets)/
  },

  // Phoenix paths configuration
  paths: {
    // Dependencies and current project directories to watch
    watched: [
      "web/static",
      "test/static"
    ],

    // Where to compile files to
    public: "priv/static"
  },

  // Configure your plugins
  plugins: {
    babel: {
      // Do not use ES6 compiler in vendor code
      ignore: [/web\/static\/vendor/]
    },
    copycat: {
      "fonts": ["node_modules/bootstrap-sass/assets/fonts/bootstrap"] // copy node_modules/bootstrap-sass/assets/fonts/bootstrap/* to priv/static/fonts/
    },
    sass: {
      options: {
        includePaths: ["node_modules/bootstrap-sass/assets/stylesheets"], // tell sass-brunch where to look for files to @import
        precision: 8 // minimum precision required by bootstrap-sass 
      }
    }
  },

  modules: {
    autoRequire: {
      "js/app.js": ["web/static/js/app"]
    }
  },

  npm: {
    enabled: true
  }
};
```

### Other useful files, when present (log, `bower.json` etc.)

  brunch:config Trying to load brunch-config +0ms
  brunch:plugins Loaded plugins: babel-brunch, copycat-brunch, css-brunch, sass-brunch, vue-brunch +674ms
  brunch:watch add package.json +19ms
  brunch:watch add brunch-config.js +1ms
  brunch:watch add web/static/css/_custom.scss +4ms
  brunch:list Reading web/static/css/_custom.scss +0ms
  brunch:watch add web/static/css/app.scss +1ms
  brunch:list Reading web/static/css/app.scss +0ms
  brunch:watch add web/static/css/phoenix.css +0ms
  brunch:list Reading web/static/css/phoenix.css +0ms
  brunch:watch add web/static/assets/favicon.ico +1ms
  brunch:list Reading web/static/assets/favicon.ico +0ms
  brunch:watch add web/static/assets/robots.txt +0ms
  brunch:list Reading web/static/assets/robots.txt +0ms
  brunch:watch add web/static/js/api.js +0ms
  brunch:list Reading web/static/js/api.js +0ms
  brunch:watch add web/static/js/app.js +1ms
  brunch:list Reading web/static/js/app.js +0ms
  brunch:watch add web/static/js/converter.js +0ms
  brunch:list Reading web/static/js/converter.js +0ms
  brunch:watch add web/static/js/event_bus.js +0ms
  brunch:list Reading web/static/js/event_bus.js +0ms
  brunch:watch add web/static/js/layout.vue +0ms
  brunch:list Reading web/static/js/layout.vue +0ms
  brunch:watch add web/static/js/router.js +0ms
  brunch:list Reading web/static/js/router.js +0ms
  brunch:watch add web/static/js/socket.js +0ms
  brunch:list Reading web/static/js/socket.js +0ms
  brunch:watch add web/static/js/translations.js +1ms
  brunch:list Reading web/static/js/translations.js +0ms
  brunch:file Init file web/static/css/app.scss +2ms
  brunch:pipeline Compiling web/static/css/app.scss @ sass-brunch +3ms
  brunch:file Init file web/static/css/phoenix.css +2ms
  brunch:pipeline Compiling web/static/css/phoenix.css @ css-brunch +1ms
  brunch:list Compiled web/static/css/phoenix.css +2ms
  brunch:asset Init asset web/static/assets/favicon.ico +1ms
  brunch:list Compiled web/static/assets/favicon.ico +1ms
  brunch:asset Init asset web/static/assets/robots.txt +0ms
  brunch:list Compiled web/static/assets/robots.txt +1ms
  brunch:file Init file web/static/js/api.js +0ms
  brunch:pipeline Compiling web/static/js/api.js @ babel-brunch +1ms
  brunch:file Init file web/static/js/app.js +285ms
  brunch:pipeline Compiling web/static/js/app.js @ babel-brunch +0ms
  brunch:file Init file web/static/js/converter.js +54ms
  brunch:pipeline Compiling web/static/js/converter.js @ babel-brunch +1ms
  brunch:file Init file web/static/js/event_bus.js +19ms
  brunch:pipeline Compiling web/static/js/event_bus.js @ babel-brunch +1ms
  brunch:file Init file web/static/js/layout.vue +9ms
  brunch:pipeline Compiling web/static/js/layout.vue @ vue-brunch +1ms
[1]    2476 segmentation fault  node node_modules/brunch/bin/brunch build -d

**Comment by paulmillr** [comment]
Unsure how to debug this...

**Comment by yavorsky** [comment]
@mlankenau  Have the same issue half a year ago. Macbook reboot helped, have you tried?

**Comment by mlankenau** [comment]
@yavorsky I just tried a reboot. Did not help.

Is there a way to get something like a stack trace or the current action that brunch is doing to debug that?

**Comment by paulmillr** [comment]
Try reducing the problem to a single plugin. For example, by removing every plugin from `package.json` until some point.

There is no way to get a stack trace, because segfault is a node.js process error — not brunch error. Brunch cannot control what happens when it happens.

This is really a node error — so please report it to node.js bugtracker.

**Comment by mlankenau** [comment]
@paulmillr Thx for the hint. That helped alot. It turned out to be an issue with vueify. A Version uprade fixed the issue.
Thx alot.
