### ISSUE TITLE
Sass brunch emits 0 exit status even if build failed

### ISSUE THREAD

**Issue by lessless** [brunch/brunch#1671]
### Description

When `brunch build` command fails, a `0` exit status is returned

```
$ brunch build
13 Feb 17:29:38 - info: compiling
13 Feb 17:29:42 - info: compiling.
13 Feb 17:29:44 - error: Invalid mapping: {"generated":{"line":3190,"column":23},"source":"node_modules/foundation-sites/scss/grid/_layout.scss","original":{"line":46,"column":-19},"name":null}

$ echo $?
0
```

### Expected behavior

If build fails a non-zero exit status should be emitted to the shell

### Actual behavior

A zero exit status is returned despite build failure

https://github.com/lessless/brunch-build-exit-status

### Environment

1. Brunch: 2.10.6
2. Node: 6.9.4
3. NPM: 3.10.10
4. Operating system: OS X El Capitan

**Comment by denysdovhan** [comment]
Hi @lessless! Thanks for your repo, I'm currently trying to reproduce and fix your problem.

**Comment by denysdovhan** [comment]
Hmmm, works fine for me.

![image](https://cloud.githubusercontent.com/assets/3459374/22972701/76782ab4-f383-11e6-8aa5-496b1c6ab079.png)

**Comment by lessless** [comment]
Hello @denysdovhan! Try to rollback to the first commit and please let me know if that helps.

**Comment by paulmillr** [comment]
@lessless reverting back allowed me to reproduce the issue; nevertheless it's related to Brunch 2.9.

Does it also appears with a new Brunch for you?

**Comment by lessless** [comment]
@paulmillr I cannot tell whether build task return zero or not in 2.10 because of this particular scenario doesn't trigger a failure after the update.

**Comment by paulmillr** [comment]
@lessless it may be possible it happened when you've updated your global brunch to 2.10 while keeping the local one on 2.9.

Closing the issue as unreproducible for now. Please keep me posted.
