### ISSUE TITLE
Passing -e flag during build/watch doesn't work since 2.9.1

### ISSUE THREAD

**Issue by maxtacco** [brunch/brunch#1675]
### Description
After upgrading Brunch from 2.9.1 to 2.10.x "-e" (environment) flag stopped working as expected.

Specifically we use constangular-brunch plugin to add Angular config modules during build time. After upgrading to 2.10.x we can see that config.env array variable used in plugin's code contains "development" as the first element and the environment passed using "-e" flag as the second element. As a result plugin uses "development" instead of the actual environment being passed.

### Expected behavior

There should be no "development" element present in the config.env array unless it is specified or "-e" flag should override it.

### Environment

1. Brunch: 2.10.x (tried 2.10.0 and 2.10.8)
1. Node.js: 7.2.0
1. NPM: 3.10.9 
1. Operating system: MacOs Sierra (12.10.3)
1. Code editor: IntelliJ Idea

### `package.json` contents

{
  ...  
  "dependencies": {
        "after-brunch": "0.0.5",
        "clean-css-brunch": "2.0.0",
        "coffee-script-brunch": "2.1.0",
        "constangular-brunch": "0.1.4",
        "css-brunch": "2.6.1 ",
        "less-brunch": "2.7.1",
        "javascript-brunch": "2.0.0",
        "jshint-brunch": "2.0.0",
        "sass-brunch": "2.7.0",
        "uglify-js-brunch": "2.0.1"
    }
}

**Comment by shvaikalesh** [comment]
Should be fixed by 1664

**Comment by maxtacco** [comment]
Thank you!

**Comment by shvaikalesh** [comment]
Hey @maxtacco, sorry for the delay. Indeed, we've added `NODE_ENV` support (along with `BRUNCH_ENV`) and `env` was broken. Thanks a lot for reporting. It would be great if you could check your workflow with latest commit in `"hellyeahllc/brunch#new-workers"`.

**Comment by maxtacco** [comment]
Hi  @shvaikalesh, I checked out that branch and everything seems to work now. Thanks a lot!

**Comment by maxtacco** [comment]
Hi,
Is it possible to merge this into master and release? Thanks you.
