### ISSUE TITLE
configure directory structure?

### ISSUE THREAD

**Issue by saun4app** [brunch/brunch#1676]
### Description

How do we configure directory structure?

Ex.  `src/app` instead of `app'.

### Expected behavior

I came across `brunch' yesterday, looks very impressive.  I expected `brunch` or  `skeleton`  allows directory structure configuration, but did not find document or examples for specifying project directory structure. 

Please point me to the document or an example.  Thank you very much.

**Comment by stelmakh** [comment]
Hi, please look into brunch config documentation. http://brunch.io/docs/config
I believe the setting you're looking for is watched directories list

```
paths: {
  watched: ['src']
}
```

**Comment by shvaikalesh** [comment]
And the `nameCleaner` thing too.

**Comment by saun4app** [comment]
@stelmakh and @shvaikalesh,  

Thank you very for your prompt and informative replies.  I will need the information about `paths` and `nameCleaner`.  Your replies also help be clarify my own question:

How to setup a `skeleton`  to produce a custom directory structure? 

Here is `https://github.com/brunch/with-es6/blob/master/brunch-config.js`:
```
exports.files = {
  javascripts: {
    joinTo: {
      'vendor.js': /^(?!app)/, // Files that are not in `app` dir.
      'app.js': /^app/
    }
  },
  stylesheets: {joinTo: 'app.css'}
};

exports.plugins = {
  babel: {presets: ['latest']}
};
```

How do we change the `brunch-config.js` so that the app directory structure:

```
── src
|   ├── app
|   |   └── assets
|   |   └── module
|   |   └── initialize.js
|   |   └── styles.css
```
or

```
── src
|   └── module
|   ├── app
|   |   └── assets
|   |   └── initialize.js
|   |   └── styles.css

```
Thank you again.

**Comment by denysdovhan** [comment]
@saun4app please, read [Conventions section](http://brunch.io/docs/config#-conventions-) from Brunch docs. You're looking for:

* `paths.watched`
* `conventions.assets`
* `conventions.vendor`

Also, notice:

> If you need to change the default directory for application's code, don't forget to add this directory to the watched field, like so:
> ```js
> paths: {
>  watched: ['src']
> }
> ```
> Also, consider [`module.nameCleaner` option](http://brunch.io/docs/config#-modules-), if you need to require your modules without prefixing with folder name.
>
> — **Brunch docs**
