### ISSUE TITLE
Allow files depend on assets

### ISSUE THREAD

**Issue by shvaikalesh** [brunch/brunch#1677]
Use case:

`component.css`:

```css
background: svg-load("icon.svg");
```

Brunch does not consider `icon.svg` a dependency. We need to expose API (additional props in `dependencies`; not "completely new thing") to allow this.

**Comment by denysdovhan** [comment]
Probably related to [progeny](https://github.com/es128/progeny). Should it be part of it?

**Comment by shvaikalesh** [comment]
Not related. `progeny` should be dropped from `postcss-brunch`.
