### ISSUE TITLE
How can i use this as compiler for site

### ISSUE THREAD

**Issue by dalisoft** [brunch/brunch#1678]
Hi. Thanks for amazing app.
I'm now using Webpack, works good. But very hard to learn to add loader, takes much of size because of many modules requirement. But compiling for site not works as excepted, so i finding other.

Why i need compiler and for what?
```javascript
// My working dir
- source [css (postcss), js (es6), ...html (handlebars or pug)]
// and i am want to export
- dist [css (.css), js (es5, es3 if possible for support to ie8+), ...html (default html)]
```

This is possible with Brunch? and how?

Thanks

**Comment by dalisoft** [comment]
I now realised that Webpack community better than Brunch and why Webpack so pupular? Answer: community (even only author can be answer for questin would be nice)

**Comment by paulmillr** [comment]
brunch new dir -s es6
cd dir
npm install --save-dev handlebars-brunch postcss-brunch
brunch watch --server

**Comment by dalisoft** [comment]
Thanks for reply

**Comment by dalisoft** [comment]
Thanks to @denysdovhan and @paulmillr. My mind changed, Brunch has awesome devs

**Comment by denysdovhan** [comment]
You're welcome @dalisoft 👍🏻
