### ISSUE TITLE
How to initialize script without requiring for security and performance

### ISSUE THREAD

**Issue by dalisoft** [brunch/brunch#1680]
### Description

How to initialize script without requiring for security and performance?

* Make just one request to script tag
* Initialize immediately
* Require script avoid (possible? for one request script tag)

### Actual behavior

Requires `require` code, but i don't want it.

If at all possible, please create a small demo app on GitHub that demonstrates the issue so it's easier for us to check and debug.

### Environment

1. Brunch: *(make sure you're on the latest release!)* YES
1. Node.js: *not sure*, v6+
1. NPM: *(npm v2 is not supported)*
1. Operating system: Windows 7 Ultimate (32-bit 2x CPU Intel)
1. Code editor: Brackets

### `package.json` contents

```json
{
  "name": "shavkatoff.com",
  "version": "0.0.0-development",
  "description": "Site of shavkatoff.com and their builder",
  "main": "public/app.js",
  "scripts": {
    "start": "brunch watch --server",
    "prod": "brunch build --production"
  },
  "devDependencies": {
    "auto-reload-brunch": "latest",
    "babel-brunch": "latest",
    "babel-preset-es2015": "latest",
    "brunch": "latest",
    "clean-css-brunch": "latest",
    "css-brunch": "latest",
    "css-mqpacker": "latest",
    "handlebars-brunch": "^2.10.0",
    "javascript-brunch": "latest",
    "npm": "latest",
    "postcss-brunch": "latest",
    "postcss-cssnext": "latest",
    "postcss-short": "latest",
    "postcss-size": "latest",
    "precss": "latest",
    "uglify-js-brunch": "latest"
  },
  "author": "dalisoft",
  "license": "GPL-3.0",
  "dependencies": {}
}

```

### brunch config contents

```javascript
exports.config = {
	files: {
		javascripts: {
			joinTo: {
				'assets/js/app.js': /^app*/
			}
		}
		, stylesheets: {
			joinTo: {
				'assets/css/app.css': /^app*/
			}
		}
        , templates: {
				'assets/js/app.js': /^app*/
			}
	},

	paths: {
		public: './public/'
	},

	plugins: {
		babel: { presets: [ 'latest', 'react' ] }
		, postcss: {
			processors: [ require( 'precss' )
		, require( "postcss-cssnext" )
		, require( 'postcss-size' )
		, require( 'postcss-short' )
		, require( 'css-mqpacker' ) ]
		},
        handlebars: {
				locals: {
					title: 'Brunch is awesome!',
                    body: 'How it was good'
				}
			}
	}
};
```

### Other useful files, when present (log, `bower.json` etc.)

If there's an unexpected error during `brunch build`/`brunch watch`, please attach the compilation log with the debug flag (`-d`) **and** stack traces enabled (`export LOGGY_STACKS=true`).

If something worked with previous versions of brunch, but stopped with a newer one, please include these details as well.

**Comment by denysdovhan** [comment]
Hi, @dalisoft!

I'm trying to help you with your problem. Could you help me and create a repo that reproduce your troubles with Brunch?

**Comment by denysdovhan** [comment]
Hi, @dalisoft and thanks for reaching us out!

Take a look at [`modules.autoRequire` option](http://brunch.io/docs/config#-modules-) in Brunch config.

> please create a small demo app on GitHub that demonstrates the issue

Sure, here it is: https://github.com/denysdovhan/brunch-issue-1680. The most important lines is [auto-requiring of `initialize` module in `app.js` file](https://github.com/denysdovhan/brunch-issue-1680/blob/master/brunch-config.js#L12-L16).

I'm closing this issue. Feel free to ask, if you still have questions.

**Comment by dalisoft** [comment]
Wow. it works. Thanks a lot.
Its now better. Now i have single-packed CSS and JS (nice and fast).

And i am have some question:

- There i can disable CSS source-mapping?
- Looking at [at here](https://github.com/colinmeinke/svg-points) i am see that there no bundled file, but works via `unpkg` nice. ES6 imports too suported, i am too trying to get like that, but not works.

I have just these 2-question now, Thanks for reply.

**Comment by paulmillr** [comment]
sourceMaps: false

not sure what you mean by the 2nd question

**Comment by shvaikalesh** [comment]
on 2nd: Brunch is not quite intended for `npm` packages, it was created for apps. So you can't do umd that `unpkg` needs. That sucks, but we are planing on fixing it in `3.0`. Sadly, can't share any release dates.

**Comment by dalisoft** [comment]
Thanks for reply. I am already configured sourceMaps. On second question i no need now as require works best.
