### ISSUE TITLE
Better `now` integration

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#1681]
Would be great to have stuff auto-built like in https://gist.github.com/rauchg/243c5109c793bf09c052

**Comment by colinbate** [comment]
`now` will run a `build` (or `now-build`) npm script as part of the deploy. So you can run brunch there, and then you can use their static [`serve`](https://www.npmjs.com/package/serve) package (or another similar one) as your npm `start` (or `now-start`) script. They discuss this here: https://zeit.co/blog/now-static
