### ISSUE TITLE
Brunch throws on CSS imports w/o css-modules

### ISSUE THREAD

**Issue by denysdovhan** [brunch/brunch#1684]
### Description

Brunch doesn't require CSS. In projects like [Spectacle](https://github.com/FormidableLabs/spectacle) there are [`require`s like these](https://github.com/FormidableLabs/spectacle/blob/master/src/components/component-playground.js#L26-L30):

```
  if (useDarkTheme) {
    require("../themes/default/dark.codemirror.css");
  } else {
    require("../themes/default/light.codemirror.css");
  }
```

Brunch can't handle such `require`s, so it fails:

![image](https://cloud.githubusercontent.com/assets/3459374/24051430/bbd2b68c-0b3a-11e7-8436-ab7ac6e2aca9.png)

Quite confusing, because it's problem with vendor not with my code itself.

### Expected behavior

When Brunch meet styles `require`, then `require` should return a string with styles (?) or css-modules object (if they are enabled) and empty object (if they are disabled). I think it have to be discussed.

### Actual behavior

Style modules isn't defined and JS errors occurs.

### Other useful files, when present (log, `bower.json` etc.)

* Also mentioned in brunch/brunch#1473
* Related issue in FormidableLabs/spectacle#291

**Comment by shvaikalesh** [comment]
Use case for string:

```js
import css from './style.css'

class MyElement extends HTMLElement {
  constructor() {
    this.attachShadow({mode: 'open'}).innerHTML = `
      <style>${css}</style> ...`
  }
}

**Comment by denysdovhan** [comment]
@shvaikalesh by now, problem is particularly solved for me with [raw-brunch](https://github.com/denysdovhan/raw-brunch) (in case with Markdown files).

> Question is to whether do this for `.css` or any file.

I think it would be better to do it for any file to let us ability to require any type of file, like Webpack do. For example, it's especially useful to do things like [this](https://github.com/denysdovhan/slides-feel-good-with-brunch/blob/master/app/presentation/index.js#L270-L274). Anyway, it should be discussed.

**Comment by kockok** [comment]
I cannot require css even though `postcss-brunch` is installed. Or brunch will NEVER be able to require css?

**Comment by shvaikalesh** [comment]
@kockok Make sure you have css modules enabled.

**Comment by kockok** [comment]
@shvaikalesh 
```
exports.plugins = {
  babel: {presets: ['latest', 'react']},
  postcss: {
    modules: true,
    processors: [
      require('autoprefixer')(['last 8 versions']),
      require('csswring')()
    ]
  }
};
```
Is this the way to enable it?
