### ISSUE TITLE
Getting errors when building a dependency's sources for my app

### ISSUE THREAD

**Issue by rjulianialtimetrik** [brunch/brunch#1687]
### Description

I've written a VueJS plugin ( [animated-vue](https://www.npmjs.com/package/animated-vue) and, by recommendation, I just added its source files to npm. When I try to add it as a dependency in another project, a web app I'm building, I get the following error: 

```shell
Processing of node_modules/animated-vue/src/index.js failed. SyntaxError: 'import' and 'export' may only appear at the top level (5:4)
```

Which means brunch is somewhat not transpiling the code... for my module alone. Any ideas how to fix that?

### Expected behavior

The module is compiled by brunch normally

### Actual behavior

```shell
Processing of node_modules/animated-vue/src/index.js failed. SyntaxError: 'import' and 'export' may only appear at the top level (5:4)
```

### Environment

1. Brunch: Latest
1. Node.js: 6.9.5
1. NPM: 3.10.10
1. Operating system: MacOSX
1. Code editor: Atom

### `package.json` contents

```json
{
  "name": "wannaworkthere",
  "version": "1.0.1",
  "description": "UI for the wannaworkthere package",
  "main": "public/app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "brunch w --server",
    "build:local": "brunch b",
    "build:production": "PRODUCTION=true brunch b --production"
  },
  "repository": {
    "type": "git",
    "url": "git+https://gitlab.com/srodriki/wannaworkthere.git"
  },
  "keywords": [
    "vue",
    "brunch",
    "vuex",
    "vue-router"
  ],
  "author": "Rodrigo Juliani <srodriki@gmail.com>",
  "license": "MIT",
  "bugs": {
    "url": "https://gitlab.com/srodriki/wannaworkthere/issues"
  },
  "homepage": "https://gitlab.com/srodriki/wannaworkthere#README",
  "devDependencies": {
    "babel-brunch": "^6.0.6",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-es2016": "^6.22.0",
    "babel-preset-latest": "^6.22.0",
    "babel-preset-stage-3": "^6.22.0",
    "brunch": "^2.10.6",
    "copycat-brunch": "^1.1.0",
    "process-env-brunch": "^1.4.5",
    "sass-brunch": "^2.10.4",
    "vue-brunch": "^2.0.0"
  },
  "dependencies": {
    "animate.css": "^3.5.2",
    "animated-vue": "^0.1.5",
    "axios": "^0.15.3",
    "bulma": "^0.3.2",
    "font-awesome": "^4.7.0",
    "izitoast": "^1.1.1",
    "moment": "^2.17.1",
    "store": "^1.3.20",
    "vee-validate": "^2.0.0-beta.25",
    "vue": "^2.1.10",
    "vue-router": "^2.2.0",
    "vuex": "^2.1.2"
  }
}

```

### brunch config contents

```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/, // Files that are not in `app` dir.
        'app.js': /^app/
      }
    },
    stylesheets: {
      joinTo: 'app.css'/*{
        'vendor.css': /^(?!app)/,
        'app.js': /^app/
      }*/
    },
    templates: {
      joinTo: 'app.js'
    }
  },
  plugins: {
    babel: {
      presets: ['latest', 'stage-3']
    },
    vue: {
      extractCSS: false
    },
    sass: {
      mode: "native",
      precision: 8,
      options: {
        includePaths: [
          'node_modules/bulma'
        ]
      }
    },
    copycat: {
      'fonts': ['node_modules/font-awesome/fonts']
    }
  },
  npm: {
    styles: {
      'izitoast': ['dist/css/iziToast.css'],
      'font-awesome': ['css/font-awesome.css'],
      'animate.css': ['animate.css']
    }
  }
}
```

Any help is much appreciated!

**Comment by shvaikalesh** [comment]
Hey @rjulianialtimetrik, thanks for the issue.

We are implementing compiler chaining to support such use cases without extra config, but it is not ready yet. For now, you can set `plugins.babel.pattern` to include `.vue`

**Comment by rjulianialtimetrik** [comment]
@shvaikalesh Thanks a lot for your answer. Actually the code for my plugin does not involve .vue files, they are all plain javascript files with a .js extension. All vue components built inside **animated-vue** are functional components. 

Just for testing purposes, I added the dependency to a project that uses webpack for building, replicated the same code I had that made use of it, and was able to use the library without issues.

Could this be something missing in my brunch-config? Maybe I'm missing some settings that makes babel process also files found under node_modules?

**Comment by colinbate** [comment]
@rjulianialtimetrik I think the issue is that your `main` property in `package.json` points to `src\index.js` and so this is the entry point that brunch is probably trying to use. When publishing to npm, you should generally point to your dist version. You may also provide a version which uses ES modules for those bundlers which support tree shaking, but you would point to that using the `module` property.
