### ISSUE TITLE
 Allow to Override NODE_ENV variable value  if  NODE_ENV has a value in --production

### ISSUE THREAD

**Issue by jitsu553** [brunch/brunch#1692]
Running Command `brunch build -p` or `brunch build --production` overrides the assigned NODE_ENV value to 'production'.

i have two different brunch configurations and  separate NODE_ENV environment value for each configs which runs on same command , so executing it  always reads the brunch.config from the production part 

Environment

Brunch: 2.10.9
Node: v5.7.1
NPM: v3.6.0
Operating system: Ubuntu 14.04

**Comment by denysdovhan** [comment]
@jitsu553 thank you for reaching us out!

Try to use [`overrides` option](http://brunch.io/docs/config#-overrides-) in `brunch-config.js`. It alternates config settings to activate via command line switches, like this:

```sh
brunch watch --env testing
BRUNCH_ENV=testing brunch build
NODE_ENV=production brunch build
```

**Comment by shvaikalesh** [comment]
Hey @jitsu553, thanks for reporting.

Indeed, recent versions of Brunch set `NODE_ENV` variable. Reverted by #1664.

//cc @IvanSanchez
