### ISSUE TITLE
Cannot Import Nested Modules

### ISSUE THREAD

**Issue by awwong1** [brunch/brunch#1695]
### Description

Discovered when working with [redux-saga](https://github.com/redux-saga/redux-saga). Cannot import on nested node module. Possibly related to this issue? https://github.com/christianalfoni/webpack-bin/issues/64

### Expected behavior

```js
import { take, call, put, fork, race } from 'redux-saga/effects';
// allows me to use take, call, put, fork, race in my code
```

### Actual behavior

```js
import { take, call, put, fork, race } from 'redux-saga/effects';
// Uncaught Error: Cannot find module 'redux-saga/effects' from 'js/sagas/index.js'
```

However, when I import without nested call, everything is fine:

```js
import { effects } from 'redux-saga';
// calling my methods effects.take, effects.call, etc.
```

Full project and effected file can be found at [js/sagas/index.js](https://github.com/udia-software/udia/blob/v0.2.0/assets/js/sagas/index.js)

### Environment

1. Brunch: *2.10.9*
1. Node.js: *v6.9.4*
1. NPM: *3.10.10*
1. Operating system: OSX El Capitan 10.11.6
1. Code editor: Visual Studio Code 1.11.1

### `package.json` contents

```json
{
  "name": "udia",
  "version": "0.0.0",
  "description": "Universal Dream, Infinite Awareness",
  "repository": {
    "type": "git",
    "url": "https://github.com/udia-software/udia.git"
  },
  "private": true,
  "license": "CPAL-1.0",
  "scripts": {
    "deploy": "brunch build --production",
    "watch": "brunch watch --stdin",
    "eslint": "eslint js"
  },
  "dependencies": {
    "babel-polyfill": "^6.23.0",
    "phoenix": "file:../deps/phoenix",
    "phoenix_html": "file:../deps/phoenix_html",
    "prop-types": "^15.5.4",
    "react": "^15.5.3",
    "react-dom": "^15.5.3",
    "react-redux": "^5.0.3",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0",
    "redux": "^3.6.0",
    "redux-logger": "^3.0.1",
    "redux-saga": "^0.14.6",
    "semantic-ui-react": "^0.67.2"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.7.1",
    "babel-brunch": "6.1.1",
    "babel-eslint": "^7.2.1",
    "babel-preset-env": "^1.3.3",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-1": "^6.24.1",
    "brunch": "2.10.9",
    "clean-css-brunch": "2.10.0",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-react": "^6.10.3",
    "hmr-brunch": "^0.1.1",
    "localStorage": "^1.0.3",
    "uglify-js-brunch": "2.10.0"
  }
}
```

### brunch config contents

```javascript
exports.config = {
  // See http://brunch.io/#documentation for docs.
  files: {
    javascripts: {
      joinTo: 'js/app.js',
    },
    stylesheets: {
      joinTo: 'css/app.css',
    },
    templates: {
      joinTo: 'js/app.js',
    },
  },

  conventions: {
    assets: /^(static)/,
  },

  paths: {
    watched: ['static', 'css', 'js', 'vendor'],
    public: '../priv/static',
  },

  plugins: {
    babel: {
      presets: ['env', 'stage-1', 'react'],
      ignore: [/vendor/],
    },
  },

  modules: {
    autoRequire: {
      'js/app.js': ['js/index'],
    },
  },

  npm: {
    enabled: true,
  },

  // Hot module reloading
  hot: true,
};
```

**Comment by denysdovhan** [comment]
Hi, @awwong1! Thanks for reaching us out!

I'm guessing that's the [`deppack`](https://github.com/yavorsky/deppack)-related issue. Trying to figure out what's the cause of problem.

Thanks for reference to https://github.com/christianalfoni/webpack-bin/issues/64!

**Comment by denysdovhan** [comment]
@awwong1 as a hotfix, try this:

```diff
- import { take, call, put, fork, race } from 'redux-saga/effects'
+ import { take, call, put, fork, race } from 'redux-saga/lib/effects'
```

The cause is, probably, strange project structure of `redux-saga` (in `effects` folder we have another `package.json`).

**Comment by Andarist** [comment]
@denysdovhan that is certainly the culprit. However as strange as it might looks like it allows such 'subpackages' and it is valid usage, node's resolution algorithm understands this just fine.

How do you resolve npm modules in `brunch`?

**Comment by tcrossland** [comment]
@awwong1 @denysdovhan Another workaround for this specific issue is to create an alias in `brunch-config.js` (for example: https://github.com/tcrossland/spacy-annotator/commit/56fca1ac0721f20f439b8686aecab541479e8fc9#diff-cf6d64b6ab9de528b5d0ed6c5db05f3a)

**Comment by Andarist** [comment]
is `brunch` es6 modules aware? What types of modules can it consume by default? cjs/umd only?

**Comment by pmyjavec** [comment]
Thanks @tcrossland, elegant workaround!

**Comment by explicitcall** [comment]
Is this going to be fixed or at least looked at? I've stumbled upon this with a library that imports `redux-saga/effects` submodule, not feasible to apply this workaround to code I don't own and I certainly don't want to switch to webpack just because of this issue.

**Comment by shvaikalesh** [comment]
Yes, it is in the works: #1664

**Comment by kavdev** [comment]
Should this work out of the box with v3? I'm having issues, specifically with ``import Creatable from "react-select/creatable"``

Relevant Resources:
* https://github.com/JedWatson/react-select
* https://github.com/JedWatson/react-select/tree/master/packages/react-select/creatable
* https://github.com/JedWatson/react-select/issues/3585 ("Multiple Entrypoints" section)

**Comment by jngbng** [comment]
@kavdev still does not works with v3.

**Comment by kavdev** [comment]
@jngbng yep, but I have another workaround that works surprisingly well. Any time there's a "cannot find module" error, I add it to a list of aliases in my brunch-confi.js npm export.

e.g. for an error that just came up for me after updating babel: `Cannot find module '@babel/runtime/helpers/extends/_index.mjs' from '@babel/runtime/helpers/esm/extends.js'`,

I have:

```javascript
exports.npm = {
    "compilers": ["babel-brunch"],
    "aliases": {
        "@babel/runtime/helpers/extends/_index.mjs": "@babel/runtime/helpers/extends",
    },
}
```

This example's not exactly the same as my earlier one, but it's the same concept of imports/exports in submodules not working as expected (babel has a redirect from helpers/extends to helpers/esm/extends back to helpers/extends). Anyway, this might be helpful for people running into a similar issue.

**Comment by Andarist** [comment]
@kavdev have you tried Babel 7.13.2? It might have been fixed there (the problem was probably introduced in 7.13.0)

**Comment by kavdev** [comment]
@Andarist I've looked through the changelog and it seems you might be correct. There are 4 bugfix releases on that specific issue 😄 

I'll test when the latest babel is released. This means then that this might be more of a package-by-package issue where each package is doing some funky module exporting.
