### ISSUE TITLE
Newly added npm modules can not be found

### ISSUE THREAD

**Issue by maxleistner** [brunch/brunch#1697]
### Description

I tried to add several npm modules like for example "masonry-layout" or "touchswipe". I did so by adding the module to the package.json. The module will be installed on the next brunch watch. After that i added the following code to initialize.js --> `require('masonry-layout);`, just underneath `var $ = require('jquery');`
Then i added my own code:
```
$(document).ready(function(){
 console.log('TEST');
$('#grid').masonry();
});
```
### Expected behavior

What should have happened is, that the masonry function works after brunch watch save. 

### Actual behavior

What happens is, that in vendor.js the masonry-layout script is successfully included and loads before the app.js. BUT i get the error, that the .masonry function can not be found, as it would not have been included. How can i include an npm module and use it via jquery in my initialize.js??

### Environment

1. Brunch: 2.10.9
1. Node.js: v6.10.0
1. NPM: 3.10.10
1. Operating system: Mac Sierra
1. Code editor: PHPStorm

### `package.json` contents

```{
  "name": „projectname“,
  "description": „Projectname“,
  "private": true,
  "author": „author name“,
  "version": "0.0.1",
  "repository": "",
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "jquery": "latest",
    "touchswipe": "latest",
    "masonry-layout": "latest"
  },
  "devDependencies": {
    "auto-reload-brunch": "latest",
    "babel-brunch": "~6.0",
    "babel-preset-latest": "^6",
    "brunch": "^2",
    "clean-css-brunch": "^2",
    "jshint-brunch": "latest",
    "sass-brunch": "latest",
    "static-handlebars-brunch": "latest",
    "uglify-js-brunch": "^2"
  }
}

```

### brunch config contents

```// See http://brunch.io for documentation.
exports.files = {
    javascripts: {
        joinTo: {
            'vendor.js': /^(?!app)/, // Files that are not in `app` dir.
            'app.js': /^app/
        },
    },
    stylesheets: {
        joinTo: 'app.css'
    }
};

exports.plugins = {
    sass: {
        mode: 'ruby',
        allowCache: true,
        sourceMapEmbed: true
    },
    jshint: {
        pattern: /^app[\\\/].*\.js$/,
        options: {
            bitwise: true,
            curly: true
        },
        globals: {
            jQuery: true
        },
        warnOnly: true
    }
};


```

### Other useful files, when present (log, `bower.json` etc.)

console log :

```
Uncaught TypeError: $(...).masonry is not a function
```

**Comment by maxleistner** [comment]
Still waiting for an answer... @paulmillr

**Comment by sheriffderek** [comment]
How are you loading the scripts?
