### ISSUE TITLE
Brunch Plugin-API faulty

### ISSUE THREAD

**Issue by max-scopp** [brunch/brunch#1704]
### Description

Quoted from **official** docs:

```
 // file: File => Promise[Array: Path]
  // Allows Brunch to calculate dependants of the file and recompile them too.
  // Examples: SASS '@import's, Jade 'include'-s.
  // getDependencies(file) { return Promise.resolve(['dep.js']); }
```

This means, if I have a SASS submodule with the path `my/sub/_module.scss` and `getDependencies` returns a path to the parent file, the Plugin's compile function is required to be re-called, if other dependant where returned.

### Expected behavior

1. Compile
2. fetch dependants
3. call the Plugin's compile function and with the proper dependant path.

### Actual behavior

1. Compiles
2. fetch Dependencies
3. Log's that it should compile a path (with the old path from 1.)
4. Doesn't call Plugin's compile function and does nothing

I attached a log with official brunch log's, capitalized words are to clarify the internal problem

### Environment

1. Brunch: latest, 2.10.9
1. Node.js: 6.10.0
1. NPM: 4.5.0 (also using yarn, 0.23.3
1. Operating system: OS X
1. Code editor: various

### brunch config contents

Generated dynamically.

**Comment by shvaikalesh** [comment]
Hey @max-scopp, thanks for the issue.

`getDependencies` should return children paths, not parents'. This allows Brunch to recompile parents:

```js
  // `path` is changed file's path, passed by watcher
  _compileParents(path) {
    const isParent = file => {
      return !this._compiled.has(file.path) &&
        anymatch(file.dependencies, path);
    };

    this._files.forEach(file => {
      if (isParent(file)) this._compile(file);
    });
  }
```
