### ISSUE TITLE
Brunch entry points and auto reload plugin problem

### ISSUE THREAD

**Issue by happyCoda** [brunch/brunch#1705]
### Description

I am using brunch configured to use `entryPoints` instead of `joinTo`. And I am using brunch auto reload plugin. When I run `brunch w -s` I get:
```
09:44:24 - info: application started on http://localhost:3333/
09:44:25 - warn: node_modules/auto-reload-brunch/src/auto-reload.js compiled, but not written. Check your javascripts.joinTo config
09:44:25 - info: compiled 5 files into 2 files, copied index.html in 1.0 sec
```
So auto reload does not working. However, if I use `joinTo` auto reload works well.

Is it a problem with this specific plugin or there something wrong with `entryPoints` entirely?

### Environment

1. Brunch: *2.10.9*
1. Node.js: 7.10.0
1. NPM: *4.5.0*
1. Operating system: OS X Yosemite 10.10.5
1. Code editor: Atom

### `package.json` contents
```json
{
  "name": "vagrant_and_brunch",
  "version": "0.1.0",
  "description": "vagrant & brunch",
  "main": "index.js",
  "dependencies": {
    "jquery": "^3.2.1"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.7.1",
    "babel-brunch": "^6.1.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "less-brunch": "^2.10.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "vagrant",
    "brunch",
    "bundling",
    "js"
  ],
  "author": "happyCoda",
  "license": "MIT"
}
```

### brunch config contents

```javascript
module.exports = {
  paths: {
    watched: ['js', 'css', 'static']
  },
  files: {
    javascripts: {
      entryPoints: {
        'js/app.js': 'js/bundle.js'
      }
    },
    stylesheets: {
      joinTo: 'css/bundle.css'
    }
  },
  modules: {
    autoRequire: {
      'js/bundle.js': ['js/app']
    }
  },
  conventions: {
    assets: /static\//
  }
};
```

**Comment by beznosd** [comment]
Hi, @happyCoda! Thanks for noticing

Yes, the only required piece of configuration is telling Brunch which output files you want.
`joinTo` is required option.

Please see [Brunch core concepts](http://brunch.io/docs/concepts) and description of [files setting](http://brunch.io/docs/config#-files-) for more details.

**Comment by happyCoda** [comment]
@beznosd, of course I did read the docs. But what I did not understand is `entryPoints` are alternative to `joinTo` or it has to be used together? Accordingly to this [issue](https://github.com/brunch/brunch/issues/1323) it is an alternative. But docs says that `joinTo` is required option. And more that that, if I use them together like so:
```javascript
javascripts: {
  joinTo: {
    'js/bundle.js': /^js\/src/
  },
  entryPoints: {
    'js/src/app.js': 'js/bundle.js'
  }
}
```
everything works great. But isn't brunch do double work in that case?

**Comment by beznosd** [comment]
@happyCoda, yeah, it's make sense. I have done some tests and yes, in case you have provided above Brunch is doing a double work. And in this case `entryPoints` and `joinTo` are an alternative of each other.

With `joinTo` we can do the same things as with `entryPoints`.

I think we can use `joinTo` for main build and `entryPoints` for additional handling of separate files or a small bunch of files if we do need that, just to keep our config clear and and don't dump all the things in one place ( `joinTo`).

Maybe i am not right, @shvaikalesh, what do you think about this?

**Comment by happyCoda** [comment]
@beznosd thanks for this information! As far as I understand, `joinTo` just concat all js files resides in `app/` folder (or whatever folder you specify in `watched`). On the other side, `entryPoints` works with dependencies, so you just specify an entry point script and brunch then build a dependency tree and include all modules in one file. The same way tools like **browserify** or **requirejs** work.

All in all, if I use only `joinTo `, I can not use npm modules in my applicatiion, because they won't be included in the build. So I have to use `vendor` which will contain my npm modules. But this is not the behaviour I want to achieve. I need all my code and third party modules to be included in the build, and `entryPoints` does the trick. Except one thing - the problem with the auto-reload plugin. And I assume, that this is not the only plugin, which cause such problem.

So, any thoughts on this issue?

**Comment by happyCoda** [comment]
Well, that looks like if I change regex from `/^js\/src/` to `/^(js\/src|(.|\/)*node_modules)/` in `joinTo`, all my modules from npm are included as well as auto-reload plugin. And that's really interesting since docs says on `joinTo`:

joinTo: (required) describes how files will be compiled & joined together. Available formats:

- 'outputFilePath' in order to have all source files compiled together to one
- map of 'outputFilePath' (see Pattern matching section)

So this

> all source files compiled together to one

is a bit misleading because I thought that this option just does concatenation of js files in folders matched to regex.

**Comment by beznosd** [comment]
Yes, Brunch handles all source files including dependencies from `node_modules` with `joinTo` and with `entryPoints` too.
