### ISSUE TITLE
brunch --production seems to have an unexpected fsevents dependency

### ISSUE THREAD

**Issue by macta** [brunch/brunch#1709]
When using brunch in a gitlab pipeline I am seeing a warning about fsevents eg.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

Looking at my npm dependencies it seems like brunch is pulling in chokidar - but I don't understand why this isn't marked as a dev dependency? It should't be needed when trying to create a production build should it?

$ npm list --production fsevents
metalsmith-mtt@0.0.1 /proj
└─┬ brunch@2.10.9
  └─┬ chokidar@1.6.1
    └── fsevents@1.1.1

**Comment by shvaikalesh** [comment]
Hey @macta, thanks for the issue.

Indeed, `chokidar` is not necessary. In `3.0`, it won't be event `require`d for `--production` builds. However, I don't see a net way to not install it for `--production` and to not require end users to specify it in their `package.json`s.

If there are any ways to achieve it, I would love to hear. Thanks.

**Comment by macta** [comment]
I'm still quite new to nodejs development, but can't you just add chokidar as a development dependency in package.json, and then in watch.js - conditionally require chokidar if you are not in production mode? And then in initWatcher() make a null proxy for a chokidar watcher if you are in production mode?

I'm not sure if thats the "node" way - but it would seem pretty straight forward if I've read the code correctly?

**Comment by shvaikalesh** [comment]
`devDependencies` of main app's dependencies (like Brunch) are not installed by default. I don't see a good way to say npm to install only `chokidar` among all of dev deps (which are extremely heavy).

>  In `3.0`, it won't be even `require`d for --production builds.

I believe you can `shrinkwrap` then and drop `chokidar`. Not sure if npm will work then, though.

**Comment by macta** [comment]
Hi @shvaikalesh - I think I haven't explained this very well, my point is that `chokidar` doesn't appear to be in the `devDependencies` of package.json - and I think it should be? As described in the original message, I am surprised when using Brunch in a CI setup (eg Gitlab) that it gives warnings about something that is irrelevant in production mode and on a linux cli image?

If 3.0 is in the works, then maybe we just live with this - but it is something to consider for 3.0 - if you run Brunch as part of your deployment system (as well as locally in dev mode), it should pull in the correct dependencies and not generate false warnings.

**Comment by shvaikalesh** [comment]
Hey @macta.

Have you tried `npm install --no-optional`?
