### ISSUE TITLE
native-notifier crashes on Ubuntu

### ISSUE THREAD

**Issue by crertel** [brunch/brunch#1710]
### Description

So, Brunch doesn't (on Ubuntu 16.04) pick up filesystem changes directly. That's fixable with `watchers: {usePolling: true}`.

What _isn't_ fixable is that if a `*.scss` file throws an error during compilation, it crashes brunch in watch mode.

### Expected behavior

When I run `node node_modules/brunch/bin/brunch w -d` and I have a source file with an error in it, Brunch should log the error but not crash.

### Actual behavior

It crashes:
```
20:50:51 - info: compiled 56 files into 3 files, copied 167 in 9.7 sec
  brunch:watch change <snip> +9m
  brunch:list Reading <snip> +1ms
  brunch:pipeline Compiling <snip>@ sass-brunch +7ms
  brunch:list Compiled <snip> +21ms
20:59:43 - error: Compiling of <snip> failed. Error: Error: Undefined variable: "$font-size-small".
           on line 449 of <snip>
   >>         font-size:$font-size-small;
      ------------------^
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn notify-send ENOENT
  at exports._errnoException (util.js:1018:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
  at onErrorNT (internal/child_process.js:367:16)
  at _combinedTickCallback (internal/process/next_tick.js:80:11)
  at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Environment

1. Brunch: 2.10.9
1. Node.js: 6.10.3
1. NPM: 3.10.10
1. Operating system: Ubuntu 16.04

### brunch config contents

```javascript
watcher: {
    usePolling: true
  }
```

**Comment by millerized** [comment]
@crertel: I've found a workaround is to turn off notifications. I meant to file an issue and got slammed last week.

Try this:
```js
…
notifications: false,
watcher: {
    usePolling: true
}
…
```

**Comment by crertel** [comment]
A+! Thank you @millerized .

Any idea why that works?

**Comment by millerized** [comment]
>Any idea why that works?

I updated my comment so you are probably seeing the original comment.

>As you can see the crash is with the `notify-send` service/package.
```log
Error: spawn notify-send ENOENT
  at exports._errnoException (util.js:1018:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
  at onErrorNT (internal/child_process.js:367:16)
  at _combinedTickCallback (internal/process/next_tick.js:80:11)
  at process._tickCallback (internal/process/next_tick.js:104:9)
```
>I meant to file an issue and got slammed last week.

**Comment by shvaikalesh** [comment]
Hey guys, thanks for the report.

I believe `notify-send` is missing on your systems, right?

**Comment by ma-df** [comment]
Yes, that was the case.  I didn't chase down the issue much further because ¯\_(ツ)_/¯

Running ubuntu 12.x in a docker env.

**Comment by millerized** [comment]
I submitted an issue: https://github.com/brunch/brunch/issues/1711. Feel free to update Issue body if needed.

**Comment by millerized** [comment]
@shvaikalesh: I submitted an issue: #1711. Feel free to close if you want to track this one instead.
