### ISSUE TITLE
Notifications crash the watcher when it is running in docker

### ISSUE THREAD

**Issue by millerized** [brunch/brunch#1711]
### Description

What's the essence of the issue?
Notifications crash the watcher when it is running in docker.

### Expected behavior
Watcher should print the trace of error and continue watching for changes.

### Actual behavior
```bash
Error: spawn notify-send ENOENT
  at exports._errnoException (util.js:1018:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
  at onErrorNT (internal/child_process.js:367:16)
  at _combinedTickCallback (internal/process/next_tick.js:80:11)
  at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Environment

1. Brunch: 2.10.9
1. Node.js: v6.9.2
1. NPM: 3.10.9
1. Operating system: 
     - Docker container w/ host OS: OS X Sierra
     - native Ubuntu linux 12.x

### brunch config contents

```javascript
notifcations: true
```

**Comment by nshafer** [comment]
Might want to update the docs somewhere that when running in docker, this should be added to the config for the smoothest experience:

```javascript
watcher: {
    usePolling: true
},
notifications: false
```

Thanks for this report, though... I've been manually restarting brunch for months on every syntax error until I found this issue and the link to #1710 that pointed to turning notifications off.
