### ISSUE TITLE
Different production folder?

### ISSUE THREAD

**Issue by vrokolos** [brunch/brunch#1723]
Just a question. I'd like to have a different folder for "public" used in production. I also want this to be automatically build by a watcher at the same time as the normal build.

Is this possible?

**Comment by shvaikalesh** [comment]
Hey @vrokolos, thanks for the question.

Try:
```js
overrides: {
  production: {
    paths: {
      public: '/user/www/deploy'
    }
  }
}
```

**Comment by vrokolos** [comment]
Thanks that works!!
