### ISSUE TITLE
Alias doesn't work for lasts skeletons

### ISSUE THREAD

**Issue by madmat92** [brunch/brunch#1724]
### Description

When trying to run `brunch new -s ...` I get a warning that brunch couldn't interpret the alias

it doesn't work for this skeletons : 

- mithril-mdl
- aspnet-knockout
- brunch-with-vuety
- preact
- skunch

### Expected behavior

Should clone the skeleton for new project.

### Actual behavior

```
brunch new -s mithril-mdl
14:42:11 - warn: Couldn't interpret "mithril-mdl" as a hosted git url
14:42:11 - log: Cloning git repo "mithril-mdl" to "-"...
(node:3884) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Git clone error: Error: Command failed: git clone mithril-mdl "-"
fatal: repository 'mithril-mdl' does not exist
```

### Environment

1. Brunch: 2.10.9
1. Node.js: 6.10.0
1. NPM: 3.10.10
1. Operating system: Windows 10

**Comment by shvaikalesh** [comment]
@paulmillr, we should either switch to depending on github version of `brunch/skeletons` or configure auto publishing on push. WDYT?

**Comment by paulmillr** [comment]
published
