### ISSUE TITLE
Use ES6 in brunch-server.js

### ISSUE THREAD

**Issue by Maxou44** [brunch/brunch#1727]
Hello,

Thanks for your software, it's awesome !

I'm trying to setup a server-rendering for my web app, I followed the documentation to create a custom web server, it's works but I can't use ES6 features / JSX features, my server script isn't parsed by babel.

Any solutions ?

**Comment by Cryde** [comment]
You will have to install a more recent version of node :)

**Comment by Maxou44** [comment]
Same problem with the latest version of node

**./server/main-serv.js**
`import express from 'express';
let app = express();

import TextStrong from '../app/components/Texts/TextStrong';

app.use(express.static('./public'));

exports default app;`


**./brunch-server.js**
`let app = require('./server/main-serv');

module.exports = (port, path, callback) => {

	callback();
	return app.listen(port);
};`

**Comment by es128** [comment]
@Maxou44 just change to CommonJS style module syntax. ES6 modules are not natively supported in node. 

It's not worth brunch wiring together babel transpilation just for this on the backend files especially considering your simple examples. If you want it badly enough, you could set up your own `npm run` style scripts to do it.
