### ISSUE TITLE
Brunch don't concat javascripts from node_modules

### ISSUE THREAD

**Issue by dlepaux** [brunch/brunch#1729]
I want to compile node_modules dependencies scripts/css with my scripts/css. (Like with bower_components)
But I don't want to use bower for some obvious reason.

### Issue

When brunch build, it don't compile any node_modules... (because there are not required ? It is not necessary for my project..)

### Environment

1. Brunch: 2.10
1. Node.js: 6.11.1
1. NPM: 3.10.10
1. Operating system: Win 7
1. Code editor: Sublime Text 3

### `package.json` contents

```json
{
  "...": "...",
  "scripts": {
    "watch": "brunch watch",
    "build": "brunch build",
    "build-production": "brunch build --production"
  },
  "dependencies": {
    "datatables": "^1.10.13",
    "jquery-ui": "^1.12.1",
    "fullcalendar": "^2.9.1",
    "bootstrap-sass": "~3.3.7",
    "bootstrap": "~3.3.7",
    "font-awesome": "^4.6.3",
    "jquery": "^2.2.4"
  },
  "devDependencies": {
    "assetsmanager-brunch": "~1.8.1",
    "brunch": "^2.0.0",
    "clean-css-brunch": ">= 1.0 < 1.8",
    "coffee-script-brunch": "^1.8.3",
    "css-brunch": ">= 1.0 < 1.8",
    "cssnano-brunch": ">= 1.1.8",
    "fingerprint-brunch": "1.2.7",
    "javascript-brunch": "^1.7.1",
    "sass-brunch": "2.6.*",
    "uglify-js-brunch": ">= 1.0 < 1.8"
  }
}
```

### brunch config contents

```coffeescript
exports.config =
  paths:
    public: './web'
    watched: ['app']

  files:
    javascripts:
      joinTo:
        '/js/master.js': /(^node_modules[\/\\]bootstrap[\/\\]dist|app)/
    stylesheets:
      joinTo:
        '/css/master.css': /(^node_modules[\/\\]bootstrap[\/\\]dist|node_modules[\/\\]font|app)/
```
Thanks for your help

**Comment by shvaikalesh** [comment]
Hey @dlepaux, thanks for the issue.

Couple things I recommend:
1. Update plugins to `^2`
2. Use [`npm.styles`](http://brunch.io/docs/config#-npm-) to include CSS from `node_modules`
3. Use `require` to include JS from `node_modules`

**Comment by dlepaux** [comment]
Hello @shvaikalesh, 

1. Update plugins to ^2 [OK]
2. Use npm.styles to inclue CSS from node_modules [OK]
3. Use require to include JS from node_modules [KO]

The npm.styles work very fine ! Thanks

But for the require, I don't understand how to do this properly.

I have created a `main.js` with :
```javascript
require('jquery'); // with variant var $ = require('jquery');
require('datatables');
```
The compiled file contain nothing... What I'm doing wrong ?

And if you can help me about how mix all these jQuery dependencies together ?

Thank you

**Comment by dlepaux** [comment]
@shvaikalesh I have just an issue, non relative with brunch, but to use jQuery (compiled) with inpage jQuery scripts (at the page bottom typically). I got the jQuery is not defined. Do you have an idea to solve this problem ? Thanks
