### ISSUE TITLE
Brunch npm.static doesn't seem to respect declared order

### ISSUE THREAD

**Issue by thiagomajesk** [brunch/brunch#1741]
Hi, I'm trying to import `jquery-validate`, `jquery.validate.unobtrusive` and `jquery.unobtrusive-ajax` as static assets, but brunch doesn't seem to respect the order in which I put the files int the array.
The problem is that I'm getting an error on `jquery.unobtrusive-ajax` as it depens on a `$.validator` variable that its declared in  `jquery-validate`.

**brunch-config:**
```
module.exports = {
    paths: {
        public: "wwwroot",
        watched: ["wwwroot/javascripts", "wwwroot/stylesheets"]
    },
    npm: {
        styles: {
            "bootstrap": ["dist/css/bootstrap.css"],
            "jquery-tags-input": ["dist/jquery/jquery.tagsinput.min.css"],
            "font-awesome": ["css/font-awesome.css"],
            "animate.css": ["animate.css"]
        },
        globals: {
            "jQuery": "jquery",
            "$": "jquery",
            "Popper": "popper.js",
            "bootstrap": "bootstrap"
        },
        static: [
            "node_modules/jquery-validation/dist/jquery.validate.js",
            "node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js",
            "node_modules/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"
        ]
    },
    files: {
        javascripts: { joinTo: "dist/site.js" },
        stylesheets: { joinTo: "dist/site.css" }
    },
    modules: {
        nameCleaner: path => path.replace(/^wwwroot\/javascripts\//, ""),
        autoRequire: { "dist/site.js": ['init'] }
    },
    plugins: {
        babel: {
            ignore: /^node_modules/,
            pattern: /\.(js|vue)$/
        },
        copycat: {
            fonts: ["node_modules/font-awesome/fonts"]
        }
    }
}
```

**Comment by shvaikalesh** [comment]
Hello @thiagomajesk, thanks for the report.

We are planning to drop `javascripts.joinTo` and `npm.static` in #1664: those are old and faulty concepts that lead to an issues.

Try migrating to `javascripts.entryPoints` and importing (requiring) scripts you have in `static`.

Workaround: having the same list of files somewhere in `files.javascripts.order.before`

**Comment by thiagomajesk** [comment]
@shvaikalesh Is there any documentation available for those changes?

**Comment by shvaikalesh** [comment]
On `entryPoints` & `order`: [docs](http://brunch.io/docs/config#-files-)

I will publish the Brunch roadmap soon enough.
