### ISSUE TITLE
Initial compilation is very long

### ISSUE THREAD

**Issue by phtrivier** [brunch/brunch#1742]
### Description

Using 2.10.10 on a build, the initial compile time (when running 'watch' or 'build') has been increasing as we add more files to the build. 
The initial build now takes up about 30s, which is becoming more and more painful. 

The build is arguably complicated, since we have : 

* ES6 (brunch-babel with 'transform-object-assign', 'transform-object-rest-spread')
* Flow type annotations to remove ('transform-flow-strip-types')
* SASS compiled to CSS Modules (brunch-sass, native)

We have about 200js files and 40 scss (for about 19kloc). Is ~30s a normal time for an initial compilation ? 
What could I use to pinpoint the plugin that causes the problem ?

**Comment by shvaikalesh** [comment]
Hey @phtrivier, please see https://github.com/brunch/brunch/issues/1735#issuecomment-325175845
