### ISSUE TITLE
Can I use Browserify plugins in Brunch?

### ISSUE THREAD

**Issue by zakharkang** [brunch/brunch#1743]
Hello people.
Can I use Browserify plugins in Brunch? And if I can, then how? (For example, [Moonify](https://github.com/kbrsh/moonify).)
Thanks in advance!

**Comment by shvaikalesh** [comment]
Hi @zakharkang, thanks for the question.

Brunch has plugin system of it is own, with simpler API. You would have to create Brunch plugin for Moon.js. Docs: http://brunch.io/docs/plugins

**Comment by zakharkang** [comment]
I thought there was another solution, even...simpler. Thanks for your answer!
Thanks for the link. I overlooked this item in the menu earlier.
Good luck! Brunch is really pleasant and lightweight.
