### ISSUE TITLE
Relay/GraphQL doesn't create __generated__ folder

### ISSUE THREAD

**Issue by abienz** [brunch/brunch#1744]
### Description

I'm using react-relay with a fairly straight forward react project and i get the following error:

`
11:47:24 - error: Processing of app/components/AppX/AppX.jsx failed. Error: Could not load module './__generated__/AppQuery.graphql' from '/home/alex/Workspace/dcm/dcm-app/app/components/AppX'. Make sure the file actually exists.
    at friendlyRequireError (/home/alex/Workspace/dcm/dcm-app/node_modules/deppack/lib/resolve.js:69:9)
    at err2 (/home/abienz/Workspace/dcm/dcm-app/node_modules/deppack/lib/resolve.js:90:17)
    at /home/alex/Workspace/dcm/dcm-app/node_modules/browser-resolve/index.js:265:24
    at /home/alex/Workspace/dcm/dcm-app/node_modules/resolve/lib/async.js:55:18
    at load (/home/alex/Workspace/dcm/dcm-app/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/alex/Workspace/dcm/dcm-app/node_modules/resolve/lib/async.js:92:31)
    at /home/alex/Workspace/dcm/dcm-app/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
`

### Expected behavior

I'm expecting a folder called __generated__ to be created with the AppQuery.graphql file, the same files in a webpack project seems to work.

### Actual behavior

No folder and file is created and the web page doesn't load

### Environment

1. Brunch: 2.10.10
1. Node.js: 6.1..2
1. NPM: 3.10.10
1. Operating system: Arch Linux
1. Code editor: nvim

### `package.json` contents

```{
  "name": "brunch-app",
  "description": "Brunch.io application",
  "private": true,
  "author": "Brunch",
  "version": "0.0.1",
  "repository": "",
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production",
    "relay": "node_modules/relay-compiler/bin/relay-compiler --src ./app --schema ./schema.graphql"
  },
  "dependencies": {
    "react": "^15.4",
    "react-dom": "^15.4",
    "react-relay": "^1.3.0"
  },
  "devDependencies": {
    "accounting": "^0.4.1",
    "auto-reload-brunch": "^2",
    "babel-brunch": "~6.0",
    "babel-plugin-relay": "^1.3.0",
    "babel-preset-latest": "^6",
    "babel-preset-react": "~6.22",
    "brunch": "^2",
    "clean-css-brunch": "^2",
    "prop-types": "^15.5.10",
    "relay-compiler": "^1.3.0",
    "stylus-brunch": "^2.10.0",
    "uglify-js-brunch": "^2"
  },
  "babel": {
    "plugins": [
      "relay"
    ]
  }
}

```

### brunch config contents

```// See http://brunch.io for documentation.
exports.files = {
  javascripts: {
    joinTo: {
      'vendor.js': /^(?!app)/,
      'app.js': /^app/
    }
  },
  stylesheets: {joinTo: 'app.css'}
};

exports.plugins = {
  babel: {
    presets: ['latest', 'react'],
    plugins: ['relay']
  }
};

exports.conventions = {
  ignored: [/^__generated__/]
}

```

**Comment by shvaikalesh** [comment]
Probably related: https://github.com/brunch/brunch/issues/1719

**Comment by abienz** [comment]
Yeah I saw that but it looks like the user was having his __generated__ folder ignored. Mine isn't even being created.

**Comment by abienz** [comment]
So I found the answer was that Relay doesn't like my top level React Component being saved as a jsx file.

renaming to .js fixed the problem.

FML
