### ISSUE TITLE
Commands fail without root/Administrator.

### ISSUE THREAD

**Issue by rendall** [brunch/brunch#1745]
### Description

Commands fail with suggestion to run the command again as root/Administrator.

### Expected behavior

root/Adminstrator unnecessary to run npm / brunch commands.

### Actual behavior

After following successfully @shvaikalesh 's advice in https://github.com/brunch/brunch/issues/1740 (to add the parameter `--no-optional`  to the `npm i -g brunch` command) I then typed the command
 
`brunch new bmapp -s inferno`

(and later, `brunch new bmapp -s inferno --no-optional`)

I received the following error message (project name is 'bmapp')

```
13:48:25 - log: Pulling recent changes from git repo "git://github.com/infe
rnojs/brunch-with-inferno.git" to "C:\Users\renda\.brunch\skeletons\45c8aa9
10470cd7f83012f821ebea7111e05260a"...
13:48:26 - log: Pulled master into "C:\Users\renda\.brunch\skeletons\45c8aa
910470cd7f83012f821ebea7111e05260a"
13:48:26 - log: Copying local skeleton to "C:\workspace\websites\bmapp"...
13:48:26 - log: Created skeleton directory layout
13:48:26 - info: Installing packages with npm...
13:49:30 - error: Command failed: npm install
npm WARN deprecated babel-preset-latest@6.24.1: 💥  preset-latest accomplis
hes the same task as babel-preset-env. 🙏  Please install it with 'npm inst
all babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "preset
s": ["env"] }'. For more info, please check the docs: http://babeljs.io/doc
s/plugins/preset-env 👌. And let us know how you're liking Babel at @babelj
s on 🐦
npm WARN deprecated babel-preset-es2016@6.24.1: We're really excited that y
ou're trying to use ES2016 syntax, but instead of making more yearly preset
s, Babel has a better preset that we recommend you use instead: npm install
 babel-preset-env --save-dev. Give us a follow @babeljs to get more updates
npm WARN deprecated babel-preset-es2017@6.24.1: We're really excited that y
ou're trying to use ES2017 syntax, but instead of making more yearly preset
s, Babel has a better preset that we recommend you use instead: npm install
 babel-preset-env --save-dev. Give us a follow @babeljs to get more updates
npm ERR! path C:\workspace\websites\bmapp\node_modules\nan\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\workspace\websit
es\bmapp\node_modules\nan\package.json'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\workspace\web
sites\bmapp\node_modules\nan\package.json'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\work
space\\websites\\bmapp\\node_modules\\nan\\package.json\'\n    at Error (na
tive)',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\workspace\\websites\\bmapp\\node_modules\\nan\\packag
e.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\renda\AppData\Roaming\npm-cache\_logs\2017-09-07T10_4
9_30_179Z-debug.log
```

To replicate, attempt to create a new project while not logged in as Administrator.

### Environment

1. Brunch: 2.10.10
1. Node.js: v6.11.2
1. NPM: 5.4.1
1. Operating system: Windows 10 x64
1. Code editor: This is pre-code editor, in the command line.

### `package.json` contents

```{
  "name": "bmapp",
  "version": "0.0.0",
  "description": "",
  "main": "js/index.js",
  "scripts": {
    "test": "test/test.js"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@bitbucket.org/rendall/xxxx.git"
  },
  "author": "rendall",
  "license": "MIT",
  "homepage": "https://bitbucket.org/rendall/xxxx#readme"
}

```

### brunch config contents

```exports.npm = {
    globals: {
        Inferno: 'inferno',
        Component: 'inferno-component'
    }
}

exports.files = {
    javascripts: {
        entryPoints: {
            'app/initialize.js': 'app.js'
        }
    },
    stylesheets: {
        joinTo: 'app.css'
    }
}

exports.modules = {
    autoRequire: {
        'app.js': ['initialize']
    }
}

```

**Comment by shvaikalesh** [comment]
Hey @rendall, thanks for issue.

Indeed, root privileges should not be required to use `brunch new`.
We should tweak temporary dir in [init-skeleton](https://github.com/brunch/init-skeleton)
Just to confirm: it **does** work under root, right?

**Comment by rendall** [comment]
Not sure.  I can check now.  Hold on.

**Comment by rendall** [comment]
Yes.  `brunch new bmapp -s inferno` installed and configured an app as expected under the administrator account.  It took a minute to configure npm for the admin account, but all is well and working.

**Comment by shvaikalesh** [comment]
Thanks for the report. I am going to collect other issues we have with `init-skeleton` and close them some time this weekend. Windows support is very important for us.

**Comment by rendall** [comment]
Great @shvaikalesh.  Good luck.  In the meantime I'll go ahead with the project created under the admin account.  Thanks!

**Comment by rendall** [comment]
Hey @shvaikalesh .  You may want to hold off on the weekend coding session with respect to this bug.  I suspect the problem may be with the latest update of NPM from yesterday.  I got this error with some other packages, as well. I'm not the only one.

https://github.com/npm/npm/issues/18441

**Comment by rendall** [comment]
@shvaikalesh You can go ahead and close this issue.  It is *definitely* npm 5.4 that's causing this.  After rolling back to npm 5.3 all of these issues stopped.

**Comment by shvaikalesh** [comment]
Thanks for the update, @rendall. Feel free to reopen if the issue persists.
