### ISSUE TITLE
Brunch server .html extension?

### ISSUE THREAD

**Issue by pikeas** [brunch/brunch#1746]
I have links like `<a href="/foo">`. In production, NGINX has a try_files directives which transparently loads `/foo.html`.

Is there a way to accomplish the same thing with Brunch's dev server? It seems like my only options are to rewrite all links as `<a href="/foo.html">`, or to create a folder `foo` with `index.html` inside, neither of which is a great solution.

**Comment by TomRK1089** [comment]
You can provide a custom server implementation for this sort of functionality: 

> If a brunch-server.js or brunch-server.coffee file exists at the root of your project, Brunch will treat this as your custom web server. This can be overridden with the server.path option.
> The server script must export a function that starts your custom server, either as the default exported module. This function should return an instance of http.Server or an object containing a close property assigned to a function that shuts down the server.

See http://brunch.io/docs/config#-server-
