### ISSUE TITLE
can't make entrypoints to work

### ISSUE THREAD

**Issue by tooltonix** [brunch/brunch#1750]
Hello,

I only work with brunch since today because I need an alternative for Webpack. So far, I have been able to define an entry point or a JavaScript file via Webpack. Additional files have been inserted via "import". These imported files are partly also in the "node_modules" -directory and could be inserted automatically by a "resolve" in Webpack. If the modules in the "node_modules" directory also have dependencies, they are also resolved via the "resolve" in Webpack. This option I just can not find in brunch. In addition, brunch seems to include all directories or modules in the "node_modules" folder, although I need only certain directories or modules.

```
App
│───	app/    // es6-files
├───	node_modules/   // external modules
├───	tmp/   // output

```

**Comment by vdcrea** [comment]
By convention Brunch compile all js files inside app. No need to define an entry point. Node modules should be out of your working.

I have a set up quite similar to yours:

```
/
|--- src   <- input folder with css and js
     |--- main.js   <- js "entry" module
|--- node_module
|--- www
     |--- src   <- output
|--- brunch-config.js
|--- package.json

```

In the brunch-config.js you can configure the input folder to watch and the output this way:

```
module.exports = {
  paths: {
    watched: ['src'],
    public: 'www/src'
  },
  modules: {
    autoRequire: {
      'js/main.js': ['src/main']
    }
  },
  npm: {
    styles: {
      'normalize.css': ['normalize.css']
    }
  },
  files: {
    javascripts: {
      joinTo: {
        'js/vendor.js': /^(?!src\/)/,
        'js/main.js': /^(src\/.*\.js)/
      }
    },
    stylesheets: {
      joinTo: {
        'css/vendor.css': /^node_modules/,
        'css/main.css': /^(src\/)/
      }
    }
  }
};
```

It asks brunch to:
- watch /src and to output in /www/src
- compile normalize.css from a npm module in vendor.css
- compile all css/stylus/sass files (depending on your brunch extensions) inside /src in /www/src/main.css
- compile all js modules inside /src in /www/src/main.js
- compile all js modules from npm in /www/src/vendor.js
- autorequire the "entry" module /scr/main.js
