### ISSUE TITLE
Unable to get Hot Module Replacement working in plain React App.

### ISSUE THREAD

**Issue by abienz** [brunch/brunch#1752]
### Description

I'm trying to integrate hmr-brunch into my own React app based on a brunch simple skeleton

### Expected behavior

Editing and saving a component will show the updates in current page/state without error.

### Actual behavior

I receive the following errors:

> Uncaught TypeError: Cannot set property 'updated' of undefined
    at runtime.js:94
    at Array.forEach (<anonymous>)
    at createMarkGraph (runtime.js:93)
    at performUpdate (runtime.js:239)
    at Function.wrap [as hmr] (runtime.js:386)
    at runtime.js:438

> Uncaught TypeError: Cannot read property 'disposeHandlers' of undefined
    at runDisposeHandlers (runtime.js:267)
    at Array.forEach (<anonymous>)
    at handleRemoved (runtime.js:371)
    at performUpdate (runtime.js:225)
    at Function.wrap [as hmr] (runtime.js:386)
    at runtime.js:438

### Environment

1. Brunch: 2.10.10
1. Node.js: 6.11.3
1. NPM: 3.10.10
1. Operating system: OS X 10.12.6
1. Code editor: NVim

### `package.json` contents

```
"dependencies": {
    "babel-polyfill": "^6.26.0",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "whatwg-fetch": "^2.0.3"
},
"devDependencies": {
    "auto-reload-brunch": "^2",
    "babel-brunch": "^6.1.1",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-env": "^1.6.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-3": "^6.24.1",
    "brunch": "^2",
    "clean-css-brunch": "^2",
    "hmr-brunch": "^0.1.1",
    "snazzy": "^7.0.0",
    "standard": "^10.0.3",
    "stylus-brunch": "^2.10.0",
    "uglify-js-brunch": "^2"
}
```

### brunch config contents

```
// See http://brunch.io for documentation.
exports.files = {
  javascripts: {
    joinTo: 'app.js'
  },
  stylesheets: {joinTo: 'app.css'}
}

exports.plugins = {
  babel: {
    presets: ['env', 'react', 'stage-3'],
    plugins: ['transform-class-properties', 'transform-async-to-generator']
  }
}

exports.hot = true
```

### Other useful files, when present (log, `bower.json` etc.)

my initialize.js:
```
import 'babel-polyfill'
import 'whatwg-fetch'
import React from 'react'
import ReactDOM from 'react-dom'å
import App from 'components/App/App'

//const render = () => {
document.addEventListener('DOMContentLoaded', function () {
  ReactDOM.render(<App />, document.querySelector('#app'))
})

//document.addEventListener('DOMContentLoaded', function () {
//  render()
//})

//if (module.hot) {
  //module.hot.accept('./components/App/App', () => {render()})
// module.hot.accept()
//}
```
Note: the commented out lines are other options I have been trying to make this work.

When I first run `brunch w -ns` the app loads fine, and I get the message:
> [HMR] All updated

In the console, but the errors appear as soon as I make a change to a file and save.

Any ideas?

**Comment by lroal** [comment]
I have the same problem, but in vue, using the plain skeleton for vue.
