### ISSUE TITLE
Brunch plugins nested in a dependency

### ISSUE THREAD

**Issue by webdif** [brunch/brunch#1758]
### Description

Brunch does not look for brunch plugins in dependencies of a dependency.

`package.json`:
```json
devDependencies: {
  "my-config": "^1.0.0"
}
```

`node_modules/my-config/package.json`: 
```json
devDependencies: {
  "babel-brunch": "^6.1.1",
}
```

### Behavior

I expected to magically work, but this is not the case. `babel-brunch` (and other brunch plugins) are not found, because brunch is searching for plugins in the `package.json`, but not recursively.

I work around this problem with adding this in my `brunch-config.js`:
```js
exports.config = {
    paths: {
      packageConfig: 'node_modules/my-config/package.json',
    },
};
```

If I do this, it takes the brunch plugins from `my-config/package.json`. But what I want is the possibility to add other brunch plugins than those in my config module.

Something like this perhaps:
```js
exports.config = {
    paths: {
      packageConfig: ['package.json', 'node_modules/my-config/package.json'],
    },
};
```

But this is not supported, as `packageConfig` is expecting a string.

---

Is there a way to achieve this?
Is this a feature to could be added to brunch?
That would be super cool!

Thanks for your reply, and all your work by the way 👍

**Comment by shvaikalesh** [comment]
Actually, this is already implemented in https://github.com/brunch/brunch/pull/1664: `node_modules` is scanned for plugins, allowing to bundle couple plugins into a single one. We have to solve multiple versions of single plugin though.

**Comment by webdif** [comment]
Very excited about 3.0! 😃 
I close this issue then, I will work around for the time being.

Thanks! And please, feel free to ping me if you need any help on #1664, I have never contributed to brunch, but maybe I can help 🙏
