### ISSUE TITLE
brunch-config and using SASS plugins?

### ISSUE THREAD

**Issue by ohNegative** [brunch/brunch#1762]
I'm using the Brunch with ES6 skeleton and want to use SASS, but am confused on how to set up the config.js file. I want to use the Susy grid with my SASS mixins.

I've been able to use Jeet grid with Stylus in the same skeleton and this is how I set up the plugin for those:

```
plugins: {
    babel: {presets: ['es2015']},
    stylus: {plugins: ['jeet', 'rupture']},
  }
};
```
I have the sass-brunch plugin installed and it will compile my scss files, but when I go to use the @import rule to import SUSY:

`@import "~susy/sass/susy";`

it won't compile and errors out on the @import rule so I'm assuming I'm not setting something up correctly with the config.js file. This is what my config file currently looks like:

```
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/,
        'app.js': /^app/
      }
    },
    stylesheets: {joinTo: 'app.css'}
  },

  plugins: {
    babel: {presets: ['es2015']},
    sass: {
      debug: 'comments',
      allowCache: true,
      modules: true,
      plugins:['susy'], 
      sourceMapEmbed: true,
      mode: 'native', // custom functions are only supported in 'native' mode
      functions: {
        sin: function(val) { types.Number(Math.sin(val.getValue())) },
        cos: function(val) { types.Number(Math.cos(val.getValue())) },
        tan: function(val) { types.Number(Math.tan(val.getValue())) }
      }

    }
  }
};
```

### Environment

1. Brunch: *(make sure you're on the latest release!)* 2.4.0
1. Node.js: 6.9.1
1. NPM: *(npm v2 is not supported)* 3.10.8
1. Operating system: Windows
1. Code editor: Visual Studio Code

I guess I just need to know how to setup up the config file properly in order to use the sass susy grid. I already know the way it's currently setup is wrong so any help would be greatly appreciated. 

Pete

**Comment by pierrebeitz** [comment]
we've been able to include bootstrap-sass source files with the following addition to `brunch-config.js`:

```
  plugins: {
    sass: {
      options: {
        includePaths: ['node_modules/bootstrap-sass/assets/stylesheets'], // so we can to @import 'bootstrap/variables' and alike
      },
    },
  }
```

you should be able to specify the susy-path (`node_modules/susy/sass`) in `includePaths` to then be able to just `@import 'susy'` within your projects's sass-files.

**Comment by ohNegative** [comment]
@pierrebeitz worked like a charm, thanks for the heads up.

Closing this one.
