### ISSUE TITLE
Output .js bundle contains everything from node_modules, even not imported

### ISSUE THREAD

**Issue by sickill** [brunch/brunch#1765]
### Description

I have this brunch config (listed below), where I'm building 2 output bundles, app.js and admin.js.

app.js is almost empty and does `import "phoenix_html"`, while admin.js does `import "react"` etc.

### Expected behavior

I would expect to have very tiny app.js file as I'm not importing react or anything big there.

### Actual behavior

Both files are about 1.3 MB in size (or 350 KB in production build). Both include everything that's installed in node_modules.

I browsed through existing and closed issues, and people keep saying "only what's required" gets concatenated. But this is not true. Is "requiring" different from `import "...."` when using babel?

### Environment

1. Brunch: 2.10.12
1. Node.js: 6.12
1. NPM: 3.10.10

### `package.json` contents

```json
{
  "repository": {},
  "license": "MIT",
  "scripts": {
    "deploy": "brunch build --production",
    "watch": "brunch watch --stdin"
  },
  "dependencies": {
    "bootstrap": "^4.0.0-beta",
    "jquery": "^3.2.1",
    "phoenix": "file:../deps/phoenix",
    "phoenix_html": "file:../deps/phoenix_html",
    "popper.js": "^1.12.6",
    "react": "^16.1.1",
    "react-dom": "^16.1.1",
    "react-phoenix": "file:../deps/react_phoenix"
  },
  "devDependencies": {
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-brunch": "6.1.1",
    "brunch": "2.10.12",
    "clean-css-brunch": "2.10.0",
    "sass-brunch": "^2.10.4",
    "uglify-js-brunch": "2.1.1"
  }
}
```

### brunch config contents

```javascript
      joinTo: {
        "js/app.js": ["js/app.js", /^node_modules/],
        "js/admin.js": ["js/admin.js",
                        /^js\/admin\//,
                        /^js\/components\//,
                        /^node_modules/],
```

**Comment by paulmillr** [comment]
The `import "phoenix_html` file may import other modules. You also need to upgrade to NPM v4 or higher.

**Comment by sickill** [comment]
Thanks. `phoenix_html` may import something, but it doesn't import React which is found in the final bundle. Will try with NPM v5 now.

**Comment by sickill** [comment]
Tried with Node 8, NPM 5, the result is the same. `app.js` is 1.2M (in dev build) while `phoenix_html`, the only imported thing in `app.js` is 1KB only and doesn't import anything else.

**Comment by aMarCruz** [comment]
@sickill , maybe I'm wrong but I think neither Brunch/React supports three-shaking, even if you App has `import React from 'react'` and nothing more, Brunch will include all the package.

**Comment by paulmillr** [comment]
True thing @aMarCruz

**Comment by colinbate** [comment]
Tree shaking isn't the issue here. @sickill I'm not sure if you tried the Brunch entry points config, but that may work (I've not tried it myself). Using the `joinTo` config above you are basically saying to put everything used from node_modules into both files. Typically you might put all of the node_modules stuff into a vendor.js and include that separately.

However for your case try the `entryPoints` config (http://brunch.io/docs/config#-files-).

**Comment by tjomk** [comment]
Having a similar issue that Brunch includes all of the React's development code (~700Kb) in production build.

**Comment by kavdev** [comment]
Still seeing this in v3.0. Requiring react and react-dom bring all of the following into the build:
```
react-dom.development.js
react-dom.production.min.js
react-is.development.js
react-is.production.min.js
react.development.js
react.production.min.js
scheduler-tracing.development.js
scheduler-tracing.production.min.js
scheduler.development.js
scheduler.production.min.js
```

Is there a config option we can set to trim this down?

**Comment by paulmillr** [comment]
The option is to include react into app/lib or something like this. Should work until we figure out how to adjust this.
