### ISSUE TITLE
Vendor.js is not generated

### ISSUE THREAD

**Issue by enzofab91** [brunch/brunch#1767]
### Description

When I run brunch build, vendor.js is not being generated

### Environment

1. Brunch: 2.10.12
2. Yarn: 1.3.2
3. Operating system: Windows 7

### `package.json` contents

{
     "name": "brunch-app",
     "description": "Brunch.io application",
     "private": true,
  "author": "Brunch",
  "version": "0.0.1",
  "repository": "",
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "jquery": "^3.2.1"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2",
    "brunch": "^2",
    "clean-css-brunch": "^2",
    "uglify-js-brunch": "^2"
  }
}

### brunch config contents

module.exports = {
  files: {
    javascripts: {joinTo: {
		'js/front.js': /^app\/js/,
		'js/vendor.js': /^(?!app)/,
    }},
    stylesheets: {joinTo: {
		'css/estilos_admin.css': /^app\/css/,
    }}
  },
   npm: {
	  enabled: false,
  }
};

**Comment by fatcop** [comment]
Be good to close off this ticket, as I don't think there is a problem other than config.

From my knowledge, having npm.enabled:false is simply not going to pull in vendor packages from node_modules.

Also you are going to need a require('jquery') in your code, for example, to have that particular module pulled into vendor.js.

Also some joinTo regexes aren't correct:
   /^app/js/ ==> /^app\/js/
   /^app/css/ ==> /^app\/css/
