### ISSUE TITLE
Dependency system not working & The name `getDependencies` is confusing

### ISSUE THREAD

**Issue by buckle2000** [brunch/brunch#1789]
The plugin method `getDependencies` actually output dependents. The name itself is confusing. I propose to change the function name into `getDependents`.
See here for an example of confusion.
https://github.com/aMarCruz/pugjs-brunch/issues/9

Or is the description incorrect?

**Comment by buckle2000** [comment]
Or is the description incorrect?

**Comment by paulmillr** [comment]
that's true.

**Comment by buckle2000** [comment]
But `stylus-brunch` is working fine. Why?

**Comment by paulmillr** [comment]
I don't know. You need to take a look at how stylus-brunch handles this.

**Comment by buckle2000** [comment]
I took a look, and the bahavior of `getDependencies` in `stylus-brunch` is the same as `getDependencies` in `pugjs-brunch`. I suspect that brunch treats stylesheet and template differently.
