### ISSUE TITLE
How to enable full rebuild after every file change

### ISSUE THREAD

**Issue by buckle2000** [brunch/brunch#1790]

**Comment by paulmillr** [comment]
What cache?

**Comment by buckle2000** [comment]
I changed the issue title. A full rebuild after every file change can solve this issue #1789 .

**Comment by clarknelson** [comment]
It doesn't seem like brunch is rebuilding when I save a partial file. 

My brunch-config.js

    files: {
        javascripts: {joinTo: 'scripts/app.js'},
        stylesheets: {joinTo: 'styles/app.css'}
    },

When I edit a `_about.scss` or any other `_*.scss` file I get the following in console while running `brunch watch`. 

info: compiled in 75 ms

But when I save the only non-partial file 'main.scss', which @imports all of the partial scss files, I get the following message. 

info: compiled main.scss and 4 cached files into app.css in 389 ms

Hopefully you can see how this would be frustrating, and how someone could think it is related to caching. I believe this had been working for me, and I think it does on other projects, but I would love to fix it

**Comment by clarknelson** [comment]
how can I tell what 4 files are cached? it seems like "${file_name} and ${cached_file_number} cached files into ${output_file}" is missing from the first statement, maybe one can not be parsed

**Comment by paulmillr** [comment]
roll back to sass-brunch 2.10.5
