### ISSUE TITLE
Brunch still requires deprecated package coffee-script

### ISSUE THREAD

**Issue by npoppeli** [brunch/brunch#1794]
The JS file brunch/lib/utils/config.js still requires the npm package coffee-script. 
However, this is a deprecated package: CoffeeScript on NPM has moved to "coffeescript" (no hyphen).

So, if you just install coffeescript (latest version 2.2.1) Brunch will not work.
If you add coffee-script, Brunch works, but you get an older version of CoffeeScript (1.12), at the price of two versions of CoffeeScript in node_modules.

Environment: Brunch 2.10.6, Node.js 8.9.4, NPM 5.6.0, OS Ubuntu Linux 16.04.

**Comment by paulmillr** [comment]
Fixed
