### ISSUE TITLE
Angular 5 (through angular cli)... We need a sample worflow

### ISSUE THREAD

**Issue by odyright** [brunch/brunch#1796]
### Description

Hello there, I recently started a new project running Angular 5 (through angular cli). I found the compile time too slow so i decided to replace it with *Brunch* but when trying to re-organise angular's path ..i faced tones of headaches errors. 
So i'm requesting help on how to set *Angular 5 + Brunch* ! (with details)
Thank you

### Environment

1. Brunch: *(2.10.9)*
1. Node.js: v9.5.0
1. NPM: *(5.6.0)*
1. Operating system: OS x 10.13.3
1. Code editor: VSCODE

**Comment by fatcop** [comment]
There is a skeleton https://github.com/colinbate/ng2-brunch available from
http://brunch.io/skeletons

Perhaps you could create a dummy project and compare structure/config.

**Comment by fatcop** [comment]
Quite a while ago I posted an issue regarding trying to get an existing project file structure to work with brunch.

I ended up having to restructure my app a little to work within brunch's idiosyncracies. It was absolutely no biggie for my small project.

This is the issue I raised:
https://github.com/brunch/brunch/issues/1519

ps. We currently use Brunch for large corporate project. Its simple config and blistering speed still give it the edge imo.

**Comment by odyright** [comment]
@fatcop i also found this repo [Todo-phoenix-angular](https://github.com/nguyenvinhlinh/todo-phoenix-angular) and compared to the others, this one had a different approach of running the newer **angular cli** with **phoenix**. 

I think the brunch team should offer to his community a recommended way to build their project with different framework they would like to run. **_i.E_** : `angular-cli-brunch`
