### ISSUE TITLE
Intermittent missing files from output

### ISSUE THREAD

**Issue by CoderJason123** [brunch/brunch#1798]
### Description

What's the essence of the issue?
Every X number of builds during watch, one of my vendor js files finds itself missing from vendor.js
### Expected behavior
All files always end up into vendor.js
### Actual behavior
The interesting tidbit is that if i run brunch watch with diagnostics enabled, this behavior NEVER happens.  This is ok as a workaround, but I really would prefer not to.  What appears to happen is that if i change 1 file, most of the time brunch picks up the single file and compiles it.  On occasion when the bad behavior happens, it looks like brunch is using "cache" files and all of those files get compiled.  It is when it tries to use these cache files that it fails to find one of my vendor javascript files.  If I then stop the watch and recompile, it usually fixes itself.

I am providing as much detail as I can, i can't recreate a separate app to do this without quite a bit of time.  I have never been able to get loggy stacks to work so if that is needed please explain actually how / where to do that.

### Environment

1. Brunch: *(make sure you're on the latest release!)* 6.1.1
1. Node.js: 9.6.1
1. NPM: *(npm v2 is not supported)* 5.6
1. Operating system: macOS high sierra
1. Code editor: vs code

### `package.json` contents

{
  "name": "TestApp",
  "private": true,
  "version": "0.0.0",
  "devDependencies": {
    "babel-brunch": "^6.1.1",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "brunch": "^2.10.12",
    "less-brunch": "^2.10.0",
    "react-hot-loader": "^3.1.3",
    "uglify-js": "^3.3.12",
    "uglify-js-brunch": "^2.10.0"
  },
  "dependencies": {
    "autocompleter": "^1.0.30",
    "bulma": "^0.6.2",
    "chartist": "^0.11.0",
    "event-source-polyfill": "0.0.9",
    "isomorphic-fetch": "2.2.1",
    "moment": "^2.20.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-rating": "^1.0.5",
    "react-router-dom": "^4.2.2",
    "svg-gauge": "^1.0.4",
    "sweetalert": "^2.1.0",
    "tiny-date-picker": "^3.1.8"
  },
  "scripts": {
    "build": "brunch build",
    "build-dev": "brunch watch -d"
  }
}

### brunch config contents

module.exports = {
    files: {
        javascripts: {
            joinTo: {
                'vendor.js': /^(?!app)/,
                'app.js': /^app/
            }
        },
        stylesheets: {
            joinTo: 'styles.css'
        }
    },
    modules: {
        autoRequire: {
            'app.js': ['index']
        }
    },
    npm: {
        styles: {
            bulma: ['css/bulma.css'],
            'tiny-date-picker': ['tiny-date-picker.css'],
            [chartist]: ['dist/chartist.css']
        }
    },
    paths: {
        public: './wwwroot'
    },
    plugins: {
        babel: {
            presets: ['env', 'react']
        },
        uglify: {
            mangle: false,
            compress: {
                global_defs: {
                    DEBUG: false
                }
            }
        }
    }
};

Here is a sample of what i mean for the cache files -- all of a sudden it jumps from 18 cached files to 109, and once this action occurs, i usually get an error like  
vendor.js?v=UBsOiAj7eVwhc2Ai-iYsSDhMq5JJAbjmyOKaWx2VJNA:61 Uncaught Error: Cannot find module 'tiny-date-picker' from 'Search.jsx'

10:03:11 - info: compiled Search.jsx and 18 cached files into app.js in 242 ms
10:03:12 - info: compiled Search.jsx and 18 cached files into app.js in 196 ms
10:03:17 - info: compiled site.css and 4 cached files into styles.css in 95 ms
10:03:29 - info: compiled Search.jsx and 109 cached files into 2 files in 420 ms
10:03:31 - info: compiled Search.jsx and 16 cached files into app.js in 219 ms
### Other useful files, when present (log, `bower.json` etc.)

If there's an unexpected error during `brunch build`/`brunch watch`, please attach the compilation log with the debug flag (`-d`) **and** stack traces enabled (`export LOGGY_STACKS=true`).

If something worked with previous versions of brunch, but stopped with a newer one, please include these details as well.

**Comment by CoderJason123** [comment]
Is there anyone that can help please?  I really like 'Brunch', I just want to get past this issue if it is in fact a real issue.

**Comment by fatcop** [comment]
Might be related to known editor saving issues:

http://brunch.io/docs/troubleshooting
