### ISSUE TITLE
Brunch watch, doesn't delete asset files

### ISSUE THREAD

**Issue by quangv** [brunch/brunch#180]
`brunch watch` doesn't seem to delete asset files no longer being used.

Example

_app/assets/index.html_

```
$> rm app/assets/index.html
$> brunch watch
[16:44:39]: [Brunch]: compiled.
```

but it doesn't delete _build/index.html_

I'm not sure if this was a design choice or not, but just reporting it ;)

**Comment by alexbepple** [comment]
This issue seems back with 1.7.20.

**Comment by paulmillr** [comment]
It works as intented right now! heh

**Comment by alexbepple** [comment]
@paulmillr Just to be clear, is it intended behavior that if I remove a file from `app/assets/`, it remains in `public/`?

**Comment by es128** [comment]
Yes it does not attempt to clean out stale assets. Some users purposely leave things in their build assets dir.

**Comment by nathanhornby** [comment]
Is there a command or option that overrides this behaviour @es128 ?

To be honest I'm struggling to imagine a use-case where you would delete the 'source' but want the 'compiled' version to remain - but surely it has to be the edge case?

**Comment by es128** [comment]
I'm not sure how prevalent it is, but several people have definitely reported using it that way. Often using multiple tools writing into the same target dir iirc.

> Is there a command or option that overrides this behaviour

`rm -rf ./public/assets/*` :wink:

There is no brunch option that I'm aware of at this point, but it seems like it would be a useful thing to add. It could probably even be done as a plugin

**Comment by nathanhornby** [comment]
> Often using multiple tools writing into the same target dir iirc.

Fair cop, hadn't considered that.

I'd personally target those resources at brunch's 'source' asset directory, as it's only copying those resources over anyway - however I'm assuming there are alternative workflow options available that contradict that.
