### ISSUE TITLE
Cannot concatenate files in assets

### ISSUE THREAD

**Issue by andreabergia** [brunch/brunch#1800]
### Description

Hi, 
I'm trying to concatenate various javascript files found in `assets`, such as:

```
    assets/scripts/ispConfigManager.js,
    assets/scripts/ispCommunicationManager.js
```

They *should* be in `vendor/`, since they are basically libraries, but unfortunately it's an external (and poorly written) angular 1 library that refers the template files via an absolute path which starts with `assets` and I don't want to mess with its source.

### Expected behavior

The output file with the concatenation.

### Actual behavior

No output file is generated. However, if I rename the directory "assets" to "vendor", everything works as expected. I'm trying to modify "configurations" but I can't seem to find out the correct settings.

### `package.json` contents

```json
{
  "name": "cfx00",
  "version": "0.0.1",
  "devDependencies": {
    "@types/angular": "^1.5.0",
    "autoprefixer": "^6",
    "babel-brunch": "^6.1.1",
    "brunch": "^2.10.12",
    "eslint": "^4",
    "typescript": "^2.6.2",
    "typescript-brunch": "^2.3.0",
    "uglify-js-brunch": "^2.10.0"
  }
}
```

### brunch config contents

```javascript
const filesIsp = [
    'assets/scripts/ispConfigManager.js',
    'assets/scripts/ispCommunicationManager.js'
    /* and more files */
];
module.exports = {
   files: {
        javascripts: {
            joinTo: {
                'isp.js': filesIsp
            }
        }
    },
    conventions: {
        vendor: /^assets/,
        assets: () => false
    }
};
```

**Comment by fatcop** [comment]
I could get it to work adding a "paths" to watch your assets/scripts folder.

docs: http://brunch.io/docs/config#-paths-

```
module.exports = {
   files: {
        javascripts: {
            joinTo: {
                'isp.js': filesIsp
                // 'isp.js': 'assets/scripts/*'
            }
        }
    },
    paths: {
        watched: ['assets/scripts']
    },
    conventions: {
        assets: () => false,
        // assets: /^assets\/(?!scripts)/,
    }
};
```

But I couldn't get the rest of the assets folder to copy to public directly - in case that is also what you needed to do.

Bit of fiddling would prob get it.
