### ISSUE TITLE
dotenv & Brunch: environment variables in code

### ISSUE THREAD

**Issue by tarciozemel** [brunch/brunch#1806]
### Description

The essence of this issue is understand how to use env variables in code with Brunch.

More specificaly, in "overrides" section of [config docs](http://brunch.io/docs/config) we found:

> It is also possible to set an additional environment value using the BRUNCH_ENV or NODE_ENV environment variable. This can be especially useful when combined with [dotenv](https://npmjs.org/package/dotenv).

So I installed dotenv, create some variables in a `.env` file in the root of the project and try to:

```javascript
import dotenv from 'dotenv'
dotenv.config()

console.log(process.env.TEST_KEY)
```
But the thing didn't goes very well...

### Expected behavior

The expected behavior is something like the Create React App wepack environment variables autoimport: I put some vars in `.env` file and voilà!

### Environment

1. Brunch: 2
1. Node.js: 9.8.0
1. NPM: 5.7.1
1. Operating system: Ubuntu 16.04.4 LTS (Linux ubuntu-pc 4.13.0-38-generic x86_64)
1. Code editor: Visual Studio Code

### `package.json` contents

```json
{
  "name": "recursos-frontend",
  "description": "Recursos front-end web site",
  "private": true,
  "author": "w!",
  "version": "1.0.0",
  "repository": "",
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "preact": "8.1.0"
  },
  "devDependencies": {
    "auto-reload-brunch": "2",
    "babel-brunch": "6.0",
    "babel-plugin-transform-react-jsx": "6.24.1",
    "babel-preset-latest": "6",
    "brunch": "2",
    "clean-css-brunch": "2",
    "dotenv": "5.0.1",
    "sass-brunch": "2.10.4",
    "uglify-js-brunch": "2"
  }
}
```

### brunch config contents

```javascript
exports.files = {
  javascripts: {
    joinTo: {
      'vendor.js': /^(?!app)/,
      'script.js': /^app/
    }
  },
  stylesheets: {joinTo: 'style.css'}
}

exports.plugins = {
  babel: {
    presets: ['latest'],
    plugins: [
      ['transform-react-jsx', {pragma: 'h'}]
    ]
  }
}

exports.watcher = {
  awaitWriteFinish: true,
  usePolling: true
}
```

**Comment by tjomk** [comment]
Any update on this?

**Comment by tarciozemel** [comment]
Brunch is very good, but his community is dead...

**Comment by reubano** [comment]
Works for me. 

Brunch: 3
Node.js: 12.6.1
NPM: 6.14.x

`brunch-config.js`
```js
require('dotenv').config()

console.log(process.env.TEST_KEY)
...
```

```bash
$ npm start

> App@1.1.1 start /Users/reubano/Documents/Projects/icc/wei-app
> brunch watch --server

test_value
...
```

**Comment by reubano** [comment]
After using `dotenv` for a while now, I've noticed that it only works in the `brunch-config.js` file. Other `js` or `coffee` files don't pick up `.env` vars.

**Comment by reubano** [comment]
Did some investigation, and this is the error that shows up: `Uncaught TypeError: fs.readFileSync is not a function`. I suspect this is because `brunch-config.js` runs in node which as `fs`, but the other files run in the browser which don't. Not sure how or if other bundlers avoid this issue.
