### ISSUE TITLE
brunch build fails with Error: Improperly-cased require: on Windows Linux Subsystem

### ISSUE THREAD

**Issue by tscott-au** [brunch/brunch#1814]
### Description
brunch build fails with the exception: "Error: Improperly-cased require" on Windows Linux Subsystem ubuntu shell when the source files are on the auto-mounted Windows host file system.

### Expected behavior
From a ubuntu bash shell, brunch build should succeed.

### Actual behavior
From a ubuntu bash shell, brunch build results in: error: Processing of app/initialize.js failed. Error: Improperly-cased require: './logger' in  /mnt/c/users/tim/dev/ubdev/proj/app/initialize.js

If the source files are within the ubuntu linux file system the build is successful,  however Microsoft strongly recommends using the auto-mounted windows file system for source code, it is on this mounted file system that the error occurs.

### How to re-produce
From a windows file system mount point within a ubuntu bash shell, follow the "Getting Started" guide. http://brunch.io/docs/getting-started

Exception happens after including require('./logger')  in initialize.js
Zip file of brunch generated project attached.
[proj.zip](https://github.com/brunch/brunch/files/2093577/proj.zip)

### Environment

1. Brunch: 2.10.12
1. Node.js: v8.10.0
1. NPM: 3.5.2
1. Operating system: Ubuntu via Windows Linux Subsystem
1. Code editor: visual studio code

### `package.json` contents

```json
{
  "name": "brunch-app",
  "description": "Brunch.io application",
  "private": true,
  "author": "Brunch",
  "version": "0.0.1",
  "repository": "",
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {
    "jquery": "^3.3.1"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2",
    "babel-brunch": "~6.0",
    "babel-preset-latest": "^6",
    "brunch": "^2",
    "clean-css-brunch": "^2",
    "uglify-js-brunch": "^2"
  }
}
```

### brunch config contents

```javascript
exports.files = {
  javascripts: {
    joinTo: {
      'vendor.js': /^(?!app)/, // Files that are not in `app` dir.
      'app.js': /^app/
    }
  },
  stylesheets: {joinTo: 'app.css'}
};

exports.plugins = {
  babel: {presets: ['latest']}
};
```

### Other useful files, when present (log, `bower.json` etc.)
19:27:34 - error: Processing of app/initialize.js failed. Error: Improperly-cased require: './logger' in /mnt/c/users/tim/dev/ubdev/proj/app/initialize.js
    at checkImproperCase (/mnt/c/users/tim/dev/ubdev/proj/node_modules/deppack/lib/resolve.js:77:15)
    at browserResolve (/mnt/c/users/tim/dev/ubdev/proj/node_modules/deppack/lib/resolve.js:95:7)
    at /mnt/c/users/tim/dev/ubdev/proj/node_modules/browser-resolve/index.js:269:13
    at onfile (/mnt/c/users/tim/dev/ubdev/proj/node_modules/resolve/lib/async.js:51:21)
    at onex (/mnt/c/users/tim/dev/ubdev/proj/node_modules/resolve/lib/async.js:93:22)
    at /mnt/c/users/tim/dev/ubdev/proj/node_modules/resolve/lib/async.js:24:18
    at FSReqWrap.oncomplete (fs.js:153:5)

**Comment by tscott-au** [comment]
Coming back to look at this today, the build now works, which is great!
After installing brunch globally, the issue persisted. Now after my computer has re-booted the issue is gone.

So for my situation the brunch build failure on Windows Linux Subsystem (ubuntu) was resolved by:
1) install brunch globally:  sudo npm install -g brunch
2) re-boot computer.

This was stopping me from using the Elixir PhoenixFramework http://phoenixframework.org/ - using this toolset is where I first detected the issue.

**Comment by tscott-au** [comment]
Re-opening this issue as have re-encountered it with a new pc, globally installing brunch has not fixed the issue.
The global install of brunch, that initially fixed my old pc is no longer working on it either.
All other details remain as per original report.

**Comment by froberg** [comment]
I had a problem with  **Improperly-cased** for my phoenix javascript files on  a new project.
It took some time but I finally realised that my current path in the Ubuntu terminal was **/mnt/c/Projects...** instead of the actual path **/mnt/c/projects...**.

I guess as unix is case insensitive you are allowed to go to a directory using capital letters even though it should be lowercase but it then caused problem for brunch. 

Maybe that can help someone.
/c

**Comment by mguidetti** [comment]
I Was having the same issue that froberg mentioned, and renaming my project's path the lowercase fixed it. Funny bug. Maybe this can help? https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/

**Comment by FVolral** [comment]
I had a very similar issue using Cygwin and fish shel and I understood how it happened in my case. The path to my project folder contains few upper and lower cases. For instance : 

`/cygdrive/c/My_projects/FOO/my_project`

but when I'm typing my `cd` commands to reach the folder using fish shell, this one allows me to do this : 

`cd cygdrive/c/my_projects/foo/my_project`

fish will not complain if I do that but for brunch it seems that the path is now wrong. brunch config doesn't matter in my case.
