### ISSUE TITLE
Brunch Watch not reloading css bundle

### ISSUE THREAD

**Issue by clarknelson** [brunch/brunch#1825]
My brunch-config.js

    files: {
        javascripts: {joinTo: 'scripts/app.js'},
        stylesheets: {joinTo: 'styles/app.css'}
    },

When I edit a partial scss file such as _about.scss, I get the following in console while running brunch watch.

    info: compiled in 75 ms

But when I save the only non-partial file 'main.scss', which @imports all of the partial scss files, I get the following message.

    info: compiled main.scss and 4 cached files into app.css in 389 ms

Hopefully you can see how this would be frustrating, and how someone could think it is related to caching. I believe this had been working for me, and I think it does on other projects, but I would love to fix it.

**Comment by paulmillr** [comment]
roll back to sass-brunch 2.10.5

**Comment by clarknelson** [comment]
I think it is working! Thank you so much 😌

**Comment by coolemur** [comment]
Hi.

Brunch is not compiling scss after I save js files.
(After I save scss file, css is compiled successfully.)

Is additional configuration needed for triggering css compilation after js save?

I tried both versions 2.10.5 and 2.10.8 .

**Comment by clarknelson** [comment]
I believe by default (based on the console messages) that only javascript is compiled when JS files are saved. Look at the config options for watcher / hooks to try and implement something yourself. https://brunch.io/docs/config#watcher

**Comment by coolemur** [comment]
Any ideas on how to trigger js or css recompilation with hooks?

```
  hooks: {
    onCompile(generatedFiles, changedAssets) {
      // RECOMPILE CSS ONLY ?
    }
  }
```

**Comment by clarknelson** [comment]
@coolemur that could easily create a loop! I think you might want to reconsider why you want that code and what you are trying to accomplish.
