### ISSUE TITLE
[Q] Is  BrunchWatcher persistency accessible in plugin?

### ISSUE THREAD

**Issue by Arcesilas** [brunch/brunch#1836]
Hi,

Is it possible to know the persistency of the BrunchWatcher in a plugin?
I'd like to know if the command was `brunch build` or `brunch watch`: the plugin needs to be executed only when brunch is watching.

**Comment by paulmillr** [comment]
Yes. config is passed to plugins. Hence, check config.persistent.

**Comment by Arcesilas** [comment]
Thanks! Did not figure out it was in the config...
