### ISSUE TITLE
How to show thumbnails below the slider

### ISSUE THREAD

**Issue by CharanjeetE** [brunch/brunch#1838]
### Description

I want to show slides thumbnails below the slider. How can I achieve this. Please help me to solve this issue.
Please see the example given below image

### Expected behavior
Thumbnails below slider.

### Actual behavior
![screenshot from 2019-02-18 17-22-22](https://user-images.githubusercontent.com/45280571/52949397-2c274380-33a2-11e9-9e7d-4af01161f334.png)

### `package.json` contents

```json
```

### brunch config contents

```javascript
```

**Comment by paulmillr** [comment]
unrelated to brunch
