### ISSUE TITLE
No assets being copied to public folder.

### ISSUE THREAD

**Issue by jcothron** [brunch/brunch#1840]
### Description
None of the assets are being copied to the public folder when running brunch build. I've tried a couple of the skeleton projects and a different computer with the latest of both node and brunch. This was working fine yesterday. Window 10 OS. VS Code terminal and or Windows command prompt.

this is one of the skeleton projects:

package.json:
{
  "name": "brunch-app",
  "description": "Brunch.io application",
  "private": true,
  "author": "Brunch",
  "version": "0.0.1",
  "repository": "",
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {},
  "devDependencies": {
    "auto-reload-brunch": "^2",
    "babel-brunch": "~6.0",
    "babel-preset-latest": "^6",
    "brunch": "^2",
    "clean-css-brunch": "^2",
    "uglify-js-brunch": "^2"
  }
}

brunch.config.js

// See http://brunch.io for documentation.
exports.files = {
  javascripts: {
    joinTo: {
      'vendor.js': /^(?!app)/, // Files that are not in `app` dir.
      'app.js': /^app/
    }
  },
  stylesheets: {joinTo: 'app.css'}
};

exports.plugins = {
  babel: {presets: ['latest']}
};

**Comment by paulmillr** [comment]
reinstall brunch

**Comment by jcothron** [comment]
> reinstall brunch

That's the first thing I tried. And just to be sure I did it again; still doesn't do anything.

**Comment by paulmillr** [comment]
what about removing and reinstalling node_modules? we've just released file watcher update; it had a bug yesterday that could have caused this - which has been fixed since

**Comment by jcothron** [comment]
I completely removed node/npm and deleted all folders in Program Files, as well as AppData; in other words removed everything from my system. Then reinstalled the latest of everything; still no love.

Node: 11.12.0
NPM: 6.7.0
Brunch: 2.10.17

Note - I just downgraded to Brunch@2.10.16 and it is creating the public folder and copying index.html.
