### ISSUE TITLE
Add plugin type for pre-processors

### ISSUE THREAD

**Issue by paulmedynski** [brunch/brunch#1841]
### Description
I'm using `js-preprocess-brunch` (a compiler plugin), `tslint-brunch` (a linter plugin), and `typescript-brunch` (a compiler plugin).  Brunch will run the linters first, and then the compilers.  However, the pre-processor should run first, then linters, then compilers.  Can we add a pre-processor plugin type that returns the post-processed `File`, and slot it after `getDependencies()` and before `lint()`?

### Expected behavior

Pre-processing occurs before linting.  Source files that contain pre-processor directives, for example in `js-preprocess-brunch` format, cause linter errors, whereas the post-processed file content does not.

### Actual behavior

Linting occurs before pre-processing, resulting in spurious errors.

### Environment

1. Brunch: 2.10.17
1. Node.js: 11.6.0
1. NPM: 6.5.0-next.0
1. Operating system: Linux
1. Code editor: Emacs

**Comment by paulmillr** [comment]
Yep
