### ISSUE TITLE
infinite recursion occurring in vendor.js when using mobx

### ISSUE THREAD

**Issue by mwkaufmann** [brunch/brunch#1844]
I cannot use mobx together with brunch due to a "too much recursion" error.

I have investigated the issue and the problem lies in the following line (in the automatically generated vendor.js file):

> require.alias("mobx/lib/mobx.js", "mobx/lib/mobx.js");

Both names are the same. Hence, when the alias is expanded, an infinite loop is created.
If I remove the offending line, everything works fine.

Here is the corresponding package.json:

> {
>   "name": "brunch-app",
>   "description": "Brunch.io application",
>   "private": true,
>   "author": "Brunch",
>   "version": "0.0.1",
>   "repository": "",
>   "scripts": {
>     "start": "brunch watch --server",
>     "build": "brunch build --production"
>   },
>   "dependencies": {
>     "@babel/preset-env": "^7.4.4",
>     "@babel/preset-react": "^7.0.0",
>     "after-brunch": "0.0.5",
>     "babel-preset-react": "^6.24.1",
>     "mobx": "^5.9.4",
>     "mobx-react": "^5.4.3",
>     "react": "^16.8.6",
>     "react-dom": "^16.8.6",
>     "react-router-dom": "^5.0.0"
>   },
>   "devDependencies": {
>     "auto-reload-brunch": "^2",
>     "babel-brunch": "7.0.1",
>     "babel-preset-latest": "^6",
>     "babel-preset-mobx": "^2.0.0",
>     "brunch": "^2",
>     "clean-css-brunch": "^2",
>     "uglify-js-brunch": "^2"
>   }
> }

If you point me towards the right direction, I might be able to fix this bug. Thank you for creating and working on brunch. the JS build ecosystem is terrible without it. :)

**Comment by lpolito** [comment]
Having the same issue.

From my research it looks like this wasn't just a brunch issue, but other bundlers have fixed it since. I was hoping for more of a fix than a "fork mobx" sort of fix.

**Comment by lpolito** [comment]
Dug some - turns out the issue springs from `commonjs-require-definition`.

See: https://github.com/brunch/brunch/blob/master/lib/utils/modules.js#L51

Inside `commonjs-require-definition` there's this function (`expandAlias`): https://github.com/brunch/commonjs-require-definition/blob/master/require.js#L46-L48

This is where the self-referential springs. If there was a check against itself, say:
```js
var expandAlias = function(name) {
    return (aliases[name] && name !== aliases[name]) ? expandAlias(aliases[name]) : name;
};
```
then everything goes swimmingly.

I will be forking `commonjs-require-definition` to open a fix.
