### ISSUE TITLE
Files content erased after changing with brunch watcher

### ISSUE THREAD

**Issue by wissem-cheriguene** [brunch/brunch#1854]
### Description

When I start a new project and launch a build  then the server with the watcher ( brunch watch --server ) I have a weird behavior.
When I make changes on my html / css files the watcher or my editor (dont know which one??) erase the content of the file in the build folder public so the browser cant see the changes and I need to rebuild each time to re-update the files.
My problem seem similar to the issue #1303 and I tried all the solutions proposed there.
My packaged are updated and I also tested with the plugin browser-sync-brunch.
I search on multiple issues related to this type of problem but I can't determine why I got this weird problem...

### Environment

1. Brunch: 3.0.0
1. Node.js: v12.16.2
1. NPM: 6.14.4
1. Operating system: Linux mint 18
1. Code editor: VSC
1. browser-sync-brunch@0.0.9

### `package.json` contents

```json
{
  "name": "brunch-app",
  "description": "Brunch.io application",
  "private": true,
  "author": "Brunch",
  "version": "0.0.1",
  "repository": "",
  "scripts": {
    "start": "brunch watch --server",
    "build": "brunch build --production"
  },
  "dependencies": {},
  "devDependencies": {
    "browser-sync-brunch": "*",
    "brunch": "*",
    "clean-css-brunch": "^3",
    "sass-brunch": "^3.0.0",
    "terser-brunch": "^4"
  }
}
```

### brunch config contents

```javascript
module.exports = {
    files: {
      javascripts: {joinTo: 'app.js'},
      stylesheets: {joinTo: 'style.css'},
    }
  }

exports.plugins = {
    browserSync: {
        files: ['*']
    }
};

exports.watcher = {
    usePolling: true,
    awaitWriteFinish: true
};
```

**Comment by paulmillr** [comment]
It can be related to the browsersync plugin. Try disabling it and see what happens.

**Comment by Wiss69** [comment]
Thanks @paulmillr but I already try without it and I have the same results.
