### ISSUE TITLE
Add a DIGEST feature because digest-brunch is not up to date

### ISSUE THREAD

**Issue by solisoft** [brunch/brunch#1855]
### Description

Do you plan to add a DIGEST feature ? 

The digest-brunch plugin is not up to date and is unmaintained. I can't install nodejs > v10  because of it. 

https://github.com/mutewinter/digest-brunch

It would be nice to have this feature back working on the latest nodejs v12+

**Comment by paulmillr** [comment]
yes, it would be nice to have

**Comment by reubano** [comment]
There is [cachebust-brunch](https://github.com/nerevu/cachebust-brunch) and [fingerprinter-brunch](https://github.com/paulcsmith/fingerprinter-brunch).

**Comment by solisoft** [comment]
Ah nice !

**Comment by reubano** [comment]
I also created [nerevu/cachebust-brunch](https://github.com/nerevu/cachebust-brunch).

**Comment by paulmillr** [comment]
Thanks @reubano, you're awesome!

**Comment by paulmillr** [comment]
tracking in #1455
