### ISSUE TITLE
brunch-config.js is missing

### ISSUE THREAD

**Issue by Dynzels** [brunch/brunch#1857]
### Description

Hello,

When I run the "brunch new project_name" command, the brunch-config-js file is missing while building my base project.

Is this normal?

Brunch v.3.0.0
![Capture d’écran du 2020-07-24 11-50-33](https://user-images.githubusercontent.com/32323118/88379899-f57a0780-cda3-11ea-8b76-b09be9d5e480.png)

**Comment by Dynzels** [comment]
I must necessarily add it manually. It's embarassing.

**Comment by paulmillr** [comment]
brunch config is optional since brunch 3.0
