### ISSUE TITLE
Cleanup old issues

### ISSUE THREAD

**Issue by sandstrom** [brunch/brunch#1861]
Maybe you could cleanup some old issues in this repo?

One neat thing is to enable 'discussions' for the repo, and move + close issues that aren't really issues into the discussions tab (or simply close them and ask them to re-open any discussion there if needed).

A few examples of issues that can probably be closed:

https://github.com/brunch/brunch/issues/1813
https://github.com/brunch/brunch/issues/1824
https://github.com/brunch/brunch/issues/1822
https://github.com/brunch/brunch/issues/1807
https://github.com/brunch/brunch/issues/1808

**Comment by paulmillr** [comment]
done, thx

**Comment by sandstrom** [comment]
@paulmillr I understand there is more work for you, but I think there are a bunch of other issues that could be closed (these were just some that I found at the first page of issues).

This is a healthy project, but with so many open issues it may inadvertently seem like a non-healthy one.

**Comment by paulmillr** [comment]
@sandstrom i'll work on this right now

**Comment by paulmillr** [comment]
Done!

**Comment by sandstrom** [comment]
awsome @paulmillr 🎉
