### ISSUE TITLE
brunch new does not work anymore

### ISSUE THREAD

**Issue by boehs** [brunch/brunch#1886]
### Description

All `brunch new` commands do not work

### Expected behavior

`brunch new` works

### Actual behavior

```
13:44:51 - info: Cloning git repo "git://github.com/brunch/dead-simple.git" to "~/.brunch/skeletons/9dfacf90"...
13:44:51 - error: Git clone error: Error: Command failed: git clone git://github.com/brunch/dead-simple.git "/home/evan/.brunch/skeletons/9dfacf90"
Cloning into '/home/evan/.brunch/skeletons/9dfacf90'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
````

### Environment

N/A

### `package.json` contents

N/A

### brunch config contents

N/A

### Other useful files, when present (log, `bower.json` etc.)

Already attached

**Comment by minemax-ua** [comment]
I have the same issue. Whatever I try, I just can't start a project. Always the same error: fatal: unable to connect to github.com:
github.com[0: 140.82.121._]: errno=Connection timed out
