### ISSUE TITLE
Config to exclude files

### ISSUE THREAD

**Issue by Ni0rd** [brunch/brunch#189]
It would be nice if we could exclude somes files and folders to the generation.

For example:

<pre>
  files:
    'scripts/app.js':
      languages:
        '\.js$': languages.JavaScriptLanguage
        '\.coffee$': languages.CoffeeScriptLanguage
        '\.eco$': languages.EcoLanguage
      order:
        before: [
          'vendor/scripts/file.js'
          'vendor/scripts/file2.js'
          'vendor/scripts/file3.js'
        ]
        after: [
          'vendor/scripts/file4.js'
        ]
      not: [
        'vendor/scripts/file5.js'
        'vendor/folder/'
      ]

    'styles/app.css':
      languages:
        '\.css$': languages.CSSLanguage
        '\.styl$': languages.StylusLanguage
      order:
        before: ['vendor/styles/normalize.css']
      not: ['vendor/styles/deprecated.css']

</pre>

**Comment by istr** [comment]
I would like to re-open this. Having only an "include this" facility may lead to extremely clumsy patterns. Having a "do not include that" facility leads to smaller / cleaner configs and alleviates integrating components (e.g. less-based CSS toolkits) that have internal dependencies not following the ```_``` convention.

**Comment by es128** [comment]
https://github.com/brunch/brunch/blob/master/docs/config.md#conventions and negated globs (starting with `!`) are two additional options for accomplishing that.

**Comment by istr** [comment]
Tried ```conventions.ignored``` with globs -- did not work (only with REs in ```conventions.ignored```). Negated globs in ```path``` did not work out, neither. See an example that works for me in https://github.com/brunch/brunch/issues/720.
