### ISSUE TITLE
4.0.2: project never finishes compiling

### ISSUE THREAD

**Issue by cxw42** [brunch/brunch#1892]
### Description

My project compiles in brunch 4.0.1, but brunch 4.0.2 says "compiling" and never finishes.

### Repro steps

1. Clone https://github.com/cxw42/cricket-scoreboard
2. `git checkout a845bae`
3. `rm -rf node_modules ; npm install && npx brunch b`
  * Observed: `info: compiled 19 files into 2 files, copied 5 in 598 ms`
4. `npm update`
5. `git diff`
  * Observed: brunch has gone from `4.0.1` to `4.0.2`
7. `rm -rf node_modules ; npm install && npx brunch b` (repeat step 3)
  * Observed: `compiling`, `compiling.`, `compiling...`, ... forever

### Environment

1. Brunch Version: 4.0.2
2. Node.js Version: 10.19.0
9. NPM Version: 6.14.10
10. Operating system: Ubuntu 20.04.5 LTS

### `package.json` contents

```json
{
  "name": "cricket-scoreboard",
  "version": "0.0.1",
  "description": "A cricket scoreboard OSD for a US audience",
  "main": "index.js",
  "scripts": {
    "start": "npx brunch watch -s",
    "doc": "npx yuidoc -o doc -x .git,public .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "p": "npx prettier --cache --write ."
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/cxw42/cricket-scoreboard.git"
  },
  "author": "Christopher White",
  "license": "BSD-3-Clause",
  "bugs": {
    "url": "https://github.com/cxw42/cricket-scoreboard/issues"
  },
  "homepage": "https://github.com/cxw42/cricket-scoreboard#readme",
  "dependencies": {
    "snapsvg": "^0.5.1",
    "two.js": "^0.8.10",
    "wcag-contrast": "^3.0.0"
  },
  "devDependencies": {
    "brunch": "^4.0.2",
    "prettier": "^2.8.3",
    "yuidocjs": "^0.10.2"
  }
}
```

### brunch config contents

```javascript
module.exports = {
    paths: {
        watched: ["3rdparty", "app", "test", "vendor"],
    },
    files: {
        javascripts: {
            joinTo: {
                "libraries.js": /^(?!app\/)/,
                "app.js": /^app\//,
            },
        },
        //stylesheets: {joinTo: 'app.css'}
    },
};
```
Thanks very much!

**Comment by paulmillr** [comment]
The only thing that changed was anymatch. Not sure how it's related.

**Comment by cxw42** [comment]
Thanks for the quick response!  I was very surprised as well.  Nothing in the [changelog](https://github.com/brunch/brunch/compare/4.0.1...4.0.2) jumped out at me.

I went back and forth several times between 4.0.1 and 4.0.2 before opening this issue and the behaviour is consistent on my system.

(And, by the way, brunch is still the best!  I was looking at other packagers recently but didn't find anything better in terms of simple workflow plus built-in `watch -s` :) .)

**Comment by paulmillr** [comment]
could you please re-install your project, and brunch on your system from scratch and tell if it solves it?

**Comment by cxw42** [comment]
Yep, after `npm cache clean --force`, it compiles normally with 4.0.2.  Sorry for the bother!  (I didn't know until today that npm _had_ a cache!)

**Comment by paulmillr** [comment]
@cxw42 seems like that happened because I messed up an upgrade of async-each!

**Comment by cxw42** [comment]
Glad to know there was a reason :) .
