### ISSUE TITLE
Brunch should exit after running "brunch build"

### ISSUE THREAD

**Issue by KyleAMathews** [brunch/brunch#273]
Right now it doesn't, it just sits. Which isn't the expected behavior and is a regression from previous versions.

**Comment by rstacruz** [comment]
This still happens for me. using `brunch build -j 4 --production` works, but `brunch build` doesn't.

https://github.com/rstacruz/halla/blob/4960eabd8f5b9a844a064cbc9e73c914b56b23b6/brunch-config.js

**Comment by paulmillr** [comment]
@shvaikalesh

**Comment by christiansakai** [comment]
What is happening to @rstacruz also happening to me.

**Comment by brandonweiss** [comment]
Also happening to me.

**Comment by troygilbert** [comment]
Happening to me as well. It sometimes terminates cleanly after a few seconds, but now seems like it's hanging indefinitely. A similar thing has happened with me in the past, I think it's a node loop not terminating. Hard to debug.

**Comment by paulmillr** [comment]
Folks, let me know if github version fixes it. It shoult.

**Comment by brandonweiss** [comment]
That fixed it for me!

**Comment by doryphores** [comment]
Any plans for a release that includes the fix?

**Comment by jacksonrayhamilton** [comment]
I agree, a release with this fix would be real nice!

**Comment by paulmillr** [comment]
We are planning to spin-off a new release as soon as we'll get the stable version in place. This should be quick.

**Comment by paulmillr** [comment]
live now. update to 2.9
