### ISSUE TITLE
Different environment setups

### ISSUE THREAD

**Issue by ghost** [brunch/brunch#332]
As we all know we usually have different settings for the development and production environment.

In development I want to use vendor scripts with debug.

In production I want to use minified vendor scripts.

It doesn't seem to be a good way to define this in the config file.

Is it a missing feature?

Are there any suggestions on how we could do this, for now?

**Comment by migore** [comment]
I used this plugin and it worked great!

https://github.com/rcs/jsenv-brunch

Just leaving this here in case someone gets here before finding that plugin like I did. :)
