### ISSUE TITLE
Improve speed

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#351]
I want to make brunch the fastest build system.

@damassi what exact speed issues do you have? What compilation time says? (`info: compiled in 70ms` etc)

**Comment by phillipp** [comment]
@paulmillr Not sure if that's the project size (186 jsx component files), but my initial build (babel + react) is 75s to 100s and changing one file in the watcher is 1 to 1.5s.

Is that expected?

**Comment by paulmillr** [comment]
100s for first build is fine if the project is big.

1.5 seconds when changing one file seems bad. Could you open a new issue clarifying your plugins, project, brunch / node version, machine config etc?
