### ISSUE TITLE
Watch function intermittently stops compiling 

### ISSUE THREAD

**Issue by shaneharter** [brunch/brunch#354]
Paul -- This is similar to the issue I reported in the now-closed bug on Thursday. 
1. I start `brunch watch` -- both with a server and without
2. I use an IDE that rsync's to the server on save. 
3. Before 1.3.3 every time I saved the file, the `watch` would fail: It would result in an empty file in the `/public` directory. Now, it's intermittent. Perhaps once every 5 times I save. 
4. Updating the source file (resaving or touch'ing it) does look like it's triggering `watch` to recompile, but it never fixes the empty output issue. 
5. Restarting the `watch` fixes it.

**Comment by jarkonik** [comment]
Setting usePolling option to true, which is documented here: https://github.com/brunch/brunch/blob/master/docs/config.md helps in case of modifying files using sshfs.

**Comment by charlesdeb** [comment]
I am still getting intermittent non-recompiles running Ubuntu 16.04, editing in VSCode 1.20 and using brunch 2.10.12. Kind of annoying. I usually need to add a space/blank line to the .less file I am working on once or twice before it will recompile. it is happening on a local machine and file system.

**Comment by fatcop** [comment]
http://brunch.io/docs/troubleshooting

**Comment by charlesdeb** [comment]
Thanks @fatcop, adding the `watcher` clause to my brunch config as mentioned in the troubleshooting doc you linked to seems to have fixed it.
