### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wnm** [brunch/brunch#404]
Hi there.

I updated brunch to the newest version recently. I tried to change something on an older project today, but always get "Uncaught RangeError: Maximum call stack size exceeded". Even when i change it back, to the way it was and the way it work, the new compiled files with the new brunch version doesnt work.

I'm on Ubuntu, brunch is 1.4.3

let me know if you need more infos,

Wolfram

**Comment by hgwood** [comment]
Stumbled upon something like thid today, and finally found a hint to the solution here: http://bloodandcode.com/2015/08/angular-maximum-call-stack-size-exceeded-when-switching-to-new-route/.

By default, the brunch server will serve `index.html` for any unknown path it is requested. This can lead to applications requesting templates and getting back `index.html` instead, which will load a new instance of the app and start an infinite loop. This happens with the Angular.js router for example.

The solution was to set `server.noPushState` to `true` in the brunch config.
