### ISSUE TITLE
How does brunch support i18n?

### ISSUE THREAD

**Issue by ShuoC** [brunch/brunch#468]
Hi, there,

Is there any lib that provides some built-in i18n support with brunch?

Thanks a lot,
Shuo

**Comment by KevinGaudin** [comment]
I'm interested in that question too, I'd like to use brunch to generate a mostly static website in 4 languages. For SEO, we need these 4 languages to be indexed, so they should be in generated html files.

Has anyone used this kind of logic since 2013 ?
