### ISSUE TITLE
Brunch doesn't let plugins take control of storage

### ISSUE THREAD

**Issue by monokrome** [brunch/brunch#557]
Brunch assumes that a plugin's compile() method needs to pass data to a callback. This is almost always correct, but there are rare cases (most commonly with templates) where a plugin might need to build static files or something else and they don't want to write something through brunch's callback.

In these cases, it would be nice if could pass a specific value as the second argument to the callback (maybe something like false) to tell brunch that no error has occured, but my plugin is going to handle storing this specific document instead of brunch.

I am wishing that I had this feature do to a recent project that I created because brunch/jade-brunch doesn't support static file rendering. I wrote my own which does. Here's an example of where I'd like to use this feature:

https://github.com/monokrome/jaded-brunch/blob/master/src/index.coffee#L110

**Comment by lalomartins** [comment]
Here via #916 — see also #1007 

As far as I can see, in the time since, the module is no longer created if I pass an empty string (which I've done for jade-static).

**Comment by monokrome** [comment]
Thanks, @lalomartins. I'll give it a try in `jaded-brunch` :)

**Comment by lalomartins** [comment]
So no, I was wrong, empty modules are still created — I wasn't seeing them because my templates.joinTo was unset ;-)

That said, if you pass in none or undefined, dependencies aren't tracked, as discussed in #916, so for now it's still better to have the empty modules…

**Comment by monokrome** [comment]
@lalomartins I think that it's better to leave it as is for now instead of having unnecessary code running in production, but mostly because this issue should be solved on the brunch side.

**Comment by lalomartins** [comment]
Agree with the sentiment, and I'll probably start a branch soon (I've been looking at the pipeline sources already).

That said: in my project I'm using the forked version that returns `''`, and I dealt with the unnecessary generated code by joining it to a dummy.js file that never gets referenced by the html.

**Comment by monokrome** [comment]
@lalomartins That's a clever solution for use in the meantime! :)
