### ISSUE TITLE
Do something with bower assets

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#633]
1. do something with files specified in `main` that are not compiled
2. don’t treat as assets `assets`-matching bower components (`bootstrap/docs/assets/boostrap.js`)

**Comment by gcatto** [comment]
What's the latest on this front? It seems like some (most?) bower assets are being copied over from my admittedly limited experience. For Bootstrap though, I am having an issue with glyphicons-halflings-regular.woff2 specifically not being copied over (although the other glyphicons-halflings files are being copied over).

**Comment by jhabdas** [comment]
Believe NPM includes now supported. Might be a good alternative to Bower.

**Comment by jhabdas** [comment]
See previous suggestions on symlinking for use with Bootstrap / FontAwesome

**Comment by gcatto** [comment]
Hmmm yes, thanks! Apparently I did that already and totally forgot about it and that's why things are being copied over and a slight bug in what I did prevented it from getting all of the files. Go me! Nothing to see here...

**Comment by mathilde-pellerin** [comment]
I agree, it will be awesome to have some common solution with a simple brunch configuration. But I think it will be more than tricky. For example, I face this issue with angular-ui-grid component which has it fonts and svg files directly on root, foler! No folder font, neither assets...
bower.json: 
```
{
  "name": "angular-ui-grid",
  "description": "A data grid for Angular",
  "main": [
    "./ui-grid.css",
    "./ui-grid.eot",
    "./ui-grid.js",
    "./ui-grid.svg",
    "./ui-grid.ttf",
    "./ui-grid.woff"
  ],...
```

**Comment by johnjarrard** [comment]
@mathilde-pellerin - Did you ever figure out how to handle the fonts for Angular-ui-grid?  I'm dealing with the exact same issue right now.

**Comment by cmelgarejo** [comment]
When using phoenix (phoenixframework.org) and using brunch I tried to use the "material-design-iconic-font" bower package install (providing as dependency in bower.json, in my root phoenix project) but it didn't copied the fonts to the /static (brunch's path.public dir) So, I grabbed an existing plugin and modified it to work a little better and came up with this, I hope helps anyone out here :smile: 

https://www.npmjs.com/package/copycat-brunch

just follow the readme.md examples :+1:

**Comment by paulmillr** [comment]
We are shutting our efforts of adding more bower features and suggest everyone to switch to NPM, which would be enabled by default in the next major Brunch release.

**Comment by yuchunc** [comment]
Thank you @cmelgarejo!! Your solution work beautifully!
