### ISSUE TITLE
Stylesheet dependency compilation/watching

### ISSUE THREAD

**Issue by mdlawson** [brunch/brunch#681]
When watching a LESS or Stylus (and presumably others) stylesheet that includes other stylesheets, brunch should, but currently doesn't:
1.) When a child stylesheet changes, rebuild the parent.
2.) When a stylesheet is a dependency of another stylesheet, don't try and build it separately.

As far as I can see, brunch already has the data to do this, via progeny. The desired end result is to be able to have stylus/less manage the assembly of their parts of the stylesheet, but also have brunch detect changes appropriately and rebuild the correct file.

**Comment by fab1an** [comment]
I have this exact same problem. I recently switched to postcss and now brunch doesn't watch my included css-files anymore. What is the way to solve this, without switching to yet another build-system :(( ?

**Comment by es128** [comment]
@fab1an probably not the *exact* same issue, as this one was resolved long ago. Sounds like the postcss plugin is neglecting to report dependencies/includes to Brunch, but you should open a separate issue about it in the plugin's tracker.
