### ISSUE TITLE
Should Brunch compile Node.js modules to AMD, Common.js, Node.js and Browser-compatible single file?

### ISSUE THREAD

**Issue by kmalakoff** [brunch/brunch#713]
We recently launched [BackboneORM](http://vidigami.github.io/backbone-orm/) which needs to run in the Browser and in Node.js.

I [modified Brunch's module system](https://github.com/vidigami/backbone-orm/blob/master/client/require.js) in a way similar to how [Superagent](https://github.com/visionmedia/superagent/blob/master/superagent.js) delivers a AMD, Common.js, Node.js and Browser-compatible single file. Basically, you would define a local module system and then expose the root symbol and its dependencies in multiple loader-compatibile formats:

```
if (typeof exports == 'object') {
  module.exports = require('backbone-orm/lib/index');
}
else if (typeof define == 'function' && define.amd) {
  define('backbone-orm', ['underscore', 'backbone', 'moment', 'inflection'], function(){return require('backbone-orm/lib/index'); });
}
else {
  window.bborm = require('backbone-orm/lib/index');
}
```

Also, I added a shim method so the bundle can [load dependencies](https://github.com/vidigami/backbone-orm/tree/master/test/web) from AMD, [Browserified](http://browserify.org/), or pull things off of window when loading in the browser. 

```
if window?
  require.shim([
    {symbol: '_', path: 'lodash', alias: 'underscore', optional: true}, {symbol: '_', path: 'underscore'}
    ...
   ])
```

Do achieve this, I combined a [grunt script](https://github.com/vidigami/backbone-orm/blob/master/Gruntfile.coffee) and [Brunch config](https://github.com/vidigami/backbone-orm/blob/master/client/brunch_config.coffee). 

I think it would be reasonably simple to add some library building config options to Brunch; for example, listing AMD dependencies. What would you think about adding this support natively to Brunch?

Input: Many files including CoffeeScript which use of Common.js
Output: AMD, Common.js, Node.js and Browser-compatible single file

**Comment by pjanik** [comment]
Any update on that? I would say it's pretty important, as lib generated by Brunch can't be used in the environment that uses RequireJS too (conflict of `require` implementations).

The final, concatenated source could be wrapped in UMD definition (https://github.com/ForbesLindesay/umd) what would be pretty simple.
However dependencies still would need to be resolved somehow. So `commonjs-require-definition` could be used, but without exporting its `require` implementation to global namespace (it would be used locally, in scope of this file only).

Perhaps two new options would need to be added to Brunch config:

- name of exported bundle (argument for UMD)
- name / path of the module that should be exported

What do you think?

**Comment by es128** [comment]
Brunch has historically been meant for building web apps, not libs, so this hasn't been _that_ important for the type of use-cases Brunch typically targets.

That said, your implementation suggestion seems reasonable, and PR welcome. I would suggest that the starting point of the implementation should be to add a `umd` option to the existing [modules config object](https://github.com/brunch/brunch/blob/master/docs/config.md#modules) and work out the remaining details from there.

**Comment by kmalakoff** [comment]
I've started using webpack instead for library packaging. 

Before that, I also tried writing some gulp modules to wrap this, but it becomes a little bit of a Rabbit hole when you start getting into things like optional dependencies, universal support including repackaging by browserify and webpack (static analysis will not accept an internal require solution that uses the keyword require. Example: https://github.com/kmalakoff/knockback/blob/master/knockback.js), etc.

I think the key decision here is either to have Brunch fully commit to all the edge and use cases of libraries packaging including compatibility with browserify and webpack OR to restrict itself to being an application builder. It is choice.

**Comment by impleri** [comment]
Even as an application builder, it's problematic. For example, I'm trying to set up an application now using goatslacker/alt on top of reactjs. However, I'm running into an issue where alt uses require differently and that leads to a broken frontend centering on the different usage of `require()` (alt performs `require("flux")` which fails because the various UMD-wrapped components end up attaching to window instead of the existing `require()` implementation. So either I've got to roll my own wrapper or return to putting everything in the global namespace.

**Comment by paulmillr** [comment]
npm integration is here, so this is kinda up too.

**Comment by pcattori** [comment]
@paulmillr could you explain what you mean by your last comment: 

> npm integration is here, so this is kinda up too.

Has library packaging in Brunch been abandoned?

**Comment by paulmillr** [comment]
Why do we need it if everyone's going towards NPM nowadays?

**Comment by pcattori** [comment]
I was hoping to write a React library with Brunch.

The idea is to write my components in `app`, have Brunch build this into a single `js` file (using Babel with `react` and `es2015` presets) that would act as the `main` for my NPM package.

Is this something I should be able to do with Brunch?

**Comment by paulmillr** [comment]
yeah we'll need to investigate different ways of solving this problem. i've meant that "AMD" and "browser-compatible" files are no longer really needed. Something to bundle it to one commonjs module would be useful.

**Comment by pjanik** [comment]
@pcattori, I'd rather look at babel compiler and/or webpack. If you publish your package to npm, you might not necessarily want to concatenate it into single file - then use babel compiler directly just to translate it to ES5. Webpack can easily built UMD package that can be published. I've switched to these tools and they seems to be really popular in React's world.

**Comment by pcattori** [comment]
@pjanik following your advice, I stuck to using pure Babel + NPM scripts to translate my library **without** concatenating and publishing the unconcatenated package. I then use Brunch with the React skeleton in an app that depends on my library. Things work perfectly :) Much appreciated!
