### ISSUE TITLE
brunch new . testapp fails (recursive copying?)

### ISSUE THREAD

**Issue by julienaubert** [brunch/brunch#806]
I want to do have a .travis.yaml in my skeleton, and would like to do `brunch new . testapp` while in the directory. However, seems there is some recursive bug when copying locally. I have also tried brunch new `pwd` `pwd`/testapp and that fails to.

git clone https://github.com/julienaubert/brunch_knockout 
cd brunch_knockout
brunch new . testapp

27 Feb 14:21:56 - log: Copying local skeleton to "testapp"...
27 Feb 14:21:57 - error: Error: Error: ENAMETOOLONG, unlink '/Users/julien/Downloads/brunch_knockout/testapp/testapp/testapp/testapp/testapp/testapp/testapp/testapp/testapp/<repeat....>/testapp/testapp/app/assets/apple-touch-icon-precomposed.png',

**Comment by paulmillr** [comment]
gh-959 would fix this
