### ISSUE TITLE
Handling prod vs. debug dependencies?

### ISSUE THREAD

**Issue by dougmoscrop** [brunch/brunch#839]
Ember is my example - they have `ember.js` which is their `main` but it contains debug logging, assertions, etc. and they also have `ember.prod.js` which is simply faster. It's not about minification or anything, but code literally omitted from their source.

Is there a straightforward or workaround way to do this with Brunch without having to bower override? Ideally via. `brunch build` vs. `brunch build --production`

My expectation is no, unless and until Bower starts supporting/encouraging some kind of notation in `bower.json`

**Comment by mattmccray** [comment]
React is the same way. It includes perf tools and debug support that's not in the production build.

So what is the work around? Is there one short of something horrible like having a build script that modifies bower.json, runs brunch build --production, then reverts it?

**Comment by es128** [comment]
@mattmccray there are several potential workaround approaches, but anything I can think of will feel ugly until Brunch adds the ability to do `env`-specific bower overrides. 

One maybe slightly better approach than the one you described would be to use bower overrides to list the dev AND prod include files as `main`, then set `env`-based `ignore` settings to exclude the dev files from prod and vice versa.

**Comment by mattmccray** [comment]
@es128 That does sounds better. I can't tell from the docs exactly how to do the `ignore` step. Would it be something like this (using React as an example)?

```coffeescript
overrides:
  production:
    conventions:
      ignored: 'bower_components/react/react-with-addons.js'
  development:
    conventions:
      ignored: 'bower_components/react/react-with-addons.min.js'
```

**Comment by mattmccray** [comment]
For those who may care, I had to do this to get it working:

```coffeescript
  overrides:

    production:
      conventions:
        ignored: [
          'bower_components/react/react-with-addons.js',
          ]

    development:
      conventions:
        ignored: [
          'bower_components/react/react-with-addons.min.js',
          ]
```

This is still a bit of a hack, obviously. But it's better than munging config files on every build.

**Comment by es128** [comment]
The bare strings didn't work like in your earlier example?

**Comment by paulmillr** [comment]
We have NPM overrides and Bower overrides now.

**Comment by jahbini** [comment]
'We have NPM overrides'  -- documented?

**Comment by paulmillr** [comment]
http://brunch.io/docs/using-modules On the bottom, albeit shitty

**Comment by jahbini** [comment]
That specifically is for Bower overrides; in my past experience, it has been perilous to assume the semantics are equivalent.

my current work-around is to create a Backbone 'hatrack' module visible to the window, and have all the 'requires' done by the initialization and hung there.  Other modules that i write get their dependencies from the hatrack.  no require, no headache.

**Comment by paulmillr** [comment]
Same for npm
