### ISSUE TITLE
Turn CommonJS wrapper off for one JS file

### ISSUE THREAD

**Issue by plum-dawg** [brunch/brunch#869]
Hey,

in my project I have a directory mapped to output into one js file which I do NOT want wrapped, however, I would like my other JS files to be wrapped. is there a way to just exclude one on brunch build? 

Thanks!

**Comment by roblafeve** [comment]
@Plummat would you mind sharing your solution? I'm struggling with the same issue.

**Comment by es128** [comment]
@roblafeve it would be something like this:

```coffee
modules:
  wrapper: (path, data) ->
    if path is 'app/special.js' 
      data 
    else
      """
require.define({#{path}: function(exports, require, module) {
  #{data}
}});\n\n
      """
```

or in vanilla:

```js
  modules: {
    wrapper: function(path, data) {
      if (path === 'app/special.js') {
        return data;
      } else {
        return "require.define({" + path + ": function(exports, require, module) {\n  " + data + "\n}});\n\n";
      }
    }
  }
```
(note that the syntax highlighter here is having some trouble with the string concatenation)

**Comment by roblafeve** [comment]
@es128 Thanks! Good to know I was heading in the right direction :+1:
