### ISSUE TITLE
Warnings on config override

### ISSUE THREAD

**Issue by ocombe** [brunch/brunch#878]
I'm using the override option to create a specialized build of my app that doesn't include all my libs from bower_components (almost, but not all), and when I watch it with the `--env` setting I get a lot of warning `26 Sep 11:39:48 - warn: 'bower_components\.....' compiled, but not written. Check your javascripts.joinTo config.`
I know that it doesn't use all my libs, it's intentional. Is there anything I could do to remove those warnings in my override ? It's really annoying...
I've checked the brunch source code but there doesn't seem to be an option for that. I only found the `config.notification` hidden option that doesn't work or doesn't apply to those warnings...

**Comment by metatalker** [comment]
Hey, how can I suppress  "xxxxx compiled, but not written. Check your javascript.joinTo config.

**Comment by es128** [comment]
Make your `paths.watched` match the same paths you actually intend to include in your build.
