### ISSUE TITLE
brunch build should complete regardless of fileListInterval

### ISSUE THREAD

**Issue by justenwalker** [brunch/brunch#889]
An issue was reported on the forums by @frykke. I don't think the issue has been addressed yet since I have experienced it in the latest build (1.7.18). It seems like it was introduced in v1.7.14 as I can reproduce it there as well, but I cannot reproduce in 1.7.13.

To summarize: `brunch build` doesn't compile files that are too deeply nested in the directory structure. `brunch watch` does not have this problem.

* **Affected Brunch Versions**: `1.7.14` to `1.7.18`
* **OS Version**: `Linux ubuntu-14 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`
* **Node Version**: `v0.10.33`

[Forum Post](http://ost.io/@brunch/brunch/topics/131):

> I have a problem using brunch build. All files are not included in the compilation. It seems to me that it misses all files in folder deeper down in directory structure. If I instead run brunch watch, my missing files will be included. If I move all files to a folder closer to the root - it also will work fine. Example:
> ```
C:\Work\MyApplicationFolder> brunch build
10 Jun 17:03:49 - info: compiled 15 files and 1 cached into 3 files, copied 5 in 2516ms
10 Jun 17:03:53 - info: compiled 131 files and 3 cached into 2 files, copied index.html in 4476
```
> All files in the C:\Work\MyApplicationFolder\app\views\templates are excluded.
```
C:\Work\MyApplicationFolder> brunch watch -s
Listening to: 3333
11 Jun 09:11:45 - info: compiled 218 files and 1 cached into 5 files, copied 5 in 8170ms
Running watch, all files in the C:\Work\MyApplicationFolder\app\views\templates are included.
```
> Move the MyApplicationFolder one level up...
> ```
C:\MyApplicationFolder> brunch build
10 Jun 17:02:31 - info: compiled 217 files and 1 cached into 5 files, copied 5 in 10678ms
```
> Running build, and all files in the C:\Work\MyApplicationFolder\app\views\templates are included. 
> I am using brunch version brunch@1.7.14

**Comment by Xample** [comment]
The problem is still here, I increased the fileListInterval, it's better but it is still not deploying all the time (it fails ~10% of the time). I am running this script in a very sensible context and therefore this issue is a critical problem. Is there any way to prevent caching once for all ?

**Comment by goshakkk** [comment]
@Xample are you still encountering the issue on the latest brunch? If so, do you think you can find a more consistent way to reproduce this? Also share more details about your environment, possibly a sample app that does demonstrate the issue... anything that would help us nail it?

**Comment by frykke** [comment]
Hi,
this issue was something related to the project/environment at this specific time. I’m not currently involved in this, so I’m sorry to say I can’t help in this case now.
/Mats F.

**Comment by Xample** [comment]
@goshakkk we recently changed the server, instead of using jenkins we are now on gitlab and as far as I can remember, we did not experience the same problem again (still I am not myself deploying all the time) it however should still persist. Also this is hard to make a toy example as it requires a lot of files dependencies which might not be cached properly, then to my understanding only big project are facing this issue…
