### ISSUE TITLE
Brunch watch is not detecting code changes

### ISSUE THREAD

**Issue by jvannistelrooy** [brunch/brunch#890]
After using brunch for almost a year, the `brunch watch` function suddenly stopped detecting my file changes today. If I run `brunch watch`, I get the normal `info: compiled X files...` message without errors, but after updating one of the files, nothing happens. If I stop brunch watch and then run it again, the changes I made before are compiled fine.

My setup:
- I run VirtualBox on a Windows host machine with help of Vagrant
- I use brunch 1.7.18 on Ubuntu 12.04.5

I've tried to update all NPM dependencies, and also reloaded and even rebuilt my vagrant box. Nothing seems to work.

How can I debug this issue?

**Comment by ahomatthew** [comment]
Bump, having this issue with Mac OS X + Vagrant running Brunch 1.8.5.  Saving the file on the host does not cause watch to rebuild, saving the file directly in Vagrant does trigger the event.  usePolling: true, does fix the issue, but wondering if the real issue has any resolve?

**Comment by es128** [comment]
> wondering if the real issue has any resolve?

There is no "real issue". This is a limitation of the OS. `usePolling` is the proper solution.

If https://github.com/paulmillr/chokidar/issues/242 ever gets resolved it will make this situation easier by automating the proper settings by default. But it isn't an easy straightforward thing to do.

**Comment by lucian303** [comment]
Having this exact same issue with brunch 2.4.2. No changes are ever detected even to the brunch.config.coffee and usePolling: true doesn't do anything. 1.7.19 works for me. 1.8.5 logs the change events when using `brunch w -d` but doesn't recompile or reload the browser. So definitely between there something got messed up and in 2.4.2 and I assume any other version 2, it doesn't even work at all. I'd test more versions from npm, but npm takes so incredibly long to install. Also, doing npm update obviously has problems and can't be relied upon to install dependencies clean.
