### ISSUE TITLE
Just copy html files which are in the same directory of source files

### ISSUE THREAD

**Issue by wb14123** [brunch/brunch#900]
I'm writing a AngularJS app and its structure is like this:

```
app
├── app.coffee
├── home
│   ├── home.coffee
│   └── home.tml.html
└── index.html
```

I'd like to copy all the html files into `public/` as the structure, but I don't want to copy other files like `*.coffee`. I don't see a way to do this in Brunch.

**Comment by pikeas** [comment]
Bump. Considering using Brunch for a new project, and this would be a problem. Is there a workaround for this issue?

**Comment by es128** [comment]
Haven't been able to reproduce the issue. The solution I described ought to work.

**Comment by jukebox017** [comment]
I also couldn't get the regex to work for `assets`

This brunch plugin will compile HTML files outside of the assets directory, works like a charm:
https://github.com/tolyo/html-pages-brunch
