### ISSUE TITLE
Big compilation time for partials

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#906]
Structure:

```
app/
  styles/
    # lots of _partials
  _all.styl
  style1.styl  # 1. specify all variables. 2. @import _all.styl
  style2.styl  # 1. specify all variables. 2. @import _all.styl
```

#### only style1
09 Jan 22:35:20 - info: compiled 159 files into 4 files, copied 103 in 11415ms

#### both; even though partials are same
09 Jan 22:35:44 - info: compiled 160 files into 5 files, copied 103 in 13223ms

20% time diff — not cool

**Comment by es128** [comment]
What's the time diff if you cut out brunch and use stylus directly?

**Comment by es128** [comment]
stylus's fault for using fs sync methods, right?
