### ISSUE TITLE
Build fails with strange error.

### ISSUE THREAD

**Issue by nbunney** [brunch/brunch#909]
I am a brunch newbie but think this one is strange.

$ brunch b

events.js:72
throw er; // Unhandled 'error' event
^
Error: ENOTDIR, open '/.../vendor/**autoload.php/bower.json'**

Does it think that /vendor/autoload.php is a directory that it should look for bower.json inside of? This has me a little amazed.

I started with brunch new gh:GulinSS/brunch-bower-site .

config.js

    exports.config = {
      conventions: {
        ignored: /^(vendor.*\.less|.+node_modules.+|.+_.+\..+)$/
      },
      modules: {
        definition: false,
        wrapper: false
      },
      paths: {
        "public": '_public'
      },
      files: {
        javascripts: {
          joinTo: {
            'js/app.js': /^app/,
            'js/vendor.js': /^vendor/
          },
          order: {
            before: ['vendor/console-polyfill/index.js']
          }
        },
        stylesheets: {
          joinTo: {
            'css/app.css': /^(app|vendor)/
          }
        },
        templates: {
          joinTo: {
            'js/templates.js': /.+\.jade$/
          }
        }
      },
      plugins: {
        jade: {
          options: {
            pretty: true
          }
        },
        bower: {
          extend: {
            "bootstrap": 'vendor/bootstrap/docs/assets/js/bootstrap.js',
            "angular-mocks": [],
            "styles": []
          },
          asserts: {
            "img": /bootstrap(\\|\/)img/,
            "font": /font-awesome(\\|\/)font/
          }
        }
      }
    };

Any help appreciated

**Comment by es128** [comment]
A lot about this report is quite strange. Why is it deciding to open a path that starts with `/.../`? Do you have any symlinks in your project? Is there an `autoload.php` file in your `vendor` dir?

**Comment by es128** [comment]
Closing for lack of response
