### ISSUE TITLE
Run server command before plugins?

### ISSUE THREAD

**Issue by teddybradford** [brunch/brunch#910]
While trying to get BrowserSync to work with a PHP server via the Brunch server command (set in config), I discovered that BrowserSync breaks because it tries to connect to the proxy server prior to it actually being started.

Relevant config:
```cson
plugins:
  browserSync:
    logLevel: "debug"
    port: 3333
    proxy: "localhost:8000"

server:
  command: "php -S localhost:8000 -t public"
```

And the log:
```
[BS] [debug] Looking for an empty port...
[BS] [debug] Using port 3333
[BS] [debug] Checking if you're online
[BS] [debug] Resolved www.google.com, setting online: true
[BS] [debug] Proxy running, proxing: http://localhost:8000
[BS] [debug] Running mode: PROXY
[BS] Proxying: http://localhost:8000
[BS] Now you can access your site through the following address:
[BS] Local URL: http://localhost:3333
[BS] [debug] Getting option: socket.path
[BS] [debug] Getting option: socket.namespace
[BS] [warn] Proxy address not reachable - is your server running?
25 Jan 14:53:50 - info: compiled 6 files into 3 files, copied 3 in 326ms
[BS] Reloading Browsers...
```

I managed to get around this issue by adding a server script to my `package.json` file:

```json
"server": "php -S localhost:8000 -t public & npm start"
```

However, it would be nice if I didn't have to do this to make things work. Is this an issue that would need to be resolved in Brunch itself or in the BrowserSync Brunch plugin?

**Comment by es128** [comment]
Brunch *does* kick off the server first, but it does so asynchronously. Is the issue that the php server is slow to start up?

You might petition the maintainer of the browsersync plugin to define an `onCompile` method in the plugin, which starts up the browsersync server the first time it's called, or something like that.
