### ISSUE TITLE
Brunch strange behaviour with Intel XDK

### ISSUE THREAD

**Issue by hyyan** [brunch/brunch#915]
Hi , Thanks for the great ,

I am trying to use brunch 1.7.20 with Intel XDK to build htm5 project , but I counter what Ii think a bug in brunch

I have a controller.js file which should be outputed to app.js file when , now I edit the controller.js , brunch output that changes in my file has been detected and cache into app.js file but when I open
the final file app.js I don't find the content of the controller.js , which is really strange 

One think i need to mention too , that this problem is random but it happens with no errors and it happens only when I use intel SDK 

Any idea ? thanks in andvance

**Comment by es128** [comment]
This is complete speculation, but it sounds like the SDK or something in your stack is writing out some of your files as blank at the time Brunch is reading them. 

It's possibly worth investigating whether any improvements could be made in the handling of source file changes detected at various stages of the compilation pipeline to ensure nothing gets lost.

**Comment by hyyan** [comment]
@es128  You may be write , but I think brunch must complain about or show a note of any kind about a file that has been read and which not empty and it has not been outputted for some reaseon ,

**Comment by hyyan** [comment]
@es128  It is definitely something related to brunch , I have just tried grunt and the problem disappeared ,  I am no trying to compare here of course I am doing this just for testing , I love brunch a lot and I'd like to help but I don't know how I can help to fix this issue .

**Comment by es128** [comment]
Can you share a repo with a minimal reproducible case?

**Comment by hyyan** [comment]
@es128  the project I am working on is a private porject but here is what I am using if this can help

[Brunch With OnsenUI](https://github.com/hyyan/brunch-with-onsenui)
[Intel XDK] (https://software.intel.com/en-us/html5/tools)

The idea is simple , I create new porject in intel XDK which point to ```www``` dir and then I  write my code and let brunch handle it.

I hope this helpfull ? I am ready to do anything which could help .

Thanks for replay

**Comment by es128** [comment]
I don't have time to figure out how to set up your stack, so in order to be able to help diagnose what's going on I need you set up a repo (without your private code) and/or provide a very simple set of instructions I can use to reproduce your problem case.

**Comment by hyyan** [comment]
@es128  You can use [Brunch With OnsenUI](https://github.com/hyyan/brunch-with-onsenui) repo it does not need anything special or a set of instructions in order to wok , it is just a normal brunch skeleton . cloned and run brunch watch

For Intel XDK , you have to download it from their site after that just opened the repo that you have cloned and try to edit any file while brunch watch is running tow or three times and you will see that brunch detect changes and output success message but it does not write the changed files .

I think that brunch can't grant file lock to output the changed file because it is opened in other IDE , but no helpful messages from brunch to make sure
