### ISSUE TITLE
dependencies of static (plugin-handled) jade files not tracked

### ISSUE THREAD

**Issue by nerdoc** [brunch/brunch#916]
I'm using brunch 1.7.20 with node.js v0.10.29 under Debian sid.
I have a simple project with a couple of jade files and some js/coffee files.
Using jaded-brunch, my main *index.static.jade* file contains a line 'include _section-content'. The file *_section-content.jade* is included and works (just contain a jade mixin).

If I start `brunch watch --server`, I can see a recompile triggered when I change the *index.static.jade* file. But If I change the *_section-content.jade* file, nothing happens in the console log, and my web page does not update.
package.json part:
```
  "dependencies": {
    "auto-reload-brunch": ">= 1.0 < 1.8",
    "clean-css-brunch": ">= 1.0 < 1.8",
    "css-brunch": ">= 1.0 < 1.8",
    "jaded-brunch": "^1.7.13",
    "javascript-brunch": ">= 1.0 < 1.8",
    "uglify-js-brunch": ">= 1.0 < 1.8"
  }
```

I have seen issue #528, but at least for me this seems not to be fixed.
Could this be an issue with jaded-brunch or is it brunch itself (or a misconfiguration on my side)?

**Comment by nerdoc** [comment]
I also already saw brunch/jade-brunch#5 - this seems to address the issue - but it is not fixed here IMHO. Is this a jaded-brunch issue or a brunch issue?

**Comment by es128** [comment]
It's an issue with jaded-brunch, and is specific to its handling of static files. If you make it a regular `.jade` file to be compiled into your javascript, you will see that changing the dependency does trigger recompilation.

**Comment by es128** [comment]
To be fair, its handling of .static.jade files is a workaround for a limitation in brunch - namely that it assumes all templates will be compiled to javascript - and that is probably the underlying cause.

Still, it may be possible to tweak the workaround to fix the dependency handling, perhaps by providing blank javascript content in response to the request to compile the .static.jade files, just so Brunch will understand how to handle the source file in its normal pipeline.

Or maybe there's a possible fix within Brunch itself. Will keep this issue open in the meantime.

**Comment by monokrome** [comment]
@es128 I think that brunch should be able to handle these cases, so it feels like a brunch issue to me. Jaded is giving the right dependencies to brunch and brunch knows what file needs to be built. Something is happening here where brunch just stops paying attention to things when a file passes back `null` as the compiled data.

I think that there may be an ordering issue where the watching for dependency changes is happening too late in the process. Is that possible? I think that the important thing here is to decide whether this is an issue that brunch wants to tackle or whether I should support a workaround for the issue in `jaded-brunch`.

**Comment by es128** [comment]
I agree that it's a brunch issue, but it's a larger issue than just this matter of dependency management as the plugin-handled file writing that jaded-brunch utilizes is something that was sort of tacked on, not treated as a first-class feature.

I'd expect the whole methodology for doing this to change in a future brunch release to address that issue, and it would likely require changes in jaded-brunch to leverage the new APIs. More specifically, I think plugins should be able to accomplish their goals without having to directly write files, and brunch will need to evolve to support that principle.

In the meantime, it's possible that changing jaded-brunch to pass an empty string or something else benign like a semicolon would fix the current issue with dependency tracking without changes in brunch. I haven't tested this theory yet, but unless someone gets to it first I might give it a shot and submit a PR to jaded-brunch.

**Comment by dnalot** [comment]
> In the meantime, it's possible that changing jaded-brunch to pass an empty string or something else benign like a semicolon would fix the current issue with dependency tracking without changes in brunch.

I was thinking the same thing :+1:

**Comment by monokrome** [comment]
This brings us back to the reason why the feature was created in the first place, however. https://github.com/brunch/brunch/issues/557#issuecomment-17785676

**Comment by es128** [comment]
Yup you're right. It's a problem that's never been given proper attention. 

Your hunch about the ordering issue is probably right as well. PR welcome if you can identify a fix obviously. I'll try to dig into it too when I get a chance.

**Comment by monokrome** [comment]
Do you know where I can look specifically? I've had a hard time figuring out what brunch is doing.

**Comment by es128** [comment]
https://github.com/brunch/brunch/blob/9989aec4ef498244a7a554fb92e7c6b55e33e828/src/fs_utils/pipeline.coffee#L56

This short-circuit is probably what's preventing the normal dependency handling from being processed.

**Comment by monokrome** [comment]
Thanks a bunch, @es128. I'll see if I can help. :)

**Comment by lalomartins** [comment]
I just fixed this for jade-static-brunch: https://github.com/stephenhutchings/jade-static-brunch/pull/1 — tl;dr returning an empty string does fix it. A quick look at jaded-brunch shows it's returning undefined (by calling `callback()`), which tells brunch nothing was compiled; so brunch doesn't ask for dependencies, which makes sense.

What we need is to remove those hacks, really, by adding first-class support for compiling source files to html (or maybe to arbitrary non-concatenated files). I guess file a separate issue?

**Comment by goshakkk** [comment]
For what it's worth, we have some new developments wrt static compiler API. Please check this comment of mine on a similar thread https://github.com/brunch/brunch/issues/1007#issuecomment-218193017
