### ISSUE TITLE
Brunch File Lock Issue

### ISSUE THREAD

**Issue by hyyan** [brunch/brunch#919]
Hey , I believe brunch sometimes fails to get file locks to update the project files . but it is not complaining about that and is not showing any kind of errors  ,

I am using netbeans to watch my www dir which must be auto generated by brunch but if any file in the www dir is opened by netbeans , brunch fails to update that opened file .

This issue is similar to the issue opened by me #915 , but I preferred to open another issue cause it is not random any more 

Note : I am using the `gh:brunch/dead-simple` skeleton

Thanks in advance

**Comment by es128** [comment]
Do you know of a way to make a reproducible case? Is there a way in node to set a file lock on win32?
