### ISSUE TITLE
brunch watch does not check if stdin was closed

### ISSUE THREAD

**Issue by josevalim** [brunch/brunch#920]
I would like to automatically run `brunch watch` as part of my application but, when my application shuts down, the brunch process persists and continue running. I have observed that my application does close STDIN, however, `brunch watch` is not checking if STDIN was closed or not. Those two lines solve the issue:

    process.stdin.on('end', function() { process.exit(0) });
    process.stdin.resume();

I would love to send a pull request for this, the question is: should we always run this or should we make it opt-in?

**Comment by es128** [comment]
You're running it as a child process? http://nodejs.org/api/child_process.html#child_process_child_kill_signal

**Comment by josevalim** [comment]
I am not running it using node. I am running on the Erlang VM which does not expose the OS Process API as node.js does (in fact, neither does the Java VM last time I checked. It is common for VMs to not expose those operations as it is hard to provide an unified API across multiple OS and hardware).

Closing the stdin as a signal is a very common mechanism in Unix utilities. Given how widespread Unix ideas are in node.js, I am surprised this behaviour isn't more common. :) Here is one example from our beloved `cat`:

```
$ cat -
hello
CTRL-D
```

`node` supports it too:

```
$ node
> 1 + 1
2
> CTRL-D
```

After this patch, `brunch watch` would support it too. :)

**Comment by josevalim** [comment]
Another reason for listening to stdin is because the OS will eventually close it if the parent process dies, guaranteeing safe termination of the child process. Relying on kill signals can be very dangerous because, if the parent process dies due to an unexpected reason (segfault, no memory, etc), it may leave orphan child processes.

**Comment by es128** [comment]
Sending Unix signals is pretty standard too. Like any other node program, Brunch does what it is supposed to do when sent a SIGTERM or SIGINT.

That said, if this remains problematic for you, go ahead and open the PR. I'm not sure it needs to be behind an option - can't think of where else this may affect someone (that they close stdin and want it to keep running)

**Comment by josevalim** [comment]
PR incoming!
