### ISSUE TITLE
Wrong URL in `brunch new`

### ISSUE THREAD

**Issue by pikeas** [brunch/brunch#927]
brunch new
    21 Feb 14:38:52 - error: Error: You must specify skeleton (boilerplate) from which new app will be initialised.
    
    You can specify directory on disk, Git URL or GitHub uri (gh:user/repo):
    
    brunch new <path-or-URI> [optional-output-dir]
    brunch new gh:paulmillr/brunch-with-chaplin
    
    Some suggestions:
    ...
    
    All other skeletons (40+) are available at
    http://git.io/skeletons

The bottom URL should presumably be http://brunch.io/skeletons

**Comment by yavorsky** [comment]
@pikeas The syntax is `brunch new <skeleton-URL>`. So you need to choose skeleton before creating project. 
Ex.: `brunch new gh:brunch/dead-simple`

**Comment by yavorsky** [comment]
@pikeas thanks.

**Comment by pikeas** [comment]
@yavorsky Yes, I understand that. Please note the copy at the end of my paste - it claims that skeletons are available at http://git.io/skeletons . This is incorrect, there is nothing at that URL, and should be changed to the correct URL we both pasted.

**Comment by es128** [comment]
Hmm the git.io url used to work, I guess they made a breaking change to that service. Yeah I suppose it should just become the brunch.io one.

**Comment by paulmillr** [comment]
Fixed.
