### ISSUE TITLE
Brunch web server not accessible outside of localhost

### ISSUE THREAD

**Issue by EvanMcEwen** [brunch/brunch#929]
I'm not sure if this is an issue then more of a question. Running the brunch server right now tells me the server is available on localhost:3333 but I want to specify it to be 0.0.0.0:3333 so that outside connections can hit it. Is this possible right now with brunch? The dev machine is separate from the device on which the single page application is viewed.

EDIT:
I should mention no firewalls are running locally and I am pingable. The device is on the same internal network as the brunch server.

**Comment by es128** [comment]
Have you tried it? The console message does say `localhost`, but the [hostname actually isn't specified](https://github.com/paulmillr/pushserve/blob/master/index.js#L58) when starting the server, which [should be the equivalent of 0.0.0.0](http://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback)

**Comment by EvanMcEwen** [comment]
If this is indeed the case then something else is up. Might be an OS X thing. I'm running Mavericks and although the firewall is indeed turned off there could be something else at play. Appreciate the response; helps in my debugging.

**Comment by es128** [comment]
Ok, closing this for now, but let us know if you track it down to an issue in Brunch (or, more specifically, [pushserve](https://github.com/paulmillr/pushserve))

**Comment by bradobro** [comment]
@es128 I dug into this and found it's basically fixed, but needs a version bump on pushserve to display the message correctly (and docs).

Details:

1. Bunch 1.8.3 passes through the configuration `server.hostname` to pushserve.
1. Pushserve 1.6 correctly uses the hostname, but doesn't incorporate @yavorsky's fix to display it properly, so still logs `application started on http://localhost:3333/` even though it correctly binds to `0.0.0.0` when I tested.

What's needed, I think:

1. A pushserve 1.6.1 incorporating @yavorsky's fix.
1. ...and a matching bump in brunch's `package.json`
1. Revised docs.

I can't do the first, but glad to PR the last two once it's done.

**Comment by DavidMikeSimon** [comment]
:+1: The output is still misleading, but the info in @bradobro's comment was enough for me to configure my brunch server to behave the way I wanted.

**Comment by nicooga** [comment]
Hi there, how I'm supposed to use the `server.hostname` option? If I modify my brunch config to include that key, `brunch watch --server` exists inmediately with no error message.

~~~coffee
module.exports =
  server:
    hostname: 0.0.0.0
  files:
# ...
~~~

**Comment by nicooga** [comment]
Also, I'm confused. @bradobro says this works with pushserve 1.6.x but the latetest release version of pushserve is 1.0.2.

**Comment by paulmillr** [comment]
@nicooga try server: config: hostname

**Comment by nicooga** [comment]
Nopes, no luck with `server: config: hostname:` either.

**Comment by shreeve** [comment]
Another option is to use the new `-n` option (shown below). If you pass this to `brunch watch`, then it will listen on all public interfaces.

```shell
brunch watch --help

  Usage: watch [options] [path]

  Watch Brunch directory and rebuild if something changed. Shortcut: w

  Options:

    -h, --help             output usage information
    -e, --env [setting]    specify a set of override settings to apply
    -p, --production       same as `--env production`
    -s, --server           run a simple http server for the public dir on localhost
    -n, --network          if `server` was given, allow access from the network
    -P, --port [port]      if `server` was given, listen on this port
    -d, --debug [pattern]  print verbose debug output to stdout
    -j, --jobs [num]       parallelize the build
    --stdin                listen to stdin and exit when stdin closes
```

**Comment by eeach** [comment]
@nicooga 

`module.exports = {
    [...]

    server: {
        hostname: '0.0.0.0',
    },

    [...]
}`
