### ISSUE TITLE
Node V12 Issues

### ISSUE THREAD

**Issue by HFreni** [brunch/brunch#931]
I Just Upgraded to V12, and when Installing I got an error. 

Harrisons-Mac-Book-Pro-4:~ hfreni$ npm install -g brunch
 
> fsevents@0.3.5 install /usr/local/lib/node_modules/brunch/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:38:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:41:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:52:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:99:15)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/brunch/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.5
/usr/local/bin/brunch -> /usr/local/lib/node_modules/brunch/bin/brunch
brunch@1.7.20 /usr/local/lib/node_modules/brunch
├── anysort@1.0.0
├── debug@0.7.4
├── async-waterfall@0.1.5
├── commonjs-require-definition@0.1.2
├── async-each@0.1.6
├── commander@2.0.0
├── ncp@0.4.2
├── mkdirp@0.3.5
├── init-skeleton@0.2.4 (rimraf@2.2.8)
├── loggy@0.2.0 (growl@1.7.0, ansi-color@0.2.1, date-utils@1.2.16)
├── anymatch@1.0.0 (minimatch@1.0.0)
├── coffee-script@1.8.0
├── source-map@0.1.43 (amdefine@0.1.0)
├── read-components@0.6.1 (component-builder@0.10.1)
├── pushserve@0.1.6 (connect-slashes@0.0.11, express@3.3.8)
└── chokidar@0.12.6 (readdirp@1.3.0)

**Comment by es128** [comment]
Despite the messages, brunch will work fine at the end of an install that looks like this.

But if you want to resolve it install the XCode command-line tools.
