### ISSUE TITLE
Un-deprecate the -c option

### ISSUE THREAD

**Issue by josevalim** [brunch/brunch#933]
Can we un-deprecate the -c option? Sometimes we need to run brunch not from the current directory and the only way to do it and load the proper config file is using the `-c` option. So it is useful beyond the environment configuration that has been discussed.

**Comment by es128** [comment]
How about an option to specify the project dir instead?

**Comment by josevalim** [comment]
Yup, that would work too!

**Comment by es128** [comment]
@josevalim please give #934 a try

**Comment by josevalim** [comment]
Works great, thanks!

**Comment by MaffooBristol** [comment]
I've wanted to see this option in the past too actually. Good going :+1:
