### ISSUE TITLE
Bower support for multiple apps

### ISSUE THREAD

**Issue by anthon** [brunch/brunch#935]
Brunch's support for multiple apps is working like a charm, but ideally it would also support multiple Bower instances:

```
backend/
    assets/
    scripts/
    styles/
    vendor/
    bower_components/
    bower.json
frontend/
    assets/
    scripts/
    styles/
    bower_components/
    bower.json
server/
    ...
public/
config.coffee
package.json
```

Right now, `my_app/bower_components` gets picked up by the compiler, but the content isn't run through read-components.

Please correct me if I'm wrong, or if there's a workaround way to solve this.

**Comment by es128** [comment]
At the moment Brunch is *not* really designed to support multiple apps. The support is for multiple build environments. So your options are to either give each of your apps their own `brunch-config` and run them separately or combine your `bower.json`s into one at the parent level and use the environment config to include/ignore the correct ones for each app.

One other possibility is to leverage the as-yet-unreleased `preCompile` hook (#928) to copy the appropriate (per environment flag) `bower.json` file to the parent level before Brunch kicks off its pipeline.

**Comment by anthon** [comment]
> So your options are to either give each of your apps their own brunch-config and run them separately

Thanks @es128, that's my current setup, and it works fine. Just thought I'd voice the idea, since there at least *used to* be an interest in multiple app support (#281).

**Comment by es128** [comment]
Yes, appreciate your thoughts.

I consider multiple apps support to be in scope for Brunch 2.0, but the high-level design needs to be determined before worrying about the kind of detail you're calling out here. What I've thought about so far is that each app will have its own `brunch-config`, but the new feature would be that a single CLI command could kick off several `watch` and/or `build` cycles at once with unified logging and possibly some degree of resource sharing (like the watcher instance) if it can be done in a way that increases efficiency.

**Comment by anthon** [comment]
Since there's already brilliant support for multiple app dirs (distributed `assets/`, `vendor/` etc), it might be easiest to give `read-components` a flexible starting point, like `conventions.assets`?

Anyway, perhaps this is indeed an edge case. Looking forward to 2.0, and I'll ping if I manage to come up with something more concrete.

**Comment by KrishnaPG** [comment]
Has this been implemented? If so, where can one find more information on how to use this feature?

**Comment by es128** [comment]
@KrishnaPG no, this has not been implemented

**Comment by KrishnaPG** [comment]
Thank you @es128 

In the current version, is it possible to make brunch work recursively (e.g., parent folder has a brunch config that specifies the include paths of children brunch configs in their own directories, and when `build` is run on the parent, all children will be built recursively) ? 

Any plugin or workaround will also be helpful.
