### ISSUE TITLE
Possible Memory Leak?

### ISSUE THREAD

**Issue by elbow-jason** [brunch/brunch#937]
```
16 Mar 19:42:11 - info: Reloading watcher...
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
```
I'm using the Phoenix Framework with Elixir which in it's most recent release included brunch to automatically build static assets. I was playing around with the config and restarting the Phoenix server quickly when I got this message. Should I be concerned?

**Comment by elbow-jason** [comment]
Here is the stack trace:

```
Trace
  at Socket.addListener (events.js:179:15)
  at Socket.Readable.on (_stream_readable.js:671:33)
  at bindWatcherEvents (/home/elbow/Prospace/juice/node_modules/brunch/lib/watch.js:567:21)
  at /home/elbow/Prospace/juice/node_modules/brunch/lib/watch.js:636:11
  at /home/elbow/Prospace/juice/node_modules/brunch/lib/watch.js:527:18
  at /home/elbow/Prospace/juice/node_modules/brunch/lib/watch.js:178:14
  at /home/elbow/Prospace/juice/node_modules/brunch/node_modules/async-each/index.js:24:44
  at /home/elbow/Prospace/juice/node_modules/brunch/lib/watch.js:165:16
  at FSReqWrap.cb [as oncomplete] (fs.js:228:19)
```

**Comment by es128** [comment]
It probably isn't problematic (in fact, I think recent versions of node have dropped this EventEmitter warning), but I don't really understand the circumstances under which you made this happen. Brunch restarts its internal processes upon a config or package.json change, so I was guessing that if you do that enough times you can end up binding too many listeners to the the watcher's events, but part of the logic there is to close the prior watcher instance.

If you can provide clearer steps to reproduce it would be helpful.

**Comment by elbow-jason** [comment]
I am using Phoenix Framework which is starting brunch each time it starts up. I restarted the Phoenix server process (which also restarts brunch) repeatedly in quick succession and got this error message. That's really all that was going on at the time. Rapid server restarts.

**Comment by elbow-jason** [comment]
If it happens again I will be sure to better document the exact circumstances of the occurrence. Sorry for being so vague.

**Comment by es128** [comment]
I just tried to reproduce this by touching the config file repeatedly while watch was running, but brunch was able to restart the watcher dozens of times without triggering the event emitter warning.

Closing for now.
