### ISSUE TITLE
Build problem 'EISDIR' in Windows

### ISSUE THREAD

**Issue by kazelsama** [brunch/brunch#938]
sorry for the little text, I do not speak English

###### OS
<pre>Windows 7 x64</pre>
###### node version
<pre>v0.12.0</pre>
###### folders
prices
╠ .sass-cache
╠ app
║╠ css
║╠ img
║╠ js
║╠ sass
║╠ views
║╚ <code>index.html</code>
╠ bower_components
╠ build
╠ node_modules
╠ .gitignore
╠ bower.json
╠ brunch-config.js
╠ config.rb
╚ package.json
###### brunch-config.js
<pre>
exports.config={
	"paths":{
		"watched":["app"],
		"public":"build",
		"compass":"config.rb"
	},
	"files":{
		"stylesheets":{
			"joinTo":"css/app.css",
			"order":{
				"after":[/css[\\/]/]
			}
		},
		"javascripts":{
			"joinTo":"js/app.js",
			"order":{
				"after":[/js[\\/]/]
			}
		}
	},
	"conventions":{
		"assets":[/img/,/index.html/]
	},
	"modules":{
		"wrapper":false,
		"definition":false
	},
	"overrides":{
		"DEV":{
			"optimize":true,
			"sourceMaps":true,
			"plugins":{
				"autoReload":{
					"enabled":true
				}
			}
		}
	}
};
exports.startServer={
	"server":{
		"indexPath":"app/"
	}
};
</pre>
###### bower.json
<pre>
{
  "name": "prices",
  "version": "0.0.0",
  "authors": [
    "kazelsama"
  ],
  "description": "description",
  "main": "app/index.html",
  "keywords": [
    "prices"
  ],
  "license": "MIT",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "jquery": "~2.1.3",
    "angular-material": "~0.8.3",
    "angular-material-icons": "~0.4.0"
  }
}
</pre>
###### error
<pre>
D:\wamp\www\prices>brunch build
22 Mar 13:56:05 - error: Copying of 'app\index.html' failed. Error: EISDIR, open 'D:\wamp\www\prices\build'
</pre>
with verbose
<pre>
brunch:common File copy: Error: EISDIR, open 'D:\wamp\www\prices\build' +43s
</pre>

**Comment by kazelsama** [comment]
I fix it:
in "brunch\lib\fs_utils\common.js"
add:
var path = require('path');
and change line 109:
output = input.pipe(fs.createWriteStream(destination));
with:
output = input.pipe(fs.createWriteStream(destination+path.sep+source.split(path.sep).pop()));
create a pull request? :smile:

**Comment by es128** [comment]
You could, but the question is why was `destination` incorrect to begin with? Also, the edits would need to go into the coffeescript source. 

Btw take not of the pattern in brunch source code to reserve the `path` identifier for other uses: `sysPath = require 'path'`

Also what you're doing there seems like it could be better expressed with something like `sysPath.join destination, sysPath.basename source`

**Comment by kazelsama** [comment]
i use node 0.12, could this be?

**Comment by kazelsama** [comment]
in common.coffee
<code>sysPath.dirname(sysPath.join(destination,sysPath.basename(source)))</code>
ok? :)

**Comment by es128** [comment]
Does that work to fix your issue? Go ahead and open the PR, but we'll still need to evaluate whether this is going to be appropriate for all cases or if it's going to break something else.  

Actually I just realized - when you wrapped it in `sysPath.dirname` the result is just `destination`. I don't really understand what you're trying to accomplish. 

Maybe what's needed is `sysPath.normalize`?

**Comment by kazelsama** [comment]
yep! tnx :sweat_smile:

**Comment by kazelsama** [comment]
mmmh, maybe it's better:
<code>destination = sysPath.normalize(sysPath.join(destination,sysPath.basename(source)))</code>

**Comment by kazelsama** [comment]
the same problem also on ubuntu 14:04
<pre>23 Mar 14:20:17 - error: Copying of 'app/index.html' failed. Error: EISDIR, open 'build'</pre>
and resolves in the same way :)

**Comment by es128** [comment]
Please provide a copy of your config.

**Comment by kazelsama** [comment]
is in my first post :sweat_smile:

**Comment by es128** [comment]
Oh right. I'm wondering about your `conventions.assets` setting. Will check it out.

**Comment by es128** [comment]
Either this has been fixed or needs to be worked out in https://github.com/paulmillr/quickly-copy-file. Closing
