### ISSUE TITLE
Include compiled files

### ISSUE THREAD

**Issue by kazelsama** [brunch/brunch#940]
I can include files compiled as bower? (or in a similar way)
I tried to find a solution but I have not found, did I miss something? sorry :confounded:

**Comment by paulmillr** [comment]
Sorry, could you clarify — do you want to publish the result as bower component?

**Comment by kazelsama** [comment]
typing error:
I can include files compiled as <b>grunt-wiredep</b>? (or in a similar way)
with grunt I compile files and grunt-wiredep put the results in html between 
<pre>
&lt;!-- bower:js -->
&lt;!-- endbower -->
</pre>
There is a similar solution in brunch?

**Comment by paulmillr** [comment]
All bower components are automatically included in your app. You must specify correct paths in brunch config.

Our [default config](https://github.com/paulmillr/brunch-with-chaplin/blob/master/brunch-config.coffee) would totally work in this case.

```
        'javascripts/vendor.js': /^(?!app)/
```

This means files from `bower_components` directory would be included in `vendor.js`.
