### ISSUE TITLE
Add config shims to npm support

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#945]
Let's just release it after a few days of testing

**Comment by jsilvestre** [comment]
I got curious and checked the change log, I saw:
> Added NPM support for client-side libraries.

I would gladly send you a gif of myself doing a famous "dance of joy" if I knew how. I'm really really looking forward to using this!

Thank you very much, Brunch Team!

**Comment by yavorsky** [comment]
@jsilvestre  LOL. We will meet your dance in some bug report's from you :) 
@paulmillr  I think we need to implement ability to specify user's node shims in config. For example user want to use own `util` module. 

*brunch-config.coffee*:
```
paths:
  shims: 
    fs: 'shims/util.coffee'
```
And brunch during loading package dependencies will load this module.

**Comment by es128** [comment]
@yavorsky Should there be a set of default shims, like whatever browserify uses?

:+1: on providing a config interface to allow users to specify their own whether or not brunch ships with a set of defaults

**Comment by yavorsky** [comment]
@es128 Yes. We can use default shims. I think it rather deppack's problem.

**Comment by paulmillr** [comment]
Let's move to gh-1023.
