### ISSUE TITLE
brunch-server.coffee/js

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#948]
Let's treat `brunch-server.coffee` as default server file that would be auto-consumed. Would RADICALLY simplify writing custom servers.

**Comment by paulmillr** [comment]
I always forget whether it's `runserver` `startserver` or something else. How can we simplify that?

**Comment by es128** [comment]
Why does it need a special name? Just export the main function that you expect brunch to run. 

Handling the stop/teardown function intuitively is a bit trickier tho

**Comment by paulmillr** [comment]
>Just export the main function that you expect brunch to run.

`module.exports = fn`? That's awesome. Let's adopt it as default value (w fallback to old ofc).

>Handling the stop/teardown function intuitively is a bit trickier tho

```
server = ->
server.teardown = -> # or server.stop / server.close. Or we can match the value for plugins
module.exports = server
```

**Comment by paulmillr** [comment]
es6 modules don't allow exporting fns like that do they?

**Comment by es128** [comment]
Regarding teardown actually calling the server function should return an object with a `stop` method (or whatever name) - to be more like the node http module. Or we might allow for several of these types of cases. 

Don't know whether es6 modules don't allow this - if they don't we should reconsider this idea. But don't they have some sort of `default` thing? Don't remember atm and on mobile so can't easily research or try it.

**Comment by paulmillr** [comment]
Just looked into es6 modules — meh

>import MyClass from 'MyClass';

Yeah, they allow `default`s — so we're cool.

**Comment by paulmillr** [comment]
dbfebb02bb85f84f2b585b9ff900d66b33ea5295
