### ISSUE TITLE
Allow onCompile to take a 'done' callback to indicate whether its job has been done

### ISSUE THREAD

**Issue by oliverzy** [brunch/brunch#951]
Hi,

Currently onCompile only takes an array of compiled files, but if I would like to do some async work in this function, I have no way to tell it that my async work has been done.

**Comment by es128** [comment]
And you'd want Brunch to wait until the callback is called before outputting the message indicating a build cycle has completed?

**Comment by oliverzy** [comment]
Yes, exactly. If auto-reload is used, it should reload the web page after the callback is called

**Comment by es128** [comment]
auto-reload also leverages `onCompile` so it's interesting to consider how to ensure the order in which these are executed is correct. 

In your case are you using a custom plugin or defining your `onCompile` in config?

**Comment by oliverzy** [comment]
I define my `onCompile` in config file.

Well, you are right. It needs a way to execute in correct order.

**Comment by es128** [comment]
An implementation of #749 which includes a config hook should allow you to accomplish what you want. Closing this issue in favor of that one.
