### ISSUE TITLE
Release 1.8.0

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#953]
* [x] gh-949
* [x] Test on Windows, 1-2 skeletons
* [x] Test on Linux, 1-2 skeletons

**Comment by es128** [comment]
[] Test a skeleton with its bower dependencies switched to npm

**Comment by paulmillr** [comment]
@es128 not critical — npm is a config option until 1.8.1 or sth so we can get more thorough testing and release 1.8.0 today

**Comment by es128** [comment]
Even as an option, what's the point of releasing until we know it at least works in some basic circumstances.
