### ISSUE TITLE
Better errors for bower

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#954]
If there is no bower present, the error should be more comprehensive

**Comment by GesJeremie** [comment]
Are you talking about that kind of errors ? 

```
error: { [Error: Component must have "/Users/Loschcode/Google Drive/projects/erasmusio_lo/app_front/bower_components/underscore/bower.json"] code: 'NO_BOWER_JSON' } 
```

**Comment by paulmillr** [comment]
yes

**Comment by GesJeremie** [comment]
Before to think about how I can code that by myself, what's the best way to solve the error ?

Ofter i just delete the "plugin" in the `bower_components` folder and I run `bower install` in the root folder, is it the best way to fix that ?

**Comment by paulmillr** [comment]
just catch this error https://github.com/paulmillr/read-components/blob/master/index.js#L70 or throw sth more meaningful that says user should run `bower install` etc
