### ISSUE TITLE
Refactor, rewrite in ES6, switch to promises

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#955]
- [ ] Get rid of the curried functions. I'm pretty tired of 1000 wrapped & curried functions here and there, let's see if we can think of a better way which is just as fast
- [ ] Switch from coffeescript to ES6
- [ ] Switch to promises. Investigate performance downside from using them.

**Comment by es128** [comment]
Well yeah... when I've been talking about rewriting in ES6 for 2.0 I didn't just mean a conversion like with decaffeinate. I hopefully have it in me to start getting it out of my head and putting together a new structure reasonably soon now that chokidar has crossed a big milestone. Way more ideas than time to implement them, like always.

**Comment by paulmillr** [comment]
@es128 if we'll find someone to do this for 1.9, why not do it? This will bring more contributors.

**Comment by es128** [comment]
Uh, sure. Are there any volunteers?

**Comment by paulmillr** [comment]
Maybe myself.

**Comment by paulmillr** [comment]
Although not sure about promises — there's some `async` / `await` stuff — but i've never played with it. Need to research it more.

**Comment by es128** [comment]
Yes I've thought about trying generators or trying to do more stream type stuff internally.

**Comment by paulmillr** [comment]
node 4 is out — which brings es6 support to the board. Which means we don't need babel.

**Comment by vendethiel** [comment]
I still think you need babel for es7's await, right?

**Comment by paulmillr** [comment]
yeah — but I don't care about `await` this much.
