### ISSUE TITLE
running brunch b breaks with a chokidar error in version 1.8

### ISSUE THREAD

**Issue by stefanspita** [brunch/brunch#956]
Stack trace:
/usr/local/lib/node_modules/brunch/node_modules/chokidar/index.js:453
    this._closers[watchPath]();
                            ^
TypeError: Property 'app' of object object is not a function
  at EventEmitter.<anonymous> (/usr/local/lib/node_modules/brunch/node_modules/chokidar/index.js:453:29)
  at Array.forEach (native)
  at EventEmitter.FSWatcher.close (/usr/local/lib/node_modules/brunch/node_modules/chokidar/index.js:452:30)
  at writeCb (/usr/local/lib/node_modules/brunch/lib/watch.js:342:17)
  at /usr/local/lib/node_modules/brunch/lib/fs_utils/write.js:156:12
  at /usr/local/lib/node_modules/brunch/node_modules/async-each/index.js:24:44
  at /usr/local/lib/node_modules/brunch/lib/fs_utils/common.js:29:14
  at /usr/local/lib/node_modules/brunch/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:104:5
  at Object.oncomplete (fs.js:108:15)

**Comment by es128** [comment]
Can't reproduce, you're going to have to show us more. Config, package.json, OS, project repo and/or a skeleton you can make this happen with?

**Comment by stefanspita** [comment]
OS - Ubuntu 14.04, node v.0.10.35
npm install -g brunch, npm install -g bower
git clone https://github.com/paulmillr/brunch-with-chaplin
then run npm install, bower install, brunch b
Compilation is successful but then the above error.

**Comment by es128** [comment]
Can't reproduce on Mac, need to set up a new Ubuntu VM so I can try it there.

The error is really weird though - there's nothing in the chokidar code looking for an `app` property

**Comment by stefanspita** [comment]
it seems to refer to line 453, which is 
this._closers[watchPath]();

**Comment by tpetr** [comment]
Seeing this as well when trying to `brunch build` a fresh copy of https://github.com/HubSpot/Singularity/tree/master/SingularityUI -- my theory is it's due to a breaking change in yesterday's [chokidar 1.0.0](https://github.com/paulmillr/chokidar/releases/tag/1.0.0) release.

I was able to temporarily work around this via [npm shrinkwrap](http://stackoverflow.com/a/17423915).

**Comment by paulmillr** [comment]
@tpetr are you on linux too?

**Comment by tpetr** [comment]
@paulmillr Should have included that, sorry. Yep -- CentOS 6.5. Running it on my dev machine (OS X 10.10.2) works fine.

**Comment by paulmillr** [comment]
That's quite unfortunate. Seems like a serious bug.

Installing the virtual machine right now.

**Comment by askaliuk** [comment]
Reproducible Ubuntu 14.04 LTS, node 0.10.25

**Comment by es128** [comment]
Will push out a chokidar 1.0.1 to resolve this momentarily

**Comment by stefanspita** [comment]
Thanks guys

**Comment by tpetr** [comment]
thanks!
