### ISSUE TITLE
Changing bower.json main as entry-point files, not distribution files

### ISSUE THREAD

**Issue by desandro** [brunch/brunch#958]
Hi there!

Head's up: over in bower/bower.json-spec#43 we're looking to settle the specification for `bower.json` `main`:

> The primary acting files necessary to use your package. While Bower does not directly use these files, they are listed with the commands `bower list --json` and `bower list --paths`, so they can be used by build tools.
> 
> The entry-point files necessary to use your package. Only one file per filetype.
> 
> Use source files with module exports and imports over pre-built distribution files.
> Do not include minified files.

From my understanding, Brunch works well when main points to distribution files, not source files. So I wanted to alert you of the issue. And also start a discussion of a proper solution once `main` specification has changed. Perhaps a `files` datapoint, that lists all files that get used, in dependency order, or a `dist` data point that lists distribution files?

**Comment by paulmillr** [comment]
We can use `files` and, if there are no `files` — `main` if that's what the specification wants.
