### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by Cedric-ruiu** [brunch/brunch#962]
Hello,

I'm new with brunch and task runner :). My config is Win7 64, brunch 1.8.0 and notifications never appear.

I try to : 
test on simple project
test with build and watch command
install manually growl for windows
install growl npm https://www.npmjs.com/package/growl
install loggy https://github.com/paulmillr/loggy

I never seen one notifications... But everything else works with brunch!

**Comment by es128** [comment]
https://github.com/brunch/brunch/blob/master/docs/config.md#notifications

http://www.growlforwindows.com/gfw/help/growlnotify.aspx

**Comment by es128** [comment]
Also another tip from https://github.com/tj/node-growl#windows - make sure you've unpacked the growlnotify files into a folder that's in your `PATH` environment variable

**Comment by Cedric-ruiu** [comment]
Little mistake, growlnotify was unpacked in wrong folder... Thank you!
