### ISSUE TITLE
Add defaultEnv to the docs

### ISSUE THREAD

**Issue by dmitrykiselyov** [brunch/brunch#965]
Add a description of [`defaultEnv` property](https://github.com/brunch/brunch/issues/748#issuecomment-30455596) to the [docs/plugins](https://github.com/brunch/brunch/blob/stable/docs/plugins.md).
Thank you!

**Comment by es128** [comment]
oops yeah that should have been documented

Had to lol at the last comment in that thread you linked to (mine, from >1yr ago). Oh well.
