### ISSUE TITLE
Brunch.build() failing after 1.8.0

### ISSUE THREAD

**Issue by matthopson** [brunch/brunch#967]
I've run into an issue after migrating from 1.7.20 to 1.8.x 

We use a deploy script that runs a build and moves changed files to various environments. As of 1.8, the deploy was failing with:

`chdir.call(process, d)
        ^
Error: Bad argument.
  at process.chdir`

Stepping through it, the issue is appearing in `watch.js` around here: `process.chdir(path)`
Sure enough, `path` is set to `{env: 'staging'}`

I did see this recent change, which seems to be the culprit given my current config.
https://github.com/brunch/brunch/blob/9b9e8c5015856eb8e770f050232e092ee88e822e/src/watch.coffee#L576
It's possible I'm overlooking something obvious and this is not a bug - I should mention if I remove the following, everything works as expected.
`if (path) {
    process.chdir(path);
  }`
  It is reproducible in OSX and from within a Vagrant box. (Node 0.10.33)

Thanks!

**Comment by paulmillr** [comment]
Are you using CLI or the node Api?

**Comment by es128** [comment]
Sounds like you're running something like `brunch build d` instead of `brunch build -d`

**Comment by es128** [comment]
Nevermind, just re-read and think I have a better idea of what's going on. Will work on figuring this out today. Also, appears to be the same bug as #957
