### ISSUE TITLE
AMD with custom wrapper

### ISSUE THREAD

**Issue by hyyan** [brunch/brunch#968]
Hey 

I am trying to use a custom wrapper for my AMD modules , something simple like this : 

```coffee
  modules:
    definition: 'amd'
    wrapper : (path, data) -> """(function(angular){#{data}})(window.angular);\n\n"""
```

All modules  follow a pattern like this : 

```js
var deps = [
     'deps1',
     'deps1'
     .....
]

define(deps,function(){
    
  // code goes here
  return something ;
});
```

But brunch output is not what I expect : 

```js
(function(angular){

var deps = [
     'deps1',
     'deps1'
     .....
]

define(deps,function(){
    
  // code goes here
  return something ;
});

})(window.angular);
```

As you can see the module name is missing ? what I am doing wrong here ?

Thanks in advance

**Comment by es128** [comment]
Use `#{path}` wherever you want the module name to go in your wrapper. I'm not sure the structure you've come up with is going to allow you to easily accomplish what you want. As-is, you'd probably need to write code to parse `data` and inject the module name where you want it. Usually the wrapper handles the `define` part.

Closing the issue as Brunch is behaving as expected.

**Comment by hyyan** [comment]
@es128  Thanks for making things clear , I've seen this pattern used in a lot of projects , and I want to know if it can work with Brunch .

**Comment by es128** [comment]
It could be done. But Brunch won't magically mess with your code to inject module names the way you seemed to be hoping for.

**Comment by hyyan** [comment]
@es128 Yes , is is clear now , I don't want to do crazy things , in order to make a pattern works , brunch is already doing great with its default support for AMD modules .
