### ISSUE TITLE
Development overrides not working

### ISSUE THREAD

**Issue by pb82** [brunch/brunch#969]
Hi,

according to the guide it's possible to override settings in the (default) development mode. So  I tried:

```js
overrides: {
  development: {
    optimize: true
  }
}
```

But the javascript remains uncompressed. Setting the mode explicitely to development with ```brunch build -e development``` works though. Am I missing something or do development overrides not work?

brunch version is 1.8.2
node version is 0.12.2
OS: linux

Thanks!

**Comment by es128** [comment]
Just add `optimize: true` to the top level of your regular config. No reason to use `overrides` for this.

**Comment by pb82** [comment]
Thanks that worked!

**Comment by es128** [comment]
I suppose [this is the guide page](https://github.com/brunch/brunch-guide/blob/master/content/en/chapter08-production-builds.md) that confused you? 

Do you have any suggestion for how it could be explained better?

/cc @tdd

**Comment by pb82** [comment]
Yes that was the section i was referring to. I will try to find a better explanation and send a pull request to brunch-guide.

**Comment by tdd** [comment]
Hey there,

How about changing "(which you can change, if you really want to)" to "(which you could change, if you really want to, but not through overrides then: use regular top-level settings for development-mode values)"?

**Comment by pb82** [comment]
Hey,

just sent you a pull request. I added a paragraph explaining the behaviour and added an example. Your suggestion also makes sense to me.

But I think it's good to explain that in development mode you do not have to 'override' anything, since it's the default mode already.

You can decide which one you like better ;-)

**Comment by tdd** [comment]
Hey,

@paulmillr merged your PR in 4 days ago, I just noticed this. So I went ahead and updated the FR L10n for it. Thanks for the input!
