### ISSUE TITLE
Unconventional watch paths not passed to nameCleaner

### ISSUE THREAD

**Issue by drakes** [brunch/brunch#972]
I added a "vendor-wrapped" directory for third-party modules I want to `require` from my code. Adding it to the watch paths gets them compiled, but those paths are never passed to `nameCleaner` to be made top-level modules. Thus they get registered as "vendor-wrapped/{module}", which is problematic when they have dependencies.

Excerpt from brunch-config.coffee:

```
modules:
	nameCleaner: (path) ->
		console.log "path: #{path}"
		path.replace(///^
			(
				app
				[\\/]
				scripts
				|vendor-wrapped
			)
			[\\/]
		///, '')
paths:
	watch: [
		'app'
		'test'
		'vendor'
		'vendor-wrapped'
	]
```

Maybe `nameCleaner` is only being passed paths from the default set instead of what's overridden?

**Comment by drakes** [comment]
Eh, maybe I should be using [browserify-brunch](https://github.com/mikew/browserify-brunch), that looks like it might be what I want.

**Comment by es128** [comment]
I suspect your odd regex formatting is the culprit. Likely need parens around `(scripts|vendor-wrapped)`

**Comment by drakes** [comment]
In this project vendor-wrapped is a top-level directory alongside app; I think the [block-formatted] regex is okay.

Either way, I say the vendor-wrapped paths are not getting passed to `nameCleaner` because I've looked at the logged output (from the first line of `nameCleaner` above); conventional paths are logged but not those starting with vendor-wrapped.

I haven't had a chance to try browserify-brunch yet. But if you think there's something worth pursuing in this issue I can post code to look at. If not that's okay too, since I probably don't have an actual use case, assuming browserify wrapping is a better solution :smile:
