### ISSUE TITLE
brunch fails including npm dependencies

### ISSUE THREAD

**Issue by davibe** [brunch/brunch#973]
I have experienced this with a specific package called trifl therefore i have created an example

https://github.com/davibe/brunch-npm-bug

**Comment by algesten** [comment]
I wrote [trifl](https://github.com/algesten/trifl) and tracked down the bug to `deppack` and provided a potential fix: https://github.com/yavorsky/deppack/issues/2

**Comment by algesten** [comment]
With pull request https://github.com/yavorsky/deppack/pull/3

**Comment by paulmillr** [comment]
Let's move to gh-1023.
