### ISSUE TITLE
Brunch build LESS file result in NameError on bootstrap functions

### ISSUE THREAD

**Issue by stl-winniechan** [brunch/brunch#975]
I have one main LESS file (main.less) that includes other LESS files (included app LESS files and Bootstrap LESS in another directory). Brunch build result in NameError on bootstrap functions: 
```
error: Compiling of 'src/less/custom.less' failed. NameError:#gradient.vertical is undefined in "src/less/custom.less:775:8"
...
 error: Compiling of 'src/app/travel/travel.less' failed. NameError:.box-shadow is undefined in "src/app/travel/travel.less:228:8"
```
We have brunch-config like this: 
```
        stylesheets: {
            joinTo: {
                'css/app.css': /^src\/less\/main.less$/,
                'css/vendor.css': /^(bower_components|vendor)/
            }
        },
```
and the main.less has include like these on the top: 
```
@import "../../bower_components/bootstrap/less/variables.less";
@import "../../bower_components/bootstrap/less/mixins.less";
```
I'm on brunch@1.8.3, less-brunch@1.8.1, and bootstrap#3.3.4

Does anyone knows what I'm doing wrong? Any help is appreciate.

**Comment by es128** [comment]
This is more of a less question than a brunch issue. It looks like you're expecting your imports to be transitive to the other imports, and I don't know whether less works that way. You may need to `@import` the relevant bootstrap files directly within your style files such as `src/app/travel/travel.less`.

If that does not help you resolve your issue, you may be better off seeking help with the less community.

P.S. `'css/app.css': /^src\/less\/main.less$/` could just be `'css/app.css': 'src/less/main.less'`
