### ISSUE TITLE
Change default conventions.assets to something less likely to conflict with vendor libs

### ISSUE THREAD

**Issue by gjaldon** [brunch/brunch#976]
I installed bootstrap-sass via bower and found that it didn't compile its javascript file to `vendor.js`. I have the ff config:

```javascript
exports.config = {
  files: {
    javascripts: {
      joinTo: {
       'js/app.js': /^(web\/static\/js)/,
       'js/vendor.js': /^(web\/static\/vendor|bower_components)/
      }
    }
}
```

It turns out bootstrap-sass has its javascript and css files inside an `assets/` dir so brunch was copying these files to a `javascripts/` directory instead. Better to avoid conflicts like these by changing the default name for assets dir to something less likely to be used by vendor libs.

**Comment by paulmillr** [comment]
This sounds right but we shouldn't make a a) backwards-incompatible change b) because only one library does it.

**Comment by gjaldon** [comment]
Ok got that. Thanks for checking anyway!
