### ISSUE TITLE
blog example

### ISSUE THREAD

**Issue by tcurdt** [brunch/brunch#979]
I cannot seem to find an example that is a blog.
Is there such a thing?

**Comment by es128** [comment]
Brunch is not designed to be a blog generator.

**Comment by tcurdt** [comment]
A blog is also just website.
Brunch is not capable enough to being used for that use case?

**Comment by es128** [comment]
Sure it is, but building the underlying blogging platform is not something Brunch does, it would be left to the user. And there's lots of other tools built specifically for that purpose. 

Specifically, Brunch has no built-in CMS and is lacking in the type of template composition that is well suited for static page generation for a blog.

But there's certainly nothing about it that would prevent anyone from building a blog with it if they wanted. That just isn't the typical use case. 

The typical use case is a web app backed by data from a RESTful API somewhere.

**Comment by tcurdt** [comment]
"blogging platform" sounds so complex. After all it's not much more than some markdown files with a frontmatter and a template engine - the usual jekyll style. I am surprised I am the first one thinking of trying this with Brunch.

I assume what could get a little tricky is having the notion of a (sorted) page collection (the posts) available during the template rendering.

**Comment by es128** [comment]
You aren't the first. But it isn't the core purpose, which is less specific. Right tool for the job, etc. 

There are so many other tools that are specifically static-site generators or blog engines. DocPad is one for instance that has some similarities to Brunch under the hood.

**Comment by tcurdt** [comment]
Indeed there are many static site generators - but most of them are just half-baked. If they are decent as blog generator they leave much to be desired from the asset pipeline point of view. I guess one could use e.g. Hugo in combination with Brunch - but a native solution via plugins sounds much more desireable. Less tools, less complexity.

The problem is - if Brunch was developed without generation of pages in mind adding this could become ugly. (Haven't looked under the hood yet)

**Comment by es128** [comment]
Yes it's a gap in Brunch currently. It's designed for template files to be compiled into javascript functions that are concatenated in with the rest. There are some plugins that work around this implicit behavior in order to, for instance, compile jade files into html files, but I'm not aware of anything that will compose full pages from a set of template partials and content. There's certainly nothing within Brunch itself to make that easy to do currently.

**Comment by tcurdt** [comment]
That's what I feared. Seems like Brunch is solely focused on javascript single page apps.
I am basically looking for static site generator (not just for a blog) that has a decent asset pipeline.

Seems like Brunch isn't that. Even Gulp seems to have an edge there.

**Comment by es128** [comment]
Here's a resource you can use to try looking for others that might meet your needs: www.staticgen.com

**Comment by tcurdt** [comment]
Thanks - but that's where the journey started ;)

**Comment by es128** [comment]
Here's the Brunch take on being listed there: https://twitter.com/brunch/status/599276747297845248
