### ISSUE TITLE
Brunch installation fails on Windows 7 NodeJS v0.12.4

### ISSUE THREAD

**Issue by snowindy** [brunch/brunch#982]
Previously I had brunch 1.7.20 and some smaller version on NodeJS, I decided to update my setup.

I installed the fresh NodeJS 0.12.4 from nodejs.org
I tried to install the fresh brunch and failed. I tried to clear cache, remove prev version of brunch, remove all starting with 'brunch' from npm/node_modules folder etc, all with about same output as follows:

```
$ npm install brunch
npm WARN optional dep failed, continuing fsevents@0.3.6
|
> brunch@1.8.3 postinstall C:\brunch_install\node_modules\brunch
> node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"

brunch@1.8.3 node_modules\brunch
├── fcache@0.1.1
├── quickly-copy-file@0.1.0
├── async-waterfall@0.1.5
├── async-each@0.1.6
├── commonjs-require-definition@0.2.0
├── commander@2.7.1 (graceful-readlink@1.0.1)
├── debug@2.1.3 (ms@0.7.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── anysort@1.0.0 (anymatch@1.0.0)
├── coffee-script@1.9.3
├── read-components@0.6.1 (component-builder@0.10.1)
├── source-map@0.3.0 (amdefine@0.1.0)
├── chokidar@1.0.3 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, is-binary-path@1.0.1, readdirp@1.3.0)
├── anymatch@1.3.0 (arrify@1.0.0, micromatch@2.1.6)
├── init-skeleton@0.4.4 (ncp@2.0.0, rimraf@2.3.4)
├── deppack@0.1.1 (browser-resolve@1.7.2, detective@4.0.3)
├── loggy@0.2.0 (growl@1.7.0, ansi-color@0.2.1, date-utils@1.2.17)
└── pushserve@0.1.6 (connect-slashes@0.0.11, commander@2.0.0, express@3.3.8)
```

In the end:
1. I can't execute brunch from command line - this means for me that it does not complete installation
2. Installation creates some dirs in the current folder. Say I was in c:\brunch_install when started installation
```
c:\brunch_install\node_modules
c:\brunch_install\node_modules\.bin
c:\brunch_install\node_modules\brunch
```

If I then execute c:\brunch_install\node_modules\.bin\brunch.cmd it seems to be working okay. Though I though brunch would have been installed in some normal destination where all npm internals go, not in the current dir.

Please help.

**Comment by es128** [comment]
You forgot to install globally. 

`npm install -g brunch`

**Comment by snowindy** [comment]
What about this?
```
node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"
```

Before I installed brunch, on prev version of node, it states something about evaluation error on this line.

**Comment by es128** [comment]
It's normal.

**Comment by psasubilli** [comment]
i am getting the same error with below command

npm install -g brunch

**Comment by es128** [comment]
What error?
