### ISSUE TITLE
Plugins not loading

### ISSUE THREAD

**Issue by WalkerCodeRanger** [brunch/brunch#983]
Not certain if this is an issue with the plugins or with brunch, but since there is more than one plugin that is not loading I think it might be a brunch issue.  I have added the plugins `ng-annotate-brunch` and `uglify-js-brunch` and neither seem to be loading or running.  I base that on the fact that my js isn't minified and that when I run `brunch build -d` the first line of output is `brunch:watch Loaded plugins: digest-brunch, javascript-brunch, jshint-brunch, postcss-brunch, sass-brunch +0ms`, and they are not listed.

My package.json contains (other packages omitted):

    "devDependencies": {
        "ng-annotate-brunch": "^1.7.2",
        "uglify-js-brunch": "^1.7.8"
    }

The packages are in my `node_modules` directory.

**Comment by paulmillr** [comment]
what if you add them to `dependencies`?

**Comment by WalkerCodeRanger** [comment]
Moving them to `dependencies` had no effect. They still don't work, even after deleting `node_modules` and running `npm install` again.  I figured that would be the case as brunch and all my other brunch plugins are in `devDependencies`.

**Comment by es128** [comment]
Those are optimizers, aren't they? Set `optimize: true` in config or add the `--production` flag in the CLI. Or for short: `brunch build -P`. You can use the debug messages again to easily validate the plugins are being loaded: `-Pd`

**Comment by WalkerCodeRanger** [comment]
Yes they are.  I was just coming to that realization myself. As you say, they run if I set `optimize: true` or do a production build.  I guess I was a little confused by the debug output of the regular build.  I expected the plugins to be listed as loaded even if they were configured not to run.
