### ISSUE TITLE
npm imported module error

### ISSUE THREAD

**Issue by jblanche** [brunch/brunch#984]
I created a very simple test case with a `main.js` file in the app requiring `jquery` (installed and "saved" in the `package.json` dependencies) and an index.html file requiring the `main.js` file. 

I get a `Uncaught Error: Cannot find module "jquery" from "main"` in the browser console. Am I missing something about the new NPM support ?

**Comment by jblanche** [comment]
The test case is accessible here https://github.com/jblanche/demoBrunchNpm

**Comment by jblanche** [comment]
OK I finally succeed adding 
```
  npm:
    enabled: true
```
to my `brunch-config.coffee`. 
I'm running the latest brunch tag `1.8.3` so the CHANGELOG saying that since `1.8.1` 
```
Enabled NPM support by default. Just load any installed npm package in your code via require('package')
``` 
is VERY confusing ;)

**Comment by paulmillr** [comment]
Sorry for that. We should adjust docs / changelog.

**Comment by hzamani** [comment]
+1

**Comment by paulmillr** [comment]
Let's move to gh-1023.
