### ISSUE TITLE
NPM import strategy

### ISSUE THREAD

**Issue by warrenseine** [brunch/brunch#986]
Hi,

I'm very glad NPM support was recently added. Bower was nice for a time, but dealing with dependencies in a single place is _much_ better.

Unfortunately, this does not do what I would have expected. That is, packaging the "distributed" file when it exists. I can see that Brunch is doing its best and reads the `main` attribute of `package.json`. But in most cases, this is not what I want:
* React, a very popular library, comes in a bundled version on NPM, with a ready-to-be-used `dist/react.js` but `main` references `main.js` (a "source" file)
* React Router has `umd/ReactRouter.js` but `main` references `lib` (a directory!)

Can I override this behavior to tell Brunch which file to package for each NPM module?

**Comment by warrenseine** [comment]
Basically, my idea would have been to fix `loadNpm` by looking at the `before` array. If some path matches `node_modules/{dep}/*`, then use this file instead of `package.json`'s `main`. It sounds a bit clumsy so I'm asking for better ideas here.

**Comment by es128** [comment]
Why not point to the specific file you want in the `require` call in your app code? `require('react/dist/react')` or something like that. 

I don't think `before` idea would work out in a general sense. If the above suggestion doesn't work, we may need something more like what happened with bower `overrides`.

**Comment by gjaldon** [comment]
@warrenseine - were you able to use react-router after overriding main with `umd/ReactRouter.js`? I tried it out but requiring reactRouter and using it gives me the error `Uncaught TypeError: _reactRouter2.default.run is not a function`. 

React works fine though when overring main with `dist/react.js`.

**Comment by warrenseine** [comment]
Yes, I figured out that `umd` was not intented to be used as `dist`. Actually, there's an issue [here](https://github.com/rackt/react-router/issues/839) to get a properly `dist` in the repository. You can precompile it yourself anyway.

**Comment by gjaldon** [comment]
@warrenseine I see. What do you mean about precompiling it? Do you precompile it with browserify now? Do you use just NPM? I'm curious as to how you went about this.

**Comment by warrenseine** [comment]
@gjaldon I made a private repo with `dist` built and embedded and pointed my `package.json` to it.

**Comment by paulmillr** [comment]
Let's move to gh-1023.
