### ISSUE TITLE
There are config settings to turn 'modules' off, but a package.json is required

### ISSUE THREAD

**Issue by jugimaster** [brunch/brunch#989]
I'm new to both Brunch _and_ JavaScript modules, so I may be missing something here.

Here's my attempt at turning modules off altogether:

```coffeescript
  modules:
    wrapper: false
    definition: false
```

But here's what Brunch says when trying to run it:

```Error: Current directory is not brunch application root path, as it does not contain package.json```

**Comment by es128** [comment]
The current working directory where you are running your `brunch` CLI command is not the base of your brunch project. It has nothing to do with what's in your config. 

Your project must have a package.json - that's how you describe which plugins you're using among other things.

**Comment by jugimaster** [comment]
I ran brunch in the root directory of my _project_. The project happens to use Brunch. 

Again, I'm trying not to be bothered with the "module" stuff, because I don't see any need for them. 

But as far as I can tell, Brunch refuses to do anything without a module-related file in the root directory, and that's a problem. It's also inconsistent with letting the user turn off the feature for wrapping JS files in modules.

**Comment by es128** [comment]
You're mixing up different concepts here. If your project uses Brunch, then it has a package.json and a brunch-config file. package.json isn't a "module-related file", it is a manifest of which plugins you're using (at a minimum).

None of this has anything to do with the Brunch's module wrapping behavior - that's an optional step for what it does to your project code.

**Comment by jugimaster** [comment]
Why do I need to list installed plugins in a package.json? Isn't it enough that I've _installed_ them with NPM?

I'm new to Node too, by the way :P

Seriously. I don't want a package.json lying around, cluttering up my projects, and _"needing it for Brunch to run"_ is not a particularly delightful reason for having one lying around.

I set up a dummy package.json and brunch actually run and did something (that I didn't want it to :P).. but hey, it's progress!

**Comment by es128** [comment]
Yes, you need a package.json for any Brunch project, or just about any project that uses node.js-based tooling. That way if you're developing the project with other people, they can just `npm install` instead of you needing to communicate by some other means which set of plugins (at which versions) need to be installed.

Sorry if you find it in an eyesore, but if you want to use Brunch it is necessary.

**Comment by es128** [comment]
Also, the package.json needs to list your brunch plugins to be effective, it isn't good enough to just have a dummy file there.

When installing plugins it's best to use `npm install --save` or `npm install --save-dev` to have them automatically listed in your package.json.

**Comment by jugimaster** [comment]
I don't get it.. 

Are you telling me that Brunch is meant _specifically_ for Node developers who work on open source projects?

Again, I'm new to Node too. Is there something about how Node works that makes a package.json absolutely, genuinely required here?

**Comment by es128** [comment]
Brunch is meant for web application developers. Open/closed source of the users' projects isn't relevant.

> Is there something about how Node works that makes a package.json absolutely, genuinely required here?

package.json is the standard means for listing a project's dependencies. Brunch runs on node.js and uses npm as its distribution system for plugins. It discovers which plugins you want to use by reading them from the package.json manifest. There could theoretically be other means of doing this (like digging around in the node_modules directory), but that's not how Brunch chooses to do it.

It is very prevalent for projects using Node-based tooling, and just about universal for any project that runs on Node itself, to include a package.json file. If you want to keep using Node and tools built on Node, get used to seeing them. Hopefully, beyond merely tolerating their presence, you'll eventually come to understand and appreciate how useful and beneficial they are.

**Comment by jugimaster** [comment]
> Brunch is meant for web application developers.

.. that use Node, apparently. But I don't - I use Clojure.

> It is very prevalent for projects using Node-based tooling, and just about universal for any project that runs on Node itself, to include a package.json file.

So it seems.

> If you want to keep using Node and tools built on Node, get used to seeing them. 

I don't care about Node or its ecosystem, but I see now that the package.json file is necessary because Brunch was built in Node. That can't be helped, then.

> Hopefully, beyond merely tolerating their presence, you'll eventually come to understand and appreciate how useful and beneficial they are.

"They", as in package.json files? :D  I'm afraid I never will.

**Comment by jugimaster** [comment]
Wow.. apparently Brunch refuses to work with globally installed Node libraries, so it mandates a ```node_modules``` -directory under every single damn project too! This is pretty sad.. for someone who's _not_ a Node developer.

**Comment by es128** [comment]
Feel free to switch to a Clojure based web app build system that does not cause these problems for you.

**Comment by jugimaster** [comment]
Yep, I guess all build tools have similar ailments. I'll try Mimosa next, in case it's less finicky. Thanks for the information anyway!
