### ISSUE TITLE
how to disable css concatenation ?

### ISSUE THREAD

**Issue by stoufdev** [brunch/brunch#990]
I have a lot of Scss files, i want to keep then separated.
I just want to compile then in Css (with : sass-brunch), 
and minify (with : i don't know yet, suggestions ?).
How to ? possible ?

**Comment by es128** [comment]
https://github.com/brunch/sass-brunch/issues/81

**Comment by es128** [comment]
Also for minification you can use clean-css-brunch. To activate it you need to either set `optimize: true` in your config or use the `-P`/`--production` switch when you run the `brunch` CLI

**Comment by stoufdev** [comment]
Thanks
