### ISSUE TITLE
Wrapping javascript files in a manner suitable for web workers

### ISSUE THREAD

**Issue by lpil** [brunch/brunch#995]
Hello!

I wish to use web workers in my application, but I also want to use es6. `window` is not available in the context of web workers, so the code brunch wraps JS files in throws an error.

Is there a way to change the way that a single file is wrapped?

Thanks,
Louis

**Comment by paulmillr** [comment]
Sure thing. Take a look at `config.modules.wrapper / definition`: https://github.com/brunch/brunch/blob/master/docs/config.md#modules

```coffeescript
# Same as 'commonjs'.
modules:
  wrapper: (path, data) ->
    """
require.define({#{path}: function(exports, require, module) {
  #{data}
}});\n\n
    """
```

**Comment by lpil** [comment]
I only want to change it for one file, not all. Is this possible?

**Comment by paulmillr** [comment]
Possible. Just define different cases:

```
  wrapper: (path, data) ->
    if path is 'app/your-file.js'
      'return one string'
    else
      'return another string'
```

**Comment by lpil** [comment]
Is there a way to have the else default to the brunch default wrapper?

**Comment by lpil** [comment]
I've realised that I should be putting these files into `app/assets`! Thank you for your help.

**Comment by paulmillr** [comment]
>Is there a way to have the else default to the brunch default wrapper?

Only by manually writing the code of brunches wrapper in [the comment](https://github.com/brunch/brunch/issues/995#issuecomment-122625446)

**Comment by JayChetty** [comment]
Hey,  similar issue.  Would like to have worker files (service and web) processed by Babel,  but not wrapped. Is this possible?

**Comment by paulmillr** [comment]
As i've mentioned in the comment above — just change `config.modules.wrapper`.

**Comment by JayChetty** [comment]
Cheers Paul.  By default Brunch is also adding a definition that is causing the same problem for the service worker. The only solution I can see just now is to attach a function to the definition attribute , returning a string copy of the setup code for non service worker files.  

Can conventions be setup to not add definitions, in the same way as wrappers?

**Comment by paulmillr** [comment]
Yep. `config.modules.definition`

It's using this (string) by default: https://github.com/brunch/commonjs-require-definition/blob/master/require.js

Feel free to change it to your needs.

**Comment by JayChetty** [comment]
Cool. Cheers
