### ISSUE TITLE
renaming files and notifying autoreloader

### ISSUE THREAD

**Issue by fab1an** [brunch/brunch#996]
I wrote a plugin that hashes files in assets based on their contents.
This broke css-autoreloading since the file name is changed and `autoreloader` injects the old css-file, without the appended hash. Is there a way around this?

**Comment by es128** [comment]
Take a look over at https://github.com/brunch/auto-reload-brunch to see if you can come up with a straightforward fix.

May be necessary to fork and make a different auto-reload plugin that fits your use case. 

You could also give https://github.com/ocombe/browser-sync-brunch a try

**Comment by fab1an** [comment]
No time for that. I thought that is a common use case to reload files that come out of the end of the build pipeline.

**Comment by es128** [comment]
I guess not common enough for anyone else to have reported this issue before
