### ISSUE TITLE
Make brunch play nicely with CSP

### ISSUE THREAD

**Issue by josevalim** [brunch/brunch#999]
I am working on adding Content Security Policy (CSP) rules to Phoenix applications and I have been struggling to make it play nicely with Brunch. The issue is that Brunch requires a script tag to require your main application module::

    <script>require("app")</script>

However CSP recommends to have no inline scripts in HTML pages. So the `require("app")` needs to be automatically embedded in the compiled script. Do you have any ideas in mind to solve this issue? I want to avoid bringing things like browserify though because it is a large dependency for a simple problem.

For example, one solution I had in mind is to support "autorequires", so one could write:

    joinTo:
      'js/app.js':
        include: /^(web\/static\/js)/
        autorequire: ["app"]
      'js/vendor.js':
        include: /^(web\/static\/vendor)/

Is there something like that in Brunch? If not, is a PR desired?

**Comment by es128** [comment]
It's a good idea, but I think it ought to be added as part of the [`modules`](https://github.com/brunch/brunch/blob/master/docs/config.md#modules) config object.

Something like:

```coffee
modules:
  wrapper: 'commonjs' # just showing context with these two
  definition: 'commonjs' # lines; they're already the defaults
  appendRequire:
    'js/app.js': ['app']
```

PR welcome

**Comment by paulmillr** [comment]
`autoRequire` — sounds like better naming here.

**Comment by es128** [comment]
Ok sure, I'm fine with `autoRequire`

**Comment by josevalim** [comment]
I actually like `appendRequire` as @es128 suggested because it makes it clear it is happening at the bottom of the joined file and not right after each definition and the oder is important. I will send a PR in a couple minutes and we can settle this there.
